const keys = ["name", "location", "folder", "open", "create", "cancel", "target", "note",
  "advanced", "history", "invalid", "ready", "details"] as const;
export type BundleCreationCopy = Record<typeof keys[number], string>;
type Row = readonly [string, string, string, string, string, string, string, string, string, string, string, string, string];

export const BUNDLE_CREATION_TRANSLATIONS: Record<string, Row> = {
  en: ["Name", "Location", "Choose folder...", "Open bundle...", "Create bundle", "Cancel", "Will create",
    "Create an empty .kyuubiki file. Existing files are never replaced.", "Advanced tools", "Recent paths and history",
    "Enter a valid file name and an absolute folder path.", "Bundle selected. Inspect it or open Workbench to continue.", "Operation details"],
  zh: ["名称", "保存位置", "选择文件夹...", "打开已有 bundle...", "创建 bundle", "取消", "将创建",
    "创建一个空的 .kyuubiki 文件，不会覆盖已有文件。", "高级工具", "最近路径与操作历史",
    "请输入合法的文件名和文件夹绝对路径。", "已选定 bundle，可继续检查或打开 Workbench。", "操作详情"],
  ja: ["名前", "保存先", "フォルダーを選択...", "既存のバンドルを開く...", "バンドルを作成", "キャンセル", "作成するファイル",
    "空の .kyuubiki ファイルを作成します。既存のファイルは上書きしません。", "詳細ツール", "最近のパスと操作履歴",
    "有効なファイル名とフォルダーの絶対パスを入力してください。", "バンドルを選択しました。検査するか Workbench を開いて続行できます。", "操作の詳細"],
  es: ["Nombre", "Ubicación", "Elegir carpeta...", "Abrir paquete...", "Crear paquete", "Cancelar", "Se creará",
    "Crea un archivo .kyuubiki vacío. No se reemplazan archivos existentes.", "Herramientas avanzadas", "Rutas recientes e historial",
    "Introduce un nombre de archivo válido y una ruta absoluta de carpeta.", "Paquete seleccionado. Inspecciónalo o abre Workbench para continuar.", "Detalles de la operación"],
  ar: ["الاسم", "الموقع", "اختيار مجلد...", "فتح حزمة...", "إنشاء حزمة", "إلغاء", "سيتم إنشاء",
    "إنشاء ملف .kyuubiki فارغ دون استبدال الملفات الموجودة.", "أدوات متقدمة", "المسارات الأخيرة والسجل",
    "أدخل اسم ملف صالحًا ومسار مجلد مطلقًا.", "تم اختيار الحزمة. افحصها أو افتح Workbench للمتابعة.", "تفاصيل العملية"],
  bn: ["নাম", "অবস্থান", "ফোল্ডার বাছুন...", "বান্ডল খুলুন...", "বান্ডল তৈরি করুন", "বাতিল", "তৈরি হবে",
    "একটি খালি .kyuubiki ফাইল তৈরি করুন। বিদ্যমান ফাইল প্রতিস্থাপন করা হবে না।", "উন্নত সরঞ্জাম", "সাম্প্রতিক পথ ও ইতিহাস",
    "একটি বৈধ ফাইলের নাম এবং ফোল্ডারের সম্পূর্ণ পথ লিখুন।", "বান্ডল নির্বাচিত। পরিদর্শন করুন বা Workbench খুলে এগিয়ে যান।", "কার্যক্রমের বিবরণ"],
  cs: ["Název", "Umístění", "Vybrat složku...", "Otevřít balíček...", "Vytvořit balíček", "Zrušit", "Bude vytvořeno",
    "Vytvoří prázdný soubor .kyuubiki. Existující soubory se nepřepisují.", "Pokročilé nástroje", "Nedávné cesty a historie",
    "Zadejte platný název souboru a absolutní cestu ke složce.", "Balíček vybrán. Zkontrolujte jej nebo pokračujte v aplikaci Workbench.", "Podrobnosti operace"],
  da: ["Navn", "Placering", "Vælg mappe...", "Åbn pakke...", "Opret pakke", "Annuller", "Opretter",
    "Opret en tom .kyuubiki-fil. Eksisterende filer overskrives ikke.", "Avancerede værktøjer", "Seneste stier og historik",
    "Indtast et gyldigt filnavn og en absolut mappesti.", "Pakke valgt. Undersøg den, eller åbn Workbench for at fortsætte.", "Handlingsdetaljer"],
  de: ["Name", "Speicherort", "Ordner wählen...", "Bundle öffnen...", "Bundle erstellen", "Abbrechen", "Wird erstellt",
    "Erstellt eine leere .kyuubiki-Datei. Vorhandene Dateien werden nicht überschrieben.", "Erweiterte Werkzeuge", "Letzte Pfade und Verlauf",
    "Gib einen gültigen Dateinamen und einen absoluten Ordnerpfad ein.", "Bundle ausgewählt. Prüfe es oder öffne Workbench, um fortzufahren.", "Vorgangsdetails"],
  el: ["Όνομα", "Τοποθεσία", "Επιλογή φακέλου...", "Άνοιγμα πακέτου...", "Δημιουργία πακέτου", "Ακύρωση", "Θα δημιουργηθεί",
    "Δημιουργεί ένα κενό αρχείο .kyuubiki. Τα υπάρχοντα αρχεία δεν αντικαθίστανται.", "Εργαλεία για προχωρημένους", "Πρόσφατες διαδρομές και ιστορικό",
    "Εισαγάγετε έγκυρο όνομα αρχείου και απόλυτη διαδρομή φακέλου.", "Το πακέτο επιλέχθηκε. Ελέγξτε το ή ανοίξτε το Workbench για συνέχεια.", "Λεπτομέρειες λειτουργίας"],
  fa: ["نام", "محل ذخیره", "انتخاب پوشه...", "باز کردن بسته...", "ایجاد بسته", "لغو", "ایجاد خواهد شد",
    "یک فایل خالی .kyuubiki ایجاد می‌شود. فایل‌های موجود جایگزین نمی‌شوند.", "ابزارهای پیشرفته", "مسیرهای اخیر و تاریخچه",
    "نام فایل معتبر و مسیر مطلق پوشه را وارد کنید.", "بسته انتخاب شد. آن را بررسی کنید یا برای ادامه Workbench را باز کنید.", "جزئیات عملیات"],
  fi: ["Nimi", "Sijainti", "Valitse kansio...", "Avaa paketti...", "Luo paketti", "Peruuta", "Luotava tiedosto",
    "Luo tyhjän .kyuubiki-tiedoston. Olemassa olevia tiedostoja ei korvata.", "Lisätyökalut", "Viimeisimmät polut ja historia",
    "Anna kelvollinen tiedostonimi ja kansion absoluuttinen polku.", "Paketti valittu. Tarkista se tai jatka avaamalla Workbench.", "Toiminnon tiedot"],
  fr: ["Nom", "Emplacement", "Choisir un dossier...", "Ouvrir un paquet...", "Créer le paquet", "Annuler", "Fichier à créer",
    "Crée un fichier .kyuubiki vide. Les fichiers existants ne sont jamais remplacés.", "Outils avancés", "Chemins récents et historique",
    "Saisissez un nom de fichier valide et un chemin de dossier absolu.", "Paquet sélectionné. Inspectez-le ou ouvrez Workbench pour continuer.", "Détails de l’opération"],
  he: ["שם", "מיקום", "בחירת תיקייה...", "פתיחת חבילה...", "יצירת חבילה", "ביטול", "הקובץ שייווצר",
    "יצירת קובץ .kyuubiki ריק. קבצים קיימים לא יוחלפו.", "כלים מתקדמים", "נתיבים אחרונים והיסטוריה",
    "יש להזין שם קובץ תקין ונתיב מוחלט לתיקייה.", "החבילה נבחרה. יש לבדוק אותה או לפתוח את Workbench כדי להמשיך.", "פרטי הפעולה"],
  hi: ["नाम", "स्थान", "फ़ोल्डर चुनें...", "बंडल खोलें...", "बंडल बनाएँ", "रद्द करें", "बनाई जाने वाली फ़ाइल",
    "एक खाली .kyuubiki फ़ाइल बनाएँ। मौजूदा फ़ाइलों को बदला नहीं जाएगा।", "उन्नत उपकरण", "हाल के पथ और इतिहास",
    "मान्य फ़ाइल नाम और फ़ोल्डर का पूर्ण पथ दर्ज करें।", "बंडल चुना गया। जाँच करें या आगे बढ़ने के लिए Workbench खोलें।", "कार्य का विवरण"],
  id: ["Nama", "Lokasi", "Pilih folder...", "Buka bundel...", "Buat bundel", "Batal", "Akan dibuat",
    "Buat file .kyuubiki kosong. File yang sudah ada tidak akan diganti.", "Alat lanjutan", "Jalur terbaru dan riwayat",
    "Masukkan nama file yang valid dan jalur folder absolut.", "Bundel dipilih. Periksa atau buka Workbench untuk melanjutkan.", "Detail operasi"],
  it: ["Nome", "Posizione", "Scegli cartella...", "Apri pacchetto...", "Crea pacchetto", "Annulla", "File da creare",
    "Crea un file .kyuubiki vuoto. I file esistenti non vengono sostituiti.", "Strumenti avanzati", "Percorsi recenti e cronologia",
    "Inserisci un nome file valido e un percorso assoluto della cartella.", "Pacchetto selezionato. Esaminalo o apri Workbench per continuare.", "Dettagli dell’operazione"],
  ko: ["이름", "저장 위치", "폴더 선택...", "번들 열기...", "번들 만들기", "취소", "생성할 파일",
    "빈 .kyuubiki 파일을 만듭니다. 기존 파일은 덮어쓰지 않습니다.", "고급 도구", "최근 경로 및 기록",
    "유효한 파일 이름과 폴더의 절대 경로를 입력하세요.", "번들을 선택했습니다. 검사하거나 Workbench를 열어 계속하세요.", "작업 세부 정보"],
  ms: ["Nama", "Lokasi", "Pilih folder...", "Buka berkas...", "Cipta berkas", "Batal", "Akan dicipta",
    "Cipta fail .kyuubiki kosong. Fail sedia ada tidak akan diganti.", "Alat lanjutan", "Laluan terkini dan sejarah",
    "Masukkan nama fail yang sah dan laluan folder mutlak.", "Berkas dipilih. Periksa atau buka Workbench untuk meneruskan.", "Butiran operasi"],
  nl: ["Naam", "Locatie", "Map kiezen...", "Bundel openen...", "Bundel maken", "Annuleren", "Wordt gemaakt",
    "Maakt een leeg .kyuubiki-bestand. Bestaande bestanden worden niet vervangen.", "Geavanceerde tools", "Recente paden en geschiedenis",
    "Voer een geldige bestandsnaam en een absoluut mappad in.", "Bundel geselecteerd. Inspecteer deze of open Workbench om door te gaan.", "Bewerkingsdetails"],
  no: ["Navn", "Plassering", "Velg mappe...", "Åpne pakke...", "Opprett pakke", "Avbryt", "Opprettes",
    "Opprett en tom .kyuubiki-fil. Eksisterende filer erstattes ikke.", "Avanserte verktøy", "Nylige stier og historikk",
    "Skriv inn et gyldig filnavn og en absolutt mappesti.", "Pakke valgt. Undersøk den eller åpne Workbench for å fortsette.", "Operasjonsdetaljer"],
  pl: ["Nazwa", "Lokalizacja", "Wybierz folder...", "Otwórz pakiet...", "Utwórz pakiet", "Anuluj", "Zostanie utworzony",
    "Tworzy pusty plik .kyuubiki. Istniejące pliki nie zostaną zastąpione.", "Narzędzia zaawansowane", "Ostatnie ścieżki i historia",
    "Podaj prawidłową nazwę pliku i bezwzględną ścieżkę folderu.", "Wybrano pakiet. Sprawdź go lub otwórz Workbench, aby kontynuować.", "Szczegóły operacji"],
  "pt-BR": ["Nome", "Local", "Escolher pasta...", "Abrir pacote...", "Criar pacote", "Cancelar", "Será criado",
    "Cria um arquivo .kyuubiki vazio. Arquivos existentes nunca são substituídos.", "Ferramentas avançadas", "Caminhos recentes e histórico",
    "Insira um nome de arquivo válido e um caminho absoluto de pasta.", "Pacote selecionado. Inspecione-o ou abra o Workbench para continuar.", "Detalhes da operação"],
  ro: ["Nume", "Locație", "Alege dosarul...", "Deschide pachetul...", "Creează pachetul", "Anulează", "Se va crea",
    "Creează un fișier .kyuubiki gol. Fișierele existente nu sunt înlocuite.", "Instrumente avansate", "Căi recente și istoric",
    "Introdu un nume de fișier valid și o cale absolută către dosar.", "Pachet selectat. Inspectează-l sau deschide Workbench pentru a continua.", "Detaliile operației"],
  ru: ["Имя", "Расположение", "Выбрать папку...", "Открыть пакет...", "Создать пакет", "Отмена", "Будет создан",
    "Создаётся пустой файл .kyuubiki. Существующие файлы не заменяются.", "Дополнительные инструменты", "Недавние пути и история",
    "Введите допустимое имя файла и абсолютный путь к папке.", "Пакет выбран. Проверьте его или откройте Workbench для продолжения.", "Подробности операции"],
  sv: ["Namn", "Plats", "Välj mapp...", "Öppna paket...", "Skapa paket", "Avbryt", "Kommer att skapas",
    "Skapa en tom .kyuubiki-fil. Befintliga filer ersätts aldrig.", "Avancerade verktyg", "Senaste sökvägar och historik",
    "Ange ett giltigt filnamn och en absolut sökväg till en mapp.", "Paket valt. Granska det eller öppna Workbench för att fortsätta.", "Åtgärdsdetaljer"],
  sw: ["Jina", "Mahali", "Chagua folda...", "Fungua kifurushi...", "Unda kifurushi", "Ghairi", "Itaundwa",
    "Unda faili tupu ya .kyuubiki. Faili zilizopo hazitabadilishwa.", "Zana za hali ya juu", "Njia za hivi karibuni na historia",
    "Weka jina halali la faili na njia kamili ya folda.", "Kifurushi kimechaguliwa. Kikague au ufungue Workbench ili kuendelea.", "Maelezo ya operesheni"],
  ta: ["பெயர்", "இடம்", "கோப்புறையைத் தேர்ந்தெடு...", "தொகுப்பைத் திற...", "தொகுப்பை உருவாக்கு", "ரத்துசெய்", "உருவாக்கப்படும் கோப்பு",
    "வெற்று .kyuubiki கோப்பை உருவாக்கும். ஏற்கனவே உள்ள கோப்புகள் மாற்றப்படாது.", "மேம்பட்ட கருவிகள்", "சமீபத்திய பாதைகள் மற்றும் வரலாறு",
    "செல்லுபடியாகும் கோப்புப் பெயரையும் கோப்புறையின் முழுப் பாதையையும் உள்ளிடவும்.", "தொகுப்பு தேர்ந்தெடுக்கப்பட்டது. ஆய்வு செய்யவும் அல்லது தொடர Workbench ஐத் திறக்கவும்.", "செயல்பாட்டு விவரங்கள்"],
  th: ["ชื่อ", "ตำแหน่ง", "เลือกโฟลเดอร์...", "เปิดบันเดิล...", "สร้างบันเดิล", "ยกเลิก", "ไฟล์ที่จะสร้าง",
    "สร้างไฟล์ .kyuubiki ว่าง โดยไม่แทนที่ไฟล์ที่มีอยู่", "เครื่องมือขั้นสูง", "เส้นทางล่าสุดและประวัติ",
    "ป้อนชื่อไฟล์ที่ถูกต้องและเส้นทางโฟลเดอร์แบบสัมบูรณ์", "เลือกบันเดิลแล้ว ตรวจสอบหรือเปิด Workbench เพื่อดำเนินการต่อ", "รายละเอียดการดำเนินการ"],
  tr: ["Ad", "Konum", "Klasör seç...", "Paket aç...", "Paket oluştur", "İptal", "Oluşturulacak dosya",
    "Boş bir .kyuubiki dosyası oluşturur. Mevcut dosyaların üzerine yazılmaz.", "Gelişmiş araçlar", "Son yollar ve geçmiş",
    "Geçerli bir dosya adı ve mutlak klasör yolu girin.", "Paket seçildi. İnceleyin veya devam etmek için Workbench'i açın.", "İşlem ayrıntıları"],
  uk: ["Назва", "Розташування", "Вибрати папку...", "Відкрити пакет...", "Створити пакет", "Скасувати", "Буде створено",
    "Створює порожній файл .kyuubiki. Наявні файли не замінюються.", "Додаткові інструменти", "Останні шляхи та історія",
    "Введіть допустиму назву файлу й абсолютний шлях до папки.", "Пакет вибрано. Перевірте його або відкрийте Workbench для продовження.", "Подробиці операції"],
  ur: ["نام", "مقام", "فولڈر منتخب کریں...", "بنڈل کھولیں...", "بنڈل بنائیں", "منسوخ", "بننے والی فائل",
    "ایک خالی .kyuubiki فائل بنائیں۔ موجودہ فائلیں تبدیل نہیں کی جائیں گی۔", "جدید اوزار", "حالیہ راستے اور تاریخچہ",
    "درست فائل نام اور فولڈر کا مکمل راستہ درج کریں۔", "بنڈل منتخب ہوگیا۔ جانچ کریں یا جاری رکھنے کے لیے Workbench کھولیں۔", "عمل کی تفصیلات"],
  vi: ["Tên", "Vị trí", "Chọn thư mục...", "Mở gói...", "Tạo gói", "Hủy", "Tệp sẽ được tạo",
    "Tạo tệp .kyuubiki trống. Không thay thế các tệp hiện có.", "Công cụ nâng cao", "Đường dẫn gần đây và lịch sử",
    "Nhập tên tệp hợp lệ và đường dẫn thư mục tuyệt đối.", "Đã chọn gói. Kiểm tra hoặc mở Workbench để tiếp tục.", "Chi tiết thao tác"],
  "zh-TW": ["名稱", "儲存位置", "選擇資料夾...", "開啟既有 bundle...", "建立 bundle", "取消", "將建立",
    "建立空的 .kyuubiki 檔案，不會覆寫既有檔案。", "進階工具", "最近路徑與操作紀錄",
    "請輸入有效的檔名和資料夾絕對路徑。", "已選定 bundle，可繼續檢查或開啟 Workbench。", "操作詳情"],
};

export function bundleCreationCopy(language: string): BundleCreationCopy {
  const row = BUNDLE_CREATION_TRANSLATIONS[language] || BUNDLE_CREATION_TRANSLATIONS.en;
  return Object.fromEntries(keys.map((key, index) => [key, row[index]])) as BundleCreationCopy;
}
