const keys = ["title", "current", "indices", "range", "invert", "translate", "array", "align", "copies",
  "total", "perNode", "internal", "touching", "copyConditions", "confirmDelete", "apply", "supports", "hint", "unchanged"] as const;
type Row = readonly [string, string, string, string, string, string, string, string, string, string,
  string, string, string, string, string, string, string, string, string];

const rows: Record<string, Row> = {
  en: ["Batch modeling", "Current selection", "Indices (from 0)", "Coordinate range", "Invert selection", "Translate", "Linear array", "Align", "Additional copies", "Total load", "Per node", "Internal members", "Touching members", "Copy loads and supports", "Delete matching nodes and all touching members", "Apply batch", "Supports", "One undo step. Copies contain internal members only; no automatic connections between copies. SI: m, N, Pa.", "No changes"],
  zh: ["批量建模", "当前选择", "编号（从 0 开始）", "坐标区间", "反选", "整体平移", "线性阵列", "坐标对齐", "新增副本数", "总载荷均分", "每个节点", "组内杆件", "关联杆件", "复制载荷和约束", "删除匹配节点及其全部关联杆件", "应用批量操作", "约束", "整批只占一步撤销。副本仅包含组内杆件，不自动连接各副本。SI：m、N、Pa。", "没有变更"],
  "zh-tw": ["批次建模", "目前選取", "編號（從 0 開始）", "座標區間", "反向選取", "整體平移", "線性陣列", "座標對齊", "新增複本數", "總負載均分", "每個節點", "群組內桿件", "關聯桿件", "複製負載和約束", "刪除符合的節點及其全部關聯桿件", "套用批次操作", "約束", "整批僅佔一步復原。複本只包含群組內桿件，不自動連接各複本。SI：m、N、Pa。", "沒有變更"],
  ja: ["一括モデリング", "現在の選択", "番号（0から）", "座標範囲", "選択を反転", "平行移動", "直線配列", "座標を整列", "追加コピー数", "総荷重を均等配分", "節点ごと", "内部部材", "接続部材", "荷重と拘束をコピー", "該当節点と接続する全ての部材を削除", "一括適用", "拘束", "一度で元に戻せます。内部部材のみコピーし、コピー間は自動接続しません。SI: m, N, Pa。", "変更なし"],
  es: ["Modelado por lotes", "Selección actual", "Índices (desde 0)", "Rango de coordenadas", "Invertir selección", "Trasladar", "Matriz lineal", "Alinear", "Copias adicionales", "Carga total", "Por nodo", "Barras internas", "Barras conectadas", "Copiar cargas y apoyos", "Eliminar nodos coincidentes y todas sus barras conectadas", "Aplicar lote", "Apoyos", "Un paso para deshacer. Solo se copian barras internas, sin conectar las copias automáticamente. SI: m, N, Pa.", "Sin cambios"],
  fr: ["Modélisation par lot", "Sélection actuelle", "Indices (à partir de 0)", "Plage de coordonnées", "Inverser la sélection", "Translater", "Réseau linéaire", "Aligner", "Copies supplémentaires", "Charge totale", "Par nœud", "Barres internes", "Barres incidentes", "Copier charges et appuis", "Supprimer les nœuds correspondants et toutes leurs barres incidentes", "Appliquer le lot", "Appuis", "Une seule annulation. Seules les barres internes sont copiées, sans liaison automatique entre copies. SI : m, N, Pa.", "Aucun changement"],
  de: ["Stapelmodellierung", "Aktuelle Auswahl", "Indizes (ab 0)", "Koordinatenbereich", "Auswahl umkehren", "Verschieben", "Lineare Anordnung", "Ausrichten", "Zusätzliche Kopien", "Gesamtlast", "Pro Knoten", "Interne Stäbe", "Angrenzende Stäbe", "Lasten und Lager kopieren", "Passende Knoten und alle angrenzenden Stäbe löschen", "Stapel anwenden", "Lager", "Ein Rückgängig-Schritt. Nur interne Stäbe werden kopiert; Kopien werden nicht automatisch verbunden. SI: m, N, Pa.", "Keine Änderungen"],
  it: ["Modellazione in blocco", "Selezione attuale", "Indici (da 0)", "Intervallo di coordinate", "Inverti selezione", "Trasla", "Serie lineare", "Allinea", "Copie aggiuntive", "Carico totale", "Per nodo", "Aste interne", "Aste incidenti", "Copia carichi e vincoli", "Elimina i nodi corrispondenti e tutte le aste incidenti", "Applica in blocco", "Vincoli", "Un solo annullamento. Si copiano solo le aste interne, senza collegamenti automatici tra copie. SI: m, N, Pa.", "Nessuna modifica"],
  "pt-br": ["Modelagem em lote", "Seleção atual", "Índices (a partir de 0)", "Intervalo de coordenadas", "Inverter seleção", "Transladar", "Matriz linear", "Alinhar", "Cópias adicionais", "Carga total", "Por nó", "Barras internas", "Barras conectadas", "Copiar cargas e apoios", "Excluir nós correspondentes e todas as barras conectadas", "Aplicar lote", "Apoios", "Uma única etapa para desfazer. Apenas barras internas são copiadas, sem conexões automáticas entre cópias. SI: m, N, Pa.", "Sem alterações"],
  ru: ["Групповое моделирование", "Текущее выделение", "Индексы (с 0)", "Диапазон координат", "Инвертировать выделение", "Перенос", "Линейный массив", "Выровнять", "Дополнительные копии", "Суммарная нагрузка", "На каждый узел", "Внутренние стержни", "Примыкающие стержни", "Копировать нагрузки и закрепления", "Удалить выбранные узлы и все примыкающие стержни", "Применить группу", "Закрепления", "Один шаг отмены. Копируются только внутренние стержни, без автоматических связей между копиями. СИ: m, N, Pa.", "Без изменений"],
  uk: ["Групове моделювання", "Поточне виділення", "Індекси (від 0)", "Діапазон координат", "Інвертувати виділення", "Перемістити", "Лінійний масив", "Вирівняти", "Додаткові копії", "Сумарне навантаження", "На кожен вузол", "Внутрішні стрижні", "Прилеглі стрижні", "Копіювати навантаження й закріплення", "Видалити відповідні вузли й усі прилеглі стрижні", "Застосувати групу", "Закріплення", "Один крок скасування. Копіюються лише внутрішні стрижні, без автоматичного з'єднання копій. SI: m, N, Pa.", "Без змін"],
  ko: ["일괄 모델링", "현재 선택", "인덱스 (0부터)", "좌표 범위", "선택 반전", "평행 이동", "선형 배열", "정렬", "추가 복사 수", "전체 하중", "절점별", "내부 부재", "연결 부재", "하중 및 구속 복사", "일치하는 절점과 연결된 모든 부재 삭제", "일괄 적용", "구속", "한 단계로 실행 취소합니다. 내부 부재만 복사하며 복사본을 자동 연결하지 않습니다. SI: m, N, Pa.", "변경 없음"],
  ar: ["نمذجة دفعية", "التحديد الحالي", "الفهارس (من 0)", "نطاق الإحداثيات", "عكس التحديد", "إزاحة", "مصفوفة خطية", "محاذاة", "نسخ إضافية", "الحمل الكلي", "لكل عقدة", "القضبان الداخلية", "القضبان المتصلة", "نسخ الأحمال والقيود", "حذف العقد المطابقة وجميع القضبان المتصلة بها", "تطبيق الدفعة", "القيود", "خطوة تراجع واحدة. تُنسخ القضبان الداخلية فقط دون وصل النسخ تلقائيًا. SI: m, N, Pa.", "لا تغييرات"],
  fa: ["مدل‌سازی دسته‌ای", "انتخاب فعلی", "شاخص‌ها (از 0)", "بازه مختصات", "معکوس کردن انتخاب", "انتقال", "آرایه خطی", "هم‌ترازسازی", "نسخه‌های اضافی", "بار کل", "برای هر گره", "میله‌های داخلی", "میله‌های متصل", "کپی بارها و قیود", "حذف گره‌های منطبق و همه میله‌های متصل", "اعمال دسته‌ای", "قیود", "بازگردانی در یک مرحله. فقط میله‌های داخلی کپی می‌شوند؛ نسخه‌ها خودکار متصل نمی‌شوند. SI: m, N, Pa.", "بدون تغییر"],
  he: ["מידול באצווה", "הבחירה הנוכחית", "אינדקסים (מ־0)", "טווח קואורדינטות", "היפוך בחירה", "הזזה", "מערך קווי", "יישור", "עותקים נוספים", "עומס כולל", "לכל צומת", "מוטות פנימיים", "מוטות מחוברים", "העתקת עומסים ותמיכות", "מחיקת הצמתים התואמים וכל המוטות המחוברים", "החלת האצווה", "תמיכות", "ביטול בפעולה אחת. רק מוטות פנימיים מועתקים, ללא חיבור אוטומטי בין עותקים. SI: m, N, Pa.", "ללא שינויים"],
  hi: ["समूह मॉडलिंग", "वर्तमान चयन", "सूचकांक (0 से)", "निर्देशांक सीमा", "चयन उलटें", "स्थानांतरण", "रैखिक सरणी", "संरेखित करें", "अतिरिक्त प्रतियाँ", "कुल भार", "प्रति नोड", "आंतरिक छड़ें", "जुड़ी छड़ें", "भार और प्रतिबंध कॉपी करें", "मेल खाते नोड और उनसे जुड़ी सभी छड़ें हटाएँ", "समूह लागू करें", "प्रतिबंध", "एक चरण में पूर्ववत करें। केवल आंतरिक छड़ें कॉपी होती हैं; प्रतियाँ स्वतः नहीं जुड़तीं। SI: m, N, Pa.", "कोई बदलाव नहीं"],
  bn: ["দলগত মডেলিং", "বর্তমান নির্বাচন", "সূচক (0 থেকে)", "স্থানাঙ্কের সীমা", "নির্বাচন উল্টান", "স্থানান্তর", "রৈখিক বিন্যাস", "সারিবদ্ধ করুন", "অতিরিক্ত অনুলিপি", "মোট ভার", "প্রতি নোড", "ভিতরের দণ্ড", "সংযুক্ত দণ্ড", "ভার ও বাধা অনুলিপি করুন", "মিলে যাওয়া নোড ও সব সংযুক্ত দণ্ড মুছুন", "দলগতভাবে প্রয়োগ করুন", "বাধা", "এক ধাপে পূর্বাবস্থায় ফেরান। কেবল ভিতরের দণ্ড অনুলিপি হয়; অনুলিপিগুলি নিজে থেকে যুক্ত হয় না। SI: m, N, Pa.", "কোনো পরিবর্তন নেই"],
  ta: ["தொகுதி மாதிரியாக்கம்", "தற்போதைய தேர்வு", "குறியீடுகள் (0 முதல்)", "ஆய வரம்பு", "தேர்வை மாற்று", "நகர்த்து", "நேரியல் வரிசை", "சீரமை", "கூடுதல் நகல்கள்", "மொத்த சுமை", "ஒவ்வொரு முனைக்கும்", "உள் கம்பிகள்", "இணைந்த கம்பிகள்", "சுமைகள் மற்றும் கட்டுப்பாடுகளை நகலெடு", "பொருந்தும் முனைகள் மற்றும் இணைந்த அனைத்து கம்பிகளையும் நீக்கு", "தொகுதியைப் பயன்படுத்து", "கட்டுப்பாடுகள்", "ஒரே படியில் செயல்தவிர்க்கலாம். உள் கம்பிகள் மட்டுமே நகலெடுக்கப்படும்; நகல்கள் தானாக இணையாது. SI: m, N, Pa.", "மாற்றங்கள் இல்லை"],
  ur: ["گروہی ماڈلنگ", "موجودہ انتخاب", "اشاریے (0 سے)", "مختصات کی حد", "انتخاب الٹیں", "منتقل کریں", "خطی ترتیب", "ہم ترتیب کریں", "اضافی نقول", "کل بوجھ", "فی نوڈ", "اندرونی سلاخیں", "منسلک سلاخیں", "بوجھ اور پابندیاں نقل کریں", "مماثل نوڈز اور تمام منسلک سلاخیں حذف کریں", "گروہ لاگو کریں", "پابندیاں", "ایک مرحلے میں واپس کریں۔ صرف اندرونی سلاخیں نقل ہوتی ہیں؛ نقول خودکار طور پر نہیں جڑتیں۔ SI: m, N, Pa.", "کوئی تبدیلی نہیں"],
  id: ["Pemodelan massal", "Pilihan saat ini", "Indeks (dari 0)", "Rentang koordinat", "Balik pilihan", "Translasi", "Larik linear", "Sejajarkan", "Salinan tambahan", "Beban total", "Per simpul", "Batang internal", "Batang terhubung", "Salin beban dan tumpuan", "Hapus simpul yang cocok dan semua batang terhubung", "Terapkan massal", "Tumpuan", "Satu langkah urungkan. Hanya batang internal disalin, tanpa sambungan otomatis antar salinan. SI: m, N, Pa.", "Tidak ada perubahan"],
  ms: ["Pemodelan kelompok", "Pilihan semasa", "Indeks (dari 0)", "Julat koordinat", "Songsangkan pilihan", "Alih", "Tatasusunan linear", "Jajarkan", "Salinan tambahan", "Jumlah beban", "Setiap nod", "Batang dalaman", "Batang bersambung", "Salin beban dan kekangan", "Padam nod sepadan dan semua batang bersambung", "Gunakan kelompok", "Kekangan", "Satu langkah buat asal. Hanya batang dalaman disalin; salinan tidak disambung secara automatik. SI: m, N, Pa.", "Tiada perubahan"],
  vi: ["Dựng mô hình hàng loạt", "Lựa chọn hiện tại", "Chỉ số (từ 0)", "Khoảng tọa độ", "Đảo lựa chọn", "Tịnh tiến", "Dãy tuyến tính", "Căn chỉnh", "Bản sao bổ sung", "Tổng tải trọng", "Mỗi nút", "Thanh nội bộ", "Thanh liên kết", "Sao chép tải trọng và ràng buộc", "Xóa các nút khớp và mọi thanh liên kết", "Áp dụng hàng loạt", "Ràng buộc", "Hoàn tác trong một bước. Chỉ sao chép thanh nội bộ, không tự nối các bản sao. SI: m, N, Pa.", "Không thay đổi"],
  th: ["สร้างแบบจำลองแบบกลุ่ม", "รายการที่เลือก", "ดัชนี (เริ่มที่ 0)", "ช่วงพิกัด", "กลับการเลือก", "เลื่อนตำแหน่ง", "ชุดเรียงเชิงเส้น", "จัดแนว", "สำเนาเพิ่มเติม", "แรงรวม", "ต่อโหนด", "ชิ้นส่วนภายใน", "ชิ้นส่วนที่เชื่อมต่อ", "คัดลอกแรงและข้อยึดรั้ง", "ลบโหนดที่ตรงกันและชิ้นส่วนที่เชื่อมต่อทั้งหมด", "ใช้กับกลุ่ม", "ข้อยึดรั้ง", "เลิกทำในขั้นตอนเดียว คัดลอกเฉพาะชิ้นส่วนภายใน ไม่เชื่อมสำเนาโดยอัตโนมัติ SI: m, N, Pa.", "ไม่มีการเปลี่ยนแปลง"],
  tr: ["Toplu modelleme", "Geçerli seçim", "İndeksler (0'dan)", "Koordinat aralığı", "Seçimi tersine çevir", "Ötele", "Doğrusal dizi", "Hizala", "Ek kopyalar", "Toplam yük", "Düğüm başına", "İç çubuklar", "Bağlı çubuklar", "Yükleri ve mesnetleri kopyala", "Eşleşen düğümleri ve tüm bağlı çubukları sil", "Toplu uygula", "Mesnetler", "Tek adımda geri alınır. Yalnız iç çubuklar kopyalanır; kopyalar otomatik bağlanmaz. SI: m, N, Pa.", "Değişiklik yok"],
  pl: ["Modelowanie zbiorcze", "Bieżący wybór", "Indeksy (od 0)", "Zakres współrzędnych", "Odwróć wybór", "Przesuń", "Szyk liniowy", "Wyrównaj", "Dodatkowe kopie", "Obciążenie całkowite", "Na węzeł", "Pręty wewnętrzne", "Pręty przyległe", "Kopiuj obciążenia i podpory", "Usuń pasujące węzły i wszystkie przyległe pręty", "Zastosuj zbiorczo", "Podpory", "Jeden krok cofania. Kopiowane są tylko pręty wewnętrzne, bez automatycznych połączeń kopii. SI: m, N, Pa.", "Bez zmian"],
  cs: ["Hromadné modelování", "Aktuální výběr", "Indexy (od 0)", "Rozsah souřadnic", "Invertovat výběr", "Posunout", "Lineární pole", "Zarovnat", "Další kopie", "Celkové zatížení", "Na uzel", "Vnitřní pruty", "Navazující pruty", "Kopírovat zatížení a podpory", "Odstranit odpovídající uzly a všechny navazující pruty", "Použít hromadně", "Podpory", "Jeden krok zpět. Kopírují se pouze vnitřní pruty, bez automatického propojení kopií. SI: m, N, Pa.", "Beze změn"],
  ro: ["Modelare în lot", "Selecția curentă", "Indici (de la 0)", "Interval de coordonate", "Inversează selecția", "Translatează", "Matrice liniară", "Aliniază", "Copii suplimentare", "Sarcină totală", "Pe nod", "Bare interne", "Bare incidente", "Copiază sarcinile și reazemele", "Șterge nodurile corespunzătoare și toate barele incidente", "Aplică lotul", "Reazeme", "Un singur pas de anulare. Se copiază doar barele interne, fără conectare automată între copii. SI: m, N, Pa.", "Fără modificări"],
  nl: ["Batchmodellering", "Huidige selectie", "Indices (vanaf 0)", "Coördinatenbereik", "Selectie omkeren", "Verplaatsen", "Lineaire reeks", "Uitlijnen", "Extra kopieën", "Totale belasting", "Per knoop", "Interne staven", "Aangrenzende staven", "Belastingen en steunen kopiëren", "Overeenkomende knopen en alle aangrenzende staven verwijderen", "Batch toepassen", "Steunen", "Eén stap ongedaan maken. Alleen interne staven worden gekopieerd, zonder automatische verbindingen tussen kopieën. SI: m, N, Pa.", "Geen wijzigingen"],
  sv: ["Batchmodellering", "Aktuellt urval", "Index (från 0)", "Koordinatintervall", "Invertera urval", "Förflytta", "Linjär serie", "Justera", "Ytterligare kopior", "Total last", "Per nod", "Interna stänger", "Anslutna stänger", "Kopiera laster och stöd", "Ta bort matchande noder och alla anslutna stänger", "Tillämpa batch", "Stöd", "Ett ångra-steg. Endast interna stänger kopieras; kopior ansluts inte automatiskt. SI: m, N, Pa.", "Inga ändringar"],
  da: ["Batchmodellering", "Aktuelt valg", "Indekser (fra 0)", "Koordinatinterval", "Invertér valg", "Flyt", "Lineær række", "Justér", "Ekstra kopier", "Samlet last", "Pr. knude", "Interne stænger", "Tilsluttede stænger", "Kopiér laster og understøtninger", "Slet matchende knuder og alle tilsluttede stænger", "Anvend batch", "Understøtninger", "Ét fortryd-trin. Kun interne stænger kopieres, uden automatisk forbindelse mellem kopier. SI: m, N, Pa.", "Ingen ændringer"],
  no: ["Batchmodellering", "Gjeldende utvalg", "Indekser (fra 0)", "Koordinatintervall", "Inverter utvalg", "Flytt", "Lineær rekke", "Juster", "Ekstra kopier", "Samlet last", "Per node", "Interne staver", "Tilkoblede staver", "Kopier laster og opplager", "Slett samsvarende noder og alle tilkoblede staver", "Bruk batch", "Opplager", "Ett angretrinn. Bare interne staver kopieres, uten automatisk forbindelse mellom kopier. SI: m, N, Pa.", "Ingen endringer"],
  fi: ["Erämallinnus", "Nykyinen valinta", "Indeksit (alkaen 0)", "Koordinaattiväli", "Käännä valinta", "Siirrä", "Lineaarinen sarja", "Kohdista", "Lisäkopiot", "Kokonaiskuorma", "Solmua kohti", "Sisäiset sauvat", "Liittyvät sauvat", "Kopioi kuormat ja tuet", "Poista vastaavat solmut ja kaikki liittyvät sauvat", "Käytä erää", "Tuet", "Yksi kumoamisvaihe. Vain sisäiset sauvat kopioidaan, ilman kopioiden automaattisia liitoksia. SI: m, N, Pa.", "Ei muutoksia"],
  el: ["Μαζική μοντελοποίηση", "Τρέχουσα επιλογή", "Δείκτες (από 0)", "Εύρος συντεταγμένων", "Αντιστροφή επιλογής", "Μετατόπιση", "Γραμμική διάταξη", "Ευθυγράμμιση", "Πρόσθετα αντίγραφα", "Συνολικό φορτίο", "Ανά κόμβο", "Εσωτερικές ράβδοι", "Συνδεδεμένες ράβδοι", "Αντιγραφή φορτίων και στηρίξεων", "Διαγραφή αντίστοιχων κόμβων και όλων των συνδεδεμένων ράβδων", "Μαζική εφαρμογή", "Στηρίξεις", "Ένα βήμα αναίρεσης. Αντιγράφονται μόνο οι εσωτερικές ράβδοι, χωρίς αυτόματες συνδέσεις αντιγράφων. SI: m, N, Pa.", "Χωρίς αλλαγές"],
  sw: ["Uundaji kwa kundi", "Uteuzi wa sasa", "Faharasa (kutoka 0)", "Masafa ya viwianishi", "Geuza uteuzi", "Hamisha", "Safu ya mstari", "Panga", "Nakala za ziada", "Mzigo wote", "Kwa kila nodi", "Fimbo za ndani", "Fimbo zilizounganishwa", "Nakili mizigo na vizuizi", "Futa nodi zinazolingana na fimbo zote zilizounganishwa", "Tekeleza kundi", "Vizuizi", "Hatua moja ya kutendua. Fimbo za ndani pekee hunakiliwa; nakala haziunganishwi kiotomatiki. SI: m, N, Pa.", "Hakuna mabadiliko"],
};

export function getModelBatchCopy(language: string) {
  const row = rows[language.toLowerCase()] ?? rows.en;
  return Object.fromEntries(keys.map((key, index) => [key, row[index]])) as Record<typeof keys[number], string>;
}
