use crate::catalog::descriptors::{
    built_in_bridge_descriptor, built_in_explicit_bridge_descriptor,
    built_in_explicit_transform_descriptor, built_in_transform_descriptor,
};
use kyuubiki_protocol::OperatorDescriptor;

pub(crate) fn bridge_descriptors() -> Vec<OperatorDescriptor> {
    vec![
        built_in_bridge_descriptor(
            "bridge.temperature_field_to_thermo_quad_2d",
            "thermo_mechanical",
            "thermal_plane_quad_2d",
            "Bridge a heat quad temperature field into a thermal quad structural model.",
            &["workflow_bridge", "temperature_field", "quad", "2d"],
        ),
        built_in_explicit_bridge_descriptor(
            "bridge.temperature_field_to_thermo_triangle_2d",
            "thermo_mechanical",
            "thermal_plane_triangle_2d",
            "Bridge a heat triangle temperature field into a thermal triangle structural model.",
            &["workflow_bridge", "temperature_field", "triangle", "2d"],
            "result/heat_plane_triangle_2d",
            "heat_plane_triangle_2d_result",
            "study_model/thermal_plane_triangle_2d",
            "thermal_plane_triangle_2d_model",
        ),
        built_in_bridge_descriptor(
            "bridge.electrostatic_field_to_heat_quad_2d",
            "electromagnetic",
            "electrostatic_to_heat_quad_2d",
            "Bridge electrostatic quad fields or stored-energy density into nodal heat loads for a downstream heat quad model.",
            &[
                "workflow_bridge",
                "electrostatic",
                "stored_energy",
                "heat",
                "quad",
                "2d",
            ],
        ),
        built_in_explicit_bridge_descriptor(
            "bridge.electrostatic_field_to_heat_triangle_2d",
            "electromagnetic",
            "electrostatic_to_heat_triangle_2d",
            "Bridge electrostatic triangle fields or stored-energy density into nodal heat loads for a downstream heat triangle model.",
            &[
                "workflow_bridge",
                "electrostatic",
                "stored_energy",
                "heat",
                "triangle",
                "2d",
            ],
            "result/electrostatic_plane_triangle_2d",
            "electrostatic_plane_triangle_2d_result",
            "study_model/heat_plane_triangle_2d",
            "heat_plane_triangle_2d_model",
        ),
        built_in_explicit_bridge_descriptor(
            "bridge.magnetostatic_field_to_heat_quad_2d",
            "electromagnetic",
            "magnetostatic_to_heat_quad_2d",
            "Bridge magnetostatic quad fields or stored magnetic energy density into heat loads for downstream thermal solves.",
            &[
                "verified",
                "workflow_bridge",
                "magnetostatic",
                "stored_energy",
                "heat",
                "quad",
                "2d",
            ],
            "result/magnetostatic_plane_quad_2d",
            "magnetostatic_plane_quad_2d_result",
            "study_model/heat_plane_quad_2d",
            "heat_plane_quad_2d_model",
        ),
        built_in_transform_descriptor(
            "transform.first_available",
            "multi_domain",
            "first_available",
            "Merge two branch payloads by forwarding the first available incoming artifact.",
            &["transform", "merge", "branch", "headless_safe"],
        ),
        built_in_explicit_transform_descriptor(
            "transform.merge_summary_pair",
            "multi_domain",
            "merge_summary_pair",
            "Merge two summary payloads into one namespaced summary artifact.",
            &["transform", "summary", "merge", "headless_safe"],
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
        ),
        built_in_explicit_transform_descriptor(
            "transform.compare_summary_pair",
            "multi_domain",
            "compare_summary_pair",
            "Compare two summary payloads and emit delta, ratio, and percent-change metrics for shared numeric fields.",
            &[
                "transform",
                "summary",
                "compare",
                "benchmark",
                "headless_safe",
            ],
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
        ),
        built_in_explicit_transform_descriptor(
            "transform.aggregate_summary_collection",
            "multi_domain",
            "aggregate_summary_collection",
            "Aggregate multiple summary payloads into min/max/mean/span benchmark metrics for shared numeric fields.",
            &[
                "transform",
                "summary",
                "aggregate",
                "benchmark",
                "headless_safe",
            ],
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
        ),
        built_in_transform_descriptor(
            "transform.normalize_summary_fields",
            "multi_domain",
            "normalize_summary_fields",
            "Rename and normalize summary fields with scale, offset, and clamp rules before downstream comparison or aggregation.",
            &[
                "transform",
                "summary",
                "normalize",
                "mapping",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.select_best_summary",
            "multi_domain",
            "select_best_summary",
            "Score multiple summary payloads against weighted min/max criteria and emit the best candidate summary with selection metadata.",
            &[
                "transform",
                "summary",
                "select",
                "ranking",
                "benchmark",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.evaluate_thermal_guard",
            "multi_domain",
            "evaluate_thermal_guard",
            "Evaluate a thermal or thermo-mechanical diagnostic payload against visible threshold rules and emit pass, warn, or block guard state.",
            &[
                "transform",
                "thermal",
                "guard",
                "threshold",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.benchmark_coupled_heat_pair",
            "multi_domain",
            "benchmark_coupled_heat_pair",
            "Benchmark paired heat or thermo-mechanical summaries against weighted min/max criteria and emit a side-by-side winner breakdown.",
            &[
                "transform",
                "thermal",
                "benchmark",
                "compare",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.evaluate_magnetostatic_guard",
            "electromagnetic",
            "evaluate_magnetostatic_guard",
            "Evaluate a magnetostatic diagnostic payload against visible threshold rules and emit pass, warn, or block guard state.",
            &[
                "transform",
                "magnetostatic",
                "guard",
                "threshold",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.benchmark_magnetostatic_pair",
            "electromagnetic",
            "benchmark_magnetostatic_pair",
            "Benchmark paired magnetostatic summaries against weighted min/max criteria and emit a side-by-side winner breakdown.",
            &[
                "transform",
                "magnetostatic",
                "benchmark",
                "compare",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.evaluate_cfd_guard",
            "fluid",
            "evaluate_cfd_guard",
            "Evaluate CFD diagnostics against visible threshold rules and emit pass, warn, or block guard state.",
            &[
                "transform",
                "fluid",
                "cfd",
                "guard",
                "threshold",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.benchmark_cfd_pair",
            "fluid",
            "benchmark_cfd_pair",
            "Benchmark paired CFD summaries against weighted min/max criteria and emit a side-by-side winner breakdown.",
            &[
                "transform",
                "fluid",
                "cfd",
                "benchmark",
                "compare",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.score_cfd_quality",
            "fluid",
            "score_cfd_quality",
            "Score CFD diagnostics into a single optimization objective with visible penalties for divergence, Reynolds number, dissipation, and field spans.",
            &[
                "transform",
                "fluid",
                "cfd",
                "objective",
                "optimization",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.compose_diagnostics_bundle",
            "multi_domain",
            "compose_diagnostics_bundle",
            "Compose multiple diagnostics payloads into a single workflow diagnostics bundle with domain, source, and metric-group metadata.",
            &[
                "transform",
                "diagnostics",
                "bundle",
                "compose",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.evaluate_diagnostics_bundle_guard",
            "multi_domain",
            "evaluate_diagnostics_bundle_guard",
            "Evaluate a workflow diagnostics bundle against visible warn/block rules and emit a unified guard decision.",
            &[
                "transform",
                "diagnostics",
                "bundle",
                "guard",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.compose_diagnostics_report_payload",
            "multi_domain",
            "compose_diagnostics_report_payload",
            "Compose a diagnostics bundle and guard result into a standard report payload for downstream export operators.",
            &[
                "transform",
                "diagnostics",
                "bundle",
                "report",
                "compose",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.select_focus_payload",
            "multi_domain",
            "select_focus_payload",
            "Select one standard focus payload by metric id from a diagnostics report payload for downstream workflow chaining.",
            &[
                "transform",
                "diagnostics",
                "focus",
                "select",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.compose_focus_chain_input",
            "multi_domain",
            "compose_focus_chain_input",
            "Compose a selected focus payload into a standard downstream chain input with bindings and orchestration annotations.",
            &[
                "transform",
                "diagnostics",
                "focus",
                "chain",
                "compose",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.compose_focus_bridge_request",
            "multi_domain",
            "compose_focus_bridge_request",
            "Compose a focus chain input into a standard bridge request payload with explicit bridge operator and bridge config.",
            &[
                "transform",
                "diagnostics",
                "focus",
                "bridge",
                "compose",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.resolve_focus_bridge_execution",
            "multi_domain",
            "resolve_focus_bridge_execution",
            "Resolve a focus bridge request into a directly executable bridge payload with operator id, source payload, and bridge config.",
            &[
                "transform",
                "diagnostics",
                "focus",
                "bridge",
                "execute",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.execute_focus_bridge_execution",
            "multi_domain",
            "execute_focus_bridge_execution",
            "Execute a resolved focus bridge execution payload and emit the resulting bridge output with execution lineage.",
            &[
                "transform",
                "diagnostics",
                "focus",
                "bridge",
                "run",
                "headless_safe",
            ],
        ),
    ]
}
