use crate::catalog::bridges::bridge_descriptors;
use crate::catalog::descriptors::built_in_solver_descriptor;
use crate::catalog::reporting::reporting_descriptors;
use kyuubiki_protocol::OperatorDescriptor;

pub fn built_in_operator_descriptors() -> Vec<OperatorDescriptor> {
    let mut descriptors = solver_descriptors();
    descriptors.extend(bridge_descriptors());
    descriptors.extend(reporting_descriptors());
    descriptors
}

fn solver_descriptors() -> Vec<OperatorDescriptor> {
    vec![
        built_in_solver_descriptor(
            "solve.bar_1d",
            "mechanical",
            "bar_1d",
            "Solve a 1D axial bar model and expose displacement and stress results.",
            &["verified", "mechanical", "bar", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.acoustic_bar_1d",
            "acoustic",
            "acoustic_bar_1d",
            "Solve a frequency-domain 1D acoustic duct model with pressure, SPL, particle velocity, and intensity outputs.",
            &[
                "verified",
                "acoustic",
                "wave",
                "frequency_domain",
                "bar",
                "1d",
            ],
        ),
        built_in_solver_descriptor(
            "solve.thermal_bar_1d",
            "thermo_mechanical",
            "thermal_bar_1d",
            "Solve a thermal 1D bar model with expansion-driven axial response.",
            &["verified", "thermo_mechanical", "bar", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.heat_bar_1d",
            "thermal",
            "heat_bar_1d",
            "Solve a 1D heat-conduction bar model and expose temperature and heat-flux results.",
            &["verified", "thermal", "heat", "bar", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.frame_3d",
            "mechanical",
            "frame_3d",
            "Solve a 3D frame model with six-DOF nodes and verified baseline coverage.",
            &["verified", "mechanical", "frame", "3d"],
        ),
        built_in_solver_descriptor(
            "solve.thermal_frame_3d",
            "thermo_mechanical",
            "thermal_frame_3d",
            "Solve a thermal 3D frame model with restrained expansion and temperature gradients.",
            &["verified", "thermo_mechanical", "frame", "3d"],
        ),
        built_in_solver_descriptor(
            "solve.electrostatic_bar_1d",
            "electromagnetic",
            "electrostatic_bar_1d",
            "Solve a 1D electrostatic bar model and expose potential, field, and flux results.",
            &["verified", "electromagnetic", "electrostatic", "bar", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.magnetostatic_bar_1d",
            "electromagnetic",
            "magnetostatic_bar_1d",
            "Solve a 1D magnetostatic bar model and expose magnetic potential, H-field, and B-field results.",
            &["verified", "electromagnetic", "magnetostatic", "bar", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.advection_diffusion_bar_1d",
            "transport",
            "advection_diffusion_bar_1d",
            "Solve a 1D steady advection-diffusion transport model and expose concentration, flux, and Peclet diagnostics.",
            &["smoke", "transport", "advection", "diffusion", "bar", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.magnetostatic_plane_triangle_2d",
            "electromagnetic",
            "magnetostatic_plane_triangle_2d",
            "Solve a 2D magnetostatic triangle model with vector potential, H-field, B-field, and stored magnetic energy outputs.",
            &[
                "verified",
                "electromagnetic",
                "magnetostatic",
                "plane",
                "triangle",
                "2d",
            ],
        ),
        built_in_solver_descriptor(
            "solve.magnetostatic_plane_quad_2d",
            "electromagnetic",
            "magnetostatic_plane_quad_2d",
            "Solve a 2D magnetostatic quad model with vector potential, H-field, B-field, and stored magnetic energy outputs.",
            &[
                "verified",
                "electromagnetic",
                "magnetostatic",
                "plane",
                "quad",
                "2d",
            ],
        ),
        built_in_solver_descriptor(
            "solve.electrostatic_plane_triangle_2d",
            "electromagnetic",
            "electrostatic_plane_triangle_2d",
            "Solve a 2D electrostatic triangle model and expose potential, field, and flux results.",
            &[
                "verified",
                "electromagnetic",
                "electrostatic",
                "plane",
                "triangle",
                "2d",
            ],
        ),
        built_in_solver_descriptor(
            "solve.electrostatic_plane_quad_2d",
            "electromagnetic",
            "electrostatic_plane_quad_2d",
            "Solve a 2D electrostatic quad model and expose potential, field, and flux results.",
            &[
                "verified",
                "electromagnetic",
                "electrostatic",
                "plane",
                "quad",
                "2d",
            ],
        ),
        built_in_solver_descriptor(
            "solve.heat_plane_triangle_2d",
            "thermal",
            "heat_plane_triangle_2d",
            "Solve a 2D heat-conduction triangle model and expose temperature and heat-flux fields.",
            &["verified", "thermal", "heat", "plane", "triangle", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.heat_plane_quad_2d",
            "thermal",
            "heat_plane_quad_2d",
            "Solve a 2D heat-conduction quad model and expose verified temperature/flux fields.",
            &["verified", "thermal", "heat", "plane", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.stokes_flow_quad_2d",
            "fluid",
            "stokes_flow_quad_2d",
            "Solve a low-Reynolds steady 2D Stokes flow quad model and expose velocity, pressure, divergence, and Reynolds diagnostics.",
            &["verified", "fluid", "cfd", "stokes", "flow", "quad", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.thermal_truss_2d",
            "thermo_mechanical",
            "thermal_truss_2d",
            "Solve a thermal 2D truss model with expansion-driven axial response.",
            &["verified", "thermo_mechanical", "truss", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.thermal_plane_quad_2d",
            "thermo_mechanical",
            "thermal_plane_quad_2d",
            "Solve a thermo-mechanical 2D quad model with structural and thermal coupling outputs.",
            &["verified", "thermo_mechanical", "plane", "quad", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.plane_triangle_2d",
            "mechanical",
            "plane_triangle_2d",
            "Solve a 2D plane triangle model and expose displacement and stress results.",
            &["verified", "mechanical", "plane", "triangle", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.thermal_plane_triangle_2d",
            "thermo_mechanical",
            "thermal_plane_triangle_2d",
            "Solve a thermo-mechanical 2D triangle model with thermal expansion outputs.",
            &["verified", "thermo_mechanical", "plane", "triangle", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.plane_quad_2d",
            "mechanical",
            "plane_quad_2d",
            "Solve a 2D plane quad model and expose displacement and stress results.",
            &["verified", "mechanical", "plane", "quad", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.thermal_truss_3d",
            "thermo_mechanical",
            "thermal_truss_3d",
            "Solve a thermal 3D truss model with expansion-driven axial response.",
            &["verified", "thermo_mechanical", "truss", "3d"],
        ),
        built_in_solver_descriptor(
            "solve.torsion_1d",
            "mechanical",
            "torsion_1d",
            "Solve a 1D torsion model and expose rotation, torque, and stress results.",
            &["verified", "mechanical", "torsion", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.spring_1d",
            "mechanical",
            "spring_1d",
            "Solve a 1D spring chain model and expose nodal displacement and spring force results.",
            &["verified", "mechanical", "spring", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.truss_2d",
            "mechanical",
            "truss_2d",
            "Solve a 2D truss model and expose nodal displacement and axial stress results.",
            &["verified", "mechanical", "truss", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.truss_3d",
            "mechanical",
            "truss_3d",
            "Solve a 3D truss model and expose spatial displacement and axial stress results.",
            &["verified", "mechanical", "truss", "3d"],
        ),
        built_in_solver_descriptor(
            "solve.frame_2d",
            "mechanical",
            "frame_2d",
            "Solve a 2D frame model and expose nodal displacement, rotation, and bending results.",
            &["verified", "mechanical", "frame", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.beam_1d",
            "mechanical",
            "beam_1d",
            "Solve a 1D beam bending model and expose displacement, rotation, and moment results.",
            &["verified", "mechanical", "beam", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.spring_2d",
            "mechanical",
            "spring_2d",
            "Solve a 2D spring network model and expose planar displacement and spring force results.",
            &["verified", "mechanical", "spring", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.spring_3d",
            "mechanical",
            "spring_3d",
            "Solve a 3D spring network model and expose spatial displacement and spring force results.",
            &["verified", "mechanical", "spring", "3d"],
        ),
        built_in_solver_descriptor(
            "solve.thermal_beam_1d",
            "thermo_mechanical",
            "thermal_beam_1d",
            "Solve a thermal 1D beam model with temperature-gradient-induced bending response.",
            &["verified", "thermo_mechanical", "beam", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.thermal_frame_2d",
            "thermo_mechanical",
            "thermal_frame_2d",
            "Solve a thermal 2D frame model and expose coupled displacement, axial force, and moment results.",
            &["verified", "thermo_mechanical", "frame", "2d"],
        ),
        built_in_solver_descriptor(
            "solve.modal_frame_2d",
            "mechanical",
            "modal_frame_2d",
            "Solve a 2D frame modal model and emit natural frequencies with normalized mode-shape vectors.",
            &[
                "verified",
                "mechanical",
                "modal",
                "vibration",
                "frame",
                "2d",
            ],
        ),
        built_in_solver_descriptor(
            "solve.modal_frame_3d",
            "mechanical",
            "modal_frame_3d",
            "Solve a 3D frame modal model and emit natural frequencies with six-DOF mode-shape vectors.",
            &[
                "verified",
                "mechanical",
                "modal",
                "vibration",
                "frame",
                "3d",
            ],
        ),
        built_in_solver_descriptor(
            "solve.nonlinear_spring_1d",
            "mechanical",
            "nonlinear_spring_1d",
            "Solve a nonlinear 1D spring chain with load stepping, tangent stiffness, and Newton convergence diagnostics.",
            &["verified", "mechanical", "nonlinear", "spring", "1d"],
        ),
        built_in_solver_descriptor(
            "solve.contact_gap_1d",
            "mechanical",
            "contact_gap_1d",
            "Solve a 1D gap-contact model with active-set contact state, penetration checks, and reaction output.",
            &["verified", "mechanical", "contact", "gap", "1d"],
        ),
    ]
}
