use crate::catalog::descriptors::{
    built_in_explicit_transform_descriptor, built_in_transform_descriptor,
};
use kyuubiki_protocol::OperatorDescriptor;

pub(super) fn workflow_summary_transform_descriptors() -> Vec<OperatorDescriptor> {
    vec![
        built_in_transform_descriptor(
            "transform.first_available",
            "multi_domain",
            "first_available",
            "Merge two branch payloads by forwarding the first available incoming artifact.",
            &["transform", "merge", "branch", "headless_safe"],
        ),
        built_in_explicit_transform_descriptor(
            "transform.merge_summary_pair",
            "multi_domain",
            "merge_summary_pair",
            "Merge two summary payloads into one namespaced summary artifact.",
            &["transform", "summary", "merge", "headless_safe"],
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
        ),
        built_in_explicit_transform_descriptor(
            "transform.compare_summary_pair",
            "multi_domain",
            "compare_summary_pair",
            "Compare two summary payloads and emit delta, ratio, and percent-change metrics for shared numeric fields.",
            &[
                "transform",
                "summary",
                "compare",
                "benchmark",
                "headless_safe",
            ],
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
        ),
        built_in_explicit_transform_descriptor(
            "transform.aggregate_summary_collection",
            "multi_domain",
            "aggregate_summary_collection",
            "Aggregate multiple summary payloads into min/max/mean/span benchmark metrics for shared numeric fields.",
            &[
                "transform",
                "summary",
                "aggregate",
                "benchmark",
                "headless_safe",
            ],
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
            "artifact/result_summary",
            "result_summary",
        ),
        built_in_transform_descriptor(
            "transform.normalize_summary_fields",
            "multi_domain",
            "normalize_summary_fields",
            "Rename and normalize summary fields with scale, offset, and clamp rules before downstream comparison or aggregation.",
            &[
                "transform",
                "summary",
                "normalize",
                "mapping",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.select_best_summary",
            "multi_domain",
            "select_best_summary",
            "Score multiple summary payloads against weighted min/max criteria and emit the best candidate summary with selection metadata.",
            &[
                "transform",
                "summary",
                "select",
                "ranking",
                "benchmark",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.compose_quality_objective",
            "multi_domain",
            "compose_quality_objective",
            "Combine domain quality scores into one weighted optimization objective for multiphysics studies.",
            &[
                "transform",
                "summary",
                "objective",
                "optimization",
                "multiphysics",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.rank_quality_candidates",
            "multi_domain",
            "rank_quality_candidates",
            "Rank candidate designs by composite domain quality objectives and emit the best ready candidate.",
            &[
                "transform",
                "summary",
                "ranking",
                "objective",
                "optimization",
                "multiphysics",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.prepare_quality_next_round_request",
            "multi_domain",
            "prepare_quality_next_round_request",
            "Convert quality candidate rankings into a stop, continue, or replan request for the next exploration round.",
            &[
                "transform",
                "summary",
                "next_round",
                "objective",
                "automation",
                "optimization",
                "multiphysics",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.compose_quality_lineage_report",
            "multi_domain",
            "compose_quality_lineage_report",
            "Compose a machine-readable lineage report from quality ranking, next-round request, sweep plan, and expanded cases.",
            &[
                "transform",
                "summary",
                "lineage",
                "provenance",
                "automation",
                "optimization",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.build_quality_parameter_sweep_plan",
            "multi_domain",
            "build_quality_parameter_sweep_plan",
            "Convert a quality next-round request into a standard parameter sweep plan for continued exploration.",
            &[
                "transform",
                "summary",
                "parameter_sweep",
                "next_round",
                "automation",
                "optimization",
                "multiphysics",
                "headless_safe",
            ],
        ),
        built_in_transform_descriptor(
            "transform.materialize_quality_sweep_expansion",
            "multi_domain",
            "materialize_quality_sweep_expansion",
            "Materialize a quality parameter sweep plan into expand_parameter_sweep payload and config.",
            &[
                "transform",
                "summary",
                "parameter_sweep",
                "materialize",
                "automation",
                "optimization",
                "headless_safe",
            ],
        ),
    ]
}
