import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function read(relativePath) {
  return fs.readFileSync(path.join(ROOT, relativePath), "utf8");
}

test("hub shell defines a least-privilege main-window capability", () => {
  const tauriConfig = JSON.parse(read("src-tauri/tauri.conf.json"));
  const capability = JSON.parse(read("src-tauri/capabilities/main.json"));
  const permissions = read("src-tauri/permissions/hub.toml");

  assert.equal(tauriConfig.app.windows[0]?.label, "main");
  assert.equal(capability.identifier, "main");
  assert.deepEqual(capability.windows, ["main"]);
  assert.ok(Array.isArray(capability.permissions));
  assert.ok(capability.permissions.includes("core:default"));
  assert.ok(capability.permissions.includes("allow-guarded-mutation-action"));
  assert.ok(capability.permissions.includes("allow-service-status"));
  assert.ok(capability.permissions.includes("allow-project-bundle-inspect"));
  assert.ok(capability.permissions.includes("allow-hub-environment"));
  assert.match(permissions, /identifier = "allow-service-status"/);
  assert.match(permissions, /commands\.allow = \["service_status"\]/);
  assert.match(permissions, /identifier = "allow-guarded-mutation-action"/);
});

test("hub shell exposes the desktop information architecture", () => {
  const html = read("ui/index.html");

  assert.match(html, /data-target="projects"/);
  assert.match(html, /data-target="runtimes"/);
  assert.match(html, /data-target="deploy"/);
  assert.match(html, /data-target="observe"/);
  assert.match(html, /data-target="tools"/);
  assert.match(html, /Open workbench/);
  assert.match(html, /data-action="open-installer"/);
  assert.match(html, /data-projects-page="guides"/);
  assert.match(html, /data-action="open-docs-index"/);
  assert.match(html, /data-action="open-current-line-doc"/);
  assert.match(html, /data-action="open-operations-doc"/);
  assert.match(html, /data-action="open-troubleshooting-doc"/);
  assert.match(html, /Start local stack/);
  assert.match(html, /Stage desktop package/);
  assert.match(html, /Desktop status/);
  assert.match(html, /Build host bundles/);
  assert.match(html, /Verify desktop release/);
  assert.match(html, /hub-desktop-status-output/);
  assert.match(html, /hub-action-state/);
  assert.match(html, /hot-runtime-log-service/);
  assert.match(html, /hot-runtime-log-auto/);
  assert.match(html, /hot-runtime-log-interval/);
  assert.match(html, /hot-runtime-log-follow-state/);
  assert.match(html, /hot-refresh-log/);
  assert.match(html, /hot-copy-log-view/);
  assert.match(html, /hot-clear-log-view/);
  assert.match(html, /hot-runtime-log-output/);
  assert.match(html, /Copy tail exports a sanitized view, not the raw log file\./);
  assert.match(html, /observe-runtime-status-output/);
  assert.match(html, /observe-runtime-status/);
  assert.match(html, /observe-hot-status/);
  assert.match(html, /observe-hot-mode/);
  assert.match(html, /observe-hot-log-service/);
  assert.match(html, /observe-hot-log-output/);
  assert.match(html, /observe-hot-follow-state/);
  assert.match(html, /observe-runtime-log-service/);
  assert.match(html, /observe-runtime-log-auto/);
  assert.match(html, /observe-runtime-log-follow-state/);
  assert.match(html, /observe-refresh-runtime-log/);
  assert.match(html, /observe-copy-runtime-log/);
  assert.match(html, /observe-runtime-log-output/);
  assert.match(html, /assistant-engine-state/);
  assert.match(html, /assistant-mode-local/);
  assert.match(html, /assistant-mode-llm/);
  assert.match(html, /assistant-local-cards/);
  assert.match(html, /Docs &amp; guides/);
  assert.match(html, /assistant-llm-panel/);
  assert.match(html, /assistant-base-url/);
  assert.match(html, /assistant-api-key/);
  assert.match(html, /assistant-model-preset/);
  assert.match(html, /assistant-model-name/);
  assert.match(html, /assistant-endpoint-policy/);
  assert.match(html, /assistant-request-plan/);
  assert.match(html, /assistant-execute-plan/);
  assert.match(html, /assistant-plan-actions/);
  assert.match(html, /assistant-output/);
  assert.match(html, /assistant-audit-list/);
  assert.match(html, /Workload library/);
  assert.match(html, /workload-catalog-url/);
  assert.match(html, /workload-label/);
  assert.match(html, /workload-import-input/);
  assert.match(html, /workload-library-list/);
  assert.match(html, /workload-library-output/);
  assert.match(html, /workflow-catalog-label/);
  assert.match(html, /workflow-catalog-title/);
  assert.match(html, /workflow-catalog-copy/);
  assert.match(html, /workflow-catalog-refresh/);
  assert.match(html, /workflow-catalog-list/);
  assert.match(html, /workflow-catalog-output/);
  assert.match(html, /Register current bundle/);
  assert.match(html, /Sync local control plane/);
  assert.match(html, /Sync remote catalog/);
  assert.match(html, /Export library JSON/);
  assert.match(html, /Import library JSON/);
  assert.match(html, /Clear library/);
  assert.match(html, /data-workload-family-filter="all"/);
  assert.match(html, /data-workload-family-filter="axial_and_springs"/);
  assert.match(html, /data-workload-family-filter="beams_and_frames"/);
  assert.match(html, /data-workload-family-filter="trusses"/);
  assert.match(html, /data-workload-family-filter="planes"/);
  assert.match(html, /project-bundle-path/);
  assert.match(html, /project-bundle-compare-path/);
  assert.match(html, /project-bundle-out-path/);
  assert.match(html, /recent-bundle-list/);
  assert.match(html, /recent-compare-list/);
  assert.match(html, /recent-output-list/);
  assert.match(html, /favorite-action-list/);
  assert.match(html, /recent-action-list/);
  assert.match(html, /data-history-filter="all"/);
  assert.match(html, /data-history-filter="failed"/);
  assert.match(html, /data-history-filter="inspect"/);
  assert.match(html, /data-history-filter="normalize"/);
  assert.match(html, /data-history-filter="diff"/);
  assert.match(html, /data-history-manage="keep-failed"/);
  assert.match(html, /data-history-manage="import-json"/);
  assert.match(html, /data-history-manage="export-json"/);
  assert.match(html, /data-history-manage="clear"/);
  assert.match(html, /history-import-input/);
  assert.match(html, /Generate plan/);
  assert.match(html, /Inspect \.kyuubiki/);
  assert.match(html, /Validate \.kyuubiki/);
  assert.match(html, /Normalize bundle/);
  assert.match(html, /Unpack bundle/);
  assert.match(html, /Pack project/);
  assert.match(html, /Diff bundles/);
});

test("hub shell registers section switching behavior", () => {
  const js = read("ui/app.js");
  const bridge = read("ui/shared/tauri-bridge.js");

  assert.match(js, /HUB_I18N/);
  assert.match(js, /setSection/);
  assert.match(js, /runAction/);
  assert.match(js, /setBusy/);
  assert.match(js, /setDesktopStatusOutput/);
  assert.match(js, /setAssistantOutput/);
  assert.match(js, /setProjectBundleOutput/);
  assert.match(js, /currentAssistantSnapshot/);
  assert.match(js, /renderAssistantContext/);
  assert.match(js, /setAssistantMode/);
  assert.match(js, /buildHubAssistantLocalCards/);
  assert.match(js, /renderHubAssistantLocalCards/);
  assert.match(js, /requestHubAssistantPlan/);
  assert.match(js, /validateAssistantBaseUrl/);
  assert.match(js, /updateAssistantEndpointPolicy/);
  assert.match(js, /renderHubAssistantPlan/);
  assert.match(js, /executeHubAssistantAction/);
  assert.match(js, /executeHubAssistantPlan/);
  assert.match(js, /loadHubAssistantAudit/);
  assert.match(js, /persistHubAssistantAudit/);
  assert.match(js, /rememberHubAssistantAudit/);
  assert.match(js, /renderHubAssistantAudit/);
  assert.match(js, /confirmHubAssistantAction/);
  assert.match(js, /assistantRiskLevel/);
  assert.match(js, /mirrorHubAssistantAuditToSecurityEvents/);
  assert.match(js, /updateHubAssistantAuditDelivery/);
  assert.match(js, /currentOrchestratorBaseUrl/);
  assert.match(js, /currentAssistantAuditContext/);
  assert.match(js, /assistantDeliveryStateClass/);
  assert.match(js, /loadHubRecents/);
  assert.match(js, /loadHubWorkloadLibrary/);
  assert.match(js, /persistHubWorkloadLibrary/);
  assert.match(js, /loadHubAssistantSettings/);
  assert.match(js, /persistHubAssistantSettings/);
  assert.match(js, /loadHubAssistantTrustedHosts/);
  assert.match(js, /persistHubAssistantTrustedHosts/);
  assert.match(js, /ensureAssistantHostTrust/);
  assert.match(js, /confirmHubDesktopAction/);
  assert.match(js, /saveProjectBundleRecents/);
  assert.match(js, /saveHubWorkloadLibrary/);
  assert.match(js, /renderHubWorkloadLibrary/);
  assert.match(js, /currentWorkflowCatalogUrl/);
  assert.match(js, /fetchWorkflowCatalog/);
  assert.match(js, /renderWorkflowCatalog/);
  assert.match(js, /runWorkflowCatalogSample/);
  assert.match(js, /waitForWorkflowJob/);
  assert.match(js, /builtInWorkflowSampleInputArtifacts/);
  assert.match(js, /normalizeHubWorkloadEntry/);
  assert.match(js, /mergeHubWorkloadLibrary/);
  assert.match(js, /workloadIdentity/);
  assert.match(js, /matchesWorkloadFamilyFilter/);
  assert.match(js, /workloadProvenanceLabel/);
  assert.match(js, /workloadProvenanceHost/);
  assert.match(js, /currentLocalWorkloadCatalogUrl/);
  assert.match(js, /ensureDefaultWorkloadCatalogUrl/);
  assert.match(js, /inferDownloadFilename/);
  assert.match(js, /downloadHubBlob/);
  assert.match(js, /downloadRemoteWorkloadBundle/);
  assert.match(js, /openWorkloadInWorkbench/);
  assert.match(js, /updateHubWorkloadEntry/);
  assert.match(js, /attachCurrentBundleToWorkload/);
  assert.match(js, /registerCurrentBundleAsWorkload/);
  assert.match(js, /syncLocalControlPlaneWorkloads/);
  assert.match(js, /syncRemoteWorkloadCatalog/);
  assert.match(js, /exportHubWorkloadLibrary/);
  assert.match(js, /importHubWorkloadLibrary/);
  assert.match(js, /clearHubWorkloadLibrary/);
  assert.match(js, /validateHubCatalogUrl/);
  assert.match(js, /validateRemoteWorkloadCatalogPayload/);
  assert.match(js, /normalizeRemoteWorkloadCatalogPayload/);
  assert.match(js, /projectSummaryFromInspectPayload/);
  assert.match(js, /analysisFamilies/);
  assert.match(js, /rememberProjectBundleAction/);
  assert.match(js, /summarizeProjectActionResult/);
  assert.match(js, /formatProjectActionTime/);
  assert.match(js, /projectActionStateClass/);
  assert.match(js, /normalizeImportedProjectAction/);
  assert.match(js, /mergeProjectActionHistory/);
  assert.match(js, /actionIdentity/);
  assert.match(js, /shellQuote/);
  assert.match(js, /buildProjectCliCommand/);
  assert.match(js, /buildPythonMacroStub/);
  assert.match(js, /copyProjectCliCommand/);
  assert.match(js, /copyPythonMacroStub/);
  assert.match(js, /sortProjectActionHistory/);
  assert.match(js, /renamePinnedProjectAction/);
  assert.match(js, /renderHubRecents/);
  assert.match(js, /renderDesktopLanguagePreference/);
  assert.match(js, /setText\(elements\.homePathTitle,\s*copy\.home\.path\.title\)/);
  assert.match(js, /setText\(elements\.homeQuickTitle,\s*copy\.home\.quick\.title\)/);
  assert.match(js, /setText\(elements\.homeClusterLibraryTitle,\s*copy\.home\.quick\.libraryTitle\)/);
  assert.match(js, /renderAssistantPanel\(\);\s*rere?nderLocalizedHubShell\(\);\s*syncDesktopStates\(\);/);
  assert.match(js, /renderRecentActionHistory/);
  assert.match(js, /renderEmptyHistoryState/);
  assert.match(js, /renderProjectActionEntries/);
  assert.match(js, /renderHistoryFilters/);
  assert.match(js, /matchesHistoryFilter/);
  assert.match(js, /currentFilteredHistoryActions/);
  assert.match(js, /downloadHubJson/);
  assert.match(js, /exportRecentActionHistory/);
  assert.match(js, /importRecentActionHistory/);
  assert.match(js, /togglePinnedProjectAction/);
  assert.match(js, /manageRecentActionHistory/);
  assert.match(js, /restoreProjectActionContext/);
  assert.match(js, /rerunProjectActionEntry/);
  assert.match(js, /runProjectBundleAction/);
  assert.match(js, /Pin/);
  assert.match(js, /Pinned/);
  assert.match(js, /Label/);
  assert.match(js, /Copy CLI/);
  assert.match(js, /Copy Python/);
  assert.match(js, /Re-run/);
  assert.match(js, /Restore/);
  assert.match(js, /Run action/);
  assert.match(js, /restored .* context/);
  assert.match(js, /status: "ok"/);
  assert.match(js, /status: "failed"/);
  assert.match(js, /pinned: Boolean/);
  assert.match(js, /favoriteLabel/);
  assert.match(js, /filtered recent actions:/);
  assert.match(js, /unpinned/);
  assert.match(js, /entry\.pinned \? "unpinned" : "pinned"/);
  assert.match(js, /No pinned favorites yet\./);
  assert.match(js, /No non-pinned actions in this view\./);
  assert.match(js, /kept failed recent actions only/);
  assert.match(js, /imported .* recent actions from JSON/);
  assert.match(js, /formatHubOperatorError/);
  assert.match(js, /Importing recent action history/);
  assert.match(js, /exported .* recent actions as JSON/);
  assert.match(js, /copied CLI command for/);
  assert.match(js, /copied Python stub for/);
  assert.match(js, /assistant request failed/);
  assert.match(js, /The assistant request/);
  assert.match(js, /localhost \/ 127\.0\.0\.1/);
  assert.match(js, /API key is sent directly to the configured base URL/);
  assert.match(js, /Sensitive/);
  assert.match(js, /High-risk/);
  assert.match(js, /assistant action/);
  assert.match(js, /model plan action/);
  assert.match(js, /No assistant actions recorded in this session\./);
  assert.match(js, /hub\.assistant\.action/);
  assert.match(js, /control-plane sync failed/);
  assert.match(js, /sync_failed/);
  assert.match(js, /synced/);
  assert.match(js, /Executed .* assistant actions\./);
  assert.match(js, /updated label for/);
  assert.match(js, /cleared recent action history/);
  assert.match(js, /currentProjectBundleOutputPayload/);
  assert.match(js, /currentProjectBundleComparePayload/);
  assert.match(js, /workload-register-local/);
  assert.match(js, /workload-sync-local/);
  assert.match(js, /workload-sync-remote/);
  assert.match(js, /workload-export-library/);
  assert.match(js, /workload-import-library/);
  assert.match(js, /workload-clear-library/);
  assert.match(js, /Open in Workbench/);
  assert.match(js, /Download/);
  assert.match(js, /Attach current bundle/);
  assert.match(js, /Reattach bundle/);
  assert.match(js, /attached local/);
  assert.match(js, /first-party control plane catalog/);
  assert.match(js, /custom remote catalog/);
  assert.match(js, /new URL\(normalized\)\.host/);
  assert.match(js, /refreshDesktopStatusOutput/);
  assert.match(js, /setHotRuntimeLogOutput/);
  assert.match(js, /clearHotRuntimeLogView/);
  assert.match(js, /copyHotRuntimeLogView/);
  assert.match(js, /sanitizeRuntimeLogForClipboard/);
  assert.match(js, /refreshHotRuntimeLog/);
  assert.match(js, /renderHotRuntimeLogServiceLabel/);
  assert.match(js, /loadHubRuntimeLogSettings/);
  assert.match(js, /persistHubRuntimeLogSettings/);
  assert.match(js, /setObserveRuntimeLogOutput/);
  assert.match(js, /renderObserveRuntimeLogFollowState/);
  assert.match(js, /currentObserveRuntimeLogService/);
  assert.match(js, /currentObserveRuntimeLogAutoRefresh/);
  assert.match(js, /persistCurrentObserveRuntimeLogSettings/);
  assert.match(js, /shouldPollObserveRuntimeLog/);
  assert.match(js, /stopObserveRuntimeLogPolling/);
  assert.match(js, /syncObserveRuntimeLogPolling/);
  assert.match(js, /refreshObserveRuntimeLog/);
  assert.match(js, /copyObserveRuntimeLogView/);
  assert.match(js, /loadHubHotLogSettings/);
  assert.match(js, /persistHubHotLogSettings/);
  assert.match(js, /persistCurrentHotLogSettings/);
  assert.match(js, /syncHotRuntimeLogPolling/);
  assert.match(js, /renderHotRuntimeLogFollowState/);
  assert.match(js, /shouldPollHotRuntimeLog/);
  assert.match(js, /currentHotRuntimeLogAutoRefresh/);
  assert.match(js, /currentHotRuntimeLogInterval/);
  assert.match(js, /stopHotRuntimeLogPolling/);
  assert.match(js, /HUB_HOT_LOG_POLL_MS/);
  assert.match(js, /read_runtime_log/);
  assert.match(js, /hot-refresh-log/);
  assert.match(js, /hot-copy-log-view/);
  assert.match(js, /hot-clear-log-view/);
  assert.match(js, /copied sanitized hot log tail/);
  assert.match(js, /copied sanitized runtime log tail/);
  assert.match(js, /Couldn't read the .* log right now/);
  assert.match(js, /Refreshing desktop packaging status/);
  assert.match(js, /project_bundle_inspect/);
  assert.match(js, /project_bundle_validate/);
  assert.match(js, /guarded_mutation_action/);
  assert.match(js, /invokeGuardedMutation/);
  assert.match(js, /project_bundle_diff/);
  assert.match(js, /launch_workbench_gui/);
  assert.match(js, /launch_installer_gui/);
  assert.match(js, /open-docs-index/);
  assert.match(js, /open-current-line-doc/);
  assert.match(js, /open-operations-doc/);
  assert.match(js, /open-troubleshooting-doc/);
  assert.match(js, /data-target-section/);
  assert.match(js, /desktop_status/);
  assert.match(js, /desktop_build_host/);
  assert.match(js, /desktop_stage/);
  assert.match(js, /desktop_verify/);
  assert.match(js, /hub-nav__item--active/);
  assert.match(js, /addEventListener\("click"/);
  assert.match(bridge, /invokeTauri/);
  assert.match(bridge, /loadDesktopBrand/);
});

test("tauri backend exposes hub runtime commands", () => {
  const rust = read("src-tauri/src/main.rs");
  const runtimeRust = read("../../workers/rust/crates/desktop-runtime/src/lib.rs");

  assert.match(rust, /service_status/);
  assert.match(rust, /service_start/);
  assert.match(rust, /service_restart/);
  assert.match(rust, /service_stop/);
  assert.match(rust, /guarded_mutation_action/);
  assert.match(rust, /read_runtime_log/);
  assert.match(runtimeRust, /failed to read .* log:/);
  assert.match(rust, /doctor_report/);
  assert.match(rust, /validate_env/);
  assert.match(rust, /desktop_status/);
  assert.match(rust, /desktop_stage/);
  assert.match(rust, /desktop_verify/);
  assert.match(rust, /desktop_build_host/);
  assert.match(rust, /desktop_status_text/);
  assert.match(rust, /render_desktop_status_for_platform/);
  assert.match(rust, /project_bundle_inspect/);
  assert.match(rust, /project_bundle_validate/);
  assert.match(rust, /project_bundle_normalize/);
  assert.match(rust, /project_bundle_unpack/);
  assert.match(rust, /project_bundle_pack/);
  assert.match(rust, /project_bundle_diff/);
  assert.match(rust, /run_project_cli/);
  assert.match(rust, /run_project_cli_with_output/);
  assert.match(rust, /run_project_cli_compare/);
  assert.match(rust, /launch_desktop_app_with_fallback/);
  assert.match(rust, /launch_built_desktop_app/);
  assert.match(rust, /launch_workbench_gui/);
  assert.match(rust, /launch_installer_gui/);
  assert.match(rust, /open_docs_index/);
  assert.match(rust, /open_current_line_doc/);
  assert.match(rust, /open_operations_doc/);
  assert.match(rust, /open_troubleshooting_doc/);
  assert.match(rust, /hub_environment/);
});
