.PHONY: help

help:
	@echo "Available targets:"
	@echo "  make tree        Print the repository scaffold"
	@echo "  make build-frontend Build the Next.js workbench production bundle"
	@echo "  make build-orchestrator Compile the Elixir control plane in production mode"
	@echo "  make build-agent Build the Rust solver agent release binary"
	@echo "  make build-hub-gui Build the Tauri hub desktop bundles for PLATFORM=<host|macos|linux|windows>"
	@echo "  make build-installer-gui Build the Tauri installer desktop bundles for PLATFORM=<host|macos|linux|windows>"
	@echo "  make build-workbench-gui Build the Tauri workbench desktop bundles for PLATFORM=<host|macos|linux|windows>"
	@echo "  make start       Start the orchestrator API, frontend, and solver agent"
	@echo "  make start-local Start services with SQLite forced for local development"
	@echo "  make start-cloud Start services with PostgreSQL forced for cloud/distributed use"
	@echo "  make start-distributed Start only the control plane for distributed deployments"
	@echo "  make status      Show local service status"
	@echo "  make stop        Stop the orchestrator API, frontend, and solver agent"
	@echo "  make restart     Restart the orchestrator API, frontend, and solver agent"
	@echo "  make restart-local Restart services with SQLite forced for local development"
	@echo "  make restart-cloud Restart services with PostgreSQL forced for cloud/distributed use"
	@echo "  make restart-distributed Restart only the control plane for distributed deployments"
	@echo "  make hot-local  Run the local full-stack dev loop with hot reload/watch"
	@echo "  make hot-cloud  Run the cloud/postgres full-stack dev loop with hot reload/watch"
	@echo "  make hot-distributed Run the distributed control-plane dev loop with hot reload/watch"
	@echo "  make hot-web    Run the Elixir control plane with restart-on-change"
	@echo "  make hot-agent  Run the Rust solver agent with restart-on-change (PORT=5001 by default)"
	@echo "  make hot-hub-gui Run the Tauri Hub shell in dev/HMR mode"
	@echo "  make hot-installer-gui Run the Tauri installer shell in dev/HMR mode"
	@echo "  make hot-workbench-gui Run the Tauri workbench shell in dev/HMR mode"
	@echo "  make export-db   Export the current database snapshot as JSON"
	@echo "  make install     Run the cross-platform installer/bootstrap utility"
	@echo "  make doctor      Check local prerequisites for this platform"
	@echo "  make validate-env Validate required .env.local configuration"
	@echo "  make package     Stage a portable release directory under dist/"
	@echo "  make package-runtime Stage the portable runtime release scaffold under dist/"
	@echo "  make package-desktop Build/stage all Tauri desktop shells for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-status Show host/platform desktop packaging readiness for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-stage Stage the desktop/runtime release scaffold for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-build-host Build all three desktop shells for the current host platform"
	@echo "  make desktop-release Stage, build, and verify desktop release output for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-verify Verify staged manifests and icon inputs for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-linux-remote Build Linux desktop packages on kyuubiki-lab"
	@echo "  make desktop-linux-remote-install-deps Install Linux desktop apt dependencies on kyuubiki-lab with sudo -n"
	@echo "  make desktop-linux-remote-preflight Check kyuubiki-lab Linux desktop build prerequisites"
	@echo "  make operator-package-preflight Run read-only external operator package admission checks"
	@echo "  make sync-desktop-shared Refresh shared desktop UI helper files into each Tauri app"
	@echo "  make build-installation-docs Regenerate installation integrity HTML docs from the shared JSON contract"
	@echo "  make build-update-catalog Regenerate the unified update catalog JSON and HTML docs"
	@echo "  make check-doc-book Verify the centralized book and Hub mirrors for version/link/text drift"
	@echo "  make sync-doc-book-version Sync hand-maintained book entry pages to the current shipping version"
	@echo "  make check-toolchains Verify Docker, Mix, Node, Rust, and lab defaults against config/toolchains.json"
	@echo "  make check-elixir-self-host Verify Elixir/Mix/OTP and self-host orchestrator env contracts"
	@echo "  make check-native-script-audit Verify native runner shell-migration audit logic"
	@echo "  make check-language-packs Validate shipped Workbench/Hub language support packs"
	@echo "  make check-ui-automation-contract Verify product-owned Workbench automation selector contracts"
	@echo "  make check-gui-runtime-capability-contract Verify GUI-to-runtime capability manifests stay decoupled from backend implementations"
	@echo "  make check-version-line Verify release, package, docs, and language-pack version contracts"
	@echo "  make check-install-update-disk-hygiene Verify release upload, local purge, rollback, and cleanup disk-use contracts"
	@echo "  make check-materialization-plan-contract Verify materialized candidate schema/example contracts"
	@echo "  make check-material-study-execution-plan-contract Verify non-executing material study plan schema/example contracts"
	@echo "  make check-material-research-bundle-contract Verify retained material research bundle schema/example contracts"
	@echo "  make check-material-study-sdk-examples Run Rust/Python/Elixir material study plan SDK examples"
	@echo "  make verify-material-research-bundle Build and check the retained material research bundle (STUDY=heat-spreader|composite-thermo-electric-panel)"
	@echo "  make material-research-bundle-index Build retained material research bundles and write tmp/material-research-bundles/index.json"
	@echo "  make check-operator-task-ir-contract Verify TaskIR mirrors, digests, and examples"
	@echo "  make check-operator-reliability-rules Verify pure operator reliability rule helpers"
	@echo "  make check-operator-reliability-schemas Verify operator reliability config/schema version contracts"
	@echo "  make check-commercial-readiness Verify the 2.0 commercial-readiness gate"
	@echo "  make build-operator-qualification-readiness Write operator qualification readiness report to OUT=tmp/operator-qualification-readiness.json"
	@echo "  make capture-line-field-qualification-provenance Write line-field qualification provenance JSON to OUT=tmp/line-field-qualification-provenance.json"
	@echo "  make capture-line-field-qualification-release-evidence Run and retain line-field qualification evidence output under OUT=tmp/line-field-qualification-release-evidence.json"
	@echo "  make check-line-field-closed-form-baseline Verify line-field closed-form qualification baseline artifact"
	@echo "  make check-line-field-qualification-release-evidence Verify release evidence JSON from IN=tmp/line-field-qualification-release-evidence.json"
	@echo "  make capture-material-research-example Run the heat-spreader automated material research example to OUT=tmp/material-research-example.json"
	@echo "  make check-material-research-example Verify the automated material research example from IN=tmp/material-research-example.json"
	@echo "  make verify-material-research-example Capture and verify the automated material research example"
	@echo "  make remote-material-research-example Sync to lab and run the material research example plus PROFILE=100k release benchmark"
	@echo "  make remote-material-research-summary Summarize retained remote material evidence and check benchmark health"
	@echo "  make check-operator-reliability Verify physics-coverage operator reliability evidence"
	@echo "  make audit-rust-lines Enforce the Rust source file line-count ceiling"
	@echo "  make audit-project-organization Enforce repository-wide source/docs line-count organization"
	@echo "  make audit-dependencies Run npm production and RustSec lockfile dependency audits"
	@echo "  make fuzz-smoke Run deterministic protocol and package security fuzz-smoke tests"
	@echo "  make architecture-check Run the lightweight new-architecture organization and TaskIR contract check"
	@echo "  make hub-gui-dev         Run the Tauri Hub GUI in development mode"
	@echo "  make hub-gui-build       Build the Tauri Hub GUI bundles"
	@echo "  make installer-gui-dev   Run the Tauri installer GUI in development mode"
	@echo "  make installer-gui-build Build the Tauri installer GUI bundles"
	@echo "  make workbench-gui-dev   Run the Tauri desktop workbench shell in development mode"
	@echo "  make workbench-gui-build Build the Tauri desktop workbench shell bundles"
	@echo "  make test        Run all project tests"
	@echo "  make test-web    Run Elixir tests"
	@echo "  make test-rust   Run Rust workspace tests"
	@echo "  make test-frontend Run frontend typecheck and production build"
	@echo "  make workflow-preflight Run workflow topology plus layout/search guards (requires frontend dev server)"
	@echo "  make test-sdk    Run Python / Elixir / Rust SDK smoke tests"
	@echo "  make test-agent-capability-smoke Run solver-agent advertised-capability smoke against AGENT_HOST/AGENT_PORT"
	@echo "  make test-hub-gui Run Hub desktop shell smoke tests"
	@echo "  make test-installer-gui Run installer desktop shell smoke tests"
	@echo "  make test-workbench-gui Run desktop workbench shell smoke tests"
	@echo "  make test-integration Run the current cross-process integration smoke suite"
	@echo "  make test-integration-api Run the local orchestrator + agent + API integration smoke test"
	@echo "  make test-integration-cluster Run the protected cluster registration/heartbeat integration smoke test"
	@echo "  make test-integration-direct-mesh Run the direct_mesh_gui LAN agent solve + chunk smoke test"
	@echo "  make test-integration-desktop-gui Run Hub + Installer + Workbench desktop preview regression checks"
	@echo "  make test-integration-benchmark-profile-index Run benchmark profile index contract smoke tests"
	@echo "  make test-integration-direct-mesh-docker Run the direct_mesh_gui benchmark harness inside Docker and export repeat summaries"
	@echo "  make test-integration-remote-ssh-fixture Run the explicit local Docker sshd fixture probe"
	@echo "  make test-integration-workflow-mesh Run the distributed workflow mesh regression trio in sequence"
	@echo "  make test-integration-workflow-mesh-nightly Run the remote workflow mesh regression flow on kyuubiki-lab and pull logs back"
	@echo "  make test-integration-ui-mechanical Run the Playwright Workbench UI smoke for representative mechanical samples"
	@echo "  make test-integration-ui-thermal Run the Playwright Workbench UI smoke for representative thermal and thermo-mechanical samples"
	@echo "  make verify      Run formatting checks and tests"
	@echo "  make format      Format all code"
	@echo "  make smoke       Run the Elixir -> Rust smoke flow"
	@echo "  make worker      Run the Rust mock worker CLI"
	@echo "  make agent       Run the Rust FEM TCP agent"
	@echo "  make orchestrator Run the Elixir orchestrator API"
	@echo "  make playground  Legacy alias for the orchestrator API"
	@echo "  make frontend    Run the Next.js workbench UI"
	@echo "  make benchmark   Run the Rust solver benchmark suite"
	@echo "  make benchmark-physics-coverage Run the 1.15.x broad physics smoke matrix"
	@echo "  make benchmark-profile-remote Run one remote benchmark profile/matrix smoke (PROFILE=400k MATRIX=thermal-core CASE=heat-plane-quad-400k REPEAT=1)"
	@echo "  make benchmark-profile-report Regenerate a profile Markdown summary from an existing local JSON report"
	@echo "  make benchmark-profile-index Rebuild the retained exploratory profile run index under tmp/benchmark-profile"
	@echo "  make benchmark-baseline Write a benchmark baseline snapshot (PROFILE=10k by default; 100k/200k/300k/400k supported)"
	@echo "  make benchmark-compare Compare current benchmark output against a checked-in baseline (PROFILE=10k/15k/20k/100k/200k/300k/400k)"
	@echo "  make benchmark-report Write a Markdown comparison report against a checked-in baseline (PROFILE=10k/15k/20k/100k/200k/300k/400k)"
	@echo "  make benchmark-standard-baselines Write the 1.9 standard matrix baselines for PROFILE=<10k|15k|20k|100k|200k|300k|400k>"
	@echo "  make benchmark-standard-compare Run the 1.9 standard matrix regression gate trio for PROFILE=<10k|15k|20k|100k|200k|300k|400k>"
	@echo "  make benchmark-standard-report Write per-matrix reports plus a merged standard comparison report"
	@echo "  make benchmark-standard-nightly Run the remote kyuubiki-lab standard benchmark regression flow and pull reports back"
	@echo "  make regression-gate-report Rebuild the normalized regression catalog and compact gate report under tmp/"
	@echo "  make test-integration-direct-mesh-docker-compare Compare a Docker direct-mesh summary against the checked-in baseline"
	@echo "  make test-integration-direct-mesh-docker-report Run the Docker direct-mesh benchmark and write a baseline comparison report"
	@echo "  make test-integration-direct-mesh-docker-nightly Run the remote direct-mesh Docker regression flow against the checked-in baseline"
	@echo "  make test-integration-workflow-catalog-compare Compare a workflow catalog benchmark summary against the checked-in baseline"
	@echo "  make test-integration-workflow-catalog-report Run the workflow catalog benchmark and write a baseline comparison report"
	@echo "  make test-integration-workflow-catalog-nightly Run the remote workflow catalog regression flow against the checked-in baseline"
	@echo "  make tdd-web     Run a focused Elixir test by FILE=... or TEST=..."
	@echo "  make tdd-rust    Run focused Rust tests with FILTER=..."
	@echo "  ./scripts/kyuubiki help        Show the unified local entrypoint"
	@echo "  KYUUBIKI_STORAGE_BACKEND=postgres DATABASE_URL=ecto://postgres:postgres@127.0.0.1:5432/kyuubiki_dev make start"
	@echo "  cp .env.example .env.local && make restart"
