.PHONY: help

help:
	@echo "Available targets:"
	@echo "  make tree        Print the repository scaffold"
	@echo "  make build-frontend Build the Next.js workbench production bundle"
	@echo "  make build-orchestrator Compile the Elixir control plane in production mode"
	@echo "  make build-agent Build the Rust solver agent release binary"
	@echo "  make build-hub-gui Build the Tauri hub desktop bundles for PLATFORM=<host|macos|linux|windows>"
	@echo "  make build-installer-gui Build the Tauri installer desktop bundles for PLATFORM=<host|macos|linux|windows>"
	@echo "  make build-workbench-gui Build the Tauri workbench desktop bundles for PLATFORM=<host|macos|linux|windows>"
	@echo "  make start       Start the orchestrator API, frontend, and solver agent"
	@echo "  make start-local Start services with SQLite forced for local development"
	@echo "  make start-cloud Start services with PostgreSQL forced for cloud/distributed use"
	@echo "  make start-distributed Start only the control plane for distributed deployments"
	@echo "  make status      Show local service status"
	@echo "  make stop        Stop the orchestrator API, frontend, and solver agent"
	@echo "  make restart     Restart the orchestrator API, frontend, and solver agent"
	@echo "  make restart-local Restart services with SQLite forced for local development"
	@echo "  make restart-cloud Restart services with PostgreSQL forced for cloud/distributed use"
	@echo "  make restart-distributed Restart only the control plane for distributed deployments"
	@echo "  make hot-local  Run the local full-stack dev loop with hot reload/watch"
	@echo "  make hot-cloud  Run the cloud/postgres full-stack dev loop with hot reload/watch"
	@echo "  make hot-distributed Run the distributed control-plane dev loop with hot reload/watch"
	@echo "  make hot-web    Run the Elixir control plane with restart-on-change"
	@echo "  make hot-agent  Run the Rust solver agent with restart-on-change (PORT=5001 by default)"
	@echo "  make hot-hub-gui Run the Tauri Hub shell in dev/HMR mode"
	@echo "  make hot-installer-gui Run the Tauri installer shell in dev/HMR mode"
	@echo "  make hot-workbench-gui Run the Tauri workbench shell in dev/HMR mode"
	@echo "  make export-db   Export the current database snapshot as JSON"
	@echo "  make install     Run the cross-platform installer/bootstrap utility"
	@echo "  make doctor      Check local prerequisites for this platform"
	@echo "  make validate-env Validate required .env.local configuration"
	@echo "  make package     Stage a portable release directory under dist/"
	@echo "  make package-runtime Stage the portable runtime release scaffold under dist/"
	@echo "  make package-desktop Build/stage all Tauri desktop shells for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-status Show host/platform desktop packaging readiness for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-stage Stage the desktop/runtime release scaffold for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-build-host Build all three desktop shells with a shared host-platform Cargo cache"
	@echo "  make desktop-release Stage, build, and verify desktop release output for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-verify Verify staged manifests and icon inputs for PLATFORM=<host|macos|linux|windows|all>"
	@echo "  make desktop-linux-remote Build Linux desktop packages on kyuubiki-lab"
	@echo "  make desktop-linux-remote-install-deps Install Linux desktop apt dependencies on kyuubiki-lab with sudo -n"
	@echo "  make desktop-linux-remote-preflight Check kyuubiki-lab Linux desktop build prerequisites"
	@echo "  make operator-package-preflight Run read-only external operator package admission checks"
	@echo "  make operator-package-dynamic-smoke Build and dynamically load the template external operator package"
	@echo "  make check-operator-package-dynamic-smoke Validate the retained dynamic-smoke JSON report"
	@echo "  make sync-desktop-shared Refresh shared desktop UI helper files into each Tauri app"
	@echo "  make check-desktop-shared Verify generated shared UI, app mirrors, brand assets, and language packs"
	@echo "  make build-installation-docs Regenerate installation integrity HTML docs from the shared JSON contract"
	@echo "  make build-update-catalog Regenerate the unified update catalog JSON and HTML docs"
	@echo "  make build-workbench-language-pack-catalog Regenerate the built-in Workbench language-pack catalog from source JSON packs"
	@echo "  make check-doc-book Verify the centralized book and Hub mirrors for version/link/text drift"
	@echo "  make check-doc-inventory Verify every docs and Hub shelf page is indexed"
	@echo "  make sync-doc-book-version Sync hand-maintained book entry pages to the current shipping version"
	@echo "  make check-toolchains Verify Docker, Mix, Node, Rust, and lab defaults against config/toolchains.json"
	@echo "  make check-elixir-self-host Verify Elixir/Mix/OTP and self-host orchestrator env contracts"
	@echo "  make check-module-topology Verify strict architecture module topology, benchmark lanes, and security lanes"
	@echo "  make check-module-function-matrix Verify module x function-paradigm coverage matrix"
	@echo "  make check-module-function-coverage-tensor Build module x function x evidence-depth coverage tensor"
	@echo "  make check-module-extension-standard Verify the standard flow for adding modules, paradigms, surfaces, lanes, and contracts"
	@echo "  make check-contracts-runtime-api-surface Verify shared contracts runtime API source/client surface index"
	@echo "  make check-verification-evidence-surface Verify verification evidence commands, artifacts, and central readiness report coverage"
	@echo "  make check-central-store-contract Verify central store schemas, backend surface, frontend client, and docs"
	@echo "  make check-central-database-readiness Verify central DB readiness for MODE=<local|cloud|distributed> BACKEND=<sqlite|postgres>"
	@echo "  make build-central-readiness-report Write machine-readable central API/schema/storage readiness to OUT=tmp/central-readiness-report.json"
	@echo "  make check-central-readiness-report Validate retained central readiness report from IN=tmp/central-readiness-report.json"
	@echo "  make build-module-topology-report Write module topology benchmark/security lane report to OUT_DIR=tmp/module-topology"
	@echo "  make check-native-script-audit Verify native runner shell-migration audit logic"
	@echo "  make check-language-packs Validate shipped Workbench/Hub language packs, paths, and unsafe-text guards"
	@echo "  make report-full-language-pack-coverage Report every visible Workbench copy key covered by each shipped language pack"
	@echo "  make plan-language-pack-translations [LANGUAGE=<code>] Show the unified static translation queue"
	@echo "  make next-language-pack-translation [LANGUAGE=<code>] Show the next incomplete translation batch"
	@echo "  make check-full-language-pack-coverage Strictly require complete visible-copy coverage for every shipped Workbench language pack"
	@echo "  make check-language-pack-coverage Strictly require full visible-copy coverage for LANGUAGE=<code>"
	@echo "  make export-language-pack-translation-batch Write source/translation pairs for LANGUAGE=<code> BATCH=<core-01|...> to OUT=tmp/..."
	@echo "  make draft-language-pack-translation-batch Create a reviewed machine-translation draft for LANGUAGE=<code> BATCH=<...>; no product files are changed"
	@echo "  make apply-language-pack-translation-batch Validate and merge a reviewed translation batch from INPUT=<path>"
	@echo "  make check-ui-automation-contract Verify product-owned Workbench automation selector contracts"
	@echo "  make test-integration-ui-invocation Run end-to-end UI action, bridge, and visible-result checks"
	@echo "  make test-integration-ui-workflow Run the Workbench workflow catalog-to-execution UI chain"
	@echo "  make check-gui-runtime-capability-contract Verify GUI-to-runtime capability manifests stay decoupled from backend implementations"
	@echo "  make check-version-line Verify release, snapshot, package, docs, and language-pack version contracts"
	@echo "  make check-workflow-dataset-contract Verify workflow dataset schema, examples, and graph dataset references"
	@echo "  make check-material-card-contract Verify material-card schema, golden fixture, docs, and workflow preflight anchors"
	@echo "  make check-install-update-disk-hygiene Verify release upload, local purge, rollback, and cleanup disk-use contracts"
	@echo "  make check-component-integrity-protocol Verify component ownership and write OUT=tmp/component-integrity-report.json"
	@echo "  make check-materialization-plan-contract Verify materialized candidate schema/example contracts"
	@echo "  make check-material-study-execution-plan-contract Verify non-executing material study plan schema/example contracts"
	@echo "  make check-material-research-bundle-contract Verify retained material research bundle schema/example contracts"
	@echo "  make check-material-study-sdk-examples Run Rust/Python/Elixir material study plan SDK examples"
	@echo "  make verify-material-research-bundle Build and check the retained material research bundle (STUDY=heat-spreader|composite-thermo-electric-panel)"
	@echo "  make material-research-bundle-index Build retained material research bundles and write tmp/material-research-bundles/index.json"
	@echo "  make check-material-research-bundle-index Verify retained bundle index counts and evidence summaries"
	@echo "  make check-material-research-bundle-index-contract Verify retained bundle index schema/example/docs contract"
	@echo "  make check-operator-task-ir-contract Verify TaskIR mirrors, digests, and examples"
	@echo "  make check-operator-package-dynamic-smoke-contract Verify external operator dynamic-smoke schema and fixture"
	@echo "  make check-operator-reliability-rules Verify pure operator reliability rule helpers"
	@echo "  make check-operator-reliability-schemas Verify operator reliability config/schema version contracts"
	@echo "  make check-operator-validation Verify operator validation profiles without executing heavy checks"
	@echo "  make verify-operator-validation Execute operator validation profile commands and write tmp/operator-validation-report.json"
	@echo "  make check-commercial-readiness Verify the 2.0 commercial-readiness gate"
	@echo "  make check-moxi-handoff Verify the final tamamono-to-moxi handoff gate"
	@echo "  make build-operator-qualification-readiness Write and validate operator qualification readiness report to OUT=tmp/operator-qualification-readiness.json"
	@echo "  make check-operator-qualification-readiness Verify operator qualification readiness report from IN=tmp/operator-qualification-readiness.json"
	@echo "  make check-operator-qualification-release-records Verify staged qualification release records from IN=releases/qualification-records/1.20.0.json"
	@echo "  make check-operator-qualification-review-decision Verify all retained review decisions, or one decision with IN=<path>"
	@echo "  make capture-line-field-qualification-provenance Write line-field qualification provenance JSON to OUT=tmp/line-field-qualification-provenance.json"
	@echo "  make capture-line-field-qualification-release-evidence Run and retain line-field qualification evidence output under OUT=tmp/line-field-qualification-release-evidence.json"
	@echo "  make capture-beam-frame-qualification-release-evidence Run and retain beam/frame/torsion validation output under OUT=tmp/beam-frame-classic-qualification-release-evidence.json"
	@echo "  make capture-thermal-plane-qualification-release-evidence Run and retain thermal plane validation output under OUT=tmp/thermal-plane-patch-qualification-release-evidence.json"
	@echo "  make capture-electromagnetic-plane-qualification-release-evidence Run and retain electromagnetic plane validation output under OUT=tmp/electromagnetic-plane-patch-qualification-release-evidence.json"
	@echo "  make capture-modal-frame-qualification-release-evidence Run and retain modal frame validation output under OUT=tmp/modal-frame-sanity-qualification-release-evidence.json"
	@echo "  make capture-stokes-flow-screening-release-evidence Run and retain Stokes screening validation output under OUT=tmp/stokes-flow-screening-release-evidence.json"
	@echo "  make capture-acoustic-bar-qualification-release-evidence Run and retain acoustic bar validation output under OUT=tmp/acoustic-bar-closed-form-release-evidence.json"
	@echo "  make capture-advection-diffusion-bar-qualification-release-evidence Run and retain transport bar validation output under OUT=tmp/advection-diffusion-bar-closed-form-release-evidence.json"
	@echo "  make capture-magnetostatic-bar-qualification-release-evidence Run and retain magnetostatic bar validation output under OUT=tmp/magnetostatic-bar-closed-form-release-evidence.json"
	@echo "  make capture-spring-1d-qualification-release-evidence Run and retain spring 1D validation output under OUT=tmp/spring-1d-closed-form-release-evidence.json"
	@echo "  make capture-spring-vector-qualification-release-evidence Run and retain spring 2D/3D validation output under OUT=tmp/spring-vector-closed-form-release-evidence.json"
	@echo "  make capture-nonlinear-spring-1d-qualification-release-evidence Run and retain nonlinear spring 1D validation output under OUT=tmp/nonlinear-spring-1d-closed-form-release-evidence.json"
	@echo "  make capture-frame-3d-qualification-release-evidence Run and retain frame 3D validation output under OUT=tmp/frame-3d-closed-form-release-evidence.json"
	@echo "  make capture-plane-2d-qualification-release-evidence Run and retain plane 2D validation output under OUT=tmp/plane-2d-patch-closed-form-release-evidence.json"
	@echo "  make capture-thermal-beam-1d-qualification-release-evidence Run and retain thermal beam 1D validation output under OUT=tmp/thermal-beam-1d-closed-form-release-evidence.json"
	@echo "  make capture-thermal-frame-2d-qualification-release-evidence Run and retain thermal frame 2D validation output under OUT=tmp/thermal-frame-2d-closed-form-release-evidence.json"
	@echo "  make capture-thermal-frame-3d-qualification-release-evidence Run and retain thermal frame 3D validation output under OUT=tmp/thermal-frame-3d-closed-form-release-evidence.json"
	@echo "  make capture-solid-tetra-3d-qualification-release-evidence Run and retain solid tetra 3D validation output under OUT=tmp/solid-tetra-3d-closed-form-release-evidence.json"
	@echo "  make capture-contact-gap-1d-qualification-release-evidence Run and retain contact gap 1D validation output under OUT=tmp/contact-gap-1d-closed-form-release-evidence.json"
	@echo "  make capture-truss-2d-qualification-release-evidence Run and retain truss 2D validation output under OUT=tmp/truss-2d-closed-form-release-evidence.json"
	@echo "  make capture-truss-3d-qualification-release-evidence Run and retain truss 3D validation output under OUT=tmp/truss-3d-closed-form-release-evidence.json"
	@echo "  make capture-thermal-truss-3d-qualification-release-evidence Run and retain thermal truss 3D validation output under OUT=tmp/thermal-truss-3d-closed-form-release-evidence.json"
	@echo "  make capture-thermal-truss-2d-qualification-release-evidence Run and retain thermal truss 2D validation output under OUT=tmp/thermal-truss-2d-closed-form-release-evidence.json"
	@echo "  make check-beam-frame-qualification-release-evidence Verify beam/frame/torsion release evidence from IN=tmp/beam-frame-classic-qualification-release-evidence.json"
	@echo "  make check-thermal-plane-qualification-release-evidence Verify thermal plane release evidence from IN=tmp/thermal-plane-patch-qualification-release-evidence.json"
	@echo "  make check-electromagnetic-plane-qualification-release-evidence Verify electromagnetic plane release evidence from IN=tmp/electromagnetic-plane-patch-qualification-release-evidence.json"
	@echo "  make check-modal-frame-qualification-release-evidence Verify modal frame release evidence from IN=tmp/modal-frame-sanity-qualification-release-evidence.json"
	@echo "  make check-stokes-flow-screening-release-evidence Verify Stokes screening release evidence from IN=tmp/stokes-flow-screening-release-evidence.json"
	@echo "  make check-acoustic-bar-qualification-release-evidence Verify acoustic bar release evidence from IN=tmp/acoustic-bar-closed-form-release-evidence.json"
	@echo "  make check-advection-diffusion-bar-qualification-release-evidence Verify transport bar release evidence from IN=tmp/advection-diffusion-bar-closed-form-release-evidence.json"
	@echo "  make check-magnetostatic-bar-qualification-release-evidence Verify magnetostatic bar release evidence from IN=tmp/magnetostatic-bar-closed-form-release-evidence.json"
	@echo "  make check-spring-1d-qualification-release-evidence Verify spring 1D release evidence from IN=tmp/spring-1d-closed-form-release-evidence.json"
	@echo "  make check-spring-vector-qualification-release-evidence Verify spring 2D/3D release evidence from IN=tmp/spring-vector-closed-form-release-evidence.json"
	@echo "  make check-nonlinear-spring-1d-qualification-release-evidence Verify nonlinear spring 1D release evidence from IN=tmp/nonlinear-spring-1d-closed-form-release-evidence.json"
	@echo "  make check-frame-3d-qualification-release-evidence Verify frame 3D release evidence from IN=tmp/frame-3d-closed-form-release-evidence.json"
	@echo "  make check-plane-2d-qualification-release-evidence Verify plane 2D release evidence from IN=tmp/plane-2d-patch-closed-form-release-evidence.json"
	@echo "  make check-thermal-beam-1d-qualification-release-evidence Verify thermal beam 1D release evidence from IN=tmp/thermal-beam-1d-closed-form-release-evidence.json"
	@echo "  make check-thermal-frame-2d-qualification-release-evidence Verify thermal frame 2D release evidence from IN=tmp/thermal-frame-2d-closed-form-release-evidence.json"
	@echo "  make check-thermal-frame-3d-qualification-release-evidence Verify thermal frame 3D release evidence from IN=tmp/thermal-frame-3d-closed-form-release-evidence.json"
	@echo "  make check-solid-tetra-3d-qualification-release-evidence Verify solid tetra 3D release evidence from IN=tmp/solid-tetra-3d-closed-form-release-evidence.json"
	@echo "  make check-contact-gap-1d-qualification-release-evidence Verify contact gap 1D release evidence from IN=tmp/contact-gap-1d-closed-form-release-evidence.json"
	@echo "  make check-truss-2d-qualification-release-evidence Verify truss 2D release evidence from IN=tmp/truss-2d-closed-form-release-evidence.json"
	@echo "  make check-truss-3d-qualification-release-evidence Verify truss 3D release evidence from IN=tmp/truss-3d-closed-form-release-evidence.json"
	@echo "  make check-thermal-truss-3d-qualification-release-evidence Verify thermal truss 3D release evidence from IN=tmp/thermal-truss-3d-closed-form-release-evidence.json"
	@echo "  make check-thermal-truss-2d-qualification-release-evidence Verify thermal truss 2D release evidence from IN=tmp/thermal-truss-2d-closed-form-release-evidence.json"
	@echo "  make check-line-field-closed-form-baseline Verify line-field closed-form qualification baseline artifact"
	@echo "  make check-line-field-qualification-release-evidence Verify release evidence JSON from IN=tmp/line-field-qualification-release-evidence.json"
	@echo "  make capture-material-research-example Run the heat-spreader automated material research example to OUT=tmp/material-research-example.json"
	@echo "  make check-material-research-example Verify the automated material research example from IN=tmp/material-research-example.json"
	@echo "  make verify-material-research-example Capture and verify the automated material research example"
	@echo "  make remote-material-research-example Sync to lab and run the material research example plus PROFILE=100k release benchmark"
	@echo "  make remote-material-research-summary Summarize retained remote material evidence and check benchmark health"
	@echo "  make check-operator-reliability Verify physics-coverage operator reliability evidence"
	@echo "  make audit-rust-lines Enforce the Rust source file line-count ceiling"
	@echo "  make audit-project-organization Enforce repository-wide source/docs line-count organization"
	@echo "  make audit-dependencies Run npm production and RustSec lockfile dependency audits"
	@echo "  make fuzz-smoke Run deterministic protocol, package, installer, central-store, and language-pack security fuzz-smoke tests"
	@echo "  make architecture-check Run the lightweight new-architecture organization and TaskIR contract check"
	@echo "  make hub-gui-dev         Run the Tauri Hub GUI in development mode"
	@echo "  make hub-gui-build       Build the Tauri Hub GUI bundles"
	@echo "  make installer-gui-dev   Run the Tauri installer GUI in development mode"
	@echo "  make installer-gui-build Build the Tauri installer GUI bundles"
	@echo "  make workbench-gui-dev   Run the Tauri desktop workbench shell in development mode"
	@echo "  make workbench-gui-build Build the Tauri desktop workbench shell bundles"
	@echo "  make test        Run all project tests"
	@echo "  make test-web    Run Elixir tests"
	@echo "  make test-rust   Run Rust workspace tests"
	@echo "  make test-rust-scale-profiles  Run serialized 200k-to-1M benchmark generation checks"
	@echo "  make test-frontend Run frontend typecheck and production build"
	@echo "  make workflow-preflight Run workflow topology plus layout/search guards (requires frontend dev server)"
	@echo "  make test-runtime-surfaces Run lightweight Hub/Installer/Workbench/Orchestra/Protocol surface tests"
	@echo "  make test-central-database-smoke Dry-run central DB smoke; set RUN_DB_SMOKE=1 DATABASE_URL=... to execute"
	@echo "  make remote-central-database-smoke Sync to REMOTE=kyuubiki-lab and run central DB readiness/smoke without storing credentials"
	@echo "  make test-sdk    Run Python / Elixir / Rust SDK smoke tests"
	@echo "  make test-agent-capability-smoke Run solver-agent advertised-capability smoke against AGENT_HOST/AGENT_PORT"
	@echo "  make test-hub-gui Run Hub desktop shell smoke tests"
	@echo "  make test-installer-gui Run installer desktop shell smoke tests"
	@echo "  make test-workbench-gui Run desktop workbench shell smoke tests"
	@echo "  make test-integration Run the current cross-process integration smoke suite"
	@echo "  make test-integration-api Run the local orchestrator + agent + API integration smoke test"
	@echo "  make test-integration-cluster Run the protected cluster registration/heartbeat integration smoke test"
	@echo "  make test-integration-direct-mesh Run the direct_mesh_gui LAN agent solve + chunk smoke test"
	@echo "  make test-integration-desktop-gui Run Hub + Installer + Workbench desktop preview regression checks"
	@echo "  make test-integration-benchmark-profile-index Run benchmark profile index contract smoke tests"
	@echo "  make test-integration-direct-mesh-docker Run the remote direct_mesh_gui Docker regression by default; use LOCAL_DOCKER=1 for local Docker"
	@echo "  make test-integration-remote-ssh-fixture Run the explicit local Docker sshd fixture probe"
	@echo "  make test-integration-workflow-mesh Run the distributed workflow mesh regression trio in sequence"
	@echo "  make test-integration-workflow-mesh-nightly Run the remote workflow mesh regression flow on kyuubiki-lab and pull logs back"
	@echo "  make test-integration-ui-mechanical Run the Playwright Workbench UI smoke for representative mechanical samples"
	@echo "  make test-integration-ui-thermal Run the Playwright Workbench UI smoke for representative thermal and thermo-mechanical samples"
	@echo "  make verify      Run formatting checks and tests"
	@echo "  make format      Format all code"
	@echo "  make smoke       Run the Elixir -> Rust smoke flow"
	@echo "  make worker      Run the Rust mock worker CLI"
	@echo "  make agent       Run the Rust FEM TCP agent"
	@echo "  make orchestrator Run the Elixir orchestrator API"
	@echo "  make playground  Legacy alias for the orchestrator API"
	@echo "  make frontend    Run the Next.js workbench UI"
	@echo "  make benchmark   Run the Rust solver benchmark suite"
	@echo "  make benchmark-shapes Print benchmark case nodes/elements/DOFs without solving (PROFILE=500k by default)"
	@echo "  make benchmark-physics-coverage Run the 1.15.x broad physics smoke matrix (optional CASE=<substring>)"
	@echo "  make benchmark-profile-remote Run one remote benchmark profile/matrix smoke (PROFILE=500k supported; use CASE for probes)"
	@echo "  make benchmark-profile-plan Build a remote profile probe plan (PROFILE=500k, SHAPES=1 to include scale)"
	@echo "  make benchmark-profile-report Regenerate a profile Markdown summary from an existing local JSON report"
	@echo "  make benchmark-profile-index Rebuild the retained exploratory profile run index under tmp/benchmark-profile"
	@echo "  make benchmark-baseline Write a benchmark baseline snapshot (PROFILE=10k by default; 500k supported; optional CASE=<substring>)"
	@echo "  make benchmark-compare Compare current benchmark output against a checked-in baseline (500k supported; optional CASE=<substring>)"
	@echo "  make benchmark-report Write a Markdown comparison report against a checked-in baseline (500k supported; optional CASE=<substring>)"
	@echo "  make benchmark-standard-baselines Write the 1.9 standard matrix baselines for PROFILE=<10k|15k|20k|100k|200k|300k|400k|500k>"
	@echo "  make benchmark-standard-compare Run the 1.9 standard matrix regression gate trio for PROFILE=<10k|15k|20k|100k|200k|300k|400k|500k>"
	@echo "  make benchmark-standard-report Write per-matrix reports plus a merged standard comparison report"
	@echo "  make benchmark-standard-nightly Run the remote kyuubiki-lab standard benchmark regression flow and pull reports back"
	@echo "  make regression-gate-report Rebuild the normalized regression catalog and compact gate report under tmp/"
	@echo "  make test-integration-direct-mesh-docker-compare Compare a Docker direct-mesh summary against the checked-in baseline"
	@echo "  make test-integration-direct-mesh-docker-report Run the remote Docker direct-mesh regression report; use LOCAL_DOCKER=1 for local report generation"
	@echo "  make test-integration-direct-mesh-docker-nightly Run the remote direct-mesh Docker regression flow against the checked-in baseline"
	@echo "  make test-integration-workflow-catalog-compare Compare a workflow catalog benchmark summary against the checked-in baseline"
	@echo "  make test-integration-workflow-catalog-report Run the workflow catalog benchmark and write a baseline comparison report"
	@echo "  make test-integration-workflow-catalog-nightly Run the remote workflow catalog regression flow against the checked-in baseline"
	@echo "  make tdd-web     Run a focused Elixir test by FILE=... or TEST=..."
	@echo "  make tdd-rust    Run focused Rust tests with FILTER=..."
	@echo "  ./scripts/kyuubiki help        Show the unified local entrypoint"
	@echo "  KYUUBIKI_STORAGE_BACKEND=postgres DATABASE_URL=$$KYUUBIKI_DATABASE_URL make start"
	@echo "  cp .env.example .env.local && make restart"
