import { copyEnCore } from "@/components/workbench/workbench-copy-en-core";
import { copyEnExtended } from "@/components/workbench/workbench-copy-en-extended";

const copyEn = {
  ...copyEnCore,
  ...copyEnExtended,
} as const;

export const copyJa = {
    ...copyEn,
    roleLabel: "解析シェル",
    title: "構造解析ワークベンチ",
    subtitle: "モデリング、オーケストレーション、結果レビューを一つにまとめた作業面です。",
    rail: { study: "解析", model: "ワークスペース", workflow: "ワークフロー", library: "履歴", system: "システム" },
    sections: { study: "解析設定", model: "ワークスペース", workflow: "ワークフロースタジオ", library: "ジョブ履歴", system: "システム" },
    studyFamilies: {
      axialAndSprings: "軸・ばね",
      beamsAndFrames: "梁・フレーム",
      trusses: "トラス",
      planes: "平面要素",
    },
    studyDomains: {
      mechanical: "力学",
      thermal: "熱",
      thermoMechanical: "熱応力",
    },
    importModel: "モデルを読み込む",
    importHint: "1D / 2D 解析用の JSON モデルを読み込みます。",
    sampleCatalogPage: "カタログ",
    sampleImportPage: "インポート",
    workflowOverviewPage: "概要",
    workflowCatalogPage: "カタログ",
    workflowBuilderPage: "ビルダー",
    workflowRunsPage: "実行",
    workflowCatalogTitle: "ワークフローカタログ",
    workflowCatalogHint: "より大きな study path に組み込む前に、命名済みの多算子 workflow をここで実行します。",
    workflowOverviewHint: "複合算子 workflow を専用作業面に集め、samples や results に埋め込まないようにします。",
    workflowBuilderHint: "graph のノード、bridge、extract、export を確認してから大きな study chain に接続します。",
    workflowRunsHint: "命名 workflow ジョブ、現在ノード、書き出し済み summary を一か所で追います。",
    workflowCatalogRefresh: "ワークフローを更新",
    workflowCatalogRun: "参照サンプルを実行",
    workflowCatalogEmpty: "まだ公開済みの命名 workflow はありません。",
    workflowCatalogReady: "ワークフローカタログの準備ができました。",
    workflowCatalogQueued: "ワークフロージョブを投入しました",
    workflowCatalogCompleted: "ワークフローが完了しました",
    workflowCatalogUnsupported: "この workflow にはまだ内蔵サンプル入力がありません。",
    workflowCatalogLoaded: "ワークフローカタログを読み込みました。",
    workflowCatalogFailed: "ワークフロー実行に失敗しました。",
    workflowSelectForBuilder: "ビルダーを開く",
    workflowNoSelection: "まず命名 workflow を選ぶと、ビルダーに graph が表示されます。",
    workflowNodesTitle: "ノード",
    workflowEdgesTitle: "エッジ",
    workflowEntryInputsTitle: "入口入力",
    workflowOutputArtifactsTitle: "出力アーティファクト",
    workflowDatasetContractTitle: "データセット契約",
    workflowDatasetValuesTitle: "データセット値",
    workflowDatasetValueLabel: "データセット値",
    workflowDatasetSemanticTypeLabel: "意味型",
    workflowDatasetEncodingLabel: "エンコード",
    workflowDatasetShapeLabel: "形状",
    workflowDatasetAxesLabel: "軸",
    workflowDatasetSchemaLabel: "スキーマ",
    workflowDatasetClassLabel: "要素型",
    workflowDatasetNoneLabel: "この workflow にはまだ dataset contract がありません。",
    workflowDatasetDraftHint: "まずここで dataset の意味付けをローカル草稿として調整し、port・edge・跨算子値を揃えてから永続化に進みます。",
    workflowDatasetEditorTitle: "データセットエディタ",
    workflowDatasetValueSelectLabel: "選択中のデータセット値",
    workflowDatasetUnitLabel: "単位",
    workflowDatasetMetadataLabel: "メタ情報",
    workflowDatasetPortMappingsTitle: "ポート対応",
    workflowDatasetEdgeMappingsTitle: "エッジ対応",
    workflowDatasetDraftLocalLabel: "ローカル草稿",
    workflowDatasetUnassignedLabel: "未割り当て",
    workflowDatasetAddValueLabel: "値を追加",
    workflowDatasetRemoveValueLabel: "値を削除",
    workflowDatasetAxesEditorTitle: "軸エディタ",
    workflowDatasetAddAxisLabel: "軸を追加",
    workflowDatasetRemoveAxisLabel: "軸を削除",
    workflowDatasetAxisIdLabel: "軸 ID",
    workflowDatasetAxisSizeLabel: "軸サイズ",
    workflowDatasetAxisSemanticLabel: "軸セマンティクス",
    workflowImportGraphLabel: "Graph JSON を取り込む",
    workflowImportDatasetContractLabel: "Dataset JSON を取り込む",
    workflowImportSuccessLabel: "ローカル workflow 草稿を取り込みました。",
    workflowImportInvalidGraphLabel: "このファイルは有効な workflow graph JSON ではありません。",
    workflowImportInvalidDatasetLabel: "このファイルは有効な workflow dataset JSON ではありません。",
    workflowValidationTitle: "整合性チェック",
    workflowValidationOkLabel: "graph と dataset contract の不整合は見つかりませんでした。",
    workflowValidationFixLabel: "修正を適用",
    workflowArtifactNodeLabel: "ノード",
    workflowArtifactTypeLabel: "artifact type",
    workflowArtifactDescriptionLabel: "説明",
    workflowArtifactRemoveLabel: "artifact を削除",
    workflowArtifactAdoptSuggestedLabel: "node port type を使う",
    workflowArtifactAddEntryLabel: "entry input を追加",
    workflowArtifactAddOutputLabel: "output artifact を追加",
    workflowArtifactDraftLocalLabel: "ローカル草稿",
    workflowExportGraphLabel: "Graph JSON を書き出す",
    workflowExportDatasetContractLabel: "Dataset JSON を書き出す",
    workflowOperatorLabel: "算子",
    workflowKindLabel: "種別",
    workflowProgressLabel: "進捗",
    workflowCurrentNodeLabel: "現在ノード",
    workflowLatestSummaryLabel: "最新サマリー",
    workflowOpenRunLabel: "実行を開く",
    workflowRunsEmpty: "まだ workflow 実行はありません。",
    projectManagePage: "管理",
    projectExchangePage: "入出力",
    modelSavedPage: "保存済み",
    modelVersionsPage: "バージョン",
    studyDomain: "物理ドメイン",
    noDomainStudies: "このドメインにはまだ公開済み study がありません。",
    jobWorkspaceTitle: "ジョブ作業面",
    jobWorkspaceHint: "まずは solver 実行を追い、必要になった時だけ個別ジョブに掘り下げます。",
    resultWorkspaceTitle: "結果作業面",
    resultWorkspaceHint: "ここでは最新の完了結果を開き、そこからレポートやエクスポートに進みます。",
    modelWorkspaceTitle: "モデル作業面",
    modelWorkspaceHint: "保存済み study と再利用用バージョンをまとめて、すぐに再開や分岐ができるようにします。",
    openLatestJob: "最新ジョブを開く",
    openLatestResult: "最新結果を開く",
    openLatestModel: "最新モデルを開く",
    waitingJobs: "結果待ち",
    readyResults: "利用可能な結果",
    savedCount: "保存済みモデル",
    versionCount: "バージョン数",
    overview: "概要",
    result: "結果",
    actions: "操作",
    details: "詳細",
    controls: "設定",
    controlsSetupPage: "編集",
    controlsReviewPage: "確認",
    studyTypeLabel: "解析タイプ",
    modelStudyPage: "解析",
    modelOverviewPage: "概要",
    modelStudioPage: "スタジオ",
    modelMaterialsPage: "材料",
    modelGeneratePage: "生成",
    workspaceStudyHint: "Study ファミリー、物理ドメイン、solver 向け setup をここで整えます。",
    workspaceStudioHint: "ノード、部材、境界、幾何の編集はここで行います。",
    workspaceMaterialsHint: "初期材料値と再利用する材料選択をここにまとめます。",
    workspaceGenerateHint: "ジェネレーターとパラメトリック補助で再現可能なモデルを作ります。",
    workspaceBrowseHint: "オブジェクト、ハイライト、結果に結び付く選択をここで参照します。",
    settings: "設定",
    scripts: "スクリプト",
    settingsConfigHint: "テーマ、言語、ルーティング、アクセストークン、言語パックをここで管理します。",
    settingsScriptsHint: "WASM Python、マクロ記録、アクションカタログをここで扱います。",
    assistant: "アシスタント",
    config: "構成",
    runtime: "ランタイム",
    data: "データ",
    packs: "言語パック",
    workspace: "ワークスペース",
    routing: "ルーティング",
    access: "アクセス",
    stack: "スタック",
    security: "セキュリティ",
    agents: "エージェント",
    audit: "監査",
    backend: "バックエンド",
    protocols: "プロトコル",
    dataAdmin: "データ管理",
    languagePacksTitle: "インストール済み言語パック",
    languagePacksHint: "今はローカル JSON パックの取り込みを先にサポートし、この画面を将来のリモート配布入口として残しておきます。",
    languagePacksEmptyLabel: "まだカスタム言語パックはありません。",
    languagePackName: "名称",
    languagePackVersion: "バージョン",
    languagePackSourceImported: "ローカル取込",
    languagePackSourceDownloaded: "リモート取得",
    languagePackDownloadTemplate: "テンプレートを出力",
    languagePackExportInstalled: "現在の言語パックを出力",
    languagePackImport: "言語パックを取込",
    languagePackRemove: "削除",
    languagePackCatalogTitle: "将来のカタログ",
    languagePackCatalogHint: "この欄は将来のリモート言語パック配布を同じ画面で扱えるように先に用意しています。",
    languagePackCatalogAction: "今後対応",
    adminJobs: "ジョブ",
    adminResults: "結果",
    adminBrowsePage: "参照",
    adminEditPage: "編集",
    themes: { linen: "リネン", marine: "マリン", graphite: "グラファイト" },
    languages: { en: "English", zh: "中文", ja: "日本語", es: "Español" },
    frontendModes: {
      orchestrated_gui: "オーケストレーション GUI",
      direct_mesh_gui: "ダイレクトメッシュ GUI",
    },
    directMeshStrategies: {
      healthiest: "最も健全なノード",
      first_reachable: "最初に到達可能なノード",
    },
    tabs: { summary: "概要", controls: "設定", tools: "ツール", tree: "参照", jobs: "ジョブ", results: "結果", models: "モデル", projects: "プロジェクト", samples: "サンプル" },
    ready: "準備完了",
    busy: "処理中",
    run: "解析を実行",
    running: "実行中...",
    historyEmpty: "まだジョブはありません。",
    refresh: "更新",
    online: "オンライン",
    offline: "オフライン",
    controlPlaneTokenHelp:
      "トークン保護された control-plane 配備向けです。/api/v1 リクエストに x-kyuubiki-token として送信されます。",
    controlPlaneTokenPlaceholder: "任意の control-plane トークン",
    clusterTokenHelp:
      "agent の登録・heartbeat・削除などの cluster ルートに使います。未入力なら control-plane token を使います。",
    clusterTokenPlaceholder: "任意の cluster 専用トークン",
    directMeshTokenHelp:
      "トークン保護された direct mesh ルート向けです。/api/direct-mesh リクエストに送信されます。",
    directMeshTokenPlaceholder: "任意の direct-mesh トークン",
    exportDatabase: "データベーススナップショットを出力",
    runtimeSecurityFooter:
      "実行中のセキュリティ状態は /api/health から取得され、フロントエンドのトークンは現在のブラウザセッションにのみ保持されます。",
    securityAudit: "セキュリティ監査",
    auditSessionLabel:
      "Workbench アシスタント、スクリプト、Hub アシスタントを含む control-plane 永続化イベント列を表示します。",
    auditWindow: "期間",
    auditSource: "ソース",
    auditRisk: "リスク",
    auditStatus: "状態",
    auditAction: "操作",
    auditSummaryTitle: "イベント要約",
    auditTrendTitle: "時間推移",
    auditTrendEmptyLabel: "現在の期間ではトレンドデータがありません。",
    auditSourceStatusTitle: "ソース × 状態",
    auditStudyFacetTitle: "Study ファセット",
    auditProjectFacetTitle: "Project ファセット",
    auditModelVersionFacetTitle: "Version ファセット",
    auditFacetEmptyLabel: "現在の期間では利用できるファセットがありません。",
    auditRefreshLabel: "イベントを更新",
    auditExportLabel: "分析バンドルを出力",
    auditExportCsvLabel: "CSV を出力",
    auditWindowOptions: { all: "全期間", h1: "直近 1 時間", h24: "直近 24 時間", d7: "直近 7 日", d30: "直近 30 日" },
    auditSourceOptions: { all: "すべて", assistant: "アシスタント", hubAssistant: "Hub アシスタント", script: "スクリプト" },
    auditRiskOptions: { all: "すべて", low: "低", sensitive: "機微", high: "高", destructive: "破壊的" },
    auditStatusOptions: { all: "すべて", prompted: "確認待ち", confirmed: "確認済み", cancelled: "取消済み", completed: "完了", failed: "失敗" },
    assistantLauncherHint: "ガイドが必要ですか？",
    assistantFloatingTitle: "ワークベンチに質問",
    assistantFloatingSubtitle: "作業面は軽く保ち、必要なときだけガイドを開きます。",
    assistantOpen: "アシスタントを開く",
    assistantClose: "アシスタントを閉じる",
    modelName: "モデル",
    material: "材料",
    load: "荷重",
    support: "拘束",
    viewport: "ビュー",
    report: "レポート",
    summary: "概要",
    messages: "メッセージ",
    nodeTable: "オブジェクト参照",
    objectTree: "オブジェクト",

} as const;
