"use client";

import {
  useDeferredValue,
  useEffect,
  useMemo,
  useRef,
  useState,
  useTransition,
  type Dispatch,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
  type SetStateAction,
} from "react";
import brand from "../../../../../assets/brand/brand.json";
import {
  buildWorkbenchAdminSelections,
  buildWorkbenchStudyFlags,
} from "@/components/workbench/workbench-admin-context";
import {
  applyJobContextToWorkbench as applyJobContextToWorkbenchWithDeps,
  applySelectedAdminJobContext as applySelectedAdminJobContextWithDeps,
  applySelectedAdminResultContext as applySelectedAdminResultContextWithDeps,
  openProjectContextById as openProjectContextByIdWithDeps,
  openSelectedAdminJobProject as openSelectedAdminJobProjectWithDeps,
  openSelectedAdminJobVersion as openSelectedAdminJobVersionWithDeps,
  openSelectedAdminResultProject as openSelectedAdminResultProjectWithDeps,
  openSelectedAdminResultVersion as openSelectedAdminResultVersionWithDeps,
  resolveScriptLinkedJob as resolveScriptLinkedJobWithDeps,
} from "@/components/workbench/workbench-admin-data-controller";
import { useWorkbenchAdminSecurityState } from "@/components/workbench/workbench-admin-security-state";
import {
  deleteWorkbenchAdminResultRecord,
  exportWorkbenchAdminResultRecord,
  refreshWorkbenchResults,
  saveWorkbenchAdminResultRecord,
} from "@/components/workbench/workbench-admin-result-controller";
import { useWorkbenchFlowControllers } from "@/components/workbench/workbench-flow-controllers";
import { buildWorkbenchFlowControllerProps } from "@/components/workbench/workbench-flow-controller-props";
import { WorkbenchMainShellMount } from "@/components/workbench/workbench-main-shell-mount";
import { buildWorkbenchMainShellComposition } from "@/components/workbench/workbench-main-shell-composition";
import { buildWorkbenchModelContent } from "@/components/workbench/workbench-model-content";
import { buildWorkbenchModelContentProps } from "@/components/workbench/workbench-model-content-props";
import { buildWorkbenchProjectFlows } from "@/components/workbench/workbench-project-flows";
import { useWorkbenchInteractionControllers } from "@/components/workbench/workbench-interaction-controllers";
import {
  copyByLanguage,
  humanizeSolverFailure,
  type WorkbenchCopy,
  type WorkbenchLanguage,
} from "@/components/workbench/workbench-copy";
import {
  defaultAxial,
  defaultBeam1d,
  defaultFrame2d,
  defaultHeatBar1d,
  defaultHeatPlaneQuad,
  defaultHeatPlaneTriangle,
  defaultPanelParametric,
  defaultParametric,
  defaultPlaneQuad,
  defaultPlaneTriangle,
  defaultSpring1d,
  defaultSpring2d,
  defaultSpring3d,
  defaultThermalBar1d,
  defaultThermalBeam1d,
  defaultThermalFrame2d,
  defaultThermalPlaneQuad,
  defaultThermalPlaneTriangle,
  defaultThermalTruss2d,
  defaultThermalTruss3d,
  defaultTorsion1d,
  defaultTruss,
  defaultTruss3d,
  type AxialFormState,
  type DirectMeshExecutionState,
  type DisplayTruss3dElement,
  type DisplayTruss3dNode,
  type DisplayTrussElement,
  type DisplayTrussNode,
  type PlaneResultField,
  type SelectionKind,
  type StabilitySummary,
  type TrussDiagnostics,
  type TrussSuggestion,
} from "@/components/workbench/workbench-defaults";
import { applyHistoryJobPayload } from "@/components/workbench/workbench-history-result";
import { useWorkbenchDataRefreshController } from "@/components/workbench/workbench-data-refresh-controller";
import {
  downloadBlobFile,
  downloadTextFile,
  resetActiveResult,
} from "@/components/workbench/workbench-file-helpers";
import {
  buildDisplayBeamElements,
  buildDisplayBeamNodes,
  buildDisplaySpring2dElements,
  buildDisplaySpring2dNodes,
  buildDisplaySpringElements,
  buildDisplaySpringNodes,
  buildDisplayThermalBeamElements,
  buildDisplayThermalBeamNodes,
  buildDisplayTorsionElements,
  buildDisplayTorsionNodes,
} from "@/components/workbench/workbench-display-line-helpers";
import { applyImportedWorkbenchModel } from "@/components/workbench/workbench-model-load";
import {
  buildThermalBarFromHeatResult,
  buildThermalPlaneQuadFromHeatResult,
  buildThermalPlaneTriangleFromHeatResult,
  ensureBeamModelMaterials,
  ensureFrameModelMaterials,
} from "@/components/workbench/workbench-model-transform-helpers";
import {
  buildDisplayFrameElements,
  buildDisplayFrameNodes,
  buildDisplayHeatBarElements,
  buildDisplayHeatBarNodes,
  buildDisplayThermalBarElements,
  buildDisplayThermalBarNodes,
  buildDisplayThermalFrameElements,
  buildDisplayThermalFrameNodes,
  buildDisplayThermalTrussElements,
  buildDisplayThermalTrussNodes,
  buildDisplayTrussElements,
  buildDisplayTrussNodes,
} from "@/components/workbench/workbench-display-planar-helpers";
import {
  downloadWorkbenchDatabaseSnapshot,
  downloadWorkbenchProjectBundleJson,
  downloadWorkbenchProjectBundleZip,
} from "@/components/workbench/workbench-export-controller";
import {
  downloadWorkbenchFrameForceSummary,
  downloadWorkbenchFrameHotspotSummary,
  downloadWorkbenchPlaneHotspotSummary,
  downloadWorkbenchResultCsv,
  downloadWorkbenchResultJson,
} from "@/components/workbench/workbench-result-export-controller";
import {
  useWorkbenchResultWindowController,
  type ResultWindowState,
} from "@/components/workbench/workbench-result-window-controller";
import { useWorkbenchEditControllers } from "@/components/workbench/workbench-edit-controllers";
import {
  buildDisplaySpring3dElements,
  buildDisplaySpring3dNodes,
  buildDisplayThermalTruss3dElements,
  buildDisplayThermalTruss3dNodes,
  buildDisplayTruss3dElements,
  buildDisplayTruss3dNodes,
  projectTruss3dPoint,
} from "@/components/workbench/workbench-display-spatial-helpers";
import {
  clusterHealthTone,
  formatJobMessage,
  formatPeerStatus,
  formatProtocolMethodLabel,
  isAxialResult,
  isBeam1dResult,
  isFrame2dResult,
  isHeatBar1dResult,
  isHeatPlaneQuad2dResult,
  isHeatPlaneTriangle2dResult,
  isPlaneResult,
  isSpring1dResult,
  isSpring2dResult,
  isSpring3dResult,
  isThermalBar1dResult,
  isThermalBeam1dResult,
  isThermalFrame2dResult,
  isThermalTruss2dResult,
  isThermalTruss3dResult,
  isTorsion1dResult,
  isTruss3dResult,
  isTrussResult,
  localMaterialLabel,
  materialColorByIndex,
} from "@/components/workbench/workbench-result-helpers";
import { useWorkbenchStudyResultDerived } from "@/components/workbench/workbench-study-result-derived";
import { WorkbenchInspectorMount } from "@/components/workbench/workbench-inspector-mount";
import { useWorkbenchJobHistoryController } from "@/components/workbench/workbench-job-history-controller";
import { WorkbenchSidebarMount } from "@/components/workbench/workbench-sidebar-mount";
import { buildWorkbenchSidebarMountProps } from "@/components/workbench/workbench-sidebar-mount-props";
import { buildWorkbenchMainShellProps } from "@/components/workbench/workbench-main-shell-props";
import { useWorkbenchShellState } from "@/components/workbench/workbench-shell-state";
import { useWorkbenchRuntimeGuards } from "@/components/workbench/workbench-runtime-guards";
import { useWorkbenchWorkspaceState } from "@/components/workbench/workbench-workspace-state";
import {
  importWorkbenchModelFile,
  openWorkbenchSample,
} from "@/components/workbench/workbench-sample-import-controller";
import {
  applyStudyKindSelection,
  createStudyKindResetHandlers,
  isWorkbenchStudyKind,
} from "@/components/workbench/workbench-study-kind-controller";
import {
  analyzeTrussModel,
  getTrussBounds,
  renderLoadGlyph,
  renderSupportGlyph,
  round,
  summarizeTrussStability,
  toSvgPoint,
} from "@/components/workbench/workbench-truss-helpers";
import { buildWorkbenchStudySidebarData } from "@/components/workbench/workbench-study-sidebar-data";
import {
  type AssistantMode,
  type BeamResultField,
  type BeamStudyJobInput,
  type FrameResultField,
  type FrameStudyJobInput,
  type HeatBarStudyJobInput,
  type HeatPlaneStudyJobInput,
  type ImmersiveToolTab,
  type Language,
  type LibraryPanelTab,
  type LineResultField,
  type ModelPanelTab,
  type PlaneStudyJobInput,
  SECURITY_EVENT_WINDOW_MS,
  type SecurityEventWindow,
  type SidebarSection,
  type Spring2dStudyJobInput,
  type Spring3dStudyJobInput,
  type SpringStudyJobInput,
  type StudyKind,
  type StudyPanelTab,
  type SystemDataTab,
  type SystemPanelTab,
  type ThermalBarStudyJobInput,
  type ThermalBeamStudyJobInput,
  type ThermalFrameStudyJobInput,
  type ThermalTruss2dStudyJobInput,
  type ThermalTruss3dStudyJobInput,
  type Theme,
  type WorkflowPanelTab,
} from "@/components/workbench/workbench-types";
import type { ModelToolsPage } from "@/components/workbench/model/workbench-model-sidebar";
import {
  isWorkflowGraphResult,
  summarizeWorkflowArtifacts,
  upsertWorkflowRunRecord,
  useWorkbenchWorkflowController,
} from "@/components/workbench/workflow/workbench-workflow-controller";
import {
  fixed,
  formatMilliseconds,
  formatTime,
  scientific,
  serializeCurrentModel,
  toAxialInput,
} from "@/lib/workbench/helpers";
import { type HistoryEntry, type WorkbenchSnapshot } from "@/lib/workbench/history";
import {
  readSecurityAuditLog,
  type WorkbenchSecurityAuditRisk,
  type WorkbenchSecurityAuditSource,
} from "@/lib/workbench/security-audit";
import {
  buildAdminJobRows,
  buildAdminResultRows,
  buildLibraryJobRows,
  buildLibraryModelRows,
  buildLibrarySampleRows,
  buildLibraryVersionRows,
  buildProtocolAgentCards,
  buildStudyDomainOptions,
  classifyStudyKindFamily,
  buildStudyKindOptionGroups,
} from "@/lib/workbench/view-models";
import {
  ensurePlaneModelMaterials,
  ensureTruss3dModelMaterials,
  ensureTrussModelMaterials,
} from "@/lib/workbench/material-commands";
import { clampChunkOffset, RESULT_WINDOW_BASE_SIZE } from "@/lib/workbench/result-window";
import { updateFrame2dNode } from "@/lib/workbench/frame2d-commands";
import { toggleDraftSelection } from "@/lib/workbench/truss2d-commands";
import {
  addTruss3dNodeCommand,
} from "@/lib/workbench/truss3d-commands";
import {
  exportStudyModel,
  type ParametricPanelConfig,
  type ParametricTrussConfig,
} from "@/lib/models";
import { SAMPLE_LIBRARY } from "@/lib/models";
import {
  type WorkbenchScriptSnapshot,
} from "@/lib/scripting/workbench-script-runtime";
import {
  createAxialBarJob,
  createBeam1dJob,
  createHeatBar1dJob,
  createHeatPlaneQuad2dJob,
  createHeatPlaneTriangle2dJob,
  createThermalBeam1dJob,
  createThermalBar1dJob,
  createThermalFrame2dJob,
  createThermalPlaneQuad2dJob,
  createThermalPlaneTriangle2dJob,
  createThermalTruss2dJob,
  createThermalTruss3dJob,
  createSpring1dJob,
  createSpring2dJob,
  createSpring3dJob,
  createTorsion1dJob,
  createDirectMeshSolve,
  createFrame2dJob,
  createPlaneQuad2dJob,
  createPlaneTriangle2dJob,
  createModel,
  createModelVersion,
  createProject,
  createTruss2dJob,
  createTruss3dJob,
  cancelJob,
  deleteJobRecord,
  deleteModel,
  deleteModelVersion,
  deleteProject,
  deleteResultRecord,
  fetchModel,
  fetchModelVersion,
  fetchModelVersions,
  fetchJobStatus,
  fetchResults,
  type AxialBarJobInput,
  type AxialBarResult,
  type Beam1dElementInput,
  type Beam1dJobInput,
  type Beam1dNodeInput,
  type Beam1dResult,
  type DirectMeshSelectionMode,
  type Frame2dElementInput,
  type Frame2dJobInput,
  type Frame2dNodeInput,
  type Frame2dResult,
  type FrontendRuntimeMode,
  type HeatBar1dElementInput,
  type HeatBar1dJobInput,
  type HeatBar1dNodeInput,
  type HeatBar1dResult,
  type HeatPlaneNodeInput,
  type HeatPlaneQuad2dJobInput,
  type HeatPlaneQuad2dResult,
  type HeatPlaneTriangle2dJobInput,
  type HeatPlaneTriangle2dResult,
  type HealthPayload,
  type JobEnvelope,
  type JobResultRecord,
  type JobState,
  type ModelRecord,
  type ModelVersionRecord,
  type PlaneQuad2dJobInput,
  type PlaneQuad2dResult,
  type PlaneTriangle2dJobInput,
  type PlaneTriangle2dResult,
  type ThermalPlaneQuad2dJobInput,
  type ThermalPlaneQuad2dResult,
  type ThermalPlaneTriangle2dJobInput,
  type ThermalPlaneTriangle2dResult,
  type ProtocolAgentDescriptor,
  type ProjectRecord,
  type ResultRecord,
  type SecurityEventRecord,
  type ThermalBeam1dElementInput,
  type ThermalBeam1dJobInput,
  type ThermalBeam1dNodeInput,
  type ThermalBeam1dResult,
  type ThermalBar1dElementInput,
  type ThermalBar1dJobInput,
  type ThermalBar1dNodeInput,
  type ThermalBar1dResult,
  type ThermalFrame2dElementInput,
  type ThermalFrame2dJobInput,
  type ThermalFrame2dNodeInput,
  type ThermalFrame2dResult,
  type ThermalTruss2dElementInput,
  type ThermalTruss2dJobInput,
  type ThermalTruss2dNodeInput,
  type ThermalTruss2dResult,
  type ThermalTruss3dElementInput,
  type ThermalTruss3dJobInput,
  type ThermalTruss3dNodeInput,
  type ThermalTruss3dResult,
  type WorkflowGraphJobResult,
  type Spring1dJobInput,
  type Spring1dResult,
  type Spring2dJobInput,
  type Spring2dResult,
  type Spring3dJobInput,
  type Spring3dResult,
  type Torsion1dJobInput,
  type Torsion1dResult,
  resolveHeatBar1dJobInput,
  resolveHeatPlaneQuad2dJobInput,
  resolveHeatPlaneTriangle2dJobInput,
  resolveBeam1dJobInput,
  resolveThermalBeam1dJobInput,
  resolveThermalBar1dJobInput,
  resolveThermalFrame2dJobInput,
  resolveThermalTruss2dJobInput,
  resolveThermalTruss3dJobInput,
  resolveSpring1dJobInput,
  resolveSpring2dJobInput,
  resolveSpring3dJobInput,
  resolveTorsion1dJobInput,
  resolveThermalPlaneQuad2dJobInput,
  resolveThermalPlaneTriangle2dJobInput,
  resolvePlaneQuad2dJobInput,
  resolvePlaneTriangle2dJobInput,
  resolveFrame2dJobInput,
  resolveTruss2dJobInput,
  resolveTruss3dJobInput,
  type Truss2dJobInput,
  type Truss2dResult,
  type Truss3dJobInput,
  type Truss3dResult,
  updateJobRecord,
  updateModel,
  updateModelVersion,
  updateProject,
  updateResultRecord,
} from "@/lib/api";

export function Workbench() {
  const workspaceState = useWorkbenchWorkspaceState({
    defaultLoadedModelName: copyByLanguage.en.defaultModel,
    defaultMessage: copyByLanguage.en.initialLoaded,
    defaultProjectLabel: copyByLanguage.en.defaultProject,
  });
  const {
    studyKind,
    setStudyKind,
    axialForm,
    setAxialForm,
    heatBarModel,
    setHeatBarModel,
    heatPlaneModel,
    setHeatPlaneModel,
    thermalBarModel,
    setThermalBarModel,
    thermalBeamModel,
    setThermalBeamModel,
    thermalFrameModel,
    setThermalFrameModel,
    thermalTrussModel,
    setThermalTrussModel,
    trussModel,
    setTrussModel,
    thermalTruss3dModel,
    setThermalTruss3dModel,
    truss3dModel,
    setTruss3dModel,
    planeModel,
    setPlaneModel,
    frameModel,
    setFrameModel,
    beamModel,
    setBeamModel,
    torsionModel,
    setTorsionModel,
    springModel,
    setSpringModel,
    spring2dModel,
    setSpring2dModel,
    spring3dModel,
    setSpring3dModel,
    parametric,
    setParametric,
    panelParametric,
    setPanelParametric,
    activeMaterial,
    setActiveMaterial,
    planeResultField,
    setPlaneResultField,
    frameResultField,
    setFrameResultField,
    beamResultField,
    setBeamResultField,
    planeHotspotLimit,
    setPlaneHotspotLimit,
    focusedPlaneElement,
    setFocusedPlaneElement,
    focusedFrameElement,
    setFocusedFrameElement,
    result,
    setResult,
    resultWindow,
    setResultWindow,
    resultWindowOffset,
    setResultWindowOffset,
    resultWindowLimit,
    setResultWindowLimit,
    canvasViewportWidth,
    setCanvasViewportWidth,
    job,
    setJob,
    resultRecords,
    setResultRecords,
    projects,
    setProjects,
    selectedProjectId,
    setSelectedProjectId,
    selectedModelId,
    setSelectedModelId,
    selectedVersionId,
    setSelectedVersionId,
    modelVersions,
    setModelVersions,
    projectNameDraft,
    setProjectNameDraft,
    projectDescriptionDraft,
    setProjectDescriptionDraft,
    loadedModelName,
    setLoadedModelName,
    message,
    setMessage,
    hiddenMaterials,
    setHiddenMaterials,
    sidebarSection,
    setSidebarSection,
    studyTab,
    setStudyTab,
    modelTab,
    setModelTab,
    modelToolsPage,
    setModelToolsPage,
    libraryTab,
    setLibraryTab,
    systemDataTab,
    setSystemDataTab,
    systemPanelTab,
    setSystemPanelTab,
    draggingNode,
    setDraggingNode,
    truss3dLinkMode,
    setTruss3dLinkMode,
    selectedTruss3dNodes,
    setSelectedTruss3dNodes,
    selectedNode,
    setSelectedNode,
    selectedElement,
    setSelectedElement,
    memberDraftNodes,
    setMemberDraftNodes,
    undoStack,
    setUndoStack,
    redoStack,
    setRedoStack,
  } = workspaceState;
  const [health, setHealth] = useState<HealthPayload | null>(null);
  const [protocolAgents, setProtocolAgents] = useState<ProtocolAgentDescriptor[]>([]);
  const shellState = useWorkbenchShellState({
    setLoadedModelName,
    setMessage,
  });
  const {
    language,
    languagePacks,
    setLanguagePacks,
    theme,
    setTheme,
    frontendRuntimeMode,
    setFrontendRuntimeMode,
    directMeshEndpointsText,
    setDirectMeshEndpointsText,
    directMeshSelectionMode,
    setDirectMeshSelectionMode,
    controlPlaneApiToken,
    setControlPlaneApiToken,
    clusterApiToken,
    setClusterApiToken,
    directMeshApiToken,
    setDirectMeshApiToken,
    assistantMode,
    setAssistantMode,
    assistantApiBaseUrl,
    setAssistantApiBaseUrl,
    assistantApiKey,
    setAssistantApiKey,
    assistantModel,
    setAssistantModel,
    assistantWindowOpen,
    setAssistantWindowOpen,
    directMeshExecution,
    setDirectMeshExecution,
    showShortcutHints,
    setShowShortcutHints,
    immersiveGuardrails,
    setImmersiveGuardrails,
    immersiveViewport,
    setImmersiveViewport,
    immersiveToolDrawerOpen,
    setImmersiveToolDrawerOpen,
    immersiveHelpDrawerOpen,
    setImmersiveHelpDrawerOpen,
    immersiveToolTab,
    setImmersiveToolTab,
    truss3dProjectionMode,
    setTruss3dProjectionMode,
    truss3dShowGrid,
    setTruss3dShowGrid,
    truss3dShowLabels,
    setTruss3dShowLabels,
    truss3dShowNodes,
    setTruss3dShowNodes,
    truss3dBoxSelectMode,
    setTruss3dBoxSelectMode,
    truss3dViewPreset,
    setTruss3dViewPreset,
    truss3dFocusRequestVersion,
    setTruss3dFocusRequestVersion,
    truss3dResetRequestVersion,
    setTruss3dResetRequestVersion,
    truss3dNudgeStep,
    setTruss3dNudgeStep,
    truss3dBatchLoadX,
    setTruss3dBatchLoadX,
    truss3dBatchLoadY,
    setTruss3dBatchLoadY,
    truss3dBatchLoadZ,
    setTruss3dBatchLoadZ,
    applyLanguagePreference,
    activeLanguagePack,
    t,
    languagePackCatalogRows,
  } = shellState;
  const [isPending, startTransition] = useTransition();
  const viewportPanelRef = useRef<HTMLElement | null>(null);
  const {
    canvasStageRef,
    drag3dHistoryCapturedRef,
    dragFrameRef,
    dragHistoryCapturedRef,
    jobPollTokenRef,
    pendingDragPointRef,
    resultRefreshSeqRef,
  } = useWorkbenchRuntimeGuards({
    beamResultField,
    focusedFrameElement,
    focusedPlaneElement,
    immersiveGuardrails,
    immersiveViewport,
    job,
    language,
    frameResultField,
    projects,
    selectedProjectId,
    setAssistantWindowOpen,
    setBeamResultField,
    setFocusedFrameElement,
    setFocusedPlaneElement,
    setFrameResultField,
    setImmersiveHelpDrawerOpen,
    setImmersiveToolDrawerOpen,
    setImmersiveViewport,
    setMessage,
    setProjectDescriptionDraft,
    setProjectNameDraft,
    setSystemPanelTab,
    studyKind,
    systemPanelTab,
    t,
    viewportPanelRef,
  });
  const jobIsActive =
    job?.status === "queued" ||
    job?.status === "preprocessing" ||
    job?.status === "partitioning" ||
    job?.status === "solving" ||
    job?.status === "postprocessing";
  const jobHistoryController = useWorkbenchJobHistoryController({
    labels: {
      jobCancelled: t.jobCancelled,
      initialFailed: t.initialFailed,
      requestTimedOut: t.requestTimedOut,
    },
    job,
    jobIsActive,
    jobPollTokenRef,
    setJob,
    setMessage,
    startTransition,
  });
  const {
    jobHistory,
    setJobHistory,
    selectedAdminJobId,
    setSelectedAdminJobId,
    refreshJobHistory,
    cancelCurrentJob,
  } = jobHistoryController;

  const resultWindowMaxTotal = resultWindow ? Math.max(resultWindow.totalNodes, resultWindow.totalElements) : 0;
  const { handleCanvasStageScroll } = useWorkbenchResultWindowController({
    canvasStageRef,
    canvasViewportWidth,
    frontendRuntimeMode,
    guards: {
      isAxialResult,
      isTrussResult,
      isHeatBar1dResult,
      isHeatPlaneQuad2dResult,
      isHeatPlaneTriangle2dResult,
      isThermalBar1dResult,
      isThermalBeam1dResult,
      isThermalTruss2dResult,
      isThermalTruss3dResult,
      isTruss3dResult,
      isSpring1dResult,
      isSpring2dResult,
      isSpring3dResult,
      isBeam1dResult,
      isTorsion1dResult,
      isFrame2dResult,
    },
    jobId: job?.job_id ?? null,
    requestTimedOutLabel: t.requestTimedOut,
    result,
    resultWindow,
    resultWindowLimit,
    resultWindowMaxTotal,
    resultWindowOffset,
    setCanvasViewportWidth,
    setMessage,
    setResultWindow,
    setResultWindowLimit,
    setResultWindowOffset,
    studyKind,
  });

  const adminSecurityState = useWorkbenchAdminSecurityState({
    jobHistory,
    resultRecords,
    selectedAdminJobId,
  });
  const {
    selectedAdminResultJobId,
    setSelectedAdminResultJobId,
    adminFilterProjectId,
    setAdminFilterProjectId,
    adminFilterModelVersionId,
    setAdminFilterModelVersionId,
    securityEventRecords,
    setSecurityEventRecords,
    scriptRecordingMode,
    setScriptRecordingMode,
    securityEventWindowFilter,
    setSecurityEventWindowFilter,
    securityEventSourceFilter,
    setSecurityEventSourceFilter,
    securityEventRiskFilter,
    setSecurityEventRiskFilter,
    securityEventStatusFilter,
    setSecurityEventStatusFilter,
    securityEventActionFilter,
    setSecurityEventActionFilter,
    adminJobMessage,
    setAdminJobMessage,
    adminJobProjectId,
    setAdminJobProjectId,
    adminJobModelVersionId,
    setAdminJobModelVersionId,
    adminJobCaseId,
    setAdminJobCaseId,
    adminResultDraft,
    setAdminResultDraft,
  } = adminSecurityState;

  const workflowController = useWorkbenchWorkflowController({
    labels: {
      workflowCatalogLoaded: t.workflowCatalogLoaded,
      workflowCatalogUnsupported: t.workflowCatalogUnsupported,
      workflowCatalogQueued: t.workflowCatalogQueued,
      workflowCatalogCompleted: t.workflowCatalogCompleted,
      workflowCatalogFailed: t.workflowCatalogFailed,
      initialFailed: t.initialFailed,
      pollingDetached: t.pollingDetached,
    },
    jobPollTokenRef,
    refreshJobHistory,
    setJob,
    setMessage,
    openWorkflowRunsSurface: (workflowId) => {
      setSelectedWorkflowId(workflowId);
      setSidebarSection("workflow");
      setWorkflowPanelTab("runs");
    },
  });
  const {
    workflowCatalog,
    workflowCatalogBusy,
    workflowPanelTab,
    setWorkflowPanelTab,
    selectedWorkflowId,
    setSelectedWorkflowId,
    workflowRuns,
    setWorkflowRuns,
    selectedWorkflow,
    latestWorkflowSummary,
    refreshWorkflowCatalog,
    runWorkflowCatalogEntry,
  } = workflowController;
  const { selectedProject, selectedProjectModels, selectedAdminJob, selectedAdminResult } = buildWorkbenchAdminSelections({
    jobHistory,
    resultRecords,
    projects,
    selectedProjectId,
    selectedAdminJobId,
    selectedAdminResultJobId,
  });
  const deferredProjectModels = useDeferredValue(selectedProjectModels);
  const deferredModelVersions = useDeferredValue(modelVersions);
  const deferredJobHistory = useDeferredValue(jobHistory);
  const deferredResultRecords = useDeferredValue(resultRecords);
  async function refreshResults() {
    await primaryActionsController.refreshResults();
  }
  const studyResultDerived = useWorkbenchStudyResultDerived({
    studyKind,
    result,
    job,
    resultWindow,
    t,
    selectedNode,
    selectedElement,
    axialForm,
    heatBarModel,
    heatPlaneModel,
    thermalBarModel,
    thermalBeamModel,
    thermalFrameModel,
    thermalTrussModel,
    thermalTruss3dModel,
    springModel,
    spring2dModel,
    spring3dModel,
    trussModel,
    truss3dModel,
    planeModel,
    frameModel,
    beamModel,
    torsionModel,
    beamResultField,
    frameResultField,
    planeResultField,
    planeHotspotLimit,
    language,
    loadedModelName,
    downloadTextFile,
    setMessage,
    health,
    frontendRuntimeMode,
    directMeshSelectionMode,
    directMeshExecution,
    directMeshApiToken,
    protocolAgents,
    hiddenMaterials,
    deferredJobHistory,
    deferredResultRecords,
    deferredProjectModels,
    deferredModelVersions,
    adminFilterProjectId,
    adminFilterModelVersionId,
    jobHistory,
    projects,
    securityEventRecords,
    securityEventWindowFilter,
    formatTime,
    formatMilliseconds,
    round,
    resultWindowLimit,
    resultWindowMaxTotal,
    resultWindowOffset,
    directMeshEndpointsText,
    immersiveViewport,
    immersiveToolDrawerOpen,
    immersiveHelpDrawerOpen,
    showShortcutHints,
  });
  const {
    refreshHealth,
    refreshProjects,
    refreshSecurityEvents,
    refreshVersions,
  } = useWorkbenchDataRefreshController({
    directMeshEndpointsText,
    directMeshSelectionMode,
    frontendRuntimeMode,
    securityEventActionFilter,
    securityEventRiskFilter,
    securityEventSourceFilter,
    securityEventStatusFilter,
    securityEventWindowFilter,
    selectedModelId,
    selectedProjectId,
    setHealth,
    setModelVersions,
    setProjects,
    setProtocolAgents,
    setSecurityEventRecords,
    setSelectedModelId,
    setSelectedProjectId,
    setSelectedVersionId,
    refreshJobHistory,
    refreshResults,
    securityEventWindowMs: SECURITY_EVENT_WINDOW_MS,
  });
  const downloadResultJson = () => {
    downloadWorkbenchResultJson(resultExportEffects);
  };

  const downloadResultCsv = () => {
    downloadWorkbenchResultCsv(resultExportEffects);
  };

  const downloadPlaneHotspotSummary = () => {
    downloadWorkbenchPlaneHotspotSummary(resultExportEffects);
  };

  const downloadFrameHotspotSummary = () => {
    downloadWorkbenchFrameHotspotSummary(resultExportEffects);
  };

  const downloadFrameForceSummary = () => {
    downloadWorkbenchFrameForceSummary(resultExportEffects);
  };

  const railItems: Array<{ key: SidebarSection; label: string; symbol: string }> = [
    { key: "model", label: t.rail.model, symbol: "M" },
    { key: "workflow", label: t.rail.workflow, symbol: "W" },
    { key: "library", label: t.rail.library, symbol: "H" },
    { key: "system", label: t.rail.system, symbol: "Y" },
  ];

  const { adminDataEffects, projectStorageController } = buildWorkbenchProjectFlows({
    selectedAdminJob,
    selectedAdminJobId,
    selectedAdminResultJobId,
    jobHistory,
    projects,
    refreshVersions,
    setAdminFilterProjectId,
    setAdminFilterModelVersionId,
    setAdminJobCaseId,
    setLibraryTab,
    setSelectedProjectId,
    setSelectedModelId,
    setSelectedVersionId,
    setModelVersions,
    setSidebarSection,
    setMessage,
    language,
    t,
    startTransition,
    activeMaterial,
    createProject,
    createModel,
    createModelVersion,
    updateModelVersion,
    fetchModel,
    fetchModelVersion,
    refreshProjects,
    recordHistory,
    resetActiveResult: () => resetActiveResult(setResult, setJob),
    setLoadedModelName,
    setStudyKind,
    setAxialForm,
    setHeatBarModel,
    setHeatPlaneModel,
    setThermalBarModel,
    setThermalBeamModel,
    setThermalFrameModel,
    setThermalTrussModel,
    setThermalTruss3dModel,
    setSpringModel,
    setSpring2dModel,
    setSpring3dModel,
    setTrussModel,
    setTruss3dModel,
    setPlaneModel,
    setFrameModel,
    setBeamModel,
    setTorsionModel,
    setPlaneResultField,
    setParametric,
    setActiveMaterial,
    selectedProject,
    selectedProjectId,
    selectedProjectModels,
    selectedModelId,
    selectedVersionId,
    projectNameDraft,
    projectDescriptionDraft,
    loadedModelName,
    studyKind,
    axialForm,
    heatBarModel,
    heatPlaneModel,
    thermalBarModel,
    thermalBeamModel,
    thermalFrameModel,
    thermalTrussModel,
    trussModel,
    thermalTruss3dModel,
    truss3dModel,
    planeModel,
    frameModel,
    beamModel,
    torsionModel,
    springModel,
    spring2dModel,
    spring3dModel,
    parametric,
    round,
    updateProject,
    deleteProject,
    updateModel,
    deleteModel,
    deleteModelVersion,
    fetchModelVersions,
    fetchJobStatus,
    serializeCurrentModel: () =>
      serializeCurrentModel(
        studyKind,
        loadedModelName,
        activeMaterial,
        axialForm,
        heatBarModel,
        heatPlaneModel,
        thermalBarModel,
        thermalBeamModel,
        thermalFrameModel,
        thermalTrussModel,
        trussModel,
        thermalTruss3dModel,
        truss3dModel,
        planeModel,
        frameModel,
        beamModel,
        torsionModel,
        springModel,
        spring2dModel,
        spring3dModel,
        parametric,
        round,
      ),
  });

  const {
    isAxial,
    isHeatBar,
    isHeatPlaneTriangle,
    isHeatPlaneQuad,
    isHeatPlane,
    isThermalBar,
    isThermalBeam,
    isThermalFrame,
    isThermalTruss2d,
    isThermalTruss3d,
    isThermalPlaneTriangle,
    isThermalPlaneQuad,
    isThermal,
    isSpring1d,
    isSpring2d,
    isSpring3d,
    isSpring,
    isBeam,
    isTorsion,
    isTruss,
    isTruss3d,
    isFrame,
    isFrameLike,
    isPlane,
    axialResult,
    heatBarResult,
    heatPlaneTriangleResult,
    heatPlaneQuadResult,
    thermalBarResult,
    thermalBeamResult,
    thermalFrameResult,
    thermalTrussResult,
    thermalTruss3dResult,
    springResult,
    spring2dResult,
    spring3dResult,
    activeSpringResult,
    activeSpringModel,
    trussResult,
    truss3dResult,
    beamResult,
    activeBeamLikeResult,
    activeBeamLikeModel,
    torsionResult,
    frameResult,
    activeFrameLikeResult,
    activeFrameLikeModel,
    planeResult,
    activePlaneInputModel,
    activeResultWindow,
    trussDiagnostics,
    trussStability,
    axialNodes,
    axialElements,
    axialLength,
    axialScale,
    planeWindowNodes,
    planeWindowElements,
    trussWindowNodes,
    trussWindowElements,
    thermalTrussWindowNodes,
    thermalTrussWindowElements,
    truss3dWindowNodes,
    truss3dWindowElements,
    beamWindowNodes,
    beamWindowElements,
    thermalBeamWindowNodes,
    thermalBeamWindowElements,
    torsionWindowNodes,
    torsionWindowElements,
    heatBarWindowNodes,
    heatBarWindowElements,
    thermalWindowNodes,
    thermalWindowElements,
    springWindowNodes,
    springWindowElements,
    spring2dWindowNodes,
    spring2dWindowElements,
    spring3dWindowNodes,
    spring3dWindowElements,
    frameWindowNodes,
    frameWindowElements,
    thermalFrameWindowNodes,
    thermalFrameWindowElements,
    displayTrussNodes,
    displayTrussElements,
    trussBounds,
    displayTruss3dNodes,
    displayTruss3dElements,
    planeNodes,
    planeElements,
    planeBounds,
    activeLineResultField,
    planeResultFieldMax,
    frameResultFieldMax,
    planeResultFieldLabel,
    planeLegendText,
    frameResultFieldLabel,
    frameLegendText,
    frameTreeValueLabel,
    planeHotspotElements,
    planeThermalRows,
    frameHotspotElements,
    frameForceRows,
    frameMaxAxialForce,
    frameMaxShearForce,
    selectedNodeData,
    selectedElementData,
    selectedTruss3dNodeData,
    selectedTruss3dElementData,
    selectedPlaneNodeData,
    selectedPlaneElementData,
    selectedFrameNodeData,
    selectedFrameElementData,
    selectedBeamNodeData,
    selectedBeamElementData,
    selectedTorsionNodeData,
    selectedTorsionElementData,
    selectedThermalNodeData,
    selectedThermalElementData,
    selectedSpringElementData,
    selectedNodeIssues,
    securityUi,
    resultExportEffects,
    thermalFrameMaxTemperatureDelta,
    thermalFrameMaxTemperatureGradient,
    thermalBeamMaxTemperatureGradient,
    heartbeatStatusValue,
    heartbeatToneValue,
    translatedFailureReason,
    currentMaterials,
    hiddenMaterialIds,
    materialColorMap,
    materialOptions,
    adminJobRows,
    adminResultRows,
    librarySampleRows,
    libraryModelRows,
    libraryVersionRows,
    libraryJobRows,
    protocolAgentCards,
    runtimeBackendRows,
    runtimeProtocolRows,
    runtimeProtocolMethods,
    runtimeSecurityRows,
    runtimeAuditEntries,
    runtimeAuditSummaryRows,
    runtimeAuditTrendBars,
    runtimeAuditSourceStatusFacets,
    runtimeAuditStudyFacets,
    runtimeAuditProjectFacets,
    runtimeAuditModelVersionFacets,
    runtimeWatchdogRows,
    trussElementColors,
    truss3dElementColors,
    planeElementColors,
    nodeCount,
    activeResultWindowLimit,
    resultWindowStart,
    resultWindowEnd,
    resultWindowJumps,
    hasViewportDock,
    showViewportToolStrip,
    shouldStretchSpaceViewport,
    viewportPixelWidth,
    directMeshEndpoints,
    hasAnyResult,
  } = studyResultDerived;
  const canProjectHeatToThermo =
    (studyKind === "heat_bar_1d" && Boolean(heatBarResult)) ||
    (studyKind === "heat_plane_triangle_2d" && Boolean(heatPlaneTriangleResult)) ||
    (studyKind === "heat_plane_quad_2d" && Boolean(heatPlaneQuadResult));
  const projectHeatToThermoStudy = () => {
    if (studyKind === "heat_bar_1d" && heatBarResult) {
      recordHistory(t.projectHeatToThermoAction);
      resetActiveResult(setResult, setJob);
      setThermalBarModel(buildThermalBarFromHeatResult(heatBarModel, heatBarResult, thermalBarModel));
      setStudyKind("thermal_bar_1d");
      openWorkspaceStudy("controls");
      setMessage(t.projectedHeatToThermo);
      return "thermal_bar_1d" as const;
    }

    if (studyKind === "heat_plane_triangle_2d" && heatPlaneTriangleResult) {
      recordHistory(t.projectHeatToThermoAction);
      resetActiveResult(setResult, setJob);
      setPlaneModel(
        buildThermalPlaneTriangleFromHeatResult(
          heatPlaneModel as HeatPlaneTriangle2dJobInput,
          heatPlaneTriangleResult,
          planeModel as ThermalPlaneTriangle2dJobInput,
          activeMaterial,
        ),
      );
      setPlaneResultField("average_temperature_delta");
      setStudyKind("thermal_plane_triangle_2d");
      openWorkspaceStudy("controls");
      setMessage(t.projectedHeatToThermo);
      return "thermal_plane_triangle_2d" as const;
    }

    if (studyKind === "heat_plane_quad_2d" && heatPlaneQuadResult) {
      recordHistory(t.projectHeatToThermoAction);
      resetActiveResult(setResult, setJob);
      setPlaneModel(
        buildThermalPlaneQuadFromHeatResult(
          heatPlaneModel as HeatPlaneQuad2dJobInput,
          heatPlaneQuadResult,
          planeModel as ThermalPlaneQuad2dJobInput,
          activeMaterial,
        ),
      );
      setPlaneResultField("average_temperature_delta");
      setStudyKind("thermal_plane_quad_2d");
      openWorkspaceStudy("controls");
      setMessage(t.projectedHeatToThermo);
      return "thermal_plane_quad_2d" as const;
    }

    return null;
  };

  const editControllers = useWorkbenchEditControllers({
    t,
    language,
    activeMaterial,
    setHiddenMaterials,
    setMessage,
    studyKind,
    activeFrameLikeModel,
    isFrameLike,
    isHeatPlane,
    isThermalFrame,
    isThermalTruss2d,
    isThermalTruss3d,
    memberDraftNodes,
    parametric,
    recordHistory,
    resetResults: () => resetActiveResult(setResult, setJob),
    round,
    selectedElement,
    selectedNode,
    selectedTruss3dNodes,
    setFrameModel,
    setHeatPlaneModel,
    setMemberDraftNodes,
    setPlaneModel,
    setSelectedElement,
    setSelectedNode,
    setSelectedTruss3dNodes,
    setSidebarSection,
    setStudyKind,
    setThermalFrameModel,
    setThermalTruss3dModel,
    setThermalTrussModel,
    setTruss3dModel,
    setTrussModel,
    truss3dBatchLoadX,
    truss3dBatchLoadY,
    truss3dBatchLoadZ,
    truss3dModel,
    trussModel,
    isBeam,
    isTorsion,
    isHeatBar,
    isThermal,
    isThermalBar,
    truss3dLinkMode,
    trussBounds,
    draggingNode,
    dragHistoryCapturedRef,
    dragFrameRef,
    pendingDragPointRef,
    setTruss3dLinkMode,
    setDraggingNode,
    setActiveMaterial,
    setAxialForm,
    setParametric,
    setTorsionModel,
    setHeatBarModel,
    setBeamModel,
  });
  const {
    createProjectRecord,
    deleteProjectRecord,
    deleteSavedModelRecord,
    deleteSelectedVersion,
    downloadDatabaseSnapshot,
    downloadProjectBundleJson,
    downloadProjectBundleZip,
    importProjectBundle,
    openModelVersionById,
    openSavedModel,
    openSavedVersion,
    renameSelectedVersion,
    saveModelVersion,
    updateProjectRecord,
  } = projectStorageController;

  const {
    addCustomMaterialToCurrentModel,
    addMaterialToCurrentModel,
    applyMaterialToCurrentModel,
    deleteCurrentMaterial,
    importMaterials,
    toggleMaterialVisibility,
    updateCurrentMaterial,
    addNode,
    applySelectedTruss3dLoads,
    assignSelectedElementMaterial,
    assignSelectedPlaneElementMaterial,
    assignSelectedTruss3dElementMaterial,
    cloneSelectedTruss3dNodes,
    deleteSelectedElement,
    deleteSelectedNode,
    deleteSelectedTruss3dElement,
    deleteSelectedTruss3dNode,
    nudgeSelectedTruss3dNodes,
    toggleMemberFromDraft,
    updateSelectedElement,
    updateSelectedNode,
    updateSelectedPlaneElement,
    updateSelectedPlaneNode,
    updateSelectedTruss3dElement,
    updateSelectedTruss3dNode,
    updateSelectedTruss3dNodes,
    addTruss3dNode,
    handleTruss3dNodePick,
    handleTruss3dNodesBoxSelect,
    handleTrussPointerMove,
    startTrussNodeDrag,
    stopDraggingNode,
    toggleDraftNode,
    toggleTruss3dLinkMode,
    toggleTruss3dMemberFromDraft,
    updateTruss3dNodePosition,
    handleMaterialChange,
    updateSelectedFrameNode,
    updateSelectedFrameElement,
    assignSelectedFrameElementMaterial,
    applyTrussSuggestion,
  } = editControllers;

  const studyKindOptionGroups = buildStudyKindOptionGroups({
    kinds: t.kinds,
    domains: t.studyDomains,
    families: t.studyFamilies,
  });
  const studyDomainOptions = buildStudyDomainOptions(t.studyDomains);
  const currentStudyFamily = classifyStudyKindFamily(studyKind);
  const currentStudyFamilyLabel = t.studyFamilies[currentStudyFamily];
  const currentStudyFamilyHint = t.familyHints[currentStudyFamily];
  const { thermalIntentValue, thermalBoundaryValue, studySummaryRows, studyControlsRows, truss3dTreeRows } =
    buildWorkbenchStudySidebarData({
      t,
      language,
      studyKind,
      loadedModelName,
      activeMaterial,
      localMaterialLabel,
      fixed,
      isAxial,
      isSpring,
      isSpring1d,
      isSpring2d,
      isSpring3d,
      isBeam,
      isTorsion,
      isTruss,
      isTruss3d,
      isFrameLike,
      isFrame,
      isPlane,
      isHeatBar,
      isHeatPlane,
      isHeatPlaneTriangle,
      isHeatPlaneQuad,
      isThermal,
      isThermalBar,
      isThermalBeam,
      isThermalFrame,
      isThermalTruss2d,
      isThermalPlaneTriangle,
      isThermalPlaneQuad,
      axialForm,
      heatBarModel,
      heatPlaneModel,
      thermalBarModel,
      thermalBeamModel,
      thermalFrameModel,
      thermalTrussModel,
      thermalTruss3dModel,
      springModel,
      spring2dModel,
      spring3dModel,
      beamModel,
      torsionModel,
      trussModel,
      truss3dModel,
      frameModel,
      activePlaneInputModel,
      activeFrameLikeModel,
      displayTruss3dElements,
      truss3dTreeNodes: isSpring3d ? spring3dModel.nodes : truss3dModel.nodes,
      selectedNode,
      selectedTruss3dNodes,
      memberDraftNodes,
    });

  const studyKindResetHandlers = useMemo(
    () =>
      createStudyKindResetHandlers({
        activeMaterial,
        setPlaneModel,
        setHeatBarModel,
        setHeatPlaneModel,
        setThermalBarModel,
        setThermalBeamModel,
        setThermalFrameModel,
        setThermalTrussModel,
        setThermalTruss3dModel,
        setSpringModel,
        setSpring2dModel,
        setSpring3dModel,
        setBeamModel,
        setTorsionModel,
        setFrameModel,
        setPlaneResultField,
        ensurePlaneModelMaterials,
        ensureBeamModelMaterials,
        ensureFrameModelMaterials,
        defaultPlaneQuad,
        defaultThermalPlaneQuad,
        defaultPlaneTriangle,
        defaultThermalPlaneTriangle,
        defaultHeatBar1d,
        defaultHeatPlaneQuad,
        defaultHeatPlaneTriangle,
        defaultThermalBar1d,
        defaultThermalBeam1d,
        defaultThermalFrame2d,
        defaultThermalTruss2d,
        defaultThermalTruss3d,
        defaultSpring1d,
        defaultSpring2d,
        defaultSpring3d,
        defaultBeam1d,
        defaultTorsion1d,
        defaultFrame2d,
      }),
    [activeMaterial],
  );

  const handleLanguageChange = (nextLanguage: Language) => {
    applyLanguagePreference(nextLanguage);
  };

  const interactionControllers = useWorkbenchInteractionControllers({
    activeLanguagePack,
    activeMaterial,
    adminFilterModelVersionId,
    adminFilterProjectId,
    frontendRuntimeMode,
    health,
    heatBarModel,
    heatPlaneModel,
    immersiveHelpDrawerOpen,
    immersiveToolDrawerOpen,
    immersiveViewport,
    job,
    jobHistory,
    language,
    libraryTab,
    loadedModelName,
    memberDraftNodes,
    modelTab,
    panelParametric,
    planeModel,
    projects,
    protocolAgents,
    redoStack,
    resultRecords,
    selectedAdminJobId,
    selectedAdminResultJobId,
    selectedElement,
    selectedModelId,
    selectedNode,
    selectedProjectId,
    selectedTruss3dNodes,
    selectedVersionId,
    setActiveMaterial,
    setAxialForm,
    setBeamModel,
    setHeatBarModel,
    setHeatPlaneModel,
    setLanguagePacks,
    setLoadedModelName,
    setMemberDraftNodes,
    setMessage,
    setPlaneModel,
    setSidebarSection,
    setSpring2dModel,
    setSpring3dModel,
    setSpringModel,
    setStudyKind,
    setStudyTab,
    setThermalBarModel,
    setThermalBeamModel,
    setThermalFrameModel,
    setThermalTrussModel,
    setThermalTruss3dModel,
    setTorsionModel,
    setTruss3dModel,
    setTrussModel,
    sidebarSection,
    spring2dModel,
    spring3dModel,
    springModel,
    studyKind,
    studyTab,
    systemDataTab,
    systemPanelTab,
    t,
    theme,
    thermalBarModel,
    thermalBeamModel,
    thermalFrameModel,
    thermalTrussModel,
    thermalTruss3dModel,
    torsionModel,
    truss3dBoxSelectMode,
    truss3dLinkMode,
    truss3dModel,
    truss3dProjectionMode,
    truss3dViewPreset,
    trussModel,
    undoStack,
    viewportPanelRef,
    workflowCatalog,
    workflowCatalogBusy,
    setUndoStack,
    setRedoStack,
    setAssistantWindowOpen,
    setTheme,
    setFrontendRuntimeMode,
    setDirectMeshEndpointsText,
    setDirectMeshSelectionMode,
    setLibraryTab,
    setModelTab,
    setModelToolsPage,
    setSystemPanelTab,
    setSystemDataTab,
    setAdminFilterProjectId,
    setAdminFilterModelVersionId,
    setSelectedAdminJobId,
    setSelectedAdminResultJobId,
    setTruss3dViewPreset,
    setTruss3dProjectionMode,
    setTruss3dBoxSelectMode,
    setTruss3dShowGrid,
    setTruss3dShowLabels,
    setTruss3dShowNodes,
    setImmersiveToolDrawerOpen,
    setImmersiveHelpDrawerOpen,
    setTruss3dFocusRequestVersion,
    setTruss3dResetRequestVersion,
    refreshWorkflowCatalog,
    toggleTruss3dLinkMode,
    resetActiveResult: () => resetActiveResult(setResult, setJob),
  });
  const {
    topLevelActions,
    assistantAudit,
    uiActionController,
    toggleImmersiveViewport,
  } = interactionControllers;
  const {
    buildScriptSnapshot,
    buildSnapshot,
    restoreSnapshot,
    scriptSnapshot,
    recordHistory: recordHistoryAction,
    handleUndo,
    handleRedo,
    handleDownloadLanguagePackTemplate,
    handleExportInstalledLanguagePack,
    handleImportLanguagePack,
    handleRemoveLanguagePack,
    downloadSecurityEventExport,
    downloadSecurityEventCsvExport,
  } = topLevelActions;
  function recordHistory(action: string) {
    recordHistoryAction(action);
  }
  const {
    assistantTransactions,
    appendScriptActionLog,
    executeAssistantPlan,
    getScriptSnapshot,
    recordManualDslAction,
    recordSecurityAuditEvent,
    rollbackAssistantTransaction,
    scriptActionLog,
    securityAuditLog,
  } = assistantAudit;
  const {
    clearAdminFilters,
    handleAdminFilterModelVersionChange,
    handleAdminFilterProjectChange,
    handleLibraryTabChange,
    handleModelTabChange,
    handleSelectAdminJob,
    handleSelectAdminResult,
    handleSidebarSectionChange,
    handleStudyTabChange,
    handleSystemDataTabChange,
    handleSystemPanelTabChange,
    handleToggleImmersiveHelpDrawer,
    handleToggleImmersiveToolDrawer,
    handleToggleImmersiveViewport,
    handleToggleTruss3dLinkMode,
    handleTruss3dBoxSelectModeChange,
    handleTruss3dFocusViewport,
    handleTruss3dProjectionModeChange,
    handleTruss3dResetViewport,
    handleTruss3dShowGridChange,
    handleTruss3dShowLabelsChange,
    handleTruss3dShowNodesChange,
    handleTruss3dViewPresetChange,
    handleWorkflowPanelTabChange,
    useCurrentProjectAsAdminFilter,
    useCurrentVersionAsAdminFilter,
  } = uiActionController;

  const selectStudyKind = (nextStudyKind: typeof studyKind) => {
    recordHistory(t.changeStudyType);
    applyStudyKindSelection({
      currentStudyKind: studyKind,
      nextStudyKind,
      setStudyKind,
      resetHandlers: studyKindResetHandlers,
    });
  };

  const openWorkspaceStudy = (tab: StudyPanelTab = "controls") => {
    setSidebarSection("model");
    setModelTab("tools");
    setModelToolsPage("study");
    setStudyTab(tab);
  };

  const handleModelToolsPageChange = (page: ModelToolsPage) => {
    uiActionController.handleModelToolsPageChange(page, modelTab);
  };
  const flowControllers = useWorkbenchFlowControllers(
    buildWorkbenchFlowControllerProps({
      t,
      setMessage,
      recordHistory,
      setAxialForm,
      setParametric,
      setPanelParametric,
      startTransition,
      resultRefreshSeqRef,
      fetchResults,
      setResultRecords,
      setSelectedAdminResultJobId,
      directMeshEndpointsText,
      directMeshSelectionMode,
      frontendRuntimeMode,
      jobPollTokenRef,
      selectedProjectId,
      selectedVersionId,
      setDirectMeshExecution,
      setJob,
      setResult,
      studyKind,
      axialForm,
      beamModel,
      frameModel,
      heatBarModel,
      heatPlaneModel,
      planeModel,
      springModel,
      spring2dModel,
      spring3dModel,
      thermalBarModel,
      thermalBeamModel,
      thermalFrameModel,
      thermalTrussModel,
      thermalTruss3dModel,
      torsionModel,
      trussModel,
      truss3dModel,
      trussDiagnostics,
      refreshJobHistory,
      fetchJobStatus,
      setSidebarSection,
      setWorkflowPanelTab,
      setSelectedWorkflowId,
      setWorkflowRuns,
      openWorkspaceStudy,
      setStudyKind,
      setHeatBarModel,
      setHeatPlaneModel,
      setThermalBarModel,
      setThermalBeamModel,
      setThermalFrameModel,
      setThermalTrussModel,
      setThermalTruss3dModel,
      setSpringModel,
      setSpring2dModel,
      setSpring3dModel,
      setTrussModel,
      setTruss3dModel,
      setPlaneModel,
      setFrameModel,
      setBeamModel,
      setTorsionModel,
      setPlaneResultField,
      setLoadedModelName,
      setSelectedModelId,
      setSelectedVersionId,
      setModelVersions,
      setActiveMaterial,
      setSelectedNode,
      setSelectedElement,
      setMemberDraftNodes,
      activeMaterial,
      round,
      parametric,
      panelParametric,
      loadedModelName,
      updateJobRecord,
      deleteJobRecord,
      selectedAdminJobId,
      adminJobMessage,
      adminJobProjectId,
      adminJobModelVersionId,
      adminJobCaseId,
      updateResultRecord,
      deleteResultRecord,
      adminResultDraft,
      downloadTextFile,
      adminDataEffects,
      language,
      directMeshEndpoints,
      health,
      jobIsActive,
      isTruss,
      isTruss3d,
      immersiveViewport,
      hasAnyResult,
      cancelCurrentJob,
      applyTrussSuggestion,
      assistantApiBaseUrl,
      assistantApiKey,
      assistantModel,
      getScriptSnapshot,
      downloadResultCsv,
      toggleImmersiveViewport,
      setLibraryTab,
      setSystemPanelTab,
      refreshHealth,
      setTheme,
      setFrontendRuntimeMode,
      setDirectMeshEndpointsText,
      setDirectMeshSelectionMode,
      refreshResults,
      refreshProjects,
      refreshSecurityEvents,
      projectNameDraft,
      projectDescriptionDraft,
      setProjectNameDraft,
      setProjectDescriptionDraft,
      refreshVersions,
      downloadProjectBundleJson,
      downloadProjectBundleZip,
      createProject,
      updateProject,
      deleteProject,
      createModel,
      updateModel,
      deleteModel,
      createModelVersion,
      updateModelVersion,
      deleteModelVersion,
      handleLanguageChange,
      studyKindResetHandlers,
      handleSidebarSectionChange,
      setStudyTab,
      setModelTab,
      setModelToolsPage,
      setAssistantWindowOpen,
      setSystemDataTab,
      ensureFrameModelMaterials,
      ensureBeamModelMaterials,
      resolveTruss2dJobInput,
      resolveTruss3dJobInput,
      resolvePlaneQuad2dJobInput,
      resolvePlaneTriangle2dJobInput,
      projectHeatToThermoStudy,
      handleUndo,
      handleRedo,
      setTruss3dLinkMode,
      setTruss3dFocusRequestVersion,
      setTruss3dResetRequestVersion,
      setTruss3dShowGrid,
      setTruss3dShowLabels,
      setTruss3dShowNodes,
      setImmersiveToolDrawerOpen,
      setImmersiveHelpDrawerOpen,
      setTruss3dBoxSelectMode,
      setTruss3dViewPreset,
      setTruss3dProjectionMode,
      setAdminFilterProjectId,
      setAdminFilterModelVersionId,
      setSelectedAdminJobId,
      resolveScriptLinkedJob: (nextPayload: Record<string, unknown>) =>
        resolveScriptLinkedJobWithDeps(nextPayload, adminDataEffects),
      openModelVersionById,
      openProjectContextById: (projectId: string) => openProjectContextByIdWithDeps(projectId, adminDataEffects),
      applyJobContextToWorkbench: (linkedJob: JobState) =>
        applyJobContextToWorkbenchWithDeps(linkedJob, adminDataEffects),
      downloadDatabaseSnapshot,
    }),
  );
  const { primaryActionsController, assistantController, invokeScriptAction } = flowControllers;

  const {
    runAnalysis,
    openHistoryJob,
    importModel,
    openSample,
    handleAxialFieldChange,
    handleParametricChange,
    handlePanelParametricChange,
    generateModel,
    generatePanelModel,
    downloadModel,
    saveAdminJobRecord,
    deleteAdminJobRecord,
    saveAdminResultRecord,
    deleteAdminResultRecord,
    exportAdminResultRecord,
    openSelectedAdminJobVersion,
    openSelectedAdminResultVersion,
    openSelectedAdminJobProject,
    openSelectedAdminResultProject,
    applySelectedAdminJobContext,
    applySelectedAdminResultContext,
  } = primaryActionsController;

  const { assistantCards, assistantPromptPresets, requestLlmAssistantPlan } = assistantController;

  const {
    studyControlsContent,
    modelStudyContent,
    modelStudioContent,
    modelMaterialsContent,
    modelGenerateContent,
    modelTreeContent,
  } = buildWorkbenchModelContent(
    buildWorkbenchModelContentProps({
      t,
      isAxial,
      axialForm,
      handleAxialFieldChange,
      handleMaterialChange,
      language,
      loadedModelName,
      studyDomainOptions,
      studyKind,
      studyKindOptionGroups,
      selectStudyKind,
      studyControlsRows,
      isPending,
      runAnalysis,
      isTruss3d,
      isFrameLike,
      isPlane,
      isTorsion,
      isThermal,
      currentStudyFamilyHint,
      selectedNode,
      selectedElement,
      truss3dLinkMode,
      undoStack,
      redoStack,
      isTruss,
      addTruss3dNode,
      addNode,
      deleteSelectedTruss3dNode,
      deleteSelectedNode,
      toggleTruss3dMemberFromDraft,
      toggleMemberFromDraft,
      deleteSelectedTruss3dElement,
      deleteSelectedElement,
      toggleTruss3dLinkMode,
      handleUndo,
      handleRedo,
      downloadModel,
      setStudyKind,
      setSidebarSection,
      setMessage,
      isBeam,
      hiddenMaterialIds,
      activeMaterial,
      currentMaterials,
      localMaterialLabel,
      materialColorMap,
      setActiveMaterial,
      addMaterialToCurrentModel,
      addCustomMaterialToCurrentModel,
      importMaterials,
      updateCurrentMaterial,
      toggleMaterialVisibility,
      applyMaterialToCurrentModel,
      deleteCurrentMaterial,
      round,
      isHeatBar,
      isThermalBar,
      panelParametric,
      parametric,
      handlePanelParametricChange,
      handleParametricChange,
      generatePanelModel,
      generateModel,
      selectedTruss3dNodes,
      memberDraftNodes,
      truss3dTreeRows,
      truss3dModel,
      setSelectedElement,
      setSelectedNode,
      setSelectedTruss3dNodes,
      setMemberDraftNodes,
      currentStudyFamilyLabel,
      spring3dModel,
      spring2dModel,
      springModel,
      thermalBarModel,
      thermalTrussModel,
      activePlaneInputModel,
      activeFrameLikeModel,
      activeBeamLikeModel,
      torsionModel,
      heatBarModel,
      planeElements,
      displayTrussElements,
      activeLineResultField,
      frameTreeValueLabel,
      trussDiagnostics,
      toggleDraftNode,
      setFocusedFrameElement,
      beamModel,
      isThermalTruss2d,
      trussModel,
      handleTruss3dNodePick,
    }),
  );

  const sidebarMountProps = buildWorkbenchSidebarMountProps({
    t,
    railItems,
    sidebarSection,
    handleSidebarSectionChange,
    studyTab,
    handleStudyTabChange,
    loadedModelName,
    studyKind,
    studyDomainOptions,
    studyKindOptionGroups,
    selectStudyKind,
    studySummaryRows,
    studyControlsRows,
    studyControlsContent,
    isPending,
    runAnalysis,
    modelTab,
    handleModelTabChange,
    modelToolsPage,
    handleModelToolsPageChange,
    isTruss3d,
    modelStudyContent,
    modelStudioContent,
    modelMaterialsContent,
    modelGenerateContent,
    modelTreeContent,
    workflowPanelTab,
    handleWorkflowPanelTabChange,
    workflowLabels: {
      sectionTitle: t.sections.workflow,
      overviewPageLabel: t.workflowOverviewPage,
      catalogPageLabel: t.workflowCatalogPage,
      builderPageLabel: t.workflowBuilderPage,
      runsPageLabel: t.workflowRunsPage,
      overviewHint: t.workflowOverviewHint,
      catalogHint: t.workflowCatalogHint,
      builderHint: t.workflowBuilderHint,
      runsHint: t.workflowRunsHint,
      catalogTitle: t.workflowCatalogTitle,
      refreshLabel: t.workflowCatalogRefresh,
      runLabel: t.workflowCatalogRun,
      emptyCatalogLabel: t.workflowCatalogEmpty,
      noSelectionLabel: t.workflowNoSelection,
      nodesTitle: t.workflowNodesTitle,
      edgesTitle: t.workflowEdgesTitle,
      entryInputsTitle: t.workflowEntryInputsTitle,
      outputArtifactsTitle: t.workflowOutputArtifactsTitle,
      datasetContractTitle: t.workflowDatasetContractTitle,
      datasetValuesTitle: t.workflowDatasetValuesTitle,
      datasetValueLabel: t.workflowDatasetValueLabel,
      datasetSemanticTypeLabel: t.workflowDatasetSemanticTypeLabel,
      datasetEncodingLabel: t.workflowDatasetEncodingLabel,
      datasetShapeLabel: t.workflowDatasetShapeLabel,
      datasetAxesLabel: t.workflowDatasetAxesLabel,
      datasetSchemaLabel: t.workflowDatasetSchemaLabel,
      datasetClassLabel: t.workflowDatasetClassLabel,
      datasetNoneLabel: t.workflowDatasetNoneLabel,
      datasetDraftHint: t.workflowDatasetDraftHint,
      datasetEditorTitle: t.workflowDatasetEditorTitle,
      datasetValueSelectLabel: t.workflowDatasetValueSelectLabel,
      datasetUnitLabel: t.workflowDatasetUnitLabel,
      datasetMetadataLabel: t.workflowDatasetMetadataLabel,
      datasetPortMappingsTitle: t.workflowDatasetPortMappingsTitle,
      datasetEdgeMappingsTitle: t.workflowDatasetEdgeMappingsTitle,
      datasetDraftLocalLabel: t.workflowDatasetDraftLocalLabel,
      datasetUnassignedLabel: t.workflowDatasetUnassignedLabel,
      exportGraphLabel: t.workflowExportGraphLabel,
      exportDatasetContractLabel: t.workflowExportDatasetContractLabel,
      operatorLabel: t.workflowOperatorLabel,
      kindLabel: t.workflowKindLabel,
      progressLabel: t.workflowProgressLabel,
      currentNodeLabel: t.workflowCurrentNodeLabel,
      latestSummaryLabel: t.workflowLatestSummaryLabel,
      openRunLabel: t.workflowOpenRunLabel,
      emptyRunsLabel: t.workflowRunsEmpty,
      selectForBuilderLabel: t.workflowSelectForBuilder,
      statusReadyLabel: t.ready,
      statusBusyLabel: t.busy,
    },
    workflowCatalog,
    workflowCatalogBusy,
    selectedWorkflowId,
    selectedWorkflow,
    job,
    latestWorkflowSummary,
    workflowRuns,
    refreshWorkflowCatalog,
    setSelectedWorkflowId,
    runWorkflowCatalogEntry,
    openHistoryJob,
    libraryTab,
    handleLibraryTabChange,
    librarySampleRows,
    projects,
    selectedProjectId,
    setSelectedProjectId,
    setSelectedModelId,
    projectNameDraft,
    setProjectNameDraft,
    projectDescriptionDraft,
    setProjectDescriptionDraft,
    createProjectRecord,
    updateProjectRecord,
    deleteProjectRecord,
    downloadProjectBundleJson,
    downloadProjectBundleZip,
    importProjectBundle,
    selectedProjectModels,
    libraryModelRows,
    selectedModelId,
    setLoadedModelName,
    saveModelVersion,
    deleteSavedModelRecord,
    openSavedModel,
    libraryVersionRows,
    modelVersions,
    selectedVersionId,
    renameSelectedVersion,
    deleteSelectedVersion,
    openSavedVersion,
    libraryJobRows,
    jobHistory,
    openSample,
    refreshJobHistory,
    refreshProjects,
    importModel,
    systemPanelTab,
    handleSystemPanelTabChange,
    health,
    runtimeBackendRows,
    runtimeProtocolRows,
    runtimeProtocolMethods,
    securityUi,
    runtimeSecurityRows,
    runtimeAuditSummaryRows,
    runtimeAuditTrendBars,
    runtimeAuditSourceStatusFacets,
    runtimeAuditStudyFacets,
    runtimeAuditProjectFacets,
    runtimeAuditModelVersionFacets,
    securityEventRecords,
    securityEventWindowFilter,
    securityEventSourceFilter,
    securityEventRiskFilter,
    securityEventStatusFilter,
    securityEventActionFilter,
    setSecurityEventWindowFilter,
    setSecurityEventSourceFilter,
    setSecurityEventRiskFilter,
    setSecurityEventStatusFilter,
    setSecurityEventActionFilter,
    refreshSecurityEvents,
    downloadSecurityEventExport,
    downloadSecurityEventCsvExport,
    runtimeAuditEntries,
    protocolAgents,
    protocolAgentCards,
    runtimeWatchdogRows,
    theme,
    language,
    frontendRuntimeMode,
    directMeshSelectionMode,
    directMeshEndpointsText,
    controlPlaneApiToken,
    clusterApiToken,
    directMeshApiToken,
    showShortcutHints,
    immersiveGuardrails,
    languagePacks,
    languagePackCatalogRows,
    setTheme,
    handleLanguageChange,
    handleDownloadLanguagePackTemplate,
    handleExportInstalledLanguagePack,
    handleImportLanguagePack,
    handleRemoveLanguagePack,
    setFrontendRuntimeMode,
    setDirectMeshSelectionMode,
    setDirectMeshEndpointsText,
    setControlPlaneApiToken,
    setClusterApiToken,
    setDirectMeshApiToken,
    setShowShortcutHints,
    setImmersiveGuardrails,
    downloadDatabaseSnapshot,
    scriptActionLog,
    getScriptSnapshot,
    scriptRecordingMode,
    invokeScriptAction,
    setScriptRecordingMode,
    scriptSnapshot,
    systemDataTab,
    handleSystemDataTabChange,
    adminJobRows,
    selectedAdminJobId,
    handleSelectAdminJob,
    selectedAdminJob,
    adminJobMessage,
    setAdminJobMessage,
    adminJobProjectId,
    setAdminJobProjectId,
    adminJobModelVersionId,
    setAdminJobModelVersionId,
    adminJobCaseId,
    setAdminJobCaseId,
    saveAdminJobRecord,
    deleteAdminJobRecord,
    adminResultRows,
    selectedAdminResultJobId,
    handleSelectAdminResult,
    adminResultDraft,
    setAdminResultDraft,
    saveAdminResultRecord,
    applySelectedAdminResultContext,
    openSelectedAdminResultProject,
    openSelectedAdminResultVersion,
    exportAdminResultRecord,
    deleteAdminResultRecord,
    adminFilterProjectId,
    handleAdminFilterProjectChange,
    adminFilterModelVersionId,
    handleAdminFilterModelVersionChange,
    useCurrentProjectAsAdminFilter,
    useCurrentVersionAsAdminFilter,
    clearAdminFilters,
    applySelectedAdminJobContext,
    openSelectedAdminJobProject,
    openSelectedAdminJobVersion,
    cancelCurrentJob,
    cancelJob,
    setMessage,
  });

  const mainShellMountProps = buildWorkbenchMainShellComposition({
    t,
    shellState,
    workspaceState,
    studyResultDerived,
    editControllers,
    interactionControllers,
    flowControllers,
    viewportPanelRef,
    canvasStageRef,
    resultWindowMaxTotal,
    handleCanvasStageScroll,
    openSample,
    openSavedModel,
    openHistoryJob,
    selectedProjectModels,
    currentStudyFamilyLabel,
    currentStudyFamilyHint,
    isPending,
    canProjectHeatToThermo,
    projectHeatToThermoStudy,
    clampChunkOffset,
    recordHistory,
    drag3dHistoryCapturedRef,
    jobIsActive,
    cancelCurrentJob,
    downloadResultJson,
    downloadResultCsv,
    downloadPlaneHotspotSummary,
    downloadFrameHotspotSummary,
    downloadFrameForceSummary,
    tipDisplacement:
      isAxial
        ? scientific(axialResult?.tip_displacement)
        : isHeatBar
          ? scientific(heatBarResult?.max_temperature)
          : isHeatPlane
            ? scientific(
                isHeatPlaneTriangle
                  ? heatPlaneTriangleResult?.max_temperature
                  : heatPlaneQuadResult?.max_temperature,
              )
            : isThermalTruss2d
              ? scientific(thermalTrussResult?.max_displacement)
              : studyKind === "thermal_truss_3d"
                ? scientific(thermalTruss3dResult?.max_displacement)
                : isTruss
                  ? scientific(trussResult?.max_displacement)
                  : isSpring3d
                    ? scientific(spring3dResult?.max_displacement)
                    : studyKind === "truss_3d"
                      ? scientific(truss3dResult?.max_displacement)
                      : isThermalBar
                        ? scientific(thermalBarResult?.max_displacement)
                        : isSpring
                          ? scientific(activeSpringResult?.max_displacement)
                          : isBeam
                            ? scientific(activeBeamLikeResult?.max_displacement)
                            : isTorsion
                              ? scientific(torsionResult?.max_rotation)
                              : isFrameLike
                                ? scientific(activeFrameLikeResult?.max_displacement)
                                : scientific(planeResult?.max_displacement),
    maxStressValue: scientific(
      isAxial
        ? axialResult?.max_stress
        : isHeatBar
          ? heatBarResult?.max_heat_flux
          : isHeatPlane
            ? isHeatPlaneTriangle
              ? heatPlaneTriangleResult?.max_heat_flux
              : heatPlaneQuadResult?.max_heat_flux
            : isThermalTruss2d
              ? thermalTrussResult?.max_stress
              : studyKind === "thermal_truss_3d"
                ? thermalTruss3dResult?.max_stress
                : isTruss
                  ? trussResult?.max_stress
                  : isSpring3d
                    ? spring3dResult?.max_force
                    : studyKind === "truss_3d"
                      ? truss3dResult?.max_stress
                      : isThermalBar
                        ? thermalBarResult?.max_stress
                        : isSpring
                          ? activeSpringResult?.max_force
                          : isBeam
                            ? activeBeamLikeResult?.max_stress
                            : isTorsion
                              ? torsionResult?.max_stress
                              : isFrameLike
                                ? activeFrameLikeResult?.max_stress
                                : planeResult?.max_stress,
    ),
    reactionValue:
      isAxial
        ? scientific(axialResult?.reaction_force)
        : isHeatBar
          ? scientific(heatBarResult?.max_heat_flux)
          : isThermalBar
            ? scientific(thermalBarResult?.max_axial_force)
            : isThermalTruss2d
              ? scientific(thermalTrussResult?.max_axial_force)
              : isThermalTruss3d
                ? scientific(thermalTruss3dResult?.max_axial_force)
                : isSpring
                  ? scientific(activeSpringResult?.max_force)
                  : isTorsion
                    ? scientific(torsionResult?.max_torque)
                    : isFrameLike
                      ? scientific(activeFrameLikeResult?.max_moment)
                      : isBeam
                        ? scientific(activeBeamLikeResult?.max_moment)
                        : "--",
    frameMaxRotationValue:
      isFrameLike
        ? scientific(activeFrameLikeResult?.max_rotation)
        : isBeam
          ? scientific(activeBeamLikeResult?.max_rotation)
          : isTorsion
            ? scientific(torsionResult?.max_rotation)
            : undefined,
    thermalPlaneMaxTemperatureDelta:
      planeResult && "max_temperature_delta" in planeResult ? planeResult.max_temperature_delta : undefined,
  });

  return (
    <div className="workbench-shell">
      <WorkbenchSidebarMount {...sidebarMountProps} />

      <WorkbenchMainShellMount {...mainShellMountProps} />
    </div>
  );
}
