export const copyZhExtended = {
    themes: { linen: "工坊灰板", marine: "蓝图青色", graphite: "Blender 锻台" },
    languages: { en: "English", zh: "中文", ja: "日本語", es: "Español" },
    frontendModes: {
      orchestrated_gui: "中心调度 GUI",
      direct_mesh_gui: "直连 Mesh GUI",
    },
    directMeshStrategies: {
      healthiest: "优先健康节点",
      first_reachable: "首个可达节点",
    },
    shortcutLegendTitle: "三维控制",
    shortcutLegendRows: [
      "拖拽平移 · Alt+拖拽旋转 · 滚轮缩放",
      "Shift+滚轮可左右平移",
      "1/2/3/4 视角 · P 投影",
      "G 网格 · L 标签 · N 节点",
      "F 聚焦 · R 重置 · WASD/方向键平移",
      "连线模式：依次点击两个节点即可切换杆件",
      "BOX 框选可见节点 · 沉浸按钮可切全屏",
    ],
    length: "跨度 (m)",
    area: "截面积 (m²)",
    modulus: "弹性模量 (GPa)",
    elements: "单元数",
    tipForce: "端部载荷 (N)",
    run: "运行研究",
    running: "运行中...",
    ready: "就绪",
    busy: "处理中",
    tipDisp: "端部位移",
    maxStress: "最大应力",
    reaction: "反力",
    maxAxialForce: "最大轴力",
    maxShearForce: "最大剪力",
    displacementMagnitude: "位移模",
    fixRz: "约束 Rz",
    momentZ: "节点弯矩",
    rotationZ: "转角 Rz",
    frameElements: "刚架杆件",
    memberEndForces: "杆端内力",
    momentOfInertia: "惯性矩",
    sectionModulus: "截面模量",
    distributedLoadY: "均布载荷 Y",
    temperatureDelta: "温升",
    temperature: "温度",
    averageTemperature: "平均温度",
    maxTemperature: "最高温度",
    conductivity: "导热系数",
    fixTemperature: "固定温度",
    heatLoad: "热载荷",
    temperatureGradientX: "温差梯度 X",
    temperatureGradientY: "温差梯度 Y",
    thermalIntent: "热载荷意图",
    thermalBoundary: "热边界模式",
    prescribedTemperatureNodes: "固定温度节点",
    sourceNodes: "热源节点",
    heatedNodes: "受温升节点",
    gradientMembers: "温差梯度杆件",
    restrainedSupports: "受约束支撑",
    thermalMembers: "热杆件",
    conductionField: "导热场",
    heatSourceField: "热源场",
    nodalTemperatureRise: "节点温升",
    memberTemperatureGradient: "杆件温差梯度",
    thermalBarResponse: "受约束热杆响应",
    thermalBeamResponse: "热梁响应",
    thermalFrameResponse: "热刚架响应",
    thermalTrussResponse: "热桁架响应",
    thermoelasticPlaneResponse: "热弹性平面响应",
    maxHeatFlux: "最大热流",
    heatFluxX: "热流 X",
    heatFluxY: "热流 Y",
    thermalCurvature: "热曲率",
    thermalStrain: "热应变",
    mechanicalStrain: "机械应变",
    totalStrain: "总应变",
    thermalExpansion: "热膨胀系数",
    bendingStress: "最大弯曲应力",
    combinedStress: "组合应力",
    maxMoment: "最大弯矩",
    maxTorque: "最大扭矩",
    torsionStress: "扭转应力",
    torqueZ: "扭矩 Z",
    torsionHint: "扭转轴研究主要看转角、扭矩传递和沿轴的剪应力。",
    maxRotation: "最大转角",
    sortBy: "排序方式",
    shearForce: "剪力",
    forceI: "i端轴力",
    shearI: "i端剪力",
    momentI: "i端弯矩",
    forceJ: "j端轴力",
    shearJ: "j端剪力",
    momentJ: "j端弯矩",
    principalStress1: "主应力 1",
    principalStress2: "主应力 2",
    maxInPlaneShear: "最大面内剪应力",
    currentField: "当前结果场",
    planeHotspots: "热点单元",
    topN: "热点数",
    exportHotspots: "导出热点",
    memberForceTable: "杆端内力表",
    elementHeatTable: "单元热量表",
    exportMemberForces: "导出杆端内力",
    planeResultLegend: "填色：von Mises · 叠加：变形后形状",
    planeViewVonMises: "von Mises",
    planeViewPrincipal1: "主应力 1",
    planeViewMaxShear: "最大剪应力",
    progress: "进度",
    iteration: "迭代",
    residual: "残差",
    worker: "执行器",
    status: "状态",
    nodes: "节点",
    axialElements: "单元结果",
    trussElements: "桁架杆件",
    spatialTrussElements: "空间桁架杆件",
    span: "区间",
    stress: "应力 (Pa)",
    axialForce: "轴力 (N)",
    importedModel: "已导入模型",
    importFailed: "导入失败",
    initialLoaded: "工作台已连接到编排器。",
    initialFailed: "无法连接到编排器。",
    dispatching: "正在向编排器提交研究任务。",
    defaultModel: "手动研究",
    online: "在线",
    offline: "离线",
    historyHint: "任务历史会在编排器重启后保留。",
    historyEmpty: "暂时还没有任务。",
    openJob: "打开",
    refresh: "刷新",
    resultWindow: "结果窗口",
    previousPage: "上一页",
    nextPage: "下一页",
    jumpStart: "开头",
    jumpQuarter: "25%",
    jumpMid: "50%",
    jumpThreeQuarter: "75%",
    jumpEnd: "末尾",
    pageRange: "区间",
    chunkSize: "窗口",
    totalElements: "单元",
    projectLibrary: "项目库",
    projectNameField: "项目名",
    projectDescriptionField: "描述",
    createProject: "新建项目",
    updateProject: "更新项目",
    deleteProject: "删除项目",
    exportProject: "导出项目",
    exportProjectJson: "项目 JSON",
    exportProjectZip: "项目 ZIP",
    importProject: "导入项目",
    importProjectHint: "导入 .kyuubiki.json 或 .kyuubiki 项目包到项目库。",
    projectEmpty: "还没有项目。",
    savedModels: "已保存模型",
    versions: "版本",
    save: "保存",
    saveAs: "另存为",
    deleteSavedModel: "删除模型",
    renameVersion: "重命名版本",
    deleteVersion: "删除版本",
    exportData: "导出数据",
    exportJson: "JSON",
    exportCsv: "CSV",
    projectHeatToThermo: "将温度场用于力-热研究",
    projectHeatToThermoAction: "已把热结果映射到力-热研究",
    projectedHeatToThermo: "已将热结果映射到力-热研究。求解前请再检查约束和材料设置。",
    noSavedModels: "这个项目里还没有保存的模型。",
    noVersions: "还没有版本记录。",
    defaultProject: "工作区",
    projectCreated: "项目已创建。",
    projectUpdated: "项目已更新。",
    projectDeleted: "项目已删除。",
    projectRequired: "保存模型前请先创建或选择一个项目。",
    projectExported: "项目包已导出。",
    projectExportedPartial: "项目包已导出，但只包含部分数据；有些模型或结果未能及时读取。",
    databaseExported: "数据库快照已导出。",
    projectImported: "项目包已导入。",
    modelSaved: "已保存新模型版本。",
    modelCreated: "已保存新模型。",
    modelDeletedStored: "已删除保存的模型。",
    versionLoaded: "已将保存版本加载到工作台。",
    persistedModelLoaded: "已从库中加载保存模型。",
    versionRenamed: "版本已重命名。",
    versionDeleted: "版本已删除。",
    resultJsonDownloaded: "分析结果 JSON 已下载。",
    resultCsvDownloaded: "分析结果 CSV 已下载。",
    jobCancelled: "任务已取消。",
    noResultToExport: "请先运行一次分析再导出结果数据。",
    modelTools: "编辑工具",
    dragHint: "直接在视图区拖拽桁架节点来修改几何。",
    planeHint: "选择平面节点和三角形单元，直接修改约束、载荷和厚度材料。",
    parametric: "参数化生成",
    panelGenerator: "面板生成器",
    spaceStudio: "三维空间工作室",
    tabs: { summary: "概览", controls: "控制", tools: "工具", tree: "浏览", jobs: "任务", results: "结果", models: "模型", projects: "项目", samples: "样板" },
    generate: "生成模型",
    generatePanel: "生成面板",
    download: "下载 JSON",
    saveForSolver: "使用当前模型",
    bays: "跨数",
    height: "高度 (m)",
    divisionsX: "X 分段",
    divisionsY: "Y 分段",
    nodeTable: "对象浏览",
    dragNode: "当前节点",
    noNodeSelected: "未选择节点",
    loadCase: "载荷工况",
    modelStudioHint: "当前建模页支持二维桁架和二维平面单元。三维研究已经支持导入、求解和结果回看。",
    frameEditorHint: "二维刚架现在已经支持导入、求解、检查和结果回看；更完整的构件编辑会继续补上。",
    spaceStudioHint: "通过旋转、平移和缩放来查看空间桁架。三维节点和杆件现在也可以选中并做数值编辑。",
    sourceModel: "来源模型",
    createdAt: "创建时间",
    updatedAt: "更新时间",
    hasResult: "结果",
    yes: "是",
    no: "否",
    jobWorkspaceTitle: "任务工作台",
    jobWorkspaceHint: "先盯 solver 运行，再在需要时钻进某一条任务记录看细节。",
    resultWorkspaceTitle: "结果工作台",
    resultWorkspaceHint: "这里先打开最新已完成结果，再继续进入报告、导出和关联记录。",
    modelWorkspaceTitle: "模型工作台",
    modelWorkspaceHint: "把保存过的研究和可复用版本放在一起，方便快速重开或分支。",
    openLatestJob: "打开最新任务",
    openLatestResult: "打开最新结果",
    openLatestModel: "打开最新模型",
    waitingJobs: "待出结果",
    readyResults: "已就绪结果",
    savedCount: "已存模型",
    versionCount: "版本数",
    dragToEdit: "拖拽编辑",
    historyLoaded: "已从历史记录加载持久化任务。",
    modelDownloaded: "模型 JSON 已下载。",
    generatedModel: "已生成参数化桁架模型。",
    planeElements: "平面单元",
    thickness: "厚度",
    poisson: "泊松比",
    poissonRatio: "泊松比",
    sampleLibrary: "样板库",
    objectTree: "对象",
    geometry: "几何",
    results: "结果",
    summary: "概览",
    properties: "属性",
    diagnostics: "诊断",
    diagnosticsClear: "当前没有阻塞性的预检查问题。",
    suggestedFixes: "建议修复",
    stabilityScore: "稳定性评分",
    hotspotNodes: "危险热区节点",
    stabilityGood: "稳定",
    stabilityWatch: "需关注",
    stabilityRisk: "高风险",
    translatedSmallDeformation: "这个结构看起来过软，已经超出小变形求解范围。请补约束或增强薄弱跨段。",
    translatedConnectivity: "桁架里可能有连接偏弱或断开的区域。请检查约束、杆件连接和孤立节点。",
    translatedSingular: "刚度矩阵是奇异的。说明模型仍然像机构一样可动，需要更多约束或对角支撑。",
    translatedWatchdogStalled: "任务长时间没有新的进度更新，已经被看门狗判定为卡住。",
    translatedWatchdogTimedOut: "任务运行时间过长，已经被看门狗超时终止。",
    translatedExecutionTimedOut: "求解器响应太久，任务已被安全超时终止。",
    translatedAgentTimeout: "求解代理在规定时间内没有响应。请检查 agent 进程，或稍后重试。",
    requestTimedOut: "请求等待过久，工作台已保留最近一次稳定状态。",
    pollingDetached: "为了保持界面流畅，实时轮询已暂停；你可以稍后手动刷新任务状态。",
    heartbeatHealthy: "正常",
    heartbeatQuiet: "安静",
    heartbeatStale: "过期",
    mechanismRisk: "这个拓扑仍然很像机构。建议先增加三角化斜撑或额外支座再求解。",
    addNode: "新增节点",
    addBranchNode: "分支节点",
    linkMode: "连线模式",
    linkModeActive: "连线中",
    linkModeIdle: "在三维视图区中依次选择两个节点，即可连接或断开。",
    linkModeEnabled: "已开启三维连线模式。",
    linkModeDisabled: "已关闭三维连线模式。",
    linkModeCompleted: "已应用三维连线修改。",
    deleteNode: "删除节点",
    addMember: "新增杆件",
    toggleMember: "切换连接",
    deleteMember: "删除杆件",
    selectTwoNodes: "请选择两个节点来创建杆件。",
    memberCreated: "杆件已创建。",
    memberRemoved: "杆件已断开。",
    nodeCreated: "节点已创建。",
    branchCreated: "节点已创建并连接。",
    nodeDeleted: "节点已删除。",
    memberDeleted: "杆件已删除。",
    selectionHint: "可以通过对象树或视图区选择节点和杆件。",
    memberSelection: "杆件选择",
    noElementSelected: "未选择杆件",
    nodeX: "节点 X",
    nodeY: "节点 Y",
    nodeZ: "节点 Z",
    fixX: "固定 X",
    fixY: "固定 Y",
    fixZ: "固定 Z",
    loadX: "载荷 X",
    loadY: "载荷 Y",
    loadZ: "载荷 Z",
    nodeI: "起点节点",
    nodeJ: "终点节点",
    nodeK: "第三节点",
    none: "无",
    precheckPrefix: "预检查失败",
    unstableSupport: "请至少提供两个受限自由度来稳定桁架。",
    isolatedNode: "每个节点在求解前都应该至少连接一根杆件。",
    underconnected: "这个桁架连接数量偏少，可能无法稳定求解。",
    freeRigidBody: "请通过约束两个平移方向来避免整体刚体运动。",
    supportXMissing: "至少增加一个 X 方向约束，避免侧向漂移。",
    supportYMissing: "至少增加一个 Y 方向约束，避免竖向漂移。",
    fixCurrentNodeXAction: "固定当前节点 X",
    fixCurrentNodeYAction: "固定当前节点 Y",
    fixNodeXAction: "固定问题节点 X",
    fixNodeYAction: "固定问题节点 Y",
    releaseX: "释放 X",
    releaseY: "释放 Y",
    releaseZ: "释放 Z",
    connectCurrentNodeAction: "将当前节点连接到最近节点",
    connectNodeAction: "将问题节点连接到最近节点",
    suggestionAppliedSupportX: "已为建议节点补上 X 约束。",
    suggestionAppliedSupportY: "已为建议节点补上 Y 约束。",
    suggestionAppliedLink: "已将该节点连接到最近的可用邻点。",
    suggestionNoLinkTarget: "附近没有可自动连接的有效节点。",
    panelGenerated: "已生成矩形平面网格。",
    planeThickness: "厚度",
    orbitHint: "拖拽平移，按住 Alt 拖拽旋转，滚轮缩放。",
    spaceNodeCreated: "三维节点已创建。",
    spaceBranchCreated: "三维节点已创建并连接。",
    spaceNodeDeleted: "三维节点已删除。",
    spaceMemberDeleted: "三维杆件已删除。",
    switchedTo2dStudio: "已切换到二维工作区。",
    switchedTo3dStudio: "已切换到三维空间工作区。",
} as const;
