export const copyEsPrimary = {
  "rail": {
    "study": "Estudio",
    "model": "Espacio de trabajo",
    "workflow": "Flujo de trabajo",
    "store": "Tienda",
    "library": "Historial",
    "system": "Sistema"
  },
  "sections": {
    "study": "Configuración del estudio",
    "workflow": "Editor de flujos de trabajo",
    "store": "Tienda del proyecto",
    "library": "Historial de tareas",
    "model": "Espacio de trabajo",
    "system": "Sistema"
  },
  "roleLabel": "Entorno de análisis",
  "overview": "Resumen",
  "result": "Resultado",
  "actions": "Acciones",
  "details": "Detalles",
  "controls": "Controles",
  "report": "Informe",
  "messages": "Mensajes",
  "viewport": "Vista",
  "settings": "Ajustes",
  "scripts": "Scripts",
  "assistant": "Asistente",
  "config": "Configuración",
  "runtime": "Entorno de ejecución",
  "data": "Datos",
  "packs": "Paquetes de idioma",
  "routing": "Enrutamiento",
  "access": "Acceso",
  "stack": "Servicios",
  "security": "Seguridad",
  "agents": "Agentes",
  "audit": "Auditoría",
  "modelMaterialsPage": "Materiales",
  "modelGeneratePage": "Generación",
  "createProject": "Crear proyecto",
  "projectNameField": "Nombre del proyecto",
  "projectDescriptionField": "Descripción",
  "importProject": "Importar proyecto",
  "exportProject": "Exportar proyecto",
  "save": "Guardar",
  "saveAs": "Guardar como",
  "deleteProject": "Eliminar proyecto",
  "workflowBuilderPage": "Editor",
  "workflowRunsPage": "Ejecuciones",
  "workflowCatalogTitle": "Catálogo de flujos de trabajo",
  "workflowRunDraftLabel": "Ejecutar borrador actual",
  "renderDiagnosticsTitle": "Diagnóstico de renderizado",
  "renderStrategyAuto": "Automático",
  "renderStrategyFull": "Completo",
  "renderStrategyProgressive": "Progresivo",
  "renderStrategyFocus": "Enfoque",
  "workspace": "Espacio de trabajo",
  "modelStudyPage": "Estudio",
  "modelStudioPage": "Espacio de trabajo",
  "modelOverviewPage": "Resumen",
  "controlsSetupPage": "Ajustes",
  "controlsReviewPage": "Detalles",
  "tabs": {
    "summary": "Resumen",
    "controls": "Controles",
    "results": "Resultado",
    "models": "Espacio de trabajo"
  }
} as const;
