"use client";

import { invokeWorkbenchScriptAction } from "@/components/workbench/workbench-script-orchestration";
import { handleWorkbenchScriptMacroDataAction } from "@/components/workbench/workbench-script-macro-data-controller";
import { handleWorkbenchScriptNavAction } from "@/components/workbench/workbench-script-nav-controller";
import { handleWorkbenchScriptProjectModelAction } from "@/components/workbench/workbench-script-project-model-controller";
import { handleWorkbenchScriptStateAction } from "@/components/workbench/workbench-script-state-controller";

export function createWorkbenchScriptInvoker(options: Record<string, any>) {
  return async (
    action: string,
    payload: Record<string, unknown> = {},
    source: "script" | "assistant" | "hub-assistant" | "" = "script",
    note?: string,
  ) =>
    invokeWorkbenchScriptAction({
      action,
      payload,
      source,
      note,
      language: options.language,
      uxGuardrailSummary: options.uxGuardrailSummary,
      recordSecurityAuditEvent: options.recordSecurityAuditEvent,
      appendScriptActionLog: options.appendScriptActionLog,
      handleWorkbenchScriptNavAction,
      handleWorkbenchScriptProjectModelAction,
      handleWorkbenchScriptStateAction,
      handleWorkbenchScriptMacroDataAction,
      navArgs: {
        action,
        payload,
        studyKind: options.studyKind,
        studyKindResetHandlers: options.studyKindResetHandlers,
        setStudyKind: options.setStudyKind,
        handleSidebarSectionChange: options.handleSidebarSectionChange,
        recordHistory: options.recordHistory,
        changeStudyTypeLabel: options.changeStudyTypeLabel,
        setStudyTab: options.setStudyTab,
        setModelTab: options.setModelTab,
        setModelToolsPage: options.setModelToolsPage,
        setLibraryTab: options.setLibraryTab,
        setSystemPanelTab: options.setSystemPanelTab,
        setAssistantWindowOpen: options.setAssistantWindowOpen,
        setSystemDataTab: options.setSystemDataTab,
        handleLanguageChange: options.handleLanguageChange,
        setTheme: options.setTheme,
        currentFrontendRuntimeMode: options.frontendRuntimeMode,
        setFrontendRuntimeMode: options.setFrontendRuntimeMode,
        currentDirectMeshEndpointsText: options.directMeshEndpointsText,
        setDirectMeshEndpointsText: options.setDirectMeshEndpointsText,
        setDirectMeshSelectionMode: options.setDirectMeshSelectionMode,
        refreshHealth: options.refreshHealth,
        refreshJobHistory: options.refreshJobHistory,
        refreshResults: options.refreshResults,
        refreshProjects: options.refreshProjects,
        refreshSecurityEvents: options.refreshSecurityEvents,
      },
      projectModelArgs: {
        action,
        payload,
        selectedProjectId: options.selectedProjectId,
        selectedModelId: options.selectedModelId,
        selectedVersionId: options.selectedVersionId,
        projectNameDraft: options.projectNameDraft,
        projectDescriptionDraft: options.projectDescriptionDraft,
        loadedModelName: options.loadedModelName,
        activeMaterial: options.activeMaterial,
        studyKind: options.studyKind,
        setSelectedProjectId: options.setSelectedProjectId,
        setProjectNameDraft: options.setProjectNameDraft,
        setProjectDescriptionDraft: options.setProjectDescriptionDraft,
        setSelectedModelId: options.setSelectedModelId,
        setSelectedVersionId: options.setSelectedVersionId,
        setModelVersions: options.setModelVersions,
        setLoadedModelName: options.setLoadedModelName,
        setActiveMaterial: options.setActiveMaterial,
        refreshProjects: options.refreshProjects,
        refreshVersions: options.refreshVersions,
        downloadProjectBundleJson: options.downloadProjectBundleJson,
        downloadProjectBundleZip: options.downloadProjectBundleZip,
        generateModel: options.generateModel,
        generatePanelModel: options.generatePanelModel,
        serializeCurrentModel: options.serializeCurrentModel,
        projectLibraryBackendService: options.projectLibraryBackendService,
        projectRequiredLabel: options.projectRequiredLabel,
        defaultProjectLabel: options.defaultProjectLabel,
        projectCreatedLabel: options.projectCreatedLabel,
        projectUpdatedLabel: options.projectUpdatedLabel,
        projectDeletedLabel: options.projectDeletedLabel,
        noSavedModelsLabel: options.noSavedModelsLabel,
        noVersionsLabel: options.noVersionsLabel,
        modelCreatedLabel: options.modelCreatedLabel,
        modelSavedLabel: options.modelSavedLabel,
        modelDeletedLabel: options.modelDeletedLabel,
        versionRenamedLabel: options.versionRenamedLabel,
        versionDeletedLabel: options.versionDeletedLabel,
        setMessage: options.setMessage,
      },
      stateArgs: {
        action,
        payload,
        language: options.language,
        setStudyKind: options.setStudyKind,
        setParametric: options.setParametric,
        setPanelParametric: options.setPanelParametric,
        setTrussModel: options.setTrussModel,
        setTruss3dModel: options.setTruss3dModel,
        setPlaneModel: options.setPlaneModel,
        setFrameModel: options.setFrameModel,
        setBeamModel: options.setBeamModel,
        setSelectedNode: options.setSelectedNode,
        setSelectedElement: options.setSelectedElement,
        setSelectedTruss3dNodes: options.setSelectedTruss3dNodes,
        setMemberDraftNodes: options.setMemberDraftNodes,
        setTruss3dLinkMode: options.setTruss3dLinkMode,
        setTruss3dFocusRequestVersion: options.setTruss3dFocusRequestVersion,
        setTruss3dResetRequestVersion: options.setTruss3dResetRequestVersion,
        setTruss3dShowGrid: options.setTruss3dShowGrid,
        setTruss3dShowLabels: options.setTruss3dShowLabels,
        setTruss3dShowNodes: options.setTruss3dShowNodes,
        setImmersiveToolDrawerOpen: options.setImmersiveToolDrawerOpen,
        setImmersiveHelpDrawerOpen: options.setImmersiveHelpDrawerOpen,
        setTruss3dBoxSelectMode: options.setTruss3dBoxSelectMode,
        immersiveViewport: options.immersiveViewport,
        recordHistory: options.recordHistory,
        importActionLabel: options.importActionLabel,
        editParametricLabel: options.editParametricLabel,
        resolveTruss2dJobInput: options.resolveTruss2dJobInput,
        resolveTruss3dJobInput: options.resolveTruss3dJobInput,
        resolvePlaneQuad2dJobInput: options.resolvePlaneQuad2dJobInput,
        resolvePlaneTriangle2dJobInput: options.resolvePlaneTriangle2dJobInput,
        ensureFrameModelMaterials: options.ensureFrameModelMaterials,
        ensureBeamModelMaterials: options.ensureBeamModelMaterials,
        activeMaterial: options.activeMaterial,
        resetActiveResult: options.resetActiveResult,
        projectHeatToThermoStudy: options.projectHeatToThermoStudy,
        toggleImmersiveViewport: options.toggleImmersiveViewport,
        handleUndo: options.handleUndo,
        handleRedo: options.handleRedo,
        runAnalysis: options.runAnalysis,
        cancelCurrentJob: options.cancelCurrentJob,
        setTruss3dViewPreset: options.setTruss3dViewPreset,
        setTruss3dProjectionMode: options.setTruss3dProjectionMode,
      },
      macroDataArgs: {
        action,
        payload,
        source,
        note,
        language: options.language,
        getScriptSnapshot: options.getScriptSnapshot,
        setSystemDataTab: options.setSystemDataTab,
        setAdminFilterProjectId: options.setAdminFilterProjectId,
        setAdminFilterModelVersionId: options.setAdminFilterModelVersionId,
        setSelectedAdminJobId: options.setSelectedAdminJobId,
        setSelectedAdminResultJobId: options.setSelectedAdminResultJobId,
        setSidebarSection: options.setSidebarSection,
        setSystemPanelTab: options.setSystemPanelTab,
        resolveScriptLinkedJob: options.resolveScriptLinkedJob,
        openModelVersionById: options.openModelVersionById,
        openProjectContextById: options.openProjectContextById,
        applyJobContextToWorkbench: options.applyJobContextToWorkbench,
        downloadDatabaseSnapshot: options.downloadDatabaseSnapshot,
      },
    });
}
