import type { Dispatch, ReactNode, SetStateAction } from "react";
import type { WorkbenchCopy } from "@/components/workbench/workbench-copy";
import type { SecurityEventWindow } from "@/components/workbench/workbench-types";
import type { WorkflowSurfaceTab } from "@/components/workbench/workflow/workbench-workflow-types";
import type { WorkbenchScriptActionLogEntry, WorkbenchScriptSnapshot } from "@/lib/scripting/workbench-script-runtime";
import type { WorkbenchSecurityAuditRisk, WorkbenchSecurityAuditSource } from "@/lib/workbench/security-audit";

export type WorkbenchSystemSidebarMountProps = {
  t: WorkbenchCopy;
  systemPanelTab: "config" | "scripts" | "runtime" | "data";
  handleSystemPanelTabChange: (tab: "config" | "scripts" | "runtime" | "data") => void;
  setSidebarSection: (section: "study" | "model" | "workflow" | "library" | "system") => void;
  handleWorkflowPanelTabChange: (tab: WorkflowSurfaceTab) => void;
  runtimeRecoveryCard?: ReactNode;
  healthStatus: string | undefined;
  healthProtocolOnline: boolean;
  healthWatchdogOnline: boolean;
  healthSecurityApiTokenConfigured: boolean;
  runtimeBackendRows: Array<{ label: string; value: ReactNode }>;
  runtimeProtocolRows: Array<{ label: string; value: ReactNode }>;
  runtimeProtocolMethods?: string[];
  securityUi: { security: string; configured: string; notConfigured: string; controlPlaneToken: string; clusterToken: string; directMeshToken: string };
  runtimeSecurityRows: Array<{ label: string; value: ReactNode }>;
  runtimeAuditSummaryRows: Array<{ label: string; value: string }>;
  runtimeAuditTrendBars: Array<{ key: string; label: string; value: string; ratio: number }>;
  runtimeAuditSourceStatusFacets: Array<{ key: string; label: string; value: string }>;
  runtimeAuditStudyFacets: Array<{ key: string; label: string; value: string }>;
  runtimeAuditProjectFacets: Array<{ key: string; label: string; value: string }>;
  runtimeAuditModelVersionFacets: Array<{ key: string; label: string; value: string }>;
  securityEventRecords: Array<unknown>;
  securityEventWindowFilter: SecurityEventWindow;
  securityEventSourceFilter: WorkbenchSecurityAuditSource | "hub-assistant" | "";
  securityEventRiskFilter: WorkbenchSecurityAuditRisk | "";
  securityEventStatusFilter: "" | "allowed" | "blocked";
  securityEventActionFilter: string;
  setSecurityEventWindowFilter: (value: SecurityEventWindow) => void;
  setSecurityEventSourceFilter: (value: WorkbenchSecurityAuditSource | "hub-assistant" | "") => void;
  setSecurityEventRiskFilter: (value: WorkbenchSecurityAuditRisk | "") => void;
  setSecurityEventStatusFilter: (value: "" | "allowed" | "blocked") => void;
  setSecurityEventActionFilter: (value: string) => void;
  refreshSecurityEvents: () => Promise<void>;
  downloadSecurityEventExport: () => Promise<void>;
  downloadSecurityEventCsvExport: () => Promise<void>;
  runtimeAuditEntries: Array<{ id: string; at: string; action: string; source: string; risk: string; status: string; note: string }>;
  protocolAgents: Array<unknown>;
  protocolAgentCards: Array<{
    id: string;
    endpoint: string;
    metrics: Array<{ label: string; value: string | number; tone?: string }>;
    chips: Array<{ key: string; label: string; tone?: string; title?: string }>;
    error?: string;
  }>;
  runtimeWatchdogRows: Array<{ label: string; value: ReactNode }>;
  theme: "linen" | "marine" | "graphite";
  language: string;
  frontendRuntimeMode: "orchestrated_gui" | "direct_mesh_gui";
  directMeshSelectionMode: "healthiest" | "first_reachable";
  directMeshEndpointsText: string;
  controlPlaneApiToken: string;
  clusterApiToken: string;
  directMeshApiToken: string;
  showShortcutHints: boolean;
  immersiveGuardrails: boolean;
  languagePacks: Array<{
    id: string;
    language: string;
    name: string;
    version: string;
    versionLine?: string;
    targetAppVersion?: string;
    source: "imported" | "downloaded";
    updatedAt: string;
    description?: string;
  }>;
  languagePackCatalogRows: Array<{ id: string; language: string; name: string; status: string }>;
  setTheme: (value: "linen" | "marine" | "graphite") => void;
  handleLanguageChange: (value: string) => void;
  handleDownloadLanguagePackTemplate: () => void;
  handleExportInstalledLanguagePack: () => void;
  handleImportLanguagePack: (file: File) => Promise<void>;
  handleRemoveLanguagePack: (packId: string) => void;
  handleInstallCatalogLanguagePack: (packId: string) => void;
  setFrontendRuntimeMode: (value: "orchestrated_gui" | "direct_mesh_gui") => void;
  setDirectMeshSelectionMode: (value: "healthiest" | "first_reachable") => void;
  setDirectMeshEndpointsText: (value: string) => void;
  setControlPlaneApiToken: (value: string) => void;
  setClusterApiToken: (value: string) => void;
  setDirectMeshApiToken: (value: string) => void;
  setShowShortcutHints: (value: boolean) => void;
  setImmersiveGuardrails: (value: boolean) => void;
  downloadDatabaseSnapshot: () => Promise<void>;
  scriptActionLog: WorkbenchScriptActionLogEntry[];
  getScriptSnapshot: () => WorkbenchScriptSnapshot;
  scriptRecordingMode: boolean;
  invokeScriptAction: (action: string, payload?: Record<string, unknown>) => Promise<unknown>;
  setScriptRecordingMode: Dispatch<SetStateAction<boolean>>;
  scriptSnapshot: WorkbenchScriptSnapshot;
  systemDataTab: "jobs" | "results";
  handleSystemDataTabChange: (tab: "jobs" | "results") => void;
  adminJobRows: Array<{ id: string; status: string; projectId: string | null; heartbeatTone: string; heartbeatLabel: string; statusDetail?: string | null; detail: string }>;
  selectedAdminJobId: string | null;
  handleSelectAdminJob: (jobId: string) => void;
  selectedAdminJob: { job_id?: string; project_id?: string | null; model_version_id?: string | null; status?: string } | null;
  adminJobMessage: string;
  setAdminJobMessage: (value: string) => void;
  adminJobProjectId: string;
  setAdminJobProjectId: (value: string) => void;
  adminJobModelVersionId: string;
  setAdminJobModelVersionId: (value: string) => void;
  adminJobCaseId: string;
  setAdminJobCaseId: (value: string) => void;
  saveAdminJobRecord: () => void;
  deleteAdminJobRecord: () => void;
  adminResultRows: Array<{
    id: string;
    updatedAt: string;
    projectId: string | null;
    modelVersionId: string | null;
    status: string | null;
    summary: string;
  }>;
  selectedAdminResultJobId: string | null;
  handleSelectAdminResult: (jobId: string) => void;
  jobHistory: Array<{
    job_id: string;
    project_id?: string | null;
    model_version_id?: string | null;
    status: string;
  }>;
  adminResultDraft: string;
  setAdminResultDraft: (value: string) => void;
  saveAdminResultRecord: () => void;
  applySelectedAdminResultContext: () => void;
  openSelectedAdminResultProject: () => void;
  openSelectedAdminResultVersion: () => void;
  exportAdminResultRecord: () => void;
  deleteAdminResultRecord: () => void;
  adminFilterProjectId: string;
  handleAdminFilterProjectChange: (value: string) => void;
  adminFilterModelVersionId: string;
  handleAdminFilterModelVersionChange: (value: string) => void;
  selectedProjectId: string | null;
  selectedVersionId: string | null;
  useCurrentProjectAsAdminFilter: () => void;
  useCurrentVersionAsAdminFilter: () => void;
  clearAdminFilters: () => void;
  applySelectedAdminJobContext: () => void;
  openSelectedAdminJobProject: () => void;
  openSelectedAdminJobVersion: () => void;
  jobId: string | null;
  cancelCurrentJob: () => void;
  cancelJob: (jobId: string) => Promise<unknown>;
  setMessage: (value: string) => void;
  refreshJobHistory: () => Promise<void>;
};
