"use client";

export type SidebarSection = "study" | "model" | "workflow" | "library" | "system";
export type StudyKind = "axial_bar_1d" | "heat_bar_1d" | "heat_plane_triangle_2d" | "heat_plane_quad_2d" | "thermal_bar_1d" | "thermal_beam_1d" | "thermal_frame_2d" | "thermal_truss_2d" | "thermal_truss_3d" | "thermal_plane_triangle_2d" | "thermal_plane_quad_2d" | "spring_1d" | "spring_2d" | "spring_3d" | "beam_1d" | "torsion_1d" | "truss_2d" | "truss_3d" | "plane_triangle_2d" | "plane_quad_2d" | "frame_2d";

export type TrussSuggestion = {
  id: string;
  label: string;
};

export type TrussDiagnostics = {
  blockingMessages: string[];
  suggestions: TrussSuggestion[];
};

export type StabilitySummary = {
  score: number;
  tone: "good" | "watch" | "risk";
  hotspotNodes: number[];
};

export type HistoryEntry = {
  label: string;
};

export type TrussNodeSelection = {
  id: string;
  x: number;
  y: number;
  load_x: number;
  load_y: number;
  fix_x: boolean;
  fix_y: boolean;
};

export type TrussElementSelection = {
  id: string;
  index: number;
  node_i: number;
  node_j: number;
};

export type Truss3dNodeSelection = {
  id: string;
  x: number;
  y: number;
  z: number;
  load_x: number;
  load_y: number;
  load_z: number;
  fix_x: boolean;
  fix_y: boolean;
  fix_z: boolean;
};

export type Truss3dElementSelection = {
  id: string;
  index: number;
  node_i: number;
  node_j: number;
};

export type PlaneNodeSelection = {
  id: string;
  x: number;
  y: number;
  load_x: number;
  load_y: number;
  fix_temperature?: boolean;
  temperature?: number;
  heat_load?: number;
  temperature_delta?: number;
  displacement_magnitude?: number;
  fix_x: boolean;
  fix_y: boolean;
};

export type PlaneElementSelection = {
  id: string;
  index: number;
  node_i: number;
  node_j: number;
  node_k: number;
  node_l?: number;
  thermal_expansion?: number;
  conductivity?: number;
  average_temperature?: number;
  temperature_gradient_x?: number;
  temperature_gradient_y?: number;
  heat_flux_x?: number;
  heat_flux_y?: number;
  heat_flux_magnitude?: number;
  average_temperature_delta?: number;
  thermal_strain?: number;
  mechanical_strain_x?: number;
  mechanical_strain_y?: number;
  total_strain_x?: number;
  total_strain_y?: number;
  principal_stress_1?: number;
  principal_stress_2?: number;
  max_in_plane_shear?: number;
};

export type FrameNodeSelection = {
  id: string;
  x: number;
  y: number;
  load_x: number;
  load_y: number;
  moment_z: number;
  fix_x: boolean;
  fix_y: boolean;
  fix_rz: boolean;
  displacement_magnitude?: number;
  rz?: number;
  temperature_delta?: number;
  temperature?: number;
  heat_load?: number;
  fix_temperature?: boolean;
};

export type FrameElementSelection = {
  id: string;
  index: number;
  node_i: number;
  node_j: number;
  area: number;
  youngs_modulus: number;
  moment_of_inertia: number;
  section_modulus: number;
  distributed_load_y?: number;
  temperature_gradient_y?: number;
  average_temperature?: number;
  temperature_gradient_x?: number;
  heat_flux_x?: number;
  heat_flux_y?: number;
  heat_flux_magnitude?: number;
  average_temperature_delta?: number;
  thermal_curvature?: number;
  axial_stress?: number;
  max_bending_stress?: number;
  max_combined_stress?: number;
  axial_force_i?: number;
  shear_force_i?: number;
  moment_i?: number;
  axial_force_j?: number;
  shear_force_j?: number;
  moment_j?: number;
};

export type JobLike = {
  status?: string | null;
  worker_id?: string | null;
  progress?: number | null;
  iteration?: number | null;
  residual?: number | null;
  has_result?: boolean | null;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  message?: string | null;
};

export type InspectorLabels = {
  overview: string;
  result: string;
  actions: string;
  summary: string;
  details: string;
  busy: string;
  ready: string;
  properties: string;
  dragNode: string;
  nodeX: string;
  nodeY: string;
  nodeZ: string;
  loadX: string;
  loadY: string;
  loadZ: string;
  fixX: string;
  fixY: string;
  fixZ: string;
  memberSelection: string;
  nodeI: string;
  nodeJ: string;
  nodeK: string;
  area: string;
  modulus: string;
  planeThickness: string;
  poissonRatio: string;
  fixRz: string;
  momentZ: string;
  torqueZ: string;
  rotationZ: string;
  frameElements: string;
  memberEndForces: string;
  momentOfInertia: string;
  sectionModulus: string;
  distributedLoadY: string;
  temperatureDelta: string;
  temperature: string;
  averageTemperature: string;
  maxTemperature: string;
  conductivity: string;
  fixTemperature: string;
  heatLoad: string;
  temperatureGradientX: string;
  temperatureGradientY: string;
  maxHeatFlux: string;
  heatFluxX: string;
  heatFluxY: string;
  thermalCurvature: string;
  thermalExpansion: string;
  bendingStress: string;
  combinedStress: string;
  maxMoment: string;
  maxTorque: string;
  torsionStress: string;
  thermalStrain: string;
  mechanicalStrain: string;
  totalStrain: string;
  maxRotation: string;
  sortBy: string;
  shearForce: string;
  forceI: string;
  shearI: string;
  momentI: string;
  forceJ: string;
  shearJ: string;
  momentJ: string;
  selectionHint: string;
  diagnostics: string;
  stabilityScore: string;
  stabilityGood: string;
  stabilityWatch: string;
  stabilityRisk: string;
  hotspotNodes: string;
  suggestedFixes: string;
  diagnosticsClear: string;
  historyPanel: string;
  undo: string;
  redo: string;
  noOperations: string;
  metrics: string;
  status: string;
  worker: string;
  progress: string;
  iteration: string;
  residual: string;
  nodes: string;
  report: string;
  exportData: string;
  exportJson: string;
  exportCsv: string;
  tipDisp: string;
  maxStress: string;
  axialForce: string;
  maxAxialForce: string;
  maxShearForce: string;
  reaction: string;
  displacementMagnitude: string;
  principalStress1: string;
  principalStress2: string;
  maxInPlaneShear: string;
  currentField: string;
  planeHotspots: string;
  topN: string;
  exportHotspots: string;
  memberForceTable: string;
  elementHeatTable: string;
  exportMemberForces: string;
  createdAt: string;
  updatedAt: string;
  lastHeartbeat: string;
  heartbeatStatus: string;
  hasResult: string;
  failureReason: string;
  cancelJob: string;
  yes: string;
  no: string;
};

export type WorkbenchInspectorProps = {
  t: InspectorLabels;
  reportScopeLabel?: string;
  reportScopeHint?: string;
  sidebarSection: SidebarSection;
  studyKind: StudyKind;
  isPending: boolean;
  selectedNodeData: TrussNodeSelection | null;
  selectedElementData: TrussElementSelection | null;
  selectedTruss3dNodeData: Truss3dNodeSelection | null;
  selectedTruss3dElementData: Truss3dElementSelection | null;
  selectedPlaneNodeData: PlaneNodeSelection | null;
  selectedPlaneElementData: PlaneElementSelection | null;
  selectedFrameNodeData: FrameNodeSelection | null;
  selectedFrameElementData: FrameElementSelection | null;
  trussElementArea: number;
  trussElementModulusGpa: number;
  trussElementMaterialId: string;
  truss3dElementArea: number;
  truss3dElementModulusGpa: number;
  truss3dElementMaterialId: string;
  planeElementThickness: number;
  planeElementModulusGpa: number;
  planeElementPoissonRatio: number;
  planeElementMaterialId: string;
  frameElementMaterialId: string;
  materialOptions: Array<{ id: string; label: string }>;
  materialLabel: string;
  onUpdateSelectedNode: (field: "x" | "y" | "load_x" | "load_y" | "fix_x" | "fix_y", value: number | boolean) => void;
  onUpdateSelectedElement: (field: "area" | "youngs_modulus", value: number) => void;
  onAssignSelectedElementMaterial: (materialId: string) => void;
  onUpdateSelectedTruss3dNode: (field: "x" | "y" | "z" | "load_x" | "load_y" | "load_z" | "fix_x" | "fix_y" | "fix_z", value: number | boolean) => void;
  onUpdateSelectedTruss3dElement: (field: "area" | "youngs_modulus", value: number) => void;
  onAssignSelectedTruss3dElementMaterial: (materialId: string) => void;
  onUpdateSelectedPlaneNode: (field: "x" | "y" | "load_x" | "load_y" | "fix_x" | "fix_y" | "temperature_delta" | "fix_temperature" | "temperature" | "heat_load", value: number | boolean) => void;
  onUpdateSelectedPlaneElement: (field: "thickness" | "youngs_modulus" | "poisson_ratio" | "thermal_expansion" | "conductivity", value: number) => void;
  onAssignSelectedPlaneElementMaterial: (materialId: string) => void;
  onUpdateSelectedFrameNode: (field: "x" | "y" | "load_x" | "load_y" | "moment_z" | "fix_x" | "fix_y" | "fix_rz" | "temperature_delta", value: number | boolean) => void;
  onUpdateSelectedFrameElement: (
    field: "area" | "youngs_modulus" | "moment_of_inertia" | "section_modulus" | "distributed_load_y" | "temperature_gradient_y",
    value: number,
  ) => void;
  onAssignSelectedFrameElementMaterial: (materialId: string) => void;
  trussDiagnostics: TrussDiagnostics | null;
  trussStability: StabilitySummary | null;
  hotspotNodeLabels: string;
  onApplyTrussSuggestion: (id: string) => void;
  undoStack: HistoryEntry[];
  redoStack: HistoryEntry[];
  onUndo: () => void;
  onRedo: () => void;
  job: JobLike | null;
  nodeCount: number;
  tipDisplacement: string;
  maxStressValue: string;
  frameMaxAxialForceValue?: string;
  frameMaxShearForceValue?: string;
  reactionValue: string;
  frameMaxRotationValue?: string;
  thermalFrameMaxTemperatureDeltaValue?: string;
  thermalFrameMaxTemperatureGradientValue?: string;
  thermalBeamMaxTemperatureGradientValue?: string;
  thermalPlaneMaxTemperatureDeltaValue?: string;
  planeHotspotFieldLabel?: string;
  planeHotspotElements: Array<{ id: string; value: string; index: number; active?: boolean; summary?: string }>;
  planeThermalRows: Array<{
    id: string;
    index: number;
    active?: boolean;
    sortTemperature: number;
    sortGradient: number;
    sortFlux: number;
    averageTemperature: string;
    temperatureGradientX: string;
    temperatureGradientY: string;
    heatFluxX: string;
    heatFluxY: string;
    heatFluxMagnitude: string;
  }>;
  frameHotspotFieldLabel?: string;
  frameHotspotElements: Array<{ id: string; value: string; index: number; active?: boolean; summary?: string }>;
  frameForceRows: Array<{
    id: string;
    index: number;
    active?: boolean;
    sortAxial: number;
    sortShear: number;
    sortMoment: number;
    axialForceI: string;
    shearForceI: string;
    momentI: string;
    axialForceJ: string;
    shearForceJ: string;
    momentJ: string;
  }>;
  planeHotspotLimit: number;
  createdAtValue: string;
  updatedAtValue: string;
  heartbeatStatusValue: string;
  heartbeatTone: "healthy" | "quiet" | "stale";
  failureReasonValue: string;
  canCancelJob: boolean;
  onCancelJob: () => void;
  onDownloadJson: () => void;
  onDownloadCsv: () => void;
  canProjectHeatToThermo?: boolean;
  projectHeatToThermoLabel?: string;
  onProjectHeatToThermo?: () => void;
  onDownloadPlaneHotspots: () => void;
  onDownloadFrameHotspots: () => void;
  onDownloadFrameForces: () => void;
  onSelectPlaneHotspot: (index: number) => void;
  onSelectFrameHotspot: (index: number) => void;
  onPlaneHotspotLimitChange: (limit: number) => void;
};

export type InspectorTab = "status" | "result" | "actions";
export type StatusPage = "properties" | "diagnostics";
export type ActionsPage = "history" | "exports";
export type ResultPage = "summary" | "details";
export type FrameForceSort = "index" | "axial" | "shear" | "moment";
export type PlaneHeatSort = "index" | "temperature" | "gradient" | "flux";
