"use client";

import { createElement } from "react";
import { buildWorkbenchSidebarMountProps } from "@/components/workbench/workbench-sidebar-mount-props";
import { WorkbenchRuntimeRecoveryCard } from "@/components/workbench/system/workbench-runtime-recovery-card";

export function buildWorkbenchSidebarComposition(props: Record<string, any>) {
  const { shellState, workspaceState, studyResultDerived, interactionControllers, flowControllers, workflowController } =
    props;
  const { topLevelActions, assistantAudit, uiActionController } = interactionControllers;
  const { primaryActionsController, invokeScriptAction } = flowControllers;

  return buildWorkbenchSidebarMountProps({
    t: props.t,
    railItems: props.railItems,
    sidebarSection: workspaceState.sidebarSection,
    handleSidebarSectionChange: uiActionController.handleSidebarSectionChange,
    studyTab: workspaceState.studyTab,
    handleStudyTabChange: uiActionController.handleStudyTabChange,
    loadedModelName: workspaceState.loadedModelName,
    studyKind: workspaceState.studyKind,
    studyDomainOptions: props.studyDomainOptions,
    studyKindOptionGroups: props.studyKindOptionGroups,
    selectStudyKind: props.selectStudyKind,
    studySummaryRows: props.studySummaryRows,
    studyControlsRows: props.studyControlsRows,
    studyControlsContent: props.studyControlsContent,
    isPending: props.isPending,
    runAnalysis: primaryActionsController.runAnalysis,
    modelTab: workspaceState.modelTab,
    handleModelTabChange: uiActionController.handleModelTabChange,
    modelToolsPage: workspaceState.modelToolsPage,
    handleModelToolsPageChange: props.handleModelToolsPageChange,
    isTruss3d: studyResultDerived.isTruss3d,
    modelStudyContent: props.modelStudyContent,
    modelStudioContent: props.modelStudioContent,
    modelMaterialsContent: props.modelMaterialsContent,
    modelGenerateContent: props.modelGenerateContent,
    modelTreeContent: props.modelTreeContent,
    workflowPanelTab: workflowController.workflowPanelTab,
    handleWorkflowPanelTabChange: uiActionController.handleWorkflowPanelTabChange,
    workflowLabels: props.workflowLabels,
    workflowCatalog: workflowController.workflowCatalog,
    workflowOperatorDescriptors: workflowController.workflowOperatorDescriptors,
    workflowCatalogBusy: workflowController.workflowCatalogBusy,
    selectedWorkflowId: workflowController.selectedWorkflowId,
    selectedWorkflow: workflowController.selectedWorkflow,
    currentStudyKind: workspaceState.studyKind,
    currentHeatPlaneModel: workspaceState.heatPlaneModel,
    currentPlaneModel: workspaceState.planeModel,
    job: workspaceState.job,
    latestWorkflowSummary: workflowController.latestWorkflowSummary,
    workflowRuns: workflowController.workflowRuns,
    refreshWorkflowCatalog: workflowController.refreshWorkflowCatalog,
    setSelectedWorkflowId: workflowController.setSelectedWorkflowId,
    setWorkflowRuns: workflowController.setWorkflowRuns,
    runWorkflowCatalogEntry: workflowController.runWorkflowCatalogEntry,
    runWorkflowDraft: workflowController.runWorkflowDraft,
    openHistoryJob: primaryActionsController.openHistoryJob,
    libraryTab: workspaceState.libraryTab,
    handleLibraryTabChange: uiActionController.handleLibraryTabChange,
    librarySampleRows: studyResultDerived.librarySampleRows,
    projects: workspaceState.projects,
    selectedProjectId: workspaceState.selectedProjectId,
    setSelectedProjectId: workspaceState.setSelectedProjectId,
    setSelectedModelId: workspaceState.setSelectedModelId,
    projectNameDraft: workspaceState.projectNameDraft,
    setProjectNameDraft: workspaceState.setProjectNameDraft,
    projectDescriptionDraft: workspaceState.projectDescriptionDraft,
    setProjectDescriptionDraft: workspaceState.setProjectDescriptionDraft,
    createProjectRecord: props.createProjectRecord,
    updateProjectRecord: props.updateProjectRecord,
    deleteProjectRecord: props.deleteProjectRecord,
    downloadProjectBundleJson: props.downloadProjectBundleJson,
    downloadProjectBundleZip: props.downloadProjectBundleZip,
    importProjectBundle: props.importProjectBundle,
    selectedProjectModels: props.selectedProjectModels,
    libraryModelRows: studyResultDerived.libraryModelRows,
    selectedModelId: workspaceState.selectedModelId,
    setLoadedModelName: workspaceState.setLoadedModelName,
    saveModelVersion: props.saveModelVersion,
    deleteSavedModelRecord: props.deleteSavedModelRecord,
    openSavedModel: props.openSavedModel,
    libraryVersionRows: studyResultDerived.libraryVersionRows,
    modelVersions: workspaceState.modelVersions,
    selectedVersionId: workspaceState.selectedVersionId,
    renameSelectedVersion: props.renameSelectedVersion,
    deleteSelectedVersion: props.deleteSelectedVersion,
    openSavedVersion: props.openSavedVersion,
    libraryJobRows: studyResultDerived.libraryJobRows,
    jobHistory: props.jobHistory,
    openSample: primaryActionsController.openSample,
    refreshJobHistory: props.refreshJobHistory,
    refreshProjects: props.refreshProjects,
    importModel: primaryActionsController.importModel,
    systemPanelTab: workspaceState.systemPanelTab,
    handleSystemPanelTabChange: uiActionController.handleSystemPanelTabChange,
    setSidebarSection: workspaceState.setSidebarSection,
    health: props.health,
    runtimeRecoveryCard: createElement(WorkbenchRuntimeRecoveryCard, {
      language: shellState.language,
      recovery: props.runtimeRecovery,
      onRetryAll: () => void props.retryRuntimeRecovery(),
      onRetryHealth: () => void props.refreshHealth(),
      onRetryProjects: () => void props.refreshProjects(),
      onRetrySecurityEvents: () => void props.refreshSecurityEvents(),
      onRetryWorkflowCatalog: () => void workflowController.refreshWorkflowCatalog(),
    }),
    runtimeBackendRows: studyResultDerived.runtimeBackendRows,
    runtimeProtocolRows: studyResultDerived.runtimeProtocolRows,
    runtimeProtocolMethods: studyResultDerived.runtimeProtocolMethods,
    securityUi: studyResultDerived.securityUi,
    runtimeSecurityRows: studyResultDerived.runtimeSecurityRows,
    runtimeAuditSummaryRows: studyResultDerived.runtimeAuditSummaryRows,
    runtimeAuditTrendBars: studyResultDerived.runtimeAuditTrendBars,
    runtimeAuditSourceStatusFacets: studyResultDerived.runtimeAuditSourceStatusFacets,
    runtimeAuditStudyFacets: studyResultDerived.runtimeAuditStudyFacets,
    runtimeAuditProjectFacets: studyResultDerived.runtimeAuditProjectFacets,
    runtimeAuditModelVersionFacets: studyResultDerived.runtimeAuditModelVersionFacets,
    securityEventRecords: props.securityEventRecords,
    securityEventWindowFilter: props.securityEventWindowFilter,
    securityEventSourceFilter: props.securityEventSourceFilter,
    securityEventRiskFilter: props.securityEventRiskFilter,
    securityEventStatusFilter: props.securityEventStatusFilter,
    securityEventActionFilter: props.securityEventActionFilter,
    setSecurityEventWindowFilter: props.setSecurityEventWindowFilter,
    setSecurityEventSourceFilter: props.setSecurityEventSourceFilter,
    setSecurityEventRiskFilter: props.setSecurityEventRiskFilter,
    setSecurityEventStatusFilter: props.setSecurityEventStatusFilter,
    setSecurityEventActionFilter: props.setSecurityEventActionFilter,
    refreshSecurityEvents: props.refreshSecurityEvents,
    downloadSecurityEventExport: topLevelActions.downloadSecurityEventExport,
    downloadSecurityEventCsvExport: topLevelActions.downloadSecurityEventCsvExport,
    runtimeAuditEntries: studyResultDerived.runtimeAuditEntries,
    protocolAgents: props.protocolAgents,
    protocolAgentCards: studyResultDerived.protocolAgentCards,
    runtimeWatchdogRows: studyResultDerived.runtimeWatchdogRows,
    theme: shellState.theme,
    language: shellState.language,
    frontendRuntimeMode: shellState.frontendRuntimeMode,
    directMeshSelectionMode: shellState.directMeshSelectionMode,
    directMeshEndpointsText: shellState.directMeshEndpointsText,
    controlPlaneApiToken: shellState.controlPlaneApiToken,
    clusterApiToken: shellState.clusterApiToken,
    directMeshApiToken: shellState.directMeshApiToken,
    showShortcutHints: shellState.showShortcutHints,
    immersiveGuardrails: shellState.immersiveGuardrails,
    languagePacks: shellState.languagePacks,
    languagePackCatalogRows: shellState.languagePackCatalogRows,
    setTheme: shellState.setTheme,
    handleLanguageChange: props.handleLanguageChange,
    handleDownloadLanguagePackTemplate: topLevelActions.handleDownloadLanguagePackTemplate,
    handleExportInstalledLanguagePack: topLevelActions.handleExportInstalledLanguagePack,
    handleImportLanguagePack: topLevelActions.handleImportLanguagePack,
    handleRemoveLanguagePack: topLevelActions.handleRemoveLanguagePack,
    setFrontendRuntimeMode: shellState.setFrontendRuntimeMode,
    setDirectMeshSelectionMode: shellState.setDirectMeshSelectionMode,
    setDirectMeshEndpointsText: shellState.setDirectMeshEndpointsText,
    setControlPlaneApiToken: shellState.setControlPlaneApiToken,
    setClusterApiToken: shellState.setClusterApiToken,
    setDirectMeshApiToken: shellState.setDirectMeshApiToken,
    setShowShortcutHints: shellState.setShowShortcutHints,
    setImmersiveGuardrails: shellState.setImmersiveGuardrails,
    downloadDatabaseSnapshot: props.downloadDatabaseSnapshot,
    scriptActionLog: assistantAudit.scriptActionLog,
    getScriptSnapshot: assistantAudit.getScriptSnapshot,
    scriptRecordingMode: props.scriptRecordingMode,
    invokeScriptAction,
    setScriptRecordingMode: props.setScriptRecordingMode,
    scriptSnapshot: topLevelActions.scriptSnapshot,
    systemDataTab: workspaceState.systemDataTab,
    handleSystemDataTabChange: uiActionController.handleSystemDataTabChange,
    adminJobRows: studyResultDerived.adminJobRows,
    selectedAdminJobId: props.selectedAdminJobId,
    handleSelectAdminJob: uiActionController.handleSelectAdminJob,
    selectedAdminJob: props.selectedAdminJob,
    adminJobMessage: props.adminJobMessage,
    setAdminJobMessage: props.setAdminJobMessage,
    adminJobProjectId: props.adminJobProjectId,
    setAdminJobProjectId: props.setAdminJobProjectId,
    adminJobModelVersionId: props.adminJobModelVersionId,
    setAdminJobModelVersionId: props.setAdminJobModelVersionId,
    adminJobCaseId: props.adminJobCaseId,
    setAdminJobCaseId: props.setAdminJobCaseId,
    saveAdminJobRecord: props.saveAdminJobRecord,
    deleteAdminJobRecord: props.deleteAdminJobRecord,
    adminResultRows: studyResultDerived.adminResultRows,
    selectedAdminResultJobId: props.selectedAdminResultJobId,
    handleSelectAdminResult: uiActionController.handleSelectAdminResult,
    adminResultDraft: props.adminResultDraft,
    setAdminResultDraft: props.setAdminResultDraft,
    saveAdminResultRecord: props.saveAdminResultRecord,
    applySelectedAdminResultContext: props.applySelectedAdminResultContext,
    openSelectedAdminResultProject: props.openSelectedAdminResultProject,
    openSelectedAdminResultVersion: props.openSelectedAdminResultVersion,
    exportAdminResultRecord: props.exportAdminResultRecord,
    deleteAdminResultRecord: props.deleteAdminResultRecord,
    adminFilterProjectId: props.adminFilterProjectId,
    handleAdminFilterProjectChange: uiActionController.handleAdminFilterProjectChange,
    adminFilterModelVersionId: props.adminFilterModelVersionId,
    handleAdminFilterModelVersionChange: uiActionController.handleAdminFilterModelVersionChange,
    useCurrentProjectAsAdminFilter: uiActionController.useCurrentProjectAsAdminFilter,
    useCurrentVersionAsAdminFilter: uiActionController.useCurrentVersionAsAdminFilter,
    clearAdminFilters: uiActionController.clearAdminFilters,
    applySelectedAdminJobContext: props.applySelectedAdminJobContext,
    openSelectedAdminJobProject: props.openSelectedAdminJobProject,
    openSelectedAdminJobVersion: props.openSelectedAdminJobVersion,
    cancelCurrentJob: props.cancelCurrentJob,
    cancelJob: props.cancelJob,
    setMessage: workspaceState.setMessage,
  });
}
