"use client";

import { buildWorkbenchAdminDataEffects } from "@/components/workbench/workbench-admin-context";
import { getWorkbenchProjectFlowCopy } from "@/components/workbench/workbench-extended-language-copy";
import { createWorkbenchProjectStorageController } from "@/components/workbench/workbench-project-storage-controller";
import type { WorkbenchNoticeItem } from "@/components/workbench/workbench-notice-state";

export function buildWorkbenchProjectFlows(props: Record<string, any>) {
  let projectStorageControllerRef: { openModelVersionById?: (versionId: string) => void } | null = null;
  const projectFlowCopy = getWorkbenchProjectFlowCopy(props.language);

  const adminDataEffects = buildWorkbenchAdminDataEffects({
    selectedAdminJob: props.selectedAdminJob,
    selectedAdminJobId: props.selectedAdminJobId,
    selectedAdminResultJobId: props.selectedAdminResultJobId,
    jobHistory: props.jobHistory,
    projects: props.projects,
    refreshVersions: props.refreshVersions,
    openModelVersionById: (versionId: string) => projectStorageControllerRef?.openModelVersionById?.(versionId),
    setAdminFilterProjectId: props.setAdminFilterProjectId,
    setAdminFilterModelVersionId: props.setAdminFilterModelVersionId,
    setAdminJobCaseId: props.setAdminJobCaseId,
    setLibraryTab: props.setLibraryTab,
    setSelectedProjectId: props.setSelectedProjectId,
    setSelectedModelId: props.setSelectedModelId,
    setSelectedVersionId: props.setSelectedVersionId,
    setModelVersions: props.setModelVersions,
    setSidebarSection: props.setSidebarSection,
    setMessage: props.setMessage,
    labels: {
      noJobVersion: projectFlowCopy.noJobVersion,
      noResultVersion: projectFlowCopy.noResultVersion,
      noRecordContext: projectFlowCopy.noRecordContext,
      linkedProjectMissing: projectFlowCopy.linkedProjectMissing,
      linkedProjectOpened: props.t.linkedProjectOpened,
      noJobProject: projectFlowCopy.noJobProject,
      noResultProject: projectFlowCopy.noResultProject,
      selectJobFirst: projectFlowCopy.selectJobFirst,
      missingResultJob: projectFlowCopy.missingResultJob,
      recordContextApplied: props.t.recordContextApplied,
    },
  });

  const persistedModelEffects = {
    startTransition: props.startTransition,
    activeMaterial: props.activeMaterial,
    createProject: props.projectLibraryBackendService.createProject,
    createModel: props.projectLibraryBackendService.createModel,
    createModelVersion: props.projectLibraryBackendService.createModelVersion,
    updateModelVersion: props.projectLibraryBackendService.updateModelVersion,
    fetchModel: props.projectLibraryBackendService.fetchModel,
    fetchModelVersion: props.projectLibraryBackendService.fetchModelVersion,
    refreshProjects: props.refreshProjects,
    refreshVersions: props.refreshVersions,
    recordHistory: props.recordHistory,
    resetActiveResult: props.resetActiveResult,
    importActionLabel: props.t.importAction,
    historyActionLabel: props.t.historyAction,
    importedModelLabel: props.t.persistedModelLoaded,
    importedProjectLabel: props.t.projectImported,
    importedVersionLabel: props.t.versionLoaded,
    importFailedLabel: props.t.importFailed,
    formatImportNotice: (skippedSensitivePresetCount: number): WorkbenchNoticeItem => ({
      id: "project-import-notice",
      tone: "warning",
      message: projectFlowCopy.skippedSensitivePresets(skippedSensitivePresetCount),
    }),
    setMessage: props.setMessage,
    setSystemAlerts: props.setSystemAlerts,
    setImportNotice: props.setImportNotice,
    setSelectedProjectId: props.setSelectedProjectId,
    setSidebarSection: props.setSidebarSection,
    setLoadedModelName: props.setLoadedModelName,
    setSelectedModelId: props.setSelectedModelId,
    setSelectedVersionId: props.setSelectedVersionId,
    setModelVersions: props.setModelVersions,
    setStudyKind: props.setStudyKind,
    setAxialForm: props.setAxialForm,
    setHeatBarModel: props.setHeatBarModel,
    setHeatPlaneModel: props.setHeatPlaneModel,
    setThermalBarModel: props.setThermalBarModel,
    setThermalBeamModel: props.setThermalBeamModel,
    setThermalFrameModel: props.setThermalFrameModel,
    setThermalTrussModel: props.setThermalTrussModel,
    setThermalTruss3dModel: props.setThermalTruss3dModel,
    setSpringModel: props.setSpringModel,
    setSpring2dModel: props.setSpring2dModel,
    setSpring3dModel: props.setSpring3dModel,
    setTrussModel: props.setTrussModel,
    setTruss3dModel: props.setTruss3dModel,
    setPlaneModel: props.setPlaneModel,
    setFrameModel: props.setFrameModel,
    setBeamModel: props.setBeamModel,
    setTorsionModel: props.setTorsionModel,
    setPlaneResultField: props.setPlaneResultField,
    setParametric: props.setParametric,
    setActiveMaterial: props.setActiveMaterial,
  };

  const projectStorageController = createWorkbenchProjectStorageController({
    t: props.t,
    getSelectedProject: () => props.selectedProject,
    selectedProjectId: props.selectedProjectId,
    getSelectedProjectModels: () => props.selectedProjectModels,
    selectedModelId: props.selectedModelId,
    selectedVersionId: props.selectedVersionId,
    projectNameDraft: props.projectNameDraft,
    projectDescriptionDraft: props.projectDescriptionDraft,
    loadedModelName: props.loadedModelName,
    activeMaterial: props.activeMaterial,
    studyKind: props.studyKind,
    jobHistory: props.jobHistory,
    axialForm: props.axialForm,
    heatBarModel: props.heatBarModel,
    heatPlaneModel: props.heatPlaneModel,
    thermalBarModel: props.thermalBarModel,
    thermalBeamModel: props.thermalBeamModel,
    thermalFrameModel: props.thermalFrameModel,
    thermalTrussModel: props.thermalTrussModel,
    trussModel: props.trussModel,
    thermalTruss3dModel: props.thermalTruss3dModel,
    truss3dModel: props.truss3dModel,
    planeModel: props.planeModel,
    frameModel: props.frameModel,
    beamModel: props.beamModel,
    torsionModel: props.torsionModel,
    springModel: props.springModel,
    spring2dModel: props.spring2dModel,
    spring3dModel: props.spring3dModel,
    parametric: props.parametric,
    round: props.round,
    startTransition: props.startTransition,
    setMessage: props.setMessage,
    setSelectedProjectId: props.setSelectedProjectId,
    setSelectedModelId: props.setSelectedModelId,
    setSelectedVersionId: props.setSelectedVersionId,
    setModelVersions: props.setModelVersions,
    adminDataBackendService: props.adminDataBackendService,
    projectLibraryBackendService: props.projectLibraryBackendService,
    refreshProjects: props.refreshProjects,
    refreshVersions: props.refreshVersions,
    serializeCurrentModel: props.serializeCurrentModel,
    getPersistedModelEffects: () => persistedModelEffects,
  });
  projectStorageControllerRef = projectStorageController;

  return {
    adminDataEffects,
    projectStorageController,
  };
}
