import brand from "../../../../../assets/brand/brand.json";

export const copyEnCore = {
    brand: brand.productName,
    shortTitle: brand.workbenchShortName ?? brand.applicationName.replace(/^Kyuubiki\s+/u, ""),
    roleLabel: brand.workbenchRoleLabel ?? "Analysis shell",
    title: brand.workbenchShortName ?? brand.applicationName.replace(/^Kyuubiki\s+/u, ""),
    subtitle: brand.workbenchDescription,
    rail: { study: "Study", model: "Workspace", workflow: "Workflow", library: "History", system: "System" },
    sections: { study: "Study Setup", model: "Workspace", workflow: "Workflow Studio", library: "Job History", system: "System" },
    kinds: {
      axial_bar_1d: "1D axial bar",
      heat_bar_1d: "1D heat bar",
      heat_plane_triangle_2d: "2D heat plane triangle",
      heat_plane_quad_2d: "2D heat plane quad",
      thermal_bar_1d: "1D thermal bar",
      thermal_beam_1d: "1D thermal beam",
      thermal_frame_2d: "2D thermal frame",
      thermal_truss_2d: "2D thermal truss",
      thermal_truss_3d: "3D thermal space truss",
      thermal_plane_triangle_2d: "2D thermal plane triangle",
      thermal_plane_quad_2d: "2D thermal plane quad",
      spring_1d: "1D spring",
      spring_2d: "2D spring",
      spring_3d: "3D spring",
      beam_1d: "1D beam",
      torsion_1d: "1D torsion shaft",
      truss_2d: "2D truss",
      truss_3d: "3D space truss",
      plane_triangle_2d: "2D plane triangle",
      plane_quad_2d: "2D plane quad",
      frame_2d: "2D frame",
    },
    studyFamilies: {
      axialAndSprings: "Axial & Springs",
      beamsAndFrames: "Beams & Frames",
      trusses: "Trusses",
      planes: "Planes",
    },
    studyDomains: {
      mechanical: "Mechanical",
      thermal: "Thermal",
      thermoMechanical: "Thermo-mechanical",
    },
    familyHints: {
      axialAndSprings: "Line studies focused on stiffness, extension, and axial force paths.",
      beamsAndFrames: "Member studies focused on bending, shear, rotation, and end-force review.",
      trusses: "Connectivity studies focused on axial load paths and structural stability.",
      planes: "Continuum studies focused on stress fields, patches, and hotspot elements.",
    },
    importModel: "Import model",
    importHint: "Load a JSON model for 1D or 2D studies.",
    sampleCatalogPage: "Catalog",
    sampleImportPage: "Import",
    workflowOverviewPage: "Overview",
    workflowCatalogPage: "Catalog",
    workflowBuilderPage: "Builder",
    workflowRunsPage: "Runs",
    workflowCatalogTitle: "Workflow Catalog",
    workflowCatalogHint: "Run named multi-operator workflows here before wiring them into a larger study path.",
    workflowOverviewHint: "Keep composite operator workflows in one dedicated surface instead of hiding them inside samples or results.",
    workflowBuilderHint: "Inspect graph nodes, bridges, extracts, and exports before turning them into a larger study chain.",
    workflowRunsHint: "Track named workflow jobs, current nodes, and exported summaries from one place.",
    workflowCatalogRefresh: "Refresh workflows",
    workflowCatalogRun: "Run reference sample",
    workflowRunDraftLabel: "Run current draft",
    workflowCatalogEmpty: "No named workflows are published yet.",
    workflowCatalogReady: "Workflow catalog ready.",
    workflowCatalogQueued: "Queued workflow job",
    workflowCatalogCompleted: "Workflow completed",
    workflowCatalogUnsupported: "This workflow does not have a built-in sample input yet.",
    workflowCatalogLoaded: "Loaded workflow catalog.",
    workflowCatalogFailed: "Workflow run failed.",
    workflowSelectForBuilder: "Open builder",
    workflowNoSelection: "Select a named workflow first so the builder can show its graph.",
    workflowNodesTitle: "Nodes",
    workflowEdgesTitle: "Edges",
    workflowTopologyEditorTitle: "Topology Editor",
    workflowAddNodeLabel: "Add node",
    workflowAddConnectedNodeLabel: "Add connected node",
    workflowInsertSolveExtractExportLabel: "Insert solve -> extract -> export",
    workflowInsertHeatBridgeThermoLabel: "Insert heat -> bridge -> thermo",
    workflowRemoveNodeLabel: "Remove node",
    workflowAddEdgeLabel: "Add edge",
    workflowRemoveEdgeLabel: "Remove edge",
    workflowNodeIdLabel: "Node ID",
    workflowEdgeIdLabel: "Edge ID",
    workflowFromLabel: "From",
    workflowToLabel: "To",
    workflowInputsTitle: "Inputs",
    workflowOutputsTitle: "Outputs",
    workflowAddInputPortLabel: "Add input port",
    workflowAddOutputPortLabel: "Add output port",
    workflowPortIdLabel: "Port ID",
    workflowRemovePortLabel: "Remove port",
    workflowEntryInputsTitle: "Entry Inputs",
    workflowOutputArtifactsTitle: "Output Artifacts",
    workflowDatasetContractTitle: "Dataset Contract",
    workflowDatasetValuesTitle: "Dataset Values",
    workflowDatasetValueLabel: "Dataset Value",
    workflowDatasetSemanticTypeLabel: "Semantic Type",
    workflowDatasetEncodingLabel: "Encoding",
    workflowDatasetShapeLabel: "Shape",
    workflowDatasetAxesLabel: "Axis",
    workflowDatasetSchemaLabel: "Schema",
    workflowDatasetClassLabel: "Element Type",
    workflowDatasetNoneLabel: "This workflow has not published a dataset contract yet.",
    workflowDatasetDraftHint: "Edit dataset semantics locally here first so ports, edges, and cross-operator values line up before we add persistence.",
    workflowDatasetEditorTitle: "Dataset Editor",
    workflowDatasetValueSelectLabel: "Selected Dataset Value",
    workflowDatasetUnitLabel: "Unit",
    workflowDatasetMetadataLabel: "Metadata",
    workflowDatasetPortMappingsTitle: "Port Mappings",
    workflowDatasetEdgeMappingsTitle: "Edge Mappings",
    workflowDatasetDraftLocalLabel: "local draft",
    workflowDatasetUnassignedLabel: "Unassigned",
    workflowDatasetAddValueLabel: "Add Value",
    workflowDatasetRemoveValueLabel: "Remove Value",
    workflowDatasetAxesEditorTitle: "Axes Editor",
    workflowDatasetAddAxisLabel: "Add Axis",
    workflowDatasetRemoveAxisLabel: "Remove Axis",
    workflowDatasetAxisIdLabel: "Axis ID",
    workflowDatasetAxisSizeLabel: "Axis Size",
    workflowDatasetAxisSemanticLabel: "Axis Semantic",
    workflowInputArtifactsTitle: "Draft Inputs",
    workflowInputArtifactsHint: "Edit the input artifact JSON for each entry node here before running the current draft graph.",
    workflowImportGraphLabel: "Import Graph JSON",
    workflowImportDatasetContractLabel: "Import Dataset JSON",
    workflowImportSuccessLabel: "Imported local workflow draft.",
    workflowImportInvalidGraphLabel: "That file is not a valid workflow graph JSON.",
    workflowImportInvalidDatasetLabel: "That file is not a valid workflow dataset JSON.",
    workflowSaveDraftLabel: "Save draft",
    workflowPromoteDraftLabel: "Promote to local workflow",
    workflowDuplicateLocalWorkflowLabel: "Duplicate as variant",
    workflowRenameLocalWorkflowLabel: "Rename local workflow",
    workflowSavedDraftsTitle: "Saved Drafts",
    workflowSavedDraftsHint: "Keep local workflow snapshots here while the builder is still evolving toward full named workflow authoring.",
    workflowSavedDraftsEmptyLabel: "No local workflow drafts have been saved yet.",
    workflowLoadDraftLabel: "Load draft",
    workflowDeleteDraftLabel: "Delete draft",
    workflowDraftSavedLabel: "Saved local workflow draft.",
    workflowDraftLoadedLabel: "Loaded local workflow draft.",
    workflowDraftDeletedLabel: "Deleted local workflow draft.",
    workflowLocalWorkflowPromotedLabel: "Promoted draft to local workflow library.",
    workflowLocalWorkflowDeleteLabel: "Delete local workflow",
    workflowLocalWorkflowDeletedLabel: "Deleted local workflow.",
    workflowLocalWorkflowBadgeLabel: "Local workflow",
    workflowLocalWorkflowDuplicatedLabel: "Duplicated local workflow as variant.",
    workflowLocalWorkflowRenamePrompt: "Rename this local workflow",
    workflowLocalWorkflowSourceLabel: "Source",
    workflowLocalWorkflowPromotedAtLabel: "Promoted",
    workflowLocalWorkflowVariantOfLabel: "Variant of",
    workflowRunDraftInvalidInputsLabel: "This input JSON is missing or invalid.",
    workflowValidationTitle: "Consistency checks",
    workflowValidationOkLabel: "No graph or dataset contract mismatches found.",
    workflowValidationFixLabel: "Apply fix",
    workflowValidationLocateLabel: "Locate",
    workflowArtifactNodeLabel: "Node",
    workflowArtifactTypeLabel: "Artifact type",
    workflowArtifactDescriptionLabel: "Description",
    workflowArtifactRemoveLabel: "Remove artifact",
    workflowArtifactAdoptSuggestedLabel: "Use node port type",
    workflowArtifactAddEntryLabel: "Add entry input",
    workflowArtifactAddOutputLabel: "Add output artifact",
    workflowArtifactDraftLocalLabel: "Local draft",
    workflowExportGraphLabel: "Export Graph JSON",
    workflowExportDatasetContractLabel: "Export Dataset JSON",
    workflowOperatorLabel: "Operator",
    workflowKindLabel: "Kind",
    workflowProgressLabel: "Progress",
    workflowCurrentNodeLabel: "Current node",
    workflowLatestSummaryLabel: "Latest summary",
    workflowOpenRunLabel: "Open run",
    workflowRunsEmpty: "No workflow runs yet.",
    projectManagePage: "Manage",
    projectExchangePage: "Exchange",
    modelSavedPage: "Saved",
    modelVersionsPage: "Versions",
    studyDomain: "Physics domain",
    noDomainStudies: "No studies are published in this domain yet.",
    axialSample: "Open 1D sample",
    trussSample: "Open 2D sample",
    modelName: "Model",
    material: "Material",
    mesh: "Mesh",
    load: "Load",
    support: "Support",
    viewport: "Viewport",
    report: "Report",
    metrics: "Solver Metrics",
    messages: "Messages",
    failureReason: "Failure reason",
    lastHeartbeat: "Last heartbeat",
    heartbeatStatus: "Heartbeat status",
    cancelJob: "Cancel job",
    historyPanel: "Operation History",
    undo: "Undo",
    redo: "Redo",
    noOperations: "No reversible operations yet.",
    undoApplied: "Rolled back the last change.",
    redoApplied: "Re-applied the last rolled-back change.",
    changeStudyType: "Changed study type",
    editAxialField: "Edited axial study input",
    editMaterial: "Changed material preset",
    editParametric: "Edited parametric generator",
    importAction: "Imported model file",
    sampleAction: "Loaded sample model",
    historyAction: "Opened historical job",
    generateAction: "Generated parametric truss",
    applySuggestionAction: "Applied diagnostic fix",
    addNodeAction: "Added node",
    deleteNodeAction: "Deleted node",
    toggleMemberAction: "Changed member connectivity",
    deleteMemberAction: "Deleted member",
    dragNodeAction: "Dragged node",
    editNodeAction: "Edited node properties",
    editMemberAction: "Edited member properties",
    overview: "Overview",
    result: "Result",
    actions: "Actions",
    details: "Details",
    controls: "Controls",
    controlsSetupPage: "Setup",
    controlsReviewPage: "Review",
    studyTypeLabel: "Study Type",
    modelStudyPage: "Study",
    modelOverviewPage: "Overview",
    modelStudioPage: "Studio",
    modelMaterialsPage: "Materials",
    modelGeneratePage: "Generate",
    workspaceStudyHint: "Choose the study family, physics domain, and solver-ready setup here.",
    workspaceStudioHint: "Build and edit nodes, members, boundaries, and geometry here.",
    workspaceMaterialsHint: "Keep starter material values and reusable material choices together here.",
    workspaceGenerateHint: "Use generators and parametric helpers to create repeatable models here.",
    workspaceBrowseHint: "Browse objects, highlights, and result-linked selections here.",
    settings: "Settings",
    scripts: "Scripts",
    settingsConfigHint: "Theme, language, routing, access tokens, and language packs stay here.",
    settingsScriptsHint: "WASM Python, macro recording, and action catalogs stay here.",
    assistant: "Assistant",
    config: "Config",
    runtime: "Runtime",
    data: "Data",
    packs: "Language packs",
    workspace: "Workspace",
    routing: "Routing",
    access: "Access",
    stack: "Stack",
    security: "Security",
    agents: "Agents",
    audit: "Audit",
    assistantSummary: "Context",
    assistantStatusReady: "Ready",
    assistantCurrentStudy: "Study",
    assistantCurrentRuntime: "Runtime",
    assistantCurrentJob: "Job",
    assistantCurrentResult: "Result",
    assistantEmpty: "The workbench looks healthy. No assisted action is needed right now.",
    assistantNeedsProject: "Attach this workspace to a project",
    assistantNeedsProjectHint: "Projects make saved models, jobs, exports, and history easier to manage.",
    assistantOpenProjects: "Open projects",
    assistantRefreshRuntime: "Refresh runtime status",
    assistantRefreshRuntimeHint: "The runtime snapshot is missing or stale. Pull the latest health and agent state.",
    assistantConfigureDirectMesh: "Configure direct mesh endpoints",
    assistantConfigureDirectMeshHint: "Direct mesh mode needs at least one reachable host:port endpoint before it can route solves.",
    assistantRunStudy: "Run the current study",
    assistantRunStudyHint: "The model is ready enough to submit. Launch a fresh solve with the current inputs.",
    assistantCancelRun: "Cancel the active run",
    assistantCancelRunHint: "A solve is still in flight. Stop it if you want to edit the model or retry with different settings.",
    assistantApplyFix: "Apply the first suggested fix",
    assistantApplyFixHint: "The 2D truss precheck found a blocking issue and already prepared a safe first repair.",
    assistantEnterImmersive: "Open immersive 3D viewport",
    assistantEnterImmersiveHint: "Switch the 3D study into fullscreen editing when you want more room for picking and navigation.",
    assistantOpenSample: "Open the official sample for this study",
    assistantOpenSampleHint: "If you are still learning this study family, start with the closest official sample before editing your own model.",
    assistantReviewControls: "Review supports, loads, and materials",
    assistantReviewControlsHint: "Before the first run, check the study controls and confirm the basic physical story makes sense.",
    assistantReviewReport: "Review the current result report",
    assistantReviewReportHint: "Open the report first, then read hotspots, summary metrics, and result-field meaning before changing the model.",
    assistantExportResult: "Export the current result data",
    assistantExportResultHint: "Export CSV once the result looks plausible so you have a stable trail for comparison and review.",
    assistantPromptExplain: "Explain this study to a beginner",
    assistantPromptMaterial: "Help me choose starter material values",
    assistantPromptBoundary: "Help me choose supports and loads",
    assistantPromptResults: "Help me read these result fields",
    assistantLauncherHint: "Need a guide?",
    assistantFloatingTitle: "Ask the workbench",
    assistantFloatingSubtitle: "Keep the main workspace clear, then pull a guide in only when you need one.",
    assistantOpen: "Open assistant",
    assistantClose: "Close assistant",
    backend: "Backend",
    protocols: "Protocols",
    controlPlaneProtocol: "Control plane",
    solverRpcProtocol: "Solver RPC",
    deploymentMode: "Deployment mode",
    discoveryMode: "Discovery",
    registeredAgents: "Registered agents",
    reachableAgents: "Reachable agents",
    runtimeMode: "Runtime mode",
    cluster: "Cluster",
    clusterSize: "Cluster size",
    clusterHealth: "Cluster health",
    peers: "Peers",
    peerState: "Peer state",
    headless: "Headless",
    capabilities: "Capabilities",
    methods: "Methods",
    protocolAgents: "Protocol agents",
    noProtocolAgents: "No reachable solver agents were described yet.",
    watchdog: "Watchdog",
    activeJobs: "Active jobs",
    stalledJobs: "Stalled jobs",
    timedOutJobs: "Timed out jobs",
    scanEvery: "Scan every",
    staleAfter: "Stall limit",
    timeoutAfter: "Timeout limit",
    dataAdmin: "Data Admin",
    orchestrator: "Elixir orchestrator",
    solverAgent: "Rust solver agent",
    ui: "Next.js UI",
    theme: "Theme",
    language: "Language",
    languagePacksTitle: "Installed language packs",
    languagePacksHint: "Import local JSON packs now, and keep this page ready for future remote pack delivery.",
    languagePacksEmptyLabel: "No custom language packs are installed yet.",
    languagePackName: "Name",
    languagePackVersion: "Version",
    languagePackSourceImported: "Imported",
    languagePackSourceDownloaded: "Downloaded",
    languagePackDownloadTemplate: "Download template",
    languagePackExportInstalled: "Export installed pack",
    languagePackImport: "Import pack",
    languagePackRemove: "Remove",
    languagePackCatalogTitle: "Future catalog",
    languagePackCatalogHint: "These slots stay visible now so future remote pack download can plug into the same surface.",
    languagePackCatalogAction: "Coming soon",
    frontendMode: "Frontend mode",
    directMeshEndpoints: "Direct mesh endpoints",
    directMeshEndpointsHelp: "Comma or newline separated host:port agents for the LAN mesh GUI path.",
    directMeshCompleted: "Direct mesh solve completed",
    directMeshStrategy: "Mesh strategy",
    directMeshLastRoute: "Last route",
    directMeshLastAgent: "Last agent",
    shortcutHints: "Shortcut hints",
    shortcutHintsHelp: "Show the 3D keyboard legend in the viewport.",
    immersiveGuard: "Immersive guard",
    immersiveGuardHelp: "In immersive view, block text selection, context menu, and common copy shortcuts.",
    enterImmersive: "Immersive",
    exitImmersive: "Exit immersive",
    immersiveModeEnabled: "Immersive viewport enabled.",
    immersiveModeDisabled: "Immersive viewport closed.",
    browserLimitsNote: "Browser extensions cannot be fully disabled from the page, but the viewport can reduce selection and copy interactions.",
    controlPlaneTokenHelp:
      "Used for token-protected control-plane deployments; sent as x-kyuubiki-token to /api/v1 requests.",
    controlPlaneTokenPlaceholder: "Optional control-plane token",
    clusterTokenHelp:
      "Used for agent register/heartbeat/remove cluster routes; falls back to the control-plane token when empty.",
    clusterTokenPlaceholder: "Optional cluster-only token",
    directMeshTokenHelp:
      "Used for token-protected direct mesh routes; sent to /api/direct-mesh requests.",
    directMeshTokenPlaceholder: "Optional direct-mesh token",
    exportDatabase: "Export database snapshot",
    runtimeSecurityFooter:
      "Runtime security state comes from /api/health; frontend tokens stay only in the current browser session.",
    securityAudit: "Security audit",
    auditSessionLabel:
      "Shows the control-plane persisted automation and assistant event stream, including Workbench assistant, scripting, and Hub assistant actions.",
    auditWindow: "Window",
    auditSource: "Source",
    auditRisk: "Risk",
    auditStatus: "Status",
    auditAction: "Action",
    auditSummaryTitle: "Event summary",
    auditTrendTitle: "Event trend",
    auditTrendEmptyLabel: "No trend data is available for the current window.",
    auditSourceStatusTitle: "Source × status",
    auditStudyFacetTitle: "Study facets",
    auditProjectFacetTitle: "Project facets",
    auditModelVersionFacetTitle: "Version facets",
    auditFacetEmptyLabel: "No facets are available for the current window.",
    auditRefreshLabel: "Refresh events",
    auditExportLabel: "Export bundle",
    auditExportCsvLabel: "Export CSV",
    auditWindowOptions: { all: "All time", h1: "Last 1 hour", h24: "Last 24 hours", d7: "Last 7 days", d30: "Last 30 days" },
    auditSourceOptions: { all: "All", assistant: "Assistant", hubAssistant: "Hub assistant", script: "Script" },
    auditRiskOptions: { all: "All", low: "Low", sensitive: "Sensitive", high: "High", destructive: "Destructive" },
    auditStatusOptions: { all: "All", prompted: "Prompted", confirmed: "Confirmed", cancelled: "Cancelled", completed: "Completed", failed: "Failed" },
    adminJobs: "Jobs",
    adminResults: "Results",
    adminBrowsePage: "Browse",
    adminEditPage: "Edit",
    selectRecord: "Select a record to inspect or edit.",
    adminMessage: "Message",
    adminProjectId: "Project ID",
    adminModelVersionId: "Model version",
    adminCaseId: "Simulation case",
    saveRecord: "Save record",
    deleteRecord: "Delete record",
    exportRecord: "Export record",
    applyRecordContext: "Apply record context",
    openLinkedProject: "Open linked project",
    openLinkedVersion: "Open linked version",
    filterProject: "Filter project",
    filterVersion: "Filter version",
    useCurrentProject: "Use current project",
    useCurrentVersion: "Use current version",
    clearFilters: "Clear filters",
    resultPayload: "Result JSON",
    resultSaved: "Result record updated.",
    resultDeleted: "Result record deleted.",
    jobSaved: "Job record updated.",
    jobDeleted: "Job record deleted.",
    recordContextApplied: "Applied the record context to the workbench.",
    linkedProjectOpened: "Opened the linked project context.",
    invalidJson: "Invalid JSON payload.",
    databaseRecordCount: "Records",
    immersiveStudy: "Study",
    immersiveModel: "Model",
    immersiveLibrary: "Library",
    immersiveTools: "Tools",
    immersiveHelp: "3D Help",
    immersiveViewTools: "View tools",
    immersiveNodeOps: "Node ops",
    immersiveMemberOps: "Member ops",
    immersiveQuickProps: "Quick properties",
    immersiveNodeSelection: "Selected nodes",
    immersiveNoNodeSelection: "Select a 3D node to edit its coordinates, supports, and loads.",
    immersiveTransform: "Transform",
    immersiveLoads: "Batch loads",
    immersiveUtilities: "Utilities",
    frameSelection: "Frame selection",
    duplicateNodes: "Duplicate",
    mirrorX: "Mirror X",
    mirrorY: "Mirror Y",
    mirrorZ: "Mirror Z",
    applyLoads: "Apply loads",
    clearLoads: "Clear loads",
    nudgeStep: "Nudge step",
    immersiveDrawer: "Immersive drawer",
    close: "Close",
    immersiveSamples: "Samples",
    immersiveModels: "Saved",
    immersiveJobs: "Recent jobs",
    immersiveEmptyModels: "No saved models in this project yet.",
    immersiveEmptyJobs: "No jobs yet.",

} as const;
