export const workbenchScriptPanelCopyFa = {
  title: "Pwdt",
  subtitle: "ابزارهای زبان Python WASM DSL با پشتیبانی Pyodide و فهرست کنش‌های ثبت‌شدهٔ مرورگر.",
  frontendSurface: "خودکارسازی رابط کاربری",
  frontendSurfaceHint: "این بخش برای خودکارسازی در مرورگر، ضبط و بازپخش ماکرو و اشکال‌زدایی رابط کاربری است.",
  headlessSurface: "SDK بدون رابط گرافیکی",
  headlessSurfaceHint: "پنل زیر سازندهٔ مستقلی برای گردش‌کار بدون رابط گرافیکی و خودکارسازی سرویس‌ها و حلگرهاست.",
  launch: "راه‌اندازی",
  author: "ویرایش",
  inspect: "بررسی",
  catalog: "فهرست",
  scriptMode: "اسکریپت",
  recordMode: "ضبط",
  outputMode: "خروجی",
  timelineMode: "خط زمانی",
  snapshotMode: "تصویر لحظه‌ای",
  presetsMode: "پیش‌تنظیم‌ها",
  actionsMode: "کنش‌ها",
  macrosMode: "ماکروها",
  authorScriptHint: "اسکریپت‌های خودکارسازی رابط کاربری را مستقیماً در اینجا بنویسید یا ویرایش کنید.",
  authorRecordHint: "کنش‌های رابط کاربری را ضبط کنید، کنش‌های اخیر را به پیش‌نویس ماکرو تبدیل کنید و دوباره در اسکریپت درج کنید.",
  inspectOutputHint: "خروجی اجرا و پیام‌های محیط اجرا در اینجا نمایش داده می‌شوند.",
  inspectTimelineHint: "کنش‌های اخیر رابط کاربری به‌صورت خط زمانی قابل بازپخش نمایش داده می‌شوند.",
  inspectSnapshotHint: "وضعیت زندهٔ میز کار به اسکریپت‌ها امکان بررسی و اشکال‌زدایی زمینهٔ رابط کاربری را می‌دهد.",
  inspectTimelineDetailHint: "یک کنش را انتخاب کنید تا داده‌های ارسالی، نتیجه و زمینهٔ بازپخش آن را با جزئیات بررسی کنید.",
  insertActionStep: "درج گام",
  insertTimelineMacroDraft: "درج پیش‌نویس ماکرو",
  sendTimelineMacroToHeadless: "ارسال به گردش‌کار",
  saveTimelineMacroPreset: "ذخیره به‌عنوان پیش‌تنظیم",
  noTimelineSelection: "یک کنش از خط زمانی را برای بررسی جزئیات کامل آن انتخاب کنید.",
  timelineFailed: "ناموفق",
  timelineCompleted: "تکمیل‌شده",
  timelineStarted: "آغازشده",
  failureReason: "دلیل شکست",
  continueFromStep: "ادامه از اینجا",
  timelineRangePreview: "پیش‌نمایش بازه",
  timelinePreviewSteps: "گام‌های خط زمانی",
  timelinePreviewMacroSteps: "گام‌های ماکرو",
  timelinePreviewIncluded: "گنجانده‌شده",
  timelinePreviewIncludedYes: "بله",
  timelinePreviewIncludedNo: "خیر",
  timelinePreviewNotEligible: "فقط برای زمینه",
  includeTimelineStep: "گنجاندن",
  excludeTimelineStep: "کنار گذاشتن",
  selectAllTimelineSteps: "انتخاب همه",
  clearTimelineSteps: "پاک کردن انتخاب",
  focusFailureWindow: "تمرکز بر شکست‌ها",
  timelineMacroDraftInserted: "پیش‌نویس ماکرو از بازهٔ انتخاب‌شدهٔ خط زمانی درج شد.",
  noTimelineMacroDraft: "این بازهٔ خط زمانی هنوز گام اجرایی قابل استفادهٔ مجدد ندارد.",
  timelineMacroPresetSaved: "بازهٔ انتخاب‌شدهٔ خط زمانی به‌عنوان پیش‌تنظیم پروژه ذخیره شد.",
  restoreBridgeMacroToFrontend: "گرهٔ پل ارتباطی به بخش خودکارسازی رابط کاربری بازگردانده شد.",
  frontendMacroAssetInserted: "دارایی ماکروی رابط کاربری دوباره در ویرایشگر بارگذاری شد.",
  frontendMacroAssetDerived: "پیش‌نویس ماکروی قابل ویرایش تازه‌ای از تصویر لحظه‌ای انتخاب‌شده ساخته شد.",
  frontendMacroAssets: "دارایی‌های ماکروی رابط کاربری",
  frontendMacroAssetsEmpty: "هنوز هیچ دارایی ماکروی رابط کاربری آماده نشده است.",
  deriveFrontendMacroAsset: "ساخت پیش‌نویس مشتق‌شده",
  snapshotCompare: "مقایسهٔ تصاویر لحظه‌ای",
  snapshotCompareEmpty: "دو تصویر لحظه‌ای را برای مقایسهٔ گام‌ها و تغییرات داده‌های ارسالی انتخاب کنید.",
  snapshotCompareChangedSteps: "گام‌های تغییرکرده",
  snapshotCompareSame: "یکسان",
  snapshotCompareChanged: "تغییرکرده",
  snapshotCompareMissing: "موجود نیست",
  snapshotCompareStepMissing: "این تصویر لحظه‌ای چنین گامی ندارد",
  snapshotComparePayloadChanged: "داده‌های ارسالی در این گام تغییر کرده‌اند.",
  snapshotCompareActionChanged: "شناسهٔ کنش در این گام تغییر کرده است.",
  compareLeftAsset: "قرار دادن در سمت چپ",
  compareRightAsset: "قرار دادن در سمت راست",
  clearCompareLeft: "پاک کردن سمت چپ",
  clearCompareRight: "پاک کردن سمت راست",
  assetSnapshotId: "شناسهٔ تصویر لحظه‌ای",
  assetSource: "منبع",
  assetUpdatedAt: "آخرین به‌روزرسانی",
  assetSourceTimeline: "انتخاب از خط زمانی",
  assetSourceBridge: "بازیابی از پل ارتباطی",
  assetSourceDerived: "مشتق‌شده از تاریخچه",
  catalogHint: "دارایی‌های قابل استفادهٔ مجدد خودکارسازی رابط کاربری در اینجا هستند: پیش‌تنظیم‌های پروژه، قطعه‌کدهای کنش و ماکروها.",
  runtime: "محیط اجرا",
  loading: "در حال بارگذاری",
  ready: "آماده",
  idle: "بیکار",
  running: "در حال اجرا",
  error: "خطا",
  sessionStorageFailed: "نشست ویرایشگر ذخیره نشد. داده‌های اسکریپت موجود بدون تغییر باقی ماندند.",
  firstRun: "در اجرای نخست، محیط اجرای Pyodide در حافظهٔ نهان مرورگر بارگیری می‌شود.",
  loadRuntime: "بارگذاری محیط اجرا",
  resetScript: "بازنشانی الگو",
  runScript: "اجرای اسکریپت",
  clearOutput: "پاک کردن خروجی",
  startRecording: "شروع ضبط",
  stopRecording: "توقف ضبط",
  recordingActive: "کنش‌های دستی رابط کاربری در جریان رویدادهای DSL ضبط می‌شوند.",
  exportMacroJson: "برون‌بری ماکرو به JSON",
  importMacroJson: "درون‌ریزی ماکرو از JSON",
  macroJsonExported: "ماکروی ضبط‌شدهٔ فعلی به قالب JSON صادر شد.",
  macroJsonImported: "پیش‌نویس ماکرو از JSON به ویرایشگر وارد شد.",
  headlessWorkflowImported: "قرارداد گردش‌کار بدون رابط گرافیکی به‌صورت پیش‌نویس ماکروی قابل اجرا وارد ویرایشگر شد.",
  projectPresets: "پیش‌تنظیم‌های پروژه",
  presetName: "نام پیش‌تنظیم",
  presetNamePlaceholder: "بررسی زمینهٔ نتیجهٔ فعلی",
  savePreset: "ذخیرهٔ پیش‌تنظیم",
  insertPreset: "درج پیش‌تنظیم",
  exportPresetJson: "برون‌بری پیش‌تنظیم به JSON",
  deletePreset: "حذف پیش‌تنظیم",
  noProjectSelected: "ابتدا یک پروژه را انتخاب کنید تا پیش‌تنظیم‌ها در زمینهٔ آن ذخیره شوند.",
  noPresetDraft: "ابتدا پیش‌نویس ماکرو بسازید یا وارد کنید تا بتوان آن را به‌عنوان پیش‌تنظیم ذخیره کرد.",
  noPresets: "هنوز پیش‌تنظیمی برای پروژهٔ فعلی ذخیره نشده است.",
  presetSaved: "پیش‌نویس ماکروی فعلی در پیش‌تنظیم‌های پروژه ذخیره شد.",
  presetDeleted: "پیش‌تنظیم انتخاب‌شدهٔ پروژه حذف شد.",
  presetInserted: "پیش‌تنظیم انتخاب‌شدهٔ پروژه در ویرایشگر درج شد.",
  sensitivePresetRejected: "ذخیرهٔ پیش‌تنظیم مسدود شد، زیرا شامل فیلدهای حساسی است که نباید به‌صورت محلی ذخیره شوند.",
  sensitivePresetRejectedDetails: "این فیلدها را بررسی کنید و توکن‌ها، کوکی‌ها، سرآیندهای مجوز و اسرار را از پیش‌تنظیم‌های ذخیره‌شده کنار بگذارید:",
  snapshot: "تصویر لحظه‌ای",
  actionCatalog: "فهرست کنش‌ها",
  macroCatalog: "فهرست ماکروها",
  editor: "اسکریپت Python",
  output: "خروجی",
  noOutput: "خروجی اسکریپت در اینجا نمایش داده می‌شود.",
  lineCount: "خط‌ها",
  stateKeys: "فیلدهای وضعیت",
  actionCount: "کنش‌ها",
  payload: "داده‌های ارسالی",
  actionLog: "گزارش کنش‌ها",
  noActionLog: "هنوز کنشی با اسکریپت اجرا نشده است.",
  insertMacroDraft: "درج پیش‌نویس ماکرو",
  macroDraftInserted: "پیش‌نویس ماکرو از گزارش کنش‌های اخیر درج شد.",
  noMacroDraftSource: "ابتدا چند کنش اجرا کنید تا پنل بتواند پیش‌نویس ماکرو بسازد.",
  actionSource: "منبع",
  actionPayload: "داده‌های ارسالی",
  actionResult: "نتیجه",
  actionNote: "یادداشت",
  riskNormal: "عادی",
  riskSensitive: "حساس",
  riskDestructive: "مخرب",
  confirmationRequired: "پیش از اجرا به تأیید نیاز دارد.",
  insertLabel: "درج",
  stepsLabel: "گام‌ها",
  macroPayloadHint: "این ماکرو از پارامترهای الگو بر پایهٔ داده‌های ارسالی پشتیبانی می‌کند.",
  categories: {
    navigation: "ناوبری",
    settings: "تنظیمات",
    runtime: "محیط اجرا",
    project: "پروژه",
    model: "مدل",
    state: "وضعیت",
    selection: "انتخاب",
    job: "کار",
    history: "تاریخچه",
    viewport: "نمای دید",
    data: "داده‌ها",
    macro: "ماکرو",
  },
} as const;
