"use client";

import { useWorkbenchEditControllers } from "@/components/workbench/workbench-edit-controllers";
import { useWorkbenchFlowControllers } from "@/components/workbench/workbench-flow-controllers";
import { buildWorkbenchFlowComposition } from "@/components/workbench/workbench-flow-composition";
import { buildWorkbenchMainShellComposition } from "@/components/workbench/workbench-main-shell-composition";
import { buildWorkbenchModelContent } from "@/components/workbench/workbench-model-content";
import { buildWorkbenchModelContentComposition } from "@/components/workbench/workbench-model-content-composition";
import { useWorkbenchInteractionControllers } from "@/components/workbench/workbench-interaction-controllers";
import { buildWorkbenchSidebarComposition } from "@/components/workbench/workbench-sidebar-composition";
import {
  buildWorkbenchMainShellSummaryProps,
  buildWorkbenchWorkflowLabels,
} from "@/components/workbench/workbench-shell-copy-composition";
import { applyStudyKindSelection } from "@/components/workbench/workbench-study-kind-controller";
import { useWorkbenchStudyShellController } from "@/components/workbench/workbench-study-shell-controller";

export function useWorkbenchMainComposition(props: Record<string, any>) {
  const {
    createProjectRecord,
    deleteProjectRecord,
    deleteSavedModelRecord,
    deleteSelectedVersion,
    downloadDatabaseSnapshot,
    downloadProjectBundleJson,
    downloadProjectBundleZip,
    importProjectBundle,
    openModelVersionById,
    openSavedModel,
    openSavedVersion,
    renameSelectedVersion,
    saveModelVersion,
    updateProjectRecord,
  } = props.projectStorageController;

  const editControllers = useWorkbenchEditControllers({
    t: props.t,
    language: props.language,
    activeMaterial: props.activeMaterial,
    setHiddenMaterials: props.setHiddenMaterials,
    setMessage: props.setMessage,
    studyKind: props.studyKind,
    activeFrameLikeModel: props.activeFrameLikeModel,
    isFrameLike: props.isFrameLike,
    isHeatPlane: props.isHeatPlane,
    isThermalFrame: props.isThermalFrame,
    isThermalTruss2d: props.isThermalTruss2d,
    isThermalTruss3d: props.isThermalTruss3d,
    memberDraftNodes: props.memberDraftNodes,
    parametric: props.parametric,
    recordHistory: props.recordHistory,
    resetResults: props.resetResults,
    round: props.round,
    selectedElement: props.selectedElement,
    selectedNode: props.selectedNode,
    selectedTruss3dNodes: props.selectedTruss3dNodes,
    setFrameModel: props.setFrameModel,
    setHeatPlaneModel: props.setHeatPlaneModel,
    setMemberDraftNodes: props.setMemberDraftNodes,
    setPlaneModel: props.setPlaneModel,
    setSelectedElement: props.setSelectedElement,
    setSelectedNode: props.setSelectedNode,
    setSelectedTruss3dNodes: props.setSelectedTruss3dNodes,
    setSidebarSection: props.setSidebarSection,
    setStudyKind: props.setStudyKind,
    setThermalFrameModel: props.setThermalFrameModel,
    setThermalTruss3dModel: props.setThermalTruss3dModel,
    setThermalTrussModel: props.setThermalTrussModel,
    setTruss3dModel: props.setTruss3dModel,
    setTrussModel: props.setTrussModel,
    truss3dBatchLoadX: props.truss3dBatchLoadX,
    truss3dBatchLoadY: props.truss3dBatchLoadY,
    truss3dBatchLoadZ: props.truss3dBatchLoadZ,
    truss3dModel: props.truss3dModel,
    trussModel: props.trussModel,
    isBeam: props.isBeam,
    isTorsion: props.isTorsion,
    isHeatBar: props.isHeatBar,
    isThermal: props.isThermal,
    isThermalBar: props.isThermalBar,
    truss3dLinkMode: props.truss3dLinkMode,
    trussBounds: props.trussBounds,
    draggingNode: props.draggingNode,
    dragHistoryCapturedRef: props.dragHistoryCapturedRef,
    dragFrameRef: props.dragFrameRef,
    pendingDragPointRef: props.pendingDragPointRef,
    setTruss3dLinkMode: props.setTruss3dLinkMode,
    setDraggingNode: props.setDraggingNode,
    setActiveMaterial: props.setActiveMaterial,
    setAxialForm: props.setAxialForm,
    setParametric: props.setParametric,
    setTorsionModel: props.setTorsionModel,
    setHeatBarModel: props.setHeatBarModel,
    setBeamModel: props.setBeamModel,
  });

  const interactionControllers = useWorkbenchInteractionControllers({
    activeLanguagePack: props.activeLanguagePack,
    activeMaterial: props.activeMaterial,
    adminFilterModelVersionId: props.adminFilterModelVersionId,
    adminFilterProjectId: props.adminFilterProjectId,
    frontendRuntimeMode: props.frontendRuntimeMode,
    health: props.health,
    heatBarModel: props.heatBarModel,
    heatPlaneModel: props.heatPlaneModel,
    immersiveHelpDrawerOpen: props.immersiveHelpDrawerOpen,
    immersiveToolDrawerOpen: props.immersiveToolDrawerOpen,
    immersiveViewport: props.immersiveViewport,
    job: props.job,
    jobHistory: props.jobHistory,
    language: props.language,
    libraryTab: props.libraryTab,
    loadedModelName: props.loadedModelName,
    memberDraftNodes: props.memberDraftNodes,
    modelTab: props.modelTab,
    panelParametric: props.panelParametric,
    planeModel: props.planeModel,
    projects: props.projects,
    protocolAgents: props.protocolAgents,
    redoStack: props.redoStack,
    resultRecords: props.resultRecords,
    selectedAdminJobId: props.selectedAdminJobId,
    selectedAdminResultJobId: props.selectedAdminResultJobId,
    selectedElement: props.selectedElement,
    selectedModelId: props.selectedModelId,
    selectedNode: props.selectedNode,
    selectedProjectId: props.selectedProjectId,
    selectedTruss3dNodes: props.selectedTruss3dNodes,
    selectedVersionId: props.selectedVersionId,
    setActiveMaterial: props.setActiveMaterial,
    setAxialForm: props.setAxialForm,
    setBeamModel: props.setBeamModel,
    setHeatBarModel: props.setHeatBarModel,
    setHeatPlaneModel: props.setHeatPlaneModel,
    setLanguagePacks: props.setLanguagePacks,
    setLoadedModelName: props.setLoadedModelName,
    setMemberDraftNodes: props.setMemberDraftNodes,
    setMessage: props.setMessage,
    setPlaneModel: props.setPlaneModel,
    setSidebarSection: props.setSidebarSection,
    setSpring2dModel: props.setSpring2dModel,
    setSpring3dModel: props.setSpring3dModel,
    setSpringModel: props.setSpringModel,
    setStudyKind: props.setStudyKind,
    setStudyTab: props.setStudyTab,
    setThermalBarModel: props.setThermalBarModel,
    setThermalBeamModel: props.setThermalBeamModel,
    setThermalFrameModel: props.setThermalFrameModel,
    setThermalTrussModel: props.setThermalTrussModel,
    setThermalTruss3dModel: props.setThermalTruss3dModel,
    setTorsionModel: props.setTorsionModel,
    setTruss3dModel: props.setTruss3dModel,
    setTrussModel: props.setTrussModel,
    sidebarSection: props.sidebarSection,
    spring2dModel: props.spring2dModel,
    spring3dModel: props.spring3dModel,
    springModel: props.springModel,
    studyKind: props.studyKind,
    studyTab: props.studyTab,
    systemDataTab: props.systemDataTab,
    systemPanelTab: props.systemPanelTab,
    t: props.t,
    theme: props.theme,
    thermalBarModel: props.thermalBarModel,
    thermalBeamModel: props.thermalBeamModel,
    thermalFrameModel: props.thermalFrameModel,
    thermalTrussModel: props.thermalTrussModel,
    thermalTruss3dModel: props.thermalTruss3dModel,
    torsionModel: props.torsionModel,
    truss3dBoxSelectMode: props.truss3dBoxSelectMode,
    truss3dLinkMode: props.truss3dLinkMode,
    truss3dModel: props.truss3dModel,
    truss3dProjectionMode: props.truss3dProjectionMode,
    truss3dViewPreset: props.truss3dViewPreset,
    trussModel: props.trussModel,
    undoStack: props.undoStack,
    viewportPanelRef: props.viewportPanelRef,
    workflowCatalog: props.workflowController.workflowCatalog,
    workflowCatalogBusy: props.workflowController.workflowCatalogBusy,
    setUndoStack: props.setUndoStack,
    setRedoStack: props.setRedoStack,
    setAssistantWindowOpen: props.setAssistantWindowOpen,
    setTheme: props.setTheme,
    setFrontendRuntimeMode: props.setFrontendRuntimeMode,
    setDirectMeshEndpointsText: props.setDirectMeshEndpointsText,
    setDirectMeshSelectionMode: props.setDirectMeshSelectionMode,
    setLibraryTab: props.setLibraryTab,
    setModelTab: props.setModelTab,
    setModelToolsPage: props.setModelToolsPage,
    setWorkflowPanelTab: props.workflowController.setWorkflowPanelTab,
    setSystemPanelTab: props.setSystemPanelTab,
    setSystemDataTab: props.setSystemDataTab,
    setAdminFilterProjectId: props.setAdminFilterProjectId,
    setAdminFilterModelVersionId: props.setAdminFilterModelVersionId,
    setSelectedAdminJobId: props.setSelectedAdminJobId,
    setSelectedAdminResultJobId: props.setSelectedAdminResultJobId,
    setTruss3dViewPreset: props.setTruss3dViewPreset,
    setTruss3dProjectionMode: props.setTruss3dProjectionMode,
    setTruss3dBoxSelectMode: props.setTruss3dBoxSelectMode,
    setTruss3dShowGrid: props.setTruss3dShowGrid,
    setTruss3dShowLabels: props.setTruss3dShowLabels,
    setTruss3dShowNodes: props.setTruss3dShowNodes,
    setImmersiveToolDrawerOpen: props.setImmersiveToolDrawerOpen,
    setImmersiveHelpDrawerOpen: props.setImmersiveHelpDrawerOpen,
    setTruss3dFocusRequestVersion: props.setTruss3dFocusRequestVersion,
    setTruss3dResetRequestVersion: props.setTruss3dResetRequestVersion,
    refreshWorkflowCatalog: props.workflowController.refreshWorkflowCatalog,
    toggleTruss3dLinkMode: editControllers.toggleTruss3dLinkMode,
    resetActiveResult: props.resetActiveResult,
  });
  const {
    topLevelActions,
    assistantAudit,
    uiActionController,
    toggleImmersiveViewport,
  } = interactionControllers;

  function recordHistory(action: string) {
    topLevelActions.recordHistory(action);
  }

  const selectStudyKind = (nextStudyKind: typeof props.studyKind) => {
    recordHistory(props.t.changeStudyType);
    applyStudyKindSelection({
      currentStudyKind: props.studyKind,
      nextStudyKind,
      setStudyKind: props.setStudyKind,
      resetHandlers: studyKindResetHandlers,
    });
  };

  function openWorkspaceStudy(tab = "controls") {
    props.setSidebarSection("model");
    props.setModelTab("tools");
    props.setModelToolsPage("study");
    props.setStudyTab(tab);
  }

  const {
    canProjectHeatToThermo,
    currentStudyFamilyHint,
    currentStudyFamilyLabel,
    handleLanguageChange,
    projectHeatToThermoStudy,
    studyControlsRows,
    studyDomainOptions,
    studyKindOptionGroups,
    studyKindResetHandlers,
    studySummaryRows,
    thermalBoundaryValue,
    thermalIntentValue,
    truss3dTreeRows,
  } = useWorkbenchStudyShellController({
    t: props.t,
    shellState: props.shellState,
    workspaceState: props.workspaceState,
    studyResultDerived: props.studyResultDerived,
    localMaterialLabel: props.localMaterialLabel,
    fixed: props.fixed,
    ensurePlaneModelMaterials: props.ensurePlaneModelMaterials,
    ensureBeamModelMaterials: props.ensureBeamModelMaterials,
    ensureFrameModelMaterials: props.ensureFrameModelMaterials,
    defaultPlaneQuad: props.defaultPlaneQuad,
    defaultThermalPlaneQuad: props.defaultThermalPlaneQuad,
    defaultPlaneTriangle: props.defaultPlaneTriangle,
    defaultThermalPlaneTriangle: props.defaultThermalPlaneTriangle,
    defaultHeatBar1d: props.defaultHeatBar1d,
    defaultHeatPlaneQuad: props.defaultHeatPlaneQuad,
    defaultHeatPlaneTriangle: props.defaultHeatPlaneTriangle,
    defaultThermalBar1d: props.defaultThermalBar1d,
    defaultThermalBeam1d: props.defaultThermalBeam1d,
    defaultThermalFrame2d: props.defaultThermalFrame2d,
    defaultThermalTruss2d: props.defaultThermalTruss2d,
    defaultThermalTruss3d: props.defaultThermalTruss3d,
    defaultSpring1d: props.defaultSpring1d,
    defaultSpring2d: props.defaultSpring2d,
    defaultSpring3d: props.defaultSpring3d,
    defaultBeam1d: props.defaultBeam1d,
    defaultTorsion1d: props.defaultTorsion1d,
    defaultFrame2d: props.defaultFrame2d,
    round: props.round,
    recordHistory,
    resetActiveResult: props.resetActiveResult,
    buildThermalBarFromHeatResult: props.buildThermalBarFromHeatResult,
    buildThermalPlaneTriangleFromHeatResult: props.buildThermalPlaneTriangleFromHeatResult,
    buildThermalPlaneQuadFromHeatResult: props.buildThermalPlaneQuadFromHeatResult,
    openWorkspaceStudy,
  });

  const handleModelToolsPageChange = (page: any) => {
    uiActionController.handleModelToolsPageChange(page, props.modelTab);
  };

  const flowControllers = useWorkbenchFlowControllers(
    buildWorkbenchFlowComposition({
      t: props.t,
      shellState: props.shellState,
      workspaceState: props.workspaceState,
      studyResultDerived: props.studyResultDerived,
      interactionControllers,
      projectFlows: props.projectFlows,
      workflowController: props.workflowController,
      recordHistory,
      startTransition: props.startTransition,
      resultRefreshSeqRef: props.resultRefreshSeqRef,
      fetchResults: props.fetchResults,
      setSelectedAdminResultJobId: props.setSelectedAdminResultJobId,
      jobPollTokenRef: props.jobPollTokenRef,
      refreshJobHistory: props.refreshJobHistory,
      fetchJobStatus: props.fetchJobStatus,
      updateJobRecord: props.updateJobRecord,
      deleteJobRecord: props.deleteJobRecord,
      updateResultRecord: props.updateResultRecord,
      deleteResultRecord: props.deleteResultRecord,
      downloadTextFile: props.downloadTextFile,
      health: props.health,
      jobIsActive: props.jobIsActive,
      cancelCurrentJob: props.cancelCurrentJob,
      refreshHealth: props.refreshHealth,
      refreshResults: props.refreshResults,
      refreshProjects: props.refreshProjects,
      refreshSecurityEvents: props.refreshSecurityEvents,
      refreshVersions: props.refreshVersions,
      createProject: props.createProject,
      updateProject: props.updateProject,
      deleteProject: props.deleteProject,
      createModel: props.createModel,
      updateModel: props.updateModel,
      deleteModel: props.deleteModel,
      createModelVersion: props.createModelVersion,
      updateModelVersion: props.updateModelVersion,
      deleteModelVersion: props.deleteModelVersion,
      handleLanguageChange,
      studyKindResetHandlers,
      ensureFrameModelMaterials: props.ensureFrameModelMaterials,
      ensureBeamModelMaterials: props.ensureBeamModelMaterials,
      resolveTruss2dJobInput: props.resolveTruss2dJobInput,
      resolveTruss3dJobInput: props.resolveTruss3dJobInput,
      resolvePlaneQuad2dJobInput: props.resolvePlaneQuad2dJobInput,
      resolvePlaneTriangle2dJobInput: props.resolvePlaneTriangle2dJobInput,
      projectHeatToThermoStudy,
      setAdminFilterProjectId: props.setAdminFilterProjectId,
      setAdminFilterModelVersionId: props.setAdminFilterModelVersionId,
      setSelectedAdminJobId: props.setSelectedAdminJobId,
      downloadDatabaseSnapshot,
      round: props.round,
      applyTrussSuggestion: editControllers.applyTrussSuggestion,
      downloadResultCsv: props.downloadResultCsv,
    }),
  );
  const { primaryActionsController, assistantController } = flowControllers;

  const {
    studyControlsContent,
    modelStudyContent,
    modelStudioContent,
    modelMaterialsContent,
    modelGenerateContent,
    modelTreeContent,
  } = buildWorkbenchModelContent(
    buildWorkbenchModelContentComposition({
      t: props.t,
      shellState: props.shellState,
      workspaceState: props.workspaceState,
      studyResultDerived: props.studyResultDerived,
      editControllers,
      primaryActionsController,
      studyDomainOptions,
      studyKindOptionGroups,
      selectStudyKind,
      studyControlsRows,
      isPending: props.isPending,
      currentStudyFamilyHint,
      currentStudyFamilyLabel,
      truss3dTreeRows,
      handleUndo: topLevelActions.handleUndo,
      handleRedo: topLevelActions.handleRedo,
      round: props.round,
      localMaterialLabel: props.localMaterialLabel,
    }),
  );

  const sidebarMountProps = buildWorkbenchSidebarComposition({
    t: props.t,
    shellState: props.shellState,
    workspaceState: props.workspaceState,
    studyResultDerived: props.studyResultDerived,
    interactionControllers,
    flowControllers,
    workflowController: props.workflowController,
    railItems: props.railItems,
    studyDomainOptions,
    studyKindOptionGroups,
    selectStudyKind,
    studySummaryRows,
    studyControlsRows,
    studyControlsContent,
    isPending: props.isPending,
    modelStudyContent,
    modelStudioContent,
    modelMaterialsContent,
    modelGenerateContent,
    modelTreeContent,
    workflowLabels: buildWorkbenchWorkflowLabels(props.t),
    createProjectRecord,
    updateProjectRecord,
    deleteProjectRecord,
    downloadProjectBundleJson,
    downloadProjectBundleZip,
    importProjectBundle,
    selectedProjectModels: props.selectedProjectModels,
    saveModelVersion,
    deleteSavedModelRecord,
    openSavedModel,
    renameSelectedVersion,
    deleteSelectedVersion,
    openSavedVersion,
    refreshJobHistory: props.refreshJobHistory,
    refreshProjects: props.refreshProjects,
    health: props.health,
    securityEventRecords: props.securityEventRecords,
    securityEventWindowFilter: props.securityEventWindowFilter,
    securityEventSourceFilter: props.securityEventSourceFilter,
    securityEventRiskFilter: props.securityEventRiskFilter,
    securityEventStatusFilter: props.securityEventStatusFilter,
    securityEventActionFilter: props.securityEventActionFilter,
    setSecurityEventWindowFilter: props.setSecurityEventWindowFilter,
    setSecurityEventSourceFilter: props.setSecurityEventSourceFilter,
    setSecurityEventRiskFilter: props.setSecurityEventRiskFilter,
    setSecurityEventStatusFilter: props.setSecurityEventStatusFilter,
    setSecurityEventActionFilter: props.setSecurityEventActionFilter,
    refreshSecurityEvents: props.refreshSecurityEvents,
    downloadDatabaseSnapshot,
    scriptRecordingMode: props.scriptRecordingMode,
    setScriptRecordingMode: props.setScriptRecordingMode,
    selectedAdminJobId: props.selectedAdminJobId,
    selectedAdminJob: props.selectedAdminJob,
    adminJobMessage: props.adminJobMessage,
    setAdminJobMessage: props.setAdminJobMessage,
    adminJobProjectId: props.adminJobProjectId,
    setAdminJobProjectId: props.setAdminJobProjectId,
    adminJobModelVersionId: props.adminJobModelVersionId,
    setAdminJobModelVersionId: props.setAdminJobModelVersionId,
    adminJobCaseId: props.adminJobCaseId,
    setAdminJobCaseId: props.setAdminJobCaseId,
    saveAdminJobRecord: primaryActionsController.saveAdminJobRecord,
    deleteAdminJobRecord: primaryActionsController.deleteAdminJobRecord,
    selectedAdminResultJobId: props.selectedAdminResultJobId,
    adminResultDraft: props.adminResultDraft,
    setAdminResultDraft: props.setAdminResultDraft,
    saveAdminResultRecord: primaryActionsController.saveAdminResultRecord,
    applySelectedAdminResultContext: primaryActionsController.applySelectedAdminResultContext,
    openSelectedAdminResultProject: primaryActionsController.openSelectedAdminResultProject,
    openSelectedAdminResultVersion: primaryActionsController.openSelectedAdminResultVersion,
    exportAdminResultRecord: primaryActionsController.exportAdminResultRecord,
    deleteAdminResultRecord: primaryActionsController.deleteAdminResultRecord,
    adminFilterProjectId: props.adminFilterProjectId,
    adminFilterModelVersionId: props.adminFilterModelVersionId,
    applySelectedAdminJobContext: primaryActionsController.applySelectedAdminJobContext,
    openSelectedAdminJobProject: primaryActionsController.openSelectedAdminJobProject,
    openSelectedAdminJobVersion: primaryActionsController.openSelectedAdminJobVersion,
    cancelCurrentJob: props.cancelCurrentJob,
    cancelJob: props.cancelJob,
    setMessage: props.setMessage,
  });

  const mainShellMountProps = buildWorkbenchMainShellComposition({
    t: props.t,
    shellState: props.shellState,
    workspaceState: props.workspaceState,
    studyResultDerived: props.studyResultDerived,
    editControllers,
    interactionControllers,
    flowControllers,
    viewportPanelRef: props.viewportPanelRef,
    canvasStageRef: props.canvasStageRef,
    resultWindowMaxTotal: props.resultWindowMaxTotal,
    handleCanvasStageScroll: props.handleCanvasStageScroll,
    openSample: primaryActionsController.openSample,
    openSavedModel,
    openHistoryJob: primaryActionsController.openHistoryJob,
    selectedProjectModels: props.selectedProjectModels,
    currentStudyFamilyLabel,
    currentStudyFamilyHint,
    isPending: props.isPending,
    canProjectHeatToThermo,
    projectHeatToThermoStudy,
    clampChunkOffset: props.clampChunkOffset,
    recordHistory,
    drag3dHistoryCapturedRef: props.drag3dHistoryCapturedRef,
    jobIsActive: props.jobIsActive,
    cancelCurrentJob: props.cancelCurrentJob,
    downloadResultJson: props.downloadResultJson,
    downloadResultCsv: props.downloadResultCsv,
    downloadPlaneHotspotSummary: props.downloadPlaneHotspotSummary,
    downloadFrameHotspotSummary: props.downloadFrameHotspotSummary,
    downloadFrameForceSummary: props.downloadFrameForceSummary,
    ...buildWorkbenchMainShellSummaryProps({
      studyResultDerived: props.studyResultDerived,
      workspaceState: props.workspaceState,
    }),
  });

  return {
    editControllers,
    interactionControllers,
    flowControllers,
    primaryActionsController,
    assistantController,
    topLevelActions,
    assistantAudit,
    uiActionController,
    toggleImmersiveViewport,
    recordHistory,
    selectStudyKind,
    handleLanguageChange,
    studyKindResetHandlers,
    projectHeatToThermoStudy,
    currentStudyFamilyHint,
    currentStudyFamilyLabel,
    canProjectHeatToThermo,
    thermalBoundaryValue,
    thermalIntentValue,
    handleModelToolsPageChange,
    sidebarMountProps,
    mainShellMountProps,
  };
}
