"use client";

import { WorkbenchImmersiveLibraryDrawer } from "@/components/workbench/workbench-immersive-library-drawer";
import { WorkbenchResultWindowBar } from "@/components/workbench/workbench-result-window-bar";
import { WorkbenchViewportDock } from "@/components/workbench/workbench-viewport-dock";
import { WorkbenchViewportHeadActions } from "@/components/workbench/workbench-viewport-head-actions";
import { WorkbenchViewportMount } from "@/components/workbench/workbench-viewport-mount";
import { WorkbenchViewportPanel } from "@/components/workbench/workbench-viewport-panel";

type WorkbenchMainViewportPanelMountProps = Record<string, any>;

export function WorkbenchMainViewportPanelMount(props: WorkbenchMainViewportPanelMountProps) {
  return (
    <WorkbenchViewportPanel
      viewportPanelRef={props.viewportPanelRef}
      immersiveViewport={props.immersiveViewport}
      title={props.title}
      headActions={
        <WorkbenchViewportHeadActions
          t={props.t}
          isTruss3d={props.isTruss3d}
          immersiveViewport={props.immersiveViewport}
          immersiveToolDrawerOpen={props.immersiveToolDrawerOpen}
          immersiveHelpDrawerOpen={props.immersiveHelpDrawerOpen}
          sidebarSection={props.sidebarSection}
          modelTab={props.modelTab}
          modelToolsPage={props.modelToolsPage}
          jobStatus={props.jobStatus}
          handleSidebarSectionChange={props.handleSidebarSectionChange}
          setModelTab={props.setModelTab}
          setModelToolsPage={props.setModelToolsPage}
          handleToggleImmersiveToolDrawer={props.handleToggleImmersiveToolDrawer}
          handleToggleImmersiveHelpDrawer={props.handleToggleImmersiveHelpDrawer}
          handleToggleImmersiveViewport={props.handleToggleImmersiveViewport}
        />
      }
      hasViewportDock={props.hasViewportDock}
      dockContent={
        <WorkbenchViewportDock
          t={props.t}
          immersiveViewport={props.immersiveViewport}
          immersiveToolDrawerOpen={props.immersiveToolDrawerOpen}
          immersiveHelpDrawerOpen={props.immersiveHelpDrawerOpen}
          showShortcutHints={props.showShortcutHints}
          showViewportToolStrip={props.showViewportToolStrip}
          immersiveToolTab={props.immersiveToolTab}
          truss3dViewPreset={props.truss3dViewPreset}
          selectedNode={props.selectedNode}
          selectedElement={props.selectedElement}
          selectedTruss3dNodes={props.selectedTruss3dNodes}
          selectedTruss3dNodeData={props.selectedTruss3dNodeData}
          truss3dLinkMode={props.truss3dLinkMode}
          truss3dProjectionMode={props.truss3dProjectionMode}
          truss3dShowGrid={props.truss3dShowGrid}
          truss3dShowLabels={props.truss3dShowLabels}
          truss3dShowNodes={props.truss3dShowNodes}
          truss3dBoxSelectMode={props.truss3dBoxSelectMode}
          truss3dNudgeStep={props.truss3dNudgeStep}
          truss3dBatchLoadX={props.truss3dBatchLoadX}
          truss3dBatchLoadY={props.truss3dBatchLoadY}
          truss3dBatchLoadZ={props.truss3dBatchLoadZ}
          undoStack={props.undoStack}
          redoStack={props.redoStack}
          truss3dModel={props.truss3dModel}
          setImmersiveToolTab={props.setImmersiveToolTab}
          handleTruss3dViewPresetChange={props.handleTruss3dViewPresetChange}
          handleTruss3dFocusViewport={props.handleTruss3dFocusViewport}
          setTruss3dFocusRequestVersion={props.setTruss3dFocusRequestVersion}
          handleTruss3dProjectionModeChange={props.handleTruss3dProjectionModeChange}
          setTruss3dShowGrid={props.setTruss3dShowGrid}
          setTruss3dShowLabels={props.setTruss3dShowLabels}
          setTruss3dShowNodes={props.setTruss3dShowNodes}
          handleTruss3dBoxSelectModeChange={props.handleTruss3dBoxSelectModeChange}
          handleTruss3dResetViewport={props.handleTruss3dResetViewport}
          addTruss3dNode={props.addTruss3dNode}
          deleteSelectedTruss3dNode={props.deleteSelectedTruss3dNode}
          handleToggleTruss3dLinkMode={props.handleToggleTruss3dLinkMode}
          toggleTruss3dMemberFromDraft={props.toggleTruss3dMemberFromDraft}
          deleteSelectedTruss3dElement={props.deleteSelectedTruss3dElement}
          cloneSelectedTruss3dNodes={props.cloneSelectedTruss3dNodes}
          handleUndo={props.handleUndo}
          handleRedo={props.handleRedo}
          updateSelectedTruss3dNode={props.updateSelectedTruss3dNode}
          nudgeSelectedTruss3dNodes={props.nudgeSelectedTruss3dNodes}
          setTruss3dNudgeStep={props.setTruss3dNudgeStep}
          updateSelectedTruss3dNodes={props.updateSelectedTruss3dNodes}
          setTruss3dBatchLoadX={props.setTruss3dBatchLoadX}
          setTruss3dBatchLoadY={props.setTruss3dBatchLoadY}
          setTruss3dBatchLoadZ={props.setTruss3dBatchLoadZ}
          applySelectedTruss3dLoads={props.applySelectedTruss3dLoads}
        />
      }
      resultWindowBar={
        <WorkbenchResultWindowBar
          t={props.t}
          activeResultWindow={props.activeResultWindow}
          resultWindowStart={props.resultWindowStart}
          resultWindowEnd={props.resultWindowEnd}
          activeResultWindowLimit={props.activeResultWindowLimit}
          resultWindowOffset={props.resultWindowOffset}
          resultWindowMaxTotal={props.resultWindowMaxTotal}
          resultWindowJumps={props.resultWindowJumps}
          isPlane={props.isPlane}
          isHeatPlane={props.isHeatPlane}
          isHeatPlaneTriangle={props.isHeatPlaneTriangle}
          isThermalPlaneTriangle={props.isThermalPlaneTriangle}
          isThermalPlaneQuad={props.isThermalPlaneQuad}
          isFrameLike={props.isFrameLike}
          isThermalFrame={props.isThermalFrame}
          isBeam={props.isBeam}
          isTorsion={props.isTorsion}
          studyKind={props.studyKind}
          planeResult={props.planeResult}
          activeFrameLikeResult={props.activeFrameLikeResult}
          activeBeamLikeResult={props.activeBeamLikeResult}
          torsionResult={props.torsionResult}
          planeResultField={props.planeResultField}
          frameResultField={props.frameResultField}
          beamResultField={props.beamResultField}
          setPlaneResultField={props.setPlaneResultField}
          setFrameResultField={props.setFrameResultField}
          setBeamResultField={props.setBeamResultField}
          setResultWindowOffset={props.setResultWindowOffset}
          clampChunkOffset={props.clampChunkOffset}
        />
      }
      isTruss3d={props.isTruss3d}
      shouldStretchSpaceViewport={props.shouldStretchSpaceViewport}
      onCanvasStageScroll={props.onCanvasStageScroll}
      canvasStageRef={props.canvasStageRef}
      viewportContent={
        <WorkbenchViewportMount
          t={props.t}
          studyKind={props.studyKind}
          sidebarSection={props.sidebarSection}
          isSpring2d={props.isSpring2d}
          isSpring1d={props.isSpring1d}
          isHeatBar={props.isHeatBar}
          isThermalBar={props.isThermalBar}
          isThermalBeam={props.isThermalBeam}
          isThermalFrame={props.isThermalFrame}
          isThermalTruss2d={props.isThermalTruss2d}
          isTorsion={props.isTorsion}
          isFrame={props.isFrame}
          isFrameLike={props.isFrameLike}
          isBeam={props.isBeam}
          isSpring={props.isSpring}
          isSpring3d={props.isSpring3d}
          isThermalTruss3d={props.isThermalTruss3d}
          isHeatPlane={props.isHeatPlane}
          isHeatPlaneTriangle={props.isHeatPlaneTriangle}
          isPlane={props.isPlane}
          isTruss={props.isTruss}
          isTruss3d={props.isTruss3d}
          isThermal={props.isThermal}
          hiddenMaterialIds={props.hiddenMaterialIds}
          frameLegendText={props.frameLegendText}
          planeLegendText={props.planeLegendText}
          axialNodes={props.axialNodes}
          axialLength={props.axialLength}
          axialScale={props.axialScale}
          displayTrussNodes={props.displayTrussNodes}
          displayTrussElements={props.displayTrussElements}
          displayTruss3dNodes={props.displayTruss3dNodes}
          displayTruss3dElements={props.displayTruss3dElements}
          planeNodes={props.planeNodes}
          planeElements={props.planeElements}
          trussElementColors={props.trussElementColors}
          truss3dElementColors={props.truss3dElementColors}
          planeElementColors={props.planeElementColors}
          trussBounds={props.trussBounds}
          planeBounds={props.planeBounds}
          trussResult={props.trussResult}
          thermalTrussResult={props.thermalTrussResult}
          activeFrameLikeResult={props.activeFrameLikeResult}
          activeBeamLikeResult={props.activeBeamLikeResult}
          torsionResult={props.torsionResult}
          heatBarResult={props.heatBarResult}
          thermalBarResult={props.thermalBarResult}
          thermalTruss3dResult={props.thermalTruss3dResult}
          springResult={props.springResult}
          spring2dResult={props.spring2dResult}
          spring3dResult={props.spring3dResult}
          heatPlaneQuadResult={props.heatPlaneQuadResult}
          heatPlaneTriangleResult={props.heatPlaneTriangleResult}
          planeResult={props.planeResult}
          activeLineResultField={props.activeLineResultField}
          frameResultFieldMax={props.frameResultFieldMax}
          focusedFrameElement={props.focusedFrameElement}
          trussStability={props.trussStability}
          trussDiagnostics={props.trussDiagnostics}
          selectedNode={props.selectedNode}
          selectedElement={props.selectedElement}
          memberDraftNodes={props.memberDraftNodes}
          stopDraggingNode={props.stopDraggingNode}
          handleTrussPointerMove={props.handleTrussPointerMove}
          setSelectedElement={props.setSelectedElement}
          setSelectedNode={props.setSelectedNode}
          setMemberDraftNodes={props.setMemberDraftNodes}
          setFocusedFrameElement={props.setFocusedFrameElement}
          startTrussNodeDrag={props.startTrussNodeDrag}
          hiddenPlaneMaterialIds={props.hiddenMaterialIds}
          planeResultField={props.planeResultField}
          planeResultFieldMax={props.planeResultFieldMax}
          selectedPlaneNodeData={props.selectedPlaneNodeData}
          focusedPlaneElement={props.focusedPlaneElement}
          handleTruss3dNodePick={props.handleTruss3dNodePick}
          setSelectedTruss3dNodes={props.setSelectedTruss3dNodes}
          updateTruss3dNodePosition={props.updateTruss3dNodePosition}
          recordHistory={props.recordHistory}
          drag3dHistoryCapturedRef={props.drag3dHistoryCapturedRef}
          truss3dLinkMode={props.truss3dLinkMode}
          immersiveViewport={props.immersiveViewport}
          truss3dProjectionMode={props.truss3dProjectionMode}
          truss3dShowGrid={props.truss3dShowGrid}
          truss3dShowLabels={props.truss3dShowLabels}
          truss3dShowNodes={props.truss3dShowNodes}
          truss3dBoxSelectMode={props.truss3dBoxSelectMode}
          truss3dViewPreset={props.truss3dViewPreset}
          truss3dFocusRequestVersion={props.truss3dFocusRequestVersion}
          truss3dResetRequestVersion={props.truss3dResetRequestVersion}
          selectedTruss3dNodes={props.selectedTruss3dNodes}
          showShortcutHints={props.showShortcutHints}
          viewportPixelWidth={props.viewportPixelWidth}
          handleTruss3dNodesBoxSelect={props.handleTruss3dNodesBoxSelect}
          handleTruss3dProjectionModeChange={props.handleTruss3dProjectionModeChange}
          handleTruss3dShowGridChange={props.handleTruss3dShowGridChange}
          handleTruss3dShowLabelsChange={props.handleTruss3dShowLabelsChange}
          handleTruss3dShowNodesChange={props.handleTruss3dShowNodesChange}
          handleTruss3dBoxSelectModeChange={props.handleTruss3dBoxSelectModeChange}
        />
      }
      immersiveDrawer={
        <WorkbenchImmersiveLibraryDrawer
          t={props.t}
          immersiveViewport={props.immersiveViewport}
          sidebarSection={props.sidebarSection}
          librarySampleRows={props.librarySampleRows}
          libraryModelRows={props.libraryModelRows}
          libraryJobRows={props.libraryJobRows}
          selectedProjectModels={props.selectedProjectModels}
          handleSidebarSectionChange={props.handleSidebarSectionChange}
          openSample={props.openSample}
          openSavedModel={props.openSavedModel}
          openHistoryJob={props.openHistoryJob}
        />
      }
    />
  );
}
