export type WorkbenchScriptWorkspaceCopy = {
  record: string;
  inspect: string;
  catalog: string;
  headless: string;
  expand: string;
  restore: string;
  help: string;
  editorHint: string;
};

const copies: Record<string, WorkbenchScriptWorkspaceCopy> = {
  "en": {
    record: "Record",
    inspect: "Inspect",
    catalog: "Catalog",
    headless: "SDK bridge",
    expand: "Expand workspace",
    restore: "Restore panel",
    help: "Help",
    editorHint: "Tab / Shift+Tab: indent. Escape, then Tab: leave the editor. Ctrl/Cmd+Enter: run.",
  },
  "zh": {
    record: "录制",
    inspect: "检查",
    catalog: "资源库",
    headless: "SDK 桥接",
    expand: "展开工作区",
    restore: "返回内嵌面板",
    help: "使用说明",
    editorHint: "Tab / Shift+Tab：调整缩进。先按 Esc，再按 Tab：离开编辑器。Ctrl/Cmd+Enter：运行。",
  },
  "ja": {
    record: "記録",
    inspect: "検査",
    catalog: "カタログ",
    headless: "SDK 連携",
    expand: "作業領域を拡大",
    restore: "埋め込みパネルに戻る",
    help: "使い方",
    editorHint: "Tab / Shift+Tab：インデント。Esc の後に Tab：エディターを離れる。Ctrl/Cmd+Enter：実行。",
  },
  "es": {
    record: "Grabar",
    inspect: "Inspeccionar",
    catalog: "Catálogo",
    headless: "Puente SDK",
    expand: "Ampliar área de trabajo",
    restore: "Volver al panel integrado",
    help: "Ayuda",
    editorHint: "Tab / Mayús+Tab: sangría. Esc y luego Tab: salir del editor. Ctrl/Cmd+Enter: ejecutar.",
  },
  "ar": {
    record: "تسجيل",
    inspect: "فحص",
    catalog: "الكتالوج",
    headless: "جسر SDK",
    expand: "توسيع مساحة العمل",
    restore: "العودة إلى اللوحة المضمّنة",
    help: "مساعدة",
    editorHint: "Tab / Shift+Tab: المسافة البادئة. Esc ثم Tab: مغادرة المحرر. Ctrl/Cmd+Enter: تشغيل.",
  },
  "bn": {
    record: "রেকর্ড",
    inspect: "পরীক্ষা",
    catalog: "ক্যাটালগ",
    headless: "SDK সংযোগ",
    expand: "কাজের এলাকা বড় করুন",
    restore: "এমবেড করা প্যানেলে ফিরুন",
    help: "সহায়তা",
    editorHint: "Tab / Shift+Tab: ইন্ডেন্ট। Esc, তারপর Tab: সম্পাদক থেকে বের হন। Ctrl/Cmd+Enter: চালান।",
  },
  "cs": {
    record: "Záznam",
    inspect: "Kontrola",
    catalog: "Katalog",
    headless: "Propojení SDK",
    expand: "Zvětšit pracovní plochu",
    restore: "Zpět do vloženého panelu",
    help: "Nápověda",
    editorHint: "Tab / Shift+Tab: odsazení. Esc a poté Tab: opustit editor. Ctrl/Cmd+Enter: spustit.",
  },
  "da": {
    record: "Optag",
    inspect: "Inspicer",
    catalog: "Katalog",
    headless: "SDK-bro",
    expand: "Udvid arbejdsområdet",
    restore: "Tilbage til indlejret panel",
    help: "Hjælp",
    editorHint: "Tab / Shift+Tab: indrykning. Esc og derefter Tab: forlad editoren. Ctrl/Cmd+Enter: kør.",
  },
  "de": {
    record: "Aufzeichnen",
    inspect: "Prüfen",
    catalog: "Katalog",
    headless: "SDK-Brücke",
    expand: "Arbeitsbereich vergrößern",
    restore: "Zum eingebetteten Panel",
    help: "Hilfe",
    editorHint: "Tab / Umschalt+Tab: Einrücken. Esc, dann Tab: Editor verlassen. Strg/Cmd+Enter: ausführen.",
  },
  "el": {
    record: "Καταγραφή",
    inspect: "Επιθεώρηση",
    catalog: "Κατάλογος",
    headless: "Γέφυρα SDK",
    expand: "Μεγέθυνση χώρου εργασίας",
    restore: "Επιστροφή στο ενσωματωμένο πλαίσιο",
    help: "Βοήθεια",
    editorHint: "Tab / Shift+Tab: εσοχή. Esc και μετά Tab: έξοδος από τον επεξεργαστή. Ctrl/Cmd+Enter: εκτέλεση.",
  },
  "fa": {
    record: "ضبط",
    inspect: "بررسی",
    catalog: "فهرست",
    headless: "پل SDK",
    expand: "بزرگ‌کردن فضای کار",
    restore: "بازگشت به پنل تعبیه‌شده",
    help: "راهنما",
    editorHint: "Tab / Shift+Tab: تورفتگی. Esc و سپس Tab: خروج از ویرایشگر. Ctrl/Cmd+Enter: اجرا.",
  },
  "fi": {
    record: "Tallenna toimet",
    inspect: "Tarkasta",
    catalog: "Luettelo",
    headless: "SDK-silta",
    expand: "Laajenna työalue",
    restore: "Palaa upotettuun paneeliin",
    help: "Ohje",
    editorHint: "Tab / Shift+Tab: sisennys. Esc, sitten Tab: poistu editorista. Ctrl/Cmd+Enter: suorita.",
  },
  "fr": {
    record: "Enregistrer",
    inspect: "Inspecter",
    catalog: "Catalogue",
    headless: "Passerelle SDK",
    expand: "Agrandir l’espace de travail",
    restore: "Revenir au panneau intégré",
    help: "Aide",
    editorHint: "Tab / Maj+Tab : indentation. Échap puis Tab : quitter l’éditeur. Ctrl/Cmd+Entrée : exécuter.",
  },
  "he": {
    record: "הקלטה",
    inspect: "בדיקה",
    catalog: "קטלוג",
    headless: "גשר SDK",
    expand: "הרחבת אזור העבודה",
    restore: "חזרה לחלונית המוטמעת",
    help: "עזרה",
    editorHint: "Tab / Shift+Tab: הזחה. Esc ואז Tab: יציאה מהעורך. Ctrl/Cmd+Enter: הרצה.",
  },
  "hi": {
    record: "रिकॉर्ड",
    inspect: "निरीक्षण",
    catalog: "सूची",
    headless: "SDK सेतु",
    expand: "कार्यक्षेत्र बड़ा करें",
    restore: "अंतर्निहित पैनल पर लौटें",
    help: "सहायता",
    editorHint: "Tab / Shift+Tab: इंडेंट। Esc, फिर Tab: संपादक से बाहर जाएँ। Ctrl/Cmd+Enter: चलाएँ।",
  },
  "id": {
    record: "Rekam",
    inspect: "Periksa",
    catalog: "Katalog",
    headless: "Jembatan SDK",
    expand: "Perluas ruang kerja",
    restore: "Kembali ke panel tertanam",
    help: "Bantuan",
    editorHint: "Tab / Shift+Tab: indentasi. Esc lalu Tab: keluar dari editor. Ctrl/Cmd+Enter: jalankan.",
  },
  "it": {
    record: "Registra",
    inspect: "Ispeziona",
    catalog: "Catalogo",
    headless: "Ponte SDK",
    expand: "Espandi area di lavoro",
    restore: "Torna al pannello integrato",
    help: "Aiuto",
    editorHint: "Tab / Maiusc+Tab: rientro. Esc, poi Tab: esci dall’editor. Ctrl/Cmd+Invio: esegui.",
  },
  "ko": {
    record: "기록",
    inspect: "검사",
    catalog: "카탈로그",
    headless: "SDK 연동",
    expand: "작업 영역 확대",
    restore: "내장 패널로 돌아가기",
    help: "도움말",
    editorHint: "Tab / Shift+Tab: 들여쓰기. Esc 다음 Tab: 편집기에서 나가기. Ctrl/Cmd+Enter: 실행.",
  },
  "ms": {
    record: "Rakam",
    inspect: "Periksa",
    catalog: "Katalog",
    headless: "Jambatan SDK",
    expand: "Luaskan ruang kerja",
    restore: "Kembali ke panel terbenam",
    help: "Bantuan",
    editorHint: "Tab / Shift+Tab: inden. Esc kemudian Tab: keluar daripada editor. Ctrl/Cmd+Enter: jalankan.",
  },
  "nl": {
    record: "Opnemen",
    inspect: "Inspecteren",
    catalog: "Catalogus",
    headless: "SDK-brug",
    expand: "Werkruimte vergroten",
    restore: "Terug naar ingebed paneel",
    help: "Help",
    editorHint: "Tab / Shift+Tab: inspringen. Esc, daarna Tab: editor verlaten. Ctrl/Cmd+Enter: uitvoeren.",
  },
  "no": {
    record: "Ta opp",
    inspect: "Inspiser",
    catalog: "Katalog",
    headless: "SDK-bro",
    expand: "Utvid arbeidsområdet",
    restore: "Tilbake til innebygd panel",
    help: "Hjelp",
    editorHint: "Tab / Shift+Tab: innrykk. Esc og deretter Tab: forlat editoren. Ctrl/Cmd+Enter: kjør.",
  },
  "pl": {
    record: "Nagrywaj",
    inspect: "Sprawdź",
    catalog: "Katalog",
    headless: "Most SDK",
    expand: "Powiększ obszar roboczy",
    restore: "Wróć do osadzonego panelu",
    help: "Pomoc",
    editorHint: "Tab / Shift+Tab: wcięcie. Esc, potem Tab: opuść edytor. Ctrl/Cmd+Enter: uruchom.",
  },
  "pt-br": {
    record: "Gravar",
    inspect: "Inspecionar",
    catalog: "Catálogo",
    headless: "Ponte SDK",
    expand: "Ampliar área de trabalho",
    restore: "Voltar ao painel integrado",
    help: "Ajuda",
    editorHint: "Tab / Shift+Tab: recuo. Esc e depois Tab: sair do editor. Ctrl/Cmd+Enter: executar.",
  },
  "ro": {
    record: "Înregistrare",
    inspect: "Inspectare",
    catalog: "Catalog",
    headless: "Punte SDK",
    expand: "Extinde spațiul de lucru",
    restore: "Înapoi la panoul integrat",
    help: "Ajutor",
    editorHint: "Tab / Shift+Tab: indentare. Esc, apoi Tab: ieșire din editor. Ctrl/Cmd+Enter: rulare.",
  },
  "ru": {
    record: "Запись",
    inspect: "Проверка",
    catalog: "Каталог",
    headless: "Мост SDK",
    expand: "Развернуть рабочую область",
    restore: "Вернуться во встроенную панель",
    help: "Справка",
    editorHint: "Tab / Shift+Tab: отступ. Esc, затем Tab: выйти из редактора. Ctrl/Cmd+Enter: выполнить.",
  },
  "sv": {
    record: "Spela in",
    inspect: "Inspektera",
    catalog: "Katalog",
    headless: "SDK-brygga",
    expand: "Utöka arbetsytan",
    restore: "Tillbaka till inbäddad panel",
    help: "Hjälp",
    editorHint: "Tab / Shift+Tab: indrag. Esc, sedan Tab: lämna redigeraren. Ctrl/Cmd+Enter: kör.",
  },
  "sw": {
    record: "Rekodi",
    inspect: "Kagua",
    catalog: "Katalogi",
    headless: "Daraja la SDK",
    expand: "Panua eneo la kazi",
    restore: "Rudi kwenye paneli iliyopachikwa",
    help: "Msaada",
    editorHint: "Tab / Shift+Tab: ujongezaji. Esc kisha Tab: ondoka kwenye kihariri. Ctrl/Cmd+Enter: endesha.",
  },
  "ta": {
    record: "பதிவு",
    inspect: "ஆய்வு",
    catalog: "பட்டியல்",
    headless: "SDK இணைப்பு",
    expand: "பணிப்பரப்பை விரிவாக்கு",
    restore: "உட்பொதிந்த பலகைக்குத் திரும்பு",
    help: "உதவி",
    editorHint: "Tab / Shift+Tab: உள்தள்ளல். Esc, பிறகு Tab: தொகுப்பியிலிருந்து வெளியேறு. Ctrl/Cmd+Enter: இயக்கு.",
  },
  "th": {
    record: "บันทึก",
    inspect: "ตรวจสอบ",
    catalog: "แค็ตตาล็อก",
    headless: "สะพาน SDK",
    expand: "ขยายพื้นที่ทำงาน",
    restore: "กลับสู่แผงฝังตัว",
    help: "วิธีใช้",
    editorHint: "Tab / Shift+Tab: เยื้องข้อความ Esc แล้ว Tab: ออกจากตัวแก้ไข Ctrl/Cmd+Enter: เรียกใช้",
  },
  "tr": {
    record: "Kaydet",
    inspect: "İncele",
    catalog: "Katalog",
    headless: "SDK köprüsü",
    expand: "Çalışma alanını genişlet",
    restore: "Gömülü panele dön",
    help: "Yardım",
    editorHint: "Tab / Shift+Tab: girinti. Esc, sonra Tab: düzenleyiciden çık. Ctrl/Cmd+Enter: çalıştır.",
  },
  "uk": {
    record: "Запис",
    inspect: "Перевірка",
    catalog: "Каталог",
    headless: "Міст SDK",
    expand: "Розгорнути робочу область",
    restore: "Повернутися до вбудованої панелі",
    help: "Довідка",
    editorHint: "Tab / Shift+Tab: відступ. Esc, потім Tab: вийти з редактора. Ctrl/Cmd+Enter: виконати.",
  },
  "ur": {
    record: "ریکارڈ",
    inspect: "معائنہ",
    catalog: "کیٹلاگ",
    headless: "SDK رابطہ",
    expand: "کام کی جگہ بڑی کریں",
    restore: "اندرونی پینل پر واپس جائیں",
    help: "مدد",
    editorHint: "Tab / Shift+Tab: انڈینٹ۔ Esc پھر Tab: ایڈیٹر سے باہر نکلیں۔ Ctrl/Cmd+Enter: چلائیں۔",
  },
  "vi": {
    record: "Ghi lại",
    inspect: "Kiểm tra",
    catalog: "Danh mục",
    headless: "Cầu nối SDK",
    expand: "Mở rộng vùng làm việc",
    restore: "Trở về bảng nhúng",
    help: "Trợ giúp",
    editorHint: "Tab / Shift+Tab: thụt lề. Esc rồi Tab: rời trình soạn thảo. Ctrl/Cmd+Enter: chạy.",
  },
  "zh-tw": {
    record: "錄製",
    inspect: "檢查",
    catalog: "資源庫",
    headless: "SDK 橋接",
    expand: "展開工作區",
    restore: "返回內嵌面板",
    help: "使用說明",
    editorHint: "Tab / Shift+Tab：調整縮排。先按 Esc，再按 Tab：離開編輯器。Ctrl/Cmd+Enter：執行。",
  },
};

export function getWorkbenchScriptWorkspaceCopy(language: string): WorkbenchScriptWorkspaceCopy {
  const key = language.trim().toLowerCase().replace(/_/g, "-");
  if (Object.hasOwn(copies, key)) return copies[key];
  const base = key.split("-")[0];
  return Object.hasOwn(copies, base) ? copies[base] : copies.en;
}
