"use client";

import {
  type Dispatch,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
  type SetStateAction,
} from "react";
import brand from "../../../../../assets/brand/brand.json";
import { buildWorkbenchStudyFlags } from "@/components/workbench/workbench-admin-context";
import {
  deleteWorkbenchAdminResultRecord,
  exportWorkbenchAdminResultRecord,
  refreshWorkbenchResults,
  saveWorkbenchAdminResultRecord,
} from "@/components/workbench/workbench-admin-result-controller";
import { WorkbenchMainShellMount } from "@/components/workbench/workbench-main-shell-mount";
import { useWorkbenchMainComposition } from "@/components/workbench/workbench-main-composition";
import { buildWorkbenchModelContent } from "@/components/workbench/workbench-model-content";
import {
  humanizeSolverFailure,
  type WorkbenchCopy,
  type WorkbenchLanguage,
} from "@/components/workbench/workbench-copy";
import {
  defaultAxial,
  defaultBeam1d,
  defaultFrame2d,
  defaultHeatBar1d,
  defaultHeatPlaneQuad,
  defaultHeatPlaneTriangle,
  defaultPanelParametric,
  defaultParametric,
  defaultPlaneQuad,
  defaultPlaneTriangle,
  defaultSpring1d,
  defaultSpring2d,
  defaultSpring3d,
  defaultThermalBar1d,
  defaultThermalBeam1d,
  defaultThermalFrame2d,
  defaultThermalPlaneQuad,
  defaultThermalPlaneTriangle,
  defaultThermalTruss2d,
  defaultThermalTruss3d,
  defaultTorsion1d,
  defaultTruss,
  defaultTruss3d,
  type AxialFormState,
  type DirectMeshExecutionState,
  type DisplayTruss3dElement,
  type DisplayTruss3dNode,
  type DisplayTrussElement,
  type DisplayTrussNode,
  type PlaneResultField,
  type SelectionKind,
  type StabilitySummary,
  type TrussDiagnostics,
  type TrussSuggestion,
} from "@/components/workbench/workbench-defaults";
import { applyHistoryJobPayload } from "@/components/workbench/workbench-history-result";
import {
  downloadBlobFile,
  downloadTextFile,
  resetActiveResult,
} from "@/components/workbench/workbench-file-helpers";
import {
  buildDisplayBeamElements,
  buildDisplayBeamNodes,
  buildDisplaySpring2dElements,
  buildDisplaySpring2dNodes,
  buildDisplaySpringElements,
  buildDisplaySpringNodes,
  buildDisplayThermalBeamElements,
  buildDisplayThermalBeamNodes,
  buildDisplayTorsionElements,
  buildDisplayTorsionNodes,
} from "@/components/workbench/workbench-display-line-helpers";
import { applyImportedWorkbenchModel } from "@/components/workbench/workbench-model-load";
import {
  buildThermalBarFromHeatResult,
  buildThermalPlaneQuadFromHeatResult,
  buildThermalPlaneTriangleFromHeatResult,
  ensureBeamModelMaterials,
  ensureFrameModelMaterials,
} from "@/components/workbench/workbench-model-transform-helpers";
import {
  buildDisplayFrameElements,
  buildDisplayFrameNodes,
  buildDisplayHeatBarElements,
  buildDisplayHeatBarNodes,
  buildDisplayThermalBarElements,
  buildDisplayThermalBarNodes,
  buildDisplayThermalFrameElements,
  buildDisplayThermalFrameNodes,
  buildDisplayThermalTrussElements,
  buildDisplayThermalTrussNodes,
  buildDisplayTrussElements,
  buildDisplayTrussNodes,
} from "@/components/workbench/workbench-display-planar-helpers";
import {
  downloadWorkbenchDatabaseSnapshot,
  downloadWorkbenchProjectBundleJson,
  downloadWorkbenchProjectBundleZip,
} from "@/components/workbench/workbench-export-controller";
import {
  downloadWorkbenchFrameForceSummary,
  downloadWorkbenchFrameHotspotSummary,
  downloadWorkbenchPlaneHotspotSummary,
  downloadWorkbenchResultCsv,
  downloadWorkbenchResultJson,
} from "@/components/workbench/workbench-result-export-controller";
import {
  useWorkbenchResultWindowController,
  type ResultWindowState,
} from "@/components/workbench/workbench-result-window-controller";
import {
  buildDisplaySpring3dElements,
  buildDisplaySpring3dNodes,
  buildDisplayThermalTruss3dElements,
  buildDisplayThermalTruss3dNodes,
  buildDisplayTruss3dElements,
  buildDisplayTruss3dNodes,
  projectTruss3dPoint,
} from "@/components/workbench/workbench-display-spatial-helpers";
import {
  clusterHealthTone,
  formatJobMessage,
  formatPeerStatus,
  formatProtocolMethodLabel,
  isAxialResult,
  isBeam1dResult,
  isFrame2dResult,
  isHeatBar1dResult,
  isHeatPlaneQuad2dResult,
  isHeatPlaneTriangle2dResult,
  isPlaneResult,
  isSpring1dResult,
  isSpring2dResult,
  isSpring3dResult,
  isThermalBar1dResult,
  isThermalBeam1dResult,
  isThermalFrame2dResult,
  isThermalTruss2dResult,
  isThermalTruss3dResult,
  isTorsion1dResult,
  isTruss3dResult,
  isTrussResult,
  localMaterialLabel,
  materialColorByIndex,
} from "@/components/workbench/workbench-result-helpers";
import { useWorkbenchStudyResultDerived } from "@/components/workbench/workbench-study-result-derived";
import { WorkbenchInspectorMount } from "@/components/workbench/workbench-inspector-mount";
import {
  bindWorkbenchMainComposition,
  bindWorkbenchStudyResultDerived,
} from "@/components/workbench/workbench-root-bindings";
import { useWorkbenchRootState } from "@/components/workbench/workbench-root-state";
import { WorkbenchSidebarMount } from "@/components/workbench/workbench-sidebar-mount";
import { useWorkbenchSessionComposition } from "@/components/workbench/workbench-session-composition";
import {
  importWorkbenchModelFile,
  openWorkbenchSample,
} from "@/components/workbench/workbench-sample-import-controller";
import { isWorkbenchStudyKind } from "@/components/workbench/workbench-study-kind-controller";
import {
  analyzeTrussModel,
  getTrussBounds,
  renderLoadGlyph,
  renderSupportGlyph,
  round,
  summarizeTrussStability,
  toSvgPoint,
} from "@/components/workbench/workbench-truss-helpers";
import {
  type AssistantMode,
  type BeamResultField,
  type BeamStudyJobInput,
  type FrameResultField,
  type FrameStudyJobInput,
  type HeatBarStudyJobInput,
  type HeatPlaneStudyJobInput,
  type ImmersiveToolTab,
  type Language,
  type LibraryPanelTab,
  type LineResultField,
  type ModelPanelTab,
  type PlaneStudyJobInput,
  SECURITY_EVENT_WINDOW_MS,
  type SecurityEventWindow,
  type SidebarSection,
  type Spring2dStudyJobInput,
  type Spring3dStudyJobInput,
  type SpringStudyJobInput,
  type StudyKind,
  type StudyPanelTab,
  type SystemDataTab,
  type SystemPanelTab,
  type ThermalBarStudyJobInput,
  type ThermalBeamStudyJobInput,
  type ThermalFrameStudyJobInput,
  type ThermalTruss2dStudyJobInput,
  type ThermalTruss3dStudyJobInput,
  type Theme,
  type WorkflowPanelTab,
} from "@/components/workbench/workbench-types";
import type { ModelToolsPage } from "@/components/workbench/model/workbench-model-sidebar";
import { isWorkflowGraphResult, summarizeWorkflowArtifacts, upsertWorkflowRunRecord } from "@/components/workbench/workflow/workbench-workflow-controller";
import {
  fixed,
  formatMilliseconds,
  formatTime,
  serializeCurrentModel,
  toAxialInput,
} from "@/lib/workbench/helpers";
import { type HistoryEntry, type WorkbenchSnapshot } from "@/lib/workbench/history";
import {
  readSecurityAuditLog,
  type WorkbenchSecurityAuditRisk,
  type WorkbenchSecurityAuditSource,
} from "@/lib/workbench/security-audit";
import { classifyStudyKindFamily } from "@/lib/workbench/view-models";
import {
  ensurePlaneModelMaterials,
  ensureTruss3dModelMaterials,
  ensureTrussModelMaterials,
} from "@/lib/workbench/material-commands";
import { clampChunkOffset, RESULT_WINDOW_BASE_SIZE } from "@/lib/workbench/result-window";
import { updateFrame2dNode } from "@/lib/workbench/frame2d-commands";
import { toggleDraftSelection } from "@/lib/workbench/truss2d-commands";
import {
  addTruss3dNodeCommand,
} from "@/lib/workbench/truss3d-commands";
import {
  exportStudyModel,
  type ParametricPanelConfig,
  type ParametricTrussConfig,
} from "@/lib/models";
import { SAMPLE_LIBRARY } from "@/lib/models";
import {
  type WorkbenchScriptSnapshot,
} from "@/lib/scripting/workbench-script-runtime";
import {
  createAxialBarJob,
  createBeam1dJob,
  createHeatBar1dJob,
  createHeatPlaneQuad2dJob,
  createHeatPlaneTriangle2dJob,
  createThermalBeam1dJob,
  createThermalBar1dJob,
  createThermalFrame2dJob,
  createThermalPlaneQuad2dJob,
  createThermalPlaneTriangle2dJob,
  createThermalTruss2dJob,
  createThermalTruss3dJob,
  createSpring1dJob,
  createSpring2dJob,
  createSpring3dJob,
  createTorsion1dJob,
  createDirectMeshSolve,
  createFrame2dJob,
  createPlaneQuad2dJob,
  createPlaneTriangle2dJob,
  createModel,
  createModelVersion,
  createProject,
  createTruss2dJob,
  createTruss3dJob,
  cancelJob,
  deleteJobRecord,
  deleteModel,
  deleteModelVersion,
  deleteProject,
  deleteResultRecord,
  fetchModel,
  fetchModelVersion,
  fetchModelVersions,
  fetchJobStatus,
  fetchResults,
  type AxialBarJobInput,
  type AxialBarResult,
  type Beam1dElementInput,
  type Beam1dJobInput,
  type Beam1dNodeInput,
  type Beam1dResult,
  type DirectMeshSelectionMode,
  type Frame2dElementInput,
  type Frame2dJobInput,
  type Frame2dNodeInput,
  type Frame2dResult,
  type FrontendRuntimeMode,
  type HeatBar1dElementInput,
  type HeatBar1dJobInput,
  type HeatBar1dNodeInput,
  type HeatBar1dResult,
  type HeatPlaneNodeInput,
  type HeatPlaneQuad2dJobInput,
  type HeatPlaneQuad2dResult,
  type HeatPlaneTriangle2dJobInput,
  type HeatPlaneTriangle2dResult,
  type JobEnvelope,
  type JobResultRecord,
  type JobState,
  type ModelRecord,
  type ModelVersionRecord,
  type PlaneQuad2dJobInput,
  type PlaneQuad2dResult,
  type PlaneTriangle2dJobInput,
  type PlaneTriangle2dResult,
  type ThermalPlaneQuad2dJobInput,
  type ThermalPlaneQuad2dResult,
  type ThermalPlaneTriangle2dJobInput,
  type ThermalPlaneTriangle2dResult,
  type ProjectRecord,
  type ResultRecord,
  type SecurityEventRecord,
  type ThermalBeam1dElementInput,
  type ThermalBeam1dJobInput,
  type ThermalBeam1dNodeInput,
  type ThermalBeam1dResult,
  type ThermalBar1dElementInput,
  type ThermalBar1dJobInput,
  type ThermalBar1dNodeInput,
  type ThermalBar1dResult,
  type ThermalFrame2dElementInput,
  type ThermalFrame2dJobInput,
  type ThermalFrame2dNodeInput,
  type ThermalFrame2dResult,
  type ThermalTruss2dElementInput,
  type ThermalTruss2dJobInput,
  type ThermalTruss2dNodeInput,
  type ThermalTruss2dResult,
  type ThermalTruss3dElementInput,
  type ThermalTruss3dJobInput,
  type ThermalTruss3dNodeInput,
  type ThermalTruss3dResult,
  type WorkflowGraphJobResult,
  type Spring1dJobInput,
  type Spring1dResult,
  type Spring2dJobInput,
  type Spring2dResult,
  type Spring3dJobInput,
  type Spring3dResult,
  type Torsion1dJobInput,
  type Torsion1dResult,
  resolveHeatBar1dJobInput,
  resolveHeatPlaneQuad2dJobInput,
  resolveHeatPlaneTriangle2dJobInput,
  resolveBeam1dJobInput,
  resolveThermalBeam1dJobInput,
  resolveThermalBar1dJobInput,
  resolveThermalFrame2dJobInput,
  resolveThermalTruss2dJobInput,
  resolveThermalTruss3dJobInput,
  resolveSpring1dJobInput,
  resolveSpring2dJobInput,
  resolveSpring3dJobInput,
  resolveTorsion1dJobInput,
  resolveThermalPlaneQuad2dJobInput,
  resolveThermalPlaneTriangle2dJobInput,
  resolvePlaneQuad2dJobInput,
  resolvePlaneTriangle2dJobInput,
  resolveFrame2dJobInput,
  resolveTruss2dJobInput,
  resolveTruss3dJobInput,
  type Truss2dJobInput,
  type Truss2dResult,
  type Truss3dJobInput,
  type Truss3dResult,
  updateJobRecord,
  updateModel,
  updateModelVersion,
  updateProject,
  updateResultRecord,
} from "@/lib/api";

export function Workbench() {
  const {
    workspaceState,
    studyKind,
    setStudyKind,
    axialForm,
    setAxialForm,
    heatBarModel,
    setHeatBarModel,
    heatPlaneModel,
    setHeatPlaneModel,
    thermalBarModel,
    setThermalBarModel,
    thermalBeamModel,
    setThermalBeamModel,
    thermalFrameModel,
    setThermalFrameModel,
    thermalTrussModel,
    setThermalTrussModel,
    trussModel,
    setTrussModel,
    thermalTruss3dModel,
    setThermalTruss3dModel,
    truss3dModel,
    setTruss3dModel,
    planeModel,
    setPlaneModel,
    frameModel,
    setFrameModel,
    beamModel,
    setBeamModel,
    torsionModel,
    setTorsionModel,
    springModel,
    setSpringModel,
    spring2dModel,
    setSpring2dModel,
    spring3dModel,
    setSpring3dModel,
    parametric,
    setParametric,
    panelParametric,
    setPanelParametric,
    activeMaterial,
    setActiveMaterial,
    planeResultField,
    setPlaneResultField,
    frameResultField,
    setFrameResultField,
    beamResultField,
    setBeamResultField,
    planeHotspotLimit,
    setPlaneHotspotLimit,
    focusedPlaneElement,
    setFocusedPlaneElement,
    focusedFrameElement,
    setFocusedFrameElement,
    result,
    setResult,
    resultWindow,
    setResultWindow,
    resultWindowOffset,
    setResultWindowOffset,
    resultWindowLimit,
    setResultWindowLimit,
    canvasViewportWidth,
    setCanvasViewportWidth,
    job,
    setJob,
    resultRecords,
    setResultRecords,
    projects,
    setProjects,
    selectedProjectId,
    setSelectedProjectId,
    selectedModelId,
    setSelectedModelId,
    selectedVersionId,
    setSelectedVersionId,
    modelVersions,
    setModelVersions,
    projectNameDraft,
    setProjectNameDraft,
    projectDescriptionDraft,
    setProjectDescriptionDraft,
    loadedModelName,
    setLoadedModelName,
    message,
    setMessage,
    hiddenMaterials,
    setHiddenMaterials,
    sidebarSection,
    setSidebarSection,
    studyTab,
    setStudyTab,
    modelTab,
    setModelTab,
    modelToolsPage,
    setModelToolsPage,
    libraryTab,
    setLibraryTab,
    systemDataTab,
    setSystemDataTab,
    systemPanelTab,
    setSystemPanelTab,
    draggingNode,
    setDraggingNode,
    truss3dLinkMode,
    setTruss3dLinkMode,
    selectedTruss3dNodes,
    setSelectedTruss3dNodes,
    selectedNode,
    setSelectedNode,
    selectedElement,
    setSelectedElement,
    memberDraftNodes,
    setMemberDraftNodes,
    undoStack,
    setUndoStack,
    redoStack,
    setRedoStack,
    health,
    setHealth,
    protocolAgents,
    setProtocolAgents,
    shellState,
    language,
    languagePacks,
    setLanguagePacks,
    theme,
    setTheme,
    frontendRuntimeMode,
    setFrontendRuntimeMode,
    directMeshEndpointsText,
    setDirectMeshEndpointsText,
    directMeshSelectionMode,
    setDirectMeshSelectionMode,
    controlPlaneApiToken,
    setControlPlaneApiToken,
    clusterApiToken,
    setClusterApiToken,
    directMeshApiToken,
    setDirectMeshApiToken,
    assistantMode,
    setAssistantMode,
    assistantApiBaseUrl,
    setAssistantApiBaseUrl,
    assistantApiKey,
    setAssistantApiKey,
    assistantModel,
    setAssistantModel,
    assistantWindowOpen,
    setAssistantWindowOpen,
    directMeshExecution,
    setDirectMeshExecution,
    showShortcutHints,
    setShowShortcutHints,
    immersiveGuardrails,
    setImmersiveGuardrails,
    immersiveViewport,
    setImmersiveViewport,
    immersiveToolDrawerOpen,
    setImmersiveToolDrawerOpen,
    immersiveHelpDrawerOpen,
    setImmersiveHelpDrawerOpen,
    immersiveToolTab,
    setImmersiveToolTab,
    truss3dProjectionMode,
    setTruss3dProjectionMode,
    truss3dShowGrid,
    setTruss3dShowGrid,
    truss3dShowLabels,
    setTruss3dShowLabels,
    truss3dShowNodes,
    setTruss3dShowNodes,
    truss3dBoxSelectMode,
    setTruss3dBoxSelectMode,
    truss3dViewPreset,
    setTruss3dViewPreset,
    truss3dFocusRequestVersion,
    setTruss3dFocusRequestVersion,
    truss3dResetRequestVersion,
    setTruss3dResetRequestVersion,
    truss3dNudgeStep,
    setTruss3dNudgeStep,
    truss3dBatchLoadX,
    setTruss3dBatchLoadX,
    truss3dBatchLoadY,
    setTruss3dBatchLoadY,
    truss3dBatchLoadZ,
    setTruss3dBatchLoadZ,
    applyLanguagePreference,
    activeLanguagePack,
    t,
    languagePackCatalogRows,
    isPending,
    startTransition,
    viewportPanelRef,
    canvasStageRef,
    drag3dHistoryCapturedRef,
    dragFrameRef,
    dragHistoryCapturedRef,
    jobPollTokenRef,
    pendingDragPointRef,
    resultRefreshSeqRef,
    jobIsActive,
  } = useWorkbenchRootState();

  const resultWindowMaxTotal = resultWindow ? Math.max(resultWindow.totalNodes, resultWindow.totalElements) : 0;
  const { handleCanvasStageScroll } = useWorkbenchResultWindowController({
    canvasStageRef,
    canvasViewportWidth,
    frontendRuntimeMode,
    guards: {
      isAxialResult,
      isTrussResult,
      isHeatBar1dResult,
      isHeatPlaneQuad2dResult,
      isHeatPlaneTriangle2dResult,
      isThermalBar1dResult,
      isThermalBeam1dResult,
      isThermalTruss2dResult,
      isThermalTruss3dResult,
      isTruss3dResult,
      isSpring1dResult,
      isSpring2dResult,
      isSpring3dResult,
      isBeam1dResult,
      isTorsion1dResult,
      isFrame2dResult,
    },
    jobId: job?.job_id ?? null,
    requestTimedOutLabel: t.requestTimedOut,
    result,
    resultWindow,
    resultWindowLimit,
    resultWindowMaxTotal,
    resultWindowOffset,
    setCanvasViewportWidth,
    setMessage,
    setResultWindow,
    setResultWindowLimit,
    setResultWindowOffset,
    studyKind,
  });
  async function refreshResults() {
    await primaryActionsController.refreshResults();
  }
  let mainCompositionRef: { recordHistory?: (action: string) => void } | null = null;
  function recordHistoryBridge(action: string) {
    mainCompositionRef?.recordHistory?.(action);
  }
  const sessionComposition = useWorkbenchSessionComposition({
    t,
    job,
    jobIsActive,
    jobPollTokenRef,
    setJob,
    setMessage,
    startTransition,
    resultRecords,
    projects,
    selectedProjectId,
    selectedModelId,
    modelVersions,
    setSidebarSection,
    directMeshEndpointsText,
    directMeshSelectionMode,
    frontendRuntimeMode,
    setHealth,
    setModelVersions,
    setProjects,
    setProtocolAgents,
    setSelectedModelId,
    setSelectedProjectId,
    setSelectedVersionId,
    refreshResults,
    securityEventWindowMs: SECURITY_EVENT_WINDOW_MS,
    setLibraryTab,
    activeMaterial,
    createProject,
    createModel,
    createModelVersion,
    updateModelVersion,
    fetchModel,
    fetchModelVersion,
    recordHistory: recordHistoryBridge,
    resetActiveResult: () => resetActiveResult(setResult, setJob),
    setLoadedModelName,
    setStudyKind,
    setAxialForm,
    setHeatBarModel,
    setHeatPlaneModel,
    setThermalBarModel,
    setThermalBeamModel,
    setThermalFrameModel,
    setThermalTrussModel,
    setThermalTruss3dModel,
    setSpringModel,
    setSpring2dModel,
    setSpring3dModel,
    setTrussModel,
    setTruss3dModel,
    setPlaneModel,
    setFrameModel,
    setBeamModel,
    setTorsionModel,
    setPlaneResultField,
    setParametric,
    setActiveMaterial,
    projectNameDraft,
    projectDescriptionDraft,
    loadedModelName,
    studyKind,
    axialForm,
    heatBarModel,
    heatPlaneModel,
    thermalBarModel,
    thermalBeamModel,
    thermalFrameModel,
    thermalTrussModel,
    trussModel,
    thermalTruss3dModel,
    truss3dModel,
    planeModel,
    frameModel,
    beamModel,
    torsionModel,
    springModel,
    spring2dModel,
    spring3dModel,
    parametric,
    round,
    updateProject,
    deleteProject,
    updateModel,
    deleteModel,
    deleteModelVersion,
    fetchModelVersions,
    fetchJobStatus,
    serializeCurrentModel: () =>
      serializeCurrentModel(
        studyKind,
        loadedModelName,
        activeMaterial,
        axialForm,
        heatBarModel,
        heatPlaneModel,
        thermalBarModel,
        thermalBeamModel,
        thermalFrameModel,
        thermalTrussModel,
        trussModel,
        thermalTruss3dModel,
        truss3dModel,
        planeModel,
        frameModel,
        beamModel,
        torsionModel,
        springModel,
        spring2dModel,
        spring3dModel,
        parametric,
        round,
      ),
  });
  const {
    jobHistoryController,
    adminSecurityState,
    workflowController,
    selectedProject,
    selectedProjectModels,
    selectedAdminJob,
    selectedAdminResult,
    deferredProjectModels,
    deferredModelVersions,
    deferredJobHistory,
    deferredResultRecords,
    refreshHealth,
    refreshProjects,
    refreshSecurityEvents,
    refreshVersions,
    projectFlows,
  } = sessionComposition;
  const {
    jobHistory,
    setJobHistory,
    selectedAdminJobId,
    setSelectedAdminJobId,
    refreshJobHistory,
    cancelCurrentJob,
  } = jobHistoryController;
  const {
    selectedAdminResultJobId,
    setSelectedAdminResultJobId,
    adminFilterProjectId,
    setAdminFilterProjectId,
    adminFilterModelVersionId,
    setAdminFilterModelVersionId,
    securityEventRecords,
    setSecurityEventRecords,
    scriptRecordingMode,
    setScriptRecordingMode,
    securityEventWindowFilter,
    setSecurityEventWindowFilter,
    securityEventSourceFilter,
    setSecurityEventSourceFilter,
    securityEventRiskFilter,
    setSecurityEventRiskFilter,
    securityEventStatusFilter,
    setSecurityEventStatusFilter,
    securityEventActionFilter,
    setSecurityEventActionFilter,
    adminJobMessage,
    setAdminJobMessage,
    adminJobProjectId,
    setAdminJobProjectId,
    adminJobModelVersionId,
    setAdminJobModelVersionId,
    adminJobCaseId,
    setAdminJobCaseId,
    adminResultDraft,
    setAdminResultDraft,
  } = adminSecurityState;
  const {
    workflowCatalog,
    workflowCatalogBusy,
    workflowPanelTab,
    setWorkflowPanelTab,
    selectedWorkflowId,
    setSelectedWorkflowId,
    workflowRuns,
    setWorkflowRuns,
    selectedWorkflow,
    latestWorkflowSummary,
    refreshWorkflowCatalog,
    runWorkflowCatalogEntry,
  } = workflowController;
  const studyResultDerived = useWorkbenchStudyResultDerived({
    studyKind,
    result,
    job,
    resultWindow,
    t,
    selectedNode,
    selectedElement,
    axialForm,
    heatBarModel,
    heatPlaneModel,
    thermalBarModel,
    thermalBeamModel,
    thermalFrameModel,
    thermalTrussModel,
    thermalTruss3dModel,
    springModel,
    spring2dModel,
    spring3dModel,
    trussModel,
    truss3dModel,
    planeModel,
    frameModel,
    beamModel,
    torsionModel,
    beamResultField,
    frameResultField,
    planeResultField,
    planeHotspotLimit,
    language,
    loadedModelName,
    downloadTextFile,
    setMessage,
    health,
    frontendRuntimeMode,
    directMeshSelectionMode,
    directMeshExecution,
    directMeshApiToken,
    protocolAgents,
    hiddenMaterials,
    deferredJobHistory,
    deferredResultRecords,
    deferredProjectModels,
    deferredModelVersions,
    adminFilterProjectId,
    adminFilterModelVersionId,
    jobHistory,
    projects,
    securityEventRecords,
    securityEventWindowFilter,
    formatTime,
    formatMilliseconds,
    round,
    resultWindowLimit,
    resultWindowMaxTotal,
    resultWindowOffset,
    directMeshEndpointsText,
    immersiveViewport,
    immersiveToolDrawerOpen,
    immersiveHelpDrawerOpen,
    showShortcutHints,
  });
  const downloadResultJson = () => {
    downloadWorkbenchResultJson(resultExportEffects);
  };

  const downloadResultCsv = () => {
    downloadWorkbenchResultCsv(resultExportEffects);
  };

  const downloadPlaneHotspotSummary = () => {
    downloadWorkbenchPlaneHotspotSummary(resultExportEffects);
  };

  const downloadFrameHotspotSummary = () => {
    downloadWorkbenchFrameHotspotSummary(resultExportEffects);
  };

  const downloadFrameForceSummary = () => {
    downloadWorkbenchFrameForceSummary(resultExportEffects);
  };

  const railItems: Array<{ key: SidebarSection; label: string; symbol: string }> = [
    { key: "model", label: t.rail.model, symbol: "M" },
    { key: "workflow", label: t.rail.workflow, symbol: "W" },
    { key: "library", label: t.rail.library, symbol: "H" },
    { key: "system", label: t.rail.system, symbol: "Y" },
  ];

  const { adminDataEffects, projectStorageController } = projectFlows;

  const {
    isAxial,
    isHeatBar,
    isHeatPlaneTriangle,
    isHeatPlaneQuad,
    isHeatPlane,
    isThermalBar,
    isThermalBeam,
    isThermalFrame,
    isThermalTruss2d,
    isThermalTruss3d,
    isThermalPlaneTriangle,
    isThermalPlaneQuad,
    isThermal,
    isSpring1d,
    isSpring2d,
    isSpring3d,
    isSpring,
    isBeam,
    isTorsion,
    isTruss,
    isTruss3d,
    isFrame,
    isFrameLike,
    isPlane,
    axialResult,
    heatBarResult,
    heatPlaneTriangleResult,
    heatPlaneQuadResult,
    thermalBarResult,
    thermalBeamResult,
    thermalFrameResult,
    thermalTrussResult,
    thermalTruss3dResult,
    springResult,
    spring2dResult,
    spring3dResult,
    activeSpringResult,
    activeSpringModel,
    trussResult,
    truss3dResult,
    beamResult,
    activeBeamLikeResult,
    activeBeamLikeModel,
    torsionResult,
    frameResult,
    activeFrameLikeResult,
    activeFrameLikeModel,
    planeResult,
    activePlaneInputModel,
    activeResultWindow,
    trussDiagnostics,
    trussStability,
    axialNodes,
    axialElements,
    axialLength,
    axialScale,
    planeWindowNodes,
    planeWindowElements,
    trussWindowNodes,
    trussWindowElements,
    thermalTrussWindowNodes,
    thermalTrussWindowElements,
    truss3dWindowNodes,
    truss3dWindowElements,
    beamWindowNodes,
    beamWindowElements,
    thermalBeamWindowNodes,
    thermalBeamWindowElements,
    torsionWindowNodes,
    torsionWindowElements,
    heatBarWindowNodes,
    heatBarWindowElements,
    thermalWindowNodes,
    thermalWindowElements,
    springWindowNodes,
    springWindowElements,
    spring2dWindowNodes,
    spring2dWindowElements,
    spring3dWindowNodes,
    spring3dWindowElements,
    frameWindowNodes,
    frameWindowElements,
    thermalFrameWindowNodes,
    thermalFrameWindowElements,
    displayTrussNodes,
    displayTrussElements,
    trussBounds,
    displayTruss3dNodes,
    displayTruss3dElements,
    planeNodes,
    planeElements,
    planeBounds,
    activeLineResultField,
    planeResultFieldMax,
    frameResultFieldMax,
    planeResultFieldLabel,
    planeLegendText,
    frameResultFieldLabel,
    frameLegendText,
    frameTreeValueLabel,
    planeHotspotElements,
    planeThermalRows,
    frameHotspotElements,
    frameForceRows,
    frameMaxAxialForce,
    frameMaxShearForce,
    selectedNodeData,
    selectedElementData,
    selectedTruss3dNodeData,
    selectedTruss3dElementData,
    selectedPlaneNodeData,
    selectedPlaneElementData,
    selectedFrameNodeData,
    selectedFrameElementData,
    selectedBeamNodeData,
    selectedBeamElementData,
    selectedTorsionNodeData,
    selectedTorsionElementData,
    selectedThermalNodeData,
    selectedThermalElementData,
    selectedSpringElementData,
    selectedNodeIssues,
    securityUi,
    resultExportEffects,
    thermalFrameMaxTemperatureDelta,
    thermalFrameMaxTemperatureGradient,
    thermalBeamMaxTemperatureGradient,
    heartbeatStatusValue,
    heartbeatToneValue,
    translatedFailureReason,
    currentMaterials,
    hiddenMaterialIds,
    materialColorMap,
    materialOptions,
    adminJobRows,
    adminResultRows,
    librarySampleRows,
    libraryModelRows,
    libraryVersionRows,
    libraryJobRows,
    protocolAgentCards,
    runtimeBackendRows,
    runtimeProtocolRows,
    runtimeProtocolMethods,
    runtimeSecurityRows,
    runtimeAuditEntries,
    runtimeAuditSummaryRows,
    runtimeAuditTrendBars,
    runtimeAuditSourceStatusFacets,
    runtimeAuditStudyFacets,
    runtimeAuditProjectFacets,
    runtimeAuditModelVersionFacets,
    runtimeWatchdogRows,
    trussElementColors,
    truss3dElementColors,
    planeElementColors,
    nodeCount,
    activeResultWindowLimit,
    resultWindowStart,
    resultWindowEnd,
    resultWindowJumps,
    hasViewportDock,
    showViewportToolStrip,
    shouldStretchSpaceViewport,
    viewportPixelWidth,
    directMeshEndpoints,
    hasAnyResult,
  } = bindWorkbenchStudyResultDerived(studyResultDerived);
  const mainComposition = useWorkbenchMainComposition({
    t,
    language,
    activeMaterial,
    setHiddenMaterials,
    setMessage,
    studyKind,
    activeFrameLikeModel,
    isFrameLike,
    isHeatPlane,
    isThermalFrame,
    isThermalTruss2d,
    isThermalTruss3d,
    memberDraftNodes,
    parametric,
    selectedElement,
    selectedNode,
    selectedTruss3dNodes,
    setFrameModel,
    setHeatPlaneModel,
    setMemberDraftNodes,
    setPlaneModel,
    setSelectedElement,
    setSelectedNode,
    setSelectedTruss3dNodes,
    setSidebarSection,
    setStudyKind,
    setThermalFrameModel,
    setThermalTruss3dModel,
    setThermalTrussModel,
    setTruss3dModel,
    setTrussModel,
    truss3dBatchLoadX,
    truss3dBatchLoadY,
    truss3dBatchLoadZ,
    truss3dModel,
    trussModel,
    isBeam,
    isTorsion,
    isHeatBar,
    isThermal,
    isThermalBar,
    truss3dLinkMode,
    trussBounds,
    draggingNode,
    dragHistoryCapturedRef,
    dragFrameRef,
    pendingDragPointRef,
    setTruss3dLinkMode,
    setDraggingNode,
    setActiveMaterial,
    setAxialForm,
    setParametric,
    setTorsionModel,
    setHeatBarModel,
    setBeamModel,
    projectStorageController,
    adminFilterModelVersionId,
    adminFilterProjectId,
    frontendRuntimeMode,
    health,
    heatBarModel,
    heatPlaneModel,
    immersiveHelpDrawerOpen,
    immersiveToolDrawerOpen,
    immersiveViewport,
    job,
    jobHistory,
    libraryTab,
    loadedModelName,
    modelTab,
    panelParametric,
    planeModel,
    projects,
    protocolAgents,
    redoStack,
    resultRecords,
    selectedAdminJobId,
    selectedAdminResultJobId,
    selectedModelId,
    selectedProjectId,
    selectedVersionId,
    setLanguagePacks,
    setStudyTab,
    sidebarSection,
    spring2dModel,
    spring3dModel,
    springModel,
    studyTab,
    systemDataTab,
    systemPanelTab,
    theme,
    thermalBarModel,
    thermalBeamModel,
    thermalFrameModel,
    thermalTrussModel,
    thermalTruss3dModel,
    torsionModel,
    truss3dBoxSelectMode,
    truss3dProjectionMode,
    truss3dViewPreset,
    undoStack,
    viewportPanelRef,
    setUndoStack,
    setRedoStack,
    setAssistantWindowOpen,
    setTheme,
    setFrontendRuntimeMode,
    setDirectMeshEndpointsText,
    setDirectMeshSelectionMode,
    setLibraryTab,
    setModelTab,
    setModelToolsPage,
    setSystemPanelTab,
    setSystemDataTab,
    setAdminFilterProjectId,
    setAdminFilterModelVersionId,
    setSelectedAdminJobId,
    setSelectedAdminResultJobId,
    setTruss3dViewPreset,
    setTruss3dProjectionMode,
    setTruss3dBoxSelectMode,
    setTruss3dShowGrid,
    setTruss3dShowLabels,
    setTruss3dShowNodes,
    setImmersiveToolDrawerOpen,
    setImmersiveHelpDrawerOpen,
    setTruss3dFocusRequestVersion,
    setTruss3dResetRequestVersion,
    workflowController,
    resetActiveResult: () => resetActiveResult(setResult, setJob),
    shellState,
    workspaceState,
    studyResultDerived,
    fixed,
    ensurePlaneModelMaterials,
    ensureBeamModelMaterials,
    ensureFrameModelMaterials,
    defaultPlaneQuad,
    defaultThermalPlaneQuad,
    defaultPlaneTriangle,
    defaultThermalPlaneTriangle,
    defaultHeatBar1d,
    defaultHeatPlaneQuad,
    defaultHeatPlaneTriangle,
    defaultThermalBar1d,
    defaultThermalBeam1d,
    defaultThermalFrame2d,
    defaultThermalTruss2d,
    defaultThermalTruss3d,
    defaultSpring1d,
    defaultSpring2d,
    defaultSpring3d,
    defaultBeam1d,
    defaultTorsion1d,
    defaultFrame2d,
    buildThermalBarFromHeatResult,
    buildThermalPlaneTriangleFromHeatResult,
    buildThermalPlaneQuadFromHeatResult,
    startTransition,
    resultRefreshSeqRef,
    fetchResults,
    jobPollTokenRef,
    refreshJobHistory,
    fetchJobStatus,
    updateJobRecord,
    deleteJobRecord,
    updateResultRecord,
    deleteResultRecord,
    downloadTextFile,
    jobIsActive,
    cancelCurrentJob,
    refreshHealth,
    refreshResults,
    refreshProjects,
    refreshSecurityEvents,
    refreshVersions,
    createProject,
    updateProject,
    deleteProject,
    createModel,
    updateModel,
    deleteModel,
    createModelVersion,
    updateModelVersion,
    deleteModelVersion,
    resolveTruss2dJobInput,
    resolveTruss3dJobInput,
    resolvePlaneQuad2dJobInput,
    resolvePlaneTriangle2dJobInput,
    round,
    downloadResultCsv,
    railItems,
    isPending,
    selectedProjectModels,
    securityEventRecords,
    securityEventWindowFilter,
    securityEventSourceFilter,
    securityEventRiskFilter,
    securityEventStatusFilter,
    securityEventActionFilter,
    setSecurityEventWindowFilter,
    setSecurityEventSourceFilter,
    setSecurityEventRiskFilter,
    setSecurityEventStatusFilter,
    setSecurityEventActionFilter,
    scriptRecordingMode,
    setScriptRecordingMode,
    selectedAdminJob,
    adminJobMessage,
    setAdminJobMessage,
    adminJobProjectId,
    setAdminJobProjectId,
    adminJobModelVersionId,
    setAdminJobModelVersionId,
    adminJobCaseId,
    setAdminJobCaseId,
    adminResultDraft,
    setAdminResultDraft,
    cancelJob,
    clampChunkOffset,
    canvasStageRef,
    resultWindowMaxTotal,
    handleCanvasStageScroll,
    downloadResultJson,
    downloadPlaneHotspotSummary,
    downloadFrameHotspotSummary,
    downloadFrameForceSummary,
    localMaterialLabel,
    activeLanguagePack,
  });
  mainCompositionRef = mainComposition;

  const {
    editControllers,
    interactionControllers,
    flowControllers,
    primaryActionsController,
    assistantController,
    topLevelActions,
    assistantAudit,
    uiActionController,
    toggleImmersiveViewport,
    recordHistory,
    handleLanguageChange,
    studyKindResetHandlers,
    projectHeatToThermoStudy,
    currentStudyFamilyHint,
    currentStudyFamilyLabel,
    canProjectHeatToThermo,
    thermalBoundaryValue,
    thermalIntentValue,
    handleModelToolsPageChange,
    sidebarMountProps,
    mainShellMountProps,
  } = bindWorkbenchMainComposition(mainComposition);

  const {
    addCustomMaterialToCurrentModel,
    addMaterialToCurrentModel,
    applyMaterialToCurrentModel,
    deleteCurrentMaterial,
    importMaterials,
    toggleMaterialVisibility,
    updateCurrentMaterial,
    addNode,
    applySelectedTruss3dLoads,
    assignSelectedElementMaterial,
    assignSelectedPlaneElementMaterial,
    assignSelectedTruss3dElementMaterial,
    cloneSelectedTruss3dNodes,
    deleteSelectedElement,
    deleteSelectedNode,
    deleteSelectedTruss3dElement,
    deleteSelectedTruss3dNode,
    nudgeSelectedTruss3dNodes,
    toggleMemberFromDraft,
    updateSelectedElement,
    updateSelectedNode,
    updateSelectedPlaneElement,
    updateSelectedPlaneNode,
    updateSelectedTruss3dElement,
    updateSelectedTruss3dNode,
    updateSelectedTruss3dNodes,
    addTruss3dNode,
    handleTruss3dNodePick,
    handleTruss3dNodesBoxSelect,
    handleTrussPointerMove,
    startTrussNodeDrag,
    stopDraggingNode,
    toggleDraftNode,
    toggleTruss3dLinkMode,
    toggleTruss3dMemberFromDraft,
    updateTruss3dNodePosition,
    handleMaterialChange,
    updateSelectedFrameNode,
    updateSelectedFrameElement,
    assignSelectedFrameElementMaterial,
    applyTrussSuggestion,
  } = editControllers;
  const {
    buildScriptSnapshot,
    buildSnapshot,
    restoreSnapshot,
    scriptSnapshot,
    handleUndo,
    handleRedo,
    handleDownloadLanguagePackTemplate,
    handleExportInstalledLanguagePack,
    handleImportLanguagePack,
    handleRemoveLanguagePack,
    downloadSecurityEventExport,
    downloadSecurityEventCsvExport,
  } = topLevelActions;
  const {
    assistantTransactions,
    appendScriptActionLog,
    executeAssistantPlan,
    getScriptSnapshot,
    recordManualDslAction,
    recordSecurityAuditEvent,
    rollbackAssistantTransaction,
    scriptActionLog,
    securityAuditLog,
  } = assistantAudit;
  const {
    clearAdminFilters,
    handleAdminFilterModelVersionChange,
    handleAdminFilterProjectChange,
    handleLibraryTabChange,
    handleModelTabChange,
    handleSelectAdminJob,
    handleSelectAdminResult,
    handleSidebarSectionChange,
    handleStudyTabChange,
    handleSystemDataTabChange,
    handleSystemPanelTabChange,
    handleToggleImmersiveHelpDrawer,
    handleToggleImmersiveToolDrawer,
    handleToggleImmersiveViewport,
    handleToggleTruss3dLinkMode,
    handleTruss3dBoxSelectModeChange,
    handleTruss3dFocusViewport,
    handleTruss3dProjectionModeChange,
    handleTruss3dResetViewport,
    handleTruss3dShowGridChange,
    handleTruss3dShowLabelsChange,
    handleTruss3dShowNodesChange,
    handleTruss3dViewPresetChange,
    handleWorkflowPanelTabChange,
    useCurrentProjectAsAdminFilter,
    useCurrentVersionAsAdminFilter,
  } = uiActionController;
  const {
    runAnalysis,
    openHistoryJob,
    importModel,
    openSample,
    handleAxialFieldChange,
    handleParametricChange,
    handlePanelParametricChange,
    generateModel,
    generatePanelModel,
    downloadModel,
    saveAdminJobRecord,
    deleteAdminJobRecord,
    saveAdminResultRecord,
    deleteAdminResultRecord,
    exportAdminResultRecord,
    openSelectedAdminJobVersion,
    openSelectedAdminResultVersion,
    openSelectedAdminJobProject,
    openSelectedAdminResultProject,
    applySelectedAdminJobContext,
    applySelectedAdminResultContext,
  } = primaryActionsController;
  const { assistantCards, assistantPromptPresets, requestLlmAssistantPlan } = assistantController;

  return (
    <div className="workbench-shell">
      <WorkbenchSidebarMount {...sidebarMountProps} />

      <WorkbenchMainShellMount {...mainShellMountProps} />
    </div>
  );
}
