import brand from "../../../../../assets/brand/brand.json";

export const copyEnExtended = {
    themes: { linen: "Workshop Slate", marine: "Blueprint Teal", graphite: "Blender Forge" },
    languages: { en: "English", zh: "中文", ja: "日本語", es: "Español" },
    frontendModes: {
      orchestrated_gui: "Orchestrated GUI",
      direct_mesh_gui: "Direct mesh GUI",
    },
    directMeshStrategies: {
      healthiest: "Healthiest agent",
      first_reachable: "First reachable",
    },
    shortcutLegendTitle: "3D controls",
    shortcutLegendRows: [
      "Drag pan · Alt+Drag orbit · Wheel zoom",
      "Shift+Wheel pans sideways",
      "1/2/3/4 views · P projection",
      "G grid · L labels · N nodes",
      "F focus · R reset · WASD/Arrows pan",
      "Link mode: click two nodes to toggle a member",
      "BOX selects visible nodes · Immersive button opens fullscreen",
    ],
    length: "Span (m)",
    area: "Area (m²)",
    modulus: "Young's modulus (GPa)",
    elements: "Elements",
    tipForce: "Tip force (N)",
    run: "Run Study",
    running: "Running...",
    ready: "ready",
    busy: "busy",
    tipDisp: "Tip displacement",
    maxStress: "Max stress",
    reaction: "Reaction",
    maxAxialForce: "Max axial force",
    maxShearForce: "Max shear force",
    displacementMagnitude: "Displacement magnitude",
    fixRz: "Fix Rz",
    momentZ: "Moment Z",
    rotationZ: "Rotation Z",
    frameElements: "Frame members",
    memberEndForces: "Member end forces",
    momentOfInertia: "Moment of inertia",
    sectionModulus: "Section modulus",
    distributedLoadY: "Distributed load Y",
    temperatureDelta: "Temperature delta",
    temperature: "Temperature",
    averageTemperature: "Average temperature",
    maxTemperature: "Max temperature",
    conductivity: "Conductivity",
    fixTemperature: "Fix temperature",
    heatLoad: "Heat load",
    temperatureGradientX: "Temperature gradient X",
    temperatureGradientY: "Temperature gradient Y",
    thermalIntent: "Thermal intent",
    thermalBoundary: "Thermal boundary",
    prescribedTemperatureNodes: "prescribed-T nodes",
    sourceNodes: "source nodes",
    heatedNodes: "heated nodes",
    gradientMembers: "gradient members",
    restrainedSupports: "restrained supports",
    thermalMembers: "thermal members",
    conductionField: "conduction field",
    heatSourceField: "heat-source field",
    nodalTemperatureRise: "nodal temperature rise",
    memberTemperatureGradient: "member temperature gradient",
    thermalBarResponse: "restrained bar response",
    thermalBeamResponse: "beam thermal response",
    thermalFrameResponse: "frame thermal response",
    thermalTrussResponse: "truss thermal response",
    thermoelasticPlaneResponse: "thermoelastic plane response",
    maxHeatFlux: "Max heat flux",
    heatFluxX: "Heat flux X",
    heatFluxY: "Heat flux Y",
    thermalCurvature: "Thermal curvature",
    thermalStrain: "Thermal strain",
    mechanicalStrain: "Mechanical strain",
    totalStrain: "Total strain",
    thermalExpansion: "Thermal expansion",
    bendingStress: "Max bending stress",
    combinedStress: "Combined stress",
    maxMoment: "Max moment",
    maxTorque: "Max torque",
    torsionStress: "Torsion stress",
    torqueZ: "Torque Z",
    torsionHint: "Shaft studies focus on twist, torque transmission, and shear stress along the axis.",
    maxRotation: "Max rotation",
    sortBy: "Sort by",
    shearForce: "Shear force",
    forceI: "Axial @ i",
    shearI: "Shear @ i",
    momentI: "Moment @ i",
    forceJ: "Axial @ j",
    shearJ: "Shear @ j",
    momentJ: "Moment @ j",
    principalStress1: "Principal stress 1",
    principalStress2: "Principal stress 2",
    maxInPlaneShear: "Max in-plane shear",
    currentField: "Current field",
    planeHotspots: "Top hot elements",
    topN: "Top N",
    exportHotspots: "Export hotspots",
    memberForceTable: "Member force table",
    elementHeatTable: "Element heat table",
    exportMemberForces: "Export member forces",
    planeResultLegend: "Fill: von Mises · Overlay: deformed shape",
    planeViewVonMises: "von Mises",
    planeViewPrincipal1: "Principal 1",
    planeViewMaxShear: "Max shear",
    progress: "Progress",
    iteration: "Iteration",
    residual: "Residual",
    worker: "Worker",
    status: "Status",
    nodes: "Nodes",
    axialElements: "Element results",
    trussElements: "Truss members",
    spatialTrussElements: "Space-truss members",
    span: "Span",
    stress: "Stress (Pa)",
    axialForce: "Axial force (N)",
    importedModel: "Imported model",
    importFailed: "Import failed",
    initialLoaded: `${brand.productName} connected to the orchestrator.`,
    initialFailed: "Unable to reach the orchestrator.",
    dispatching: "Submitting a study to the orchestrator.",
    defaultModel: "manual-study",
    online: "online",
    offline: "offline",
    historyHint: "Durable jobs survive orchestrator restarts.",
    historyEmpty: "No jobs yet.",
    openJob: "Open",
    refresh: "Refresh",
    resultWindow: "Result Window",
    previousPage: "Previous",
    nextPage: "Next",
    jumpStart: "Start",
    jumpQuarter: "25%",
    jumpMid: "50%",
    jumpThreeQuarter: "75%",
    jumpEnd: "End",
    pageRange: "Rows",
    chunkSize: "Chunk",
    totalElements: "Elements",
    projectLibrary: "Project Library",
    projectNameField: "Project name",
    projectDescriptionField: "Description",
    createProject: "Create project",
    updateProject: "Rename project",
    deleteProject: "Delete project",
    exportProject: "Export project",
    exportProjectJson: "Project JSON",
    exportProjectZip: "Project ZIP",
    importProject: "Import project",
    importProjectHint: "Load a .kyuubiki.json or .kyuubiki archive into the project library.",
    projectEmpty: "No projects yet.",
    savedModels: "Saved Models",
    versions: "Versions",
    save: "Save",
    saveAs: "Save As",
    deleteSavedModel: "Delete model",
    renameVersion: "Rename version",
    deleteVersion: "Delete version",
    exportData: "Export Data",
    exportJson: "JSON",
    exportCsv: "CSV",
    projectHeatToThermo: "Use temperatures in thermo study",
    projectHeatToThermoAction: "Mapped heat result into thermo study",
    projectedHeatToThermo: "Mapped the heat result into a thermo-mechanical study. Review supports and materials before solving.",
    noSavedModels: "No saved models in this project yet.",
    noVersions: "No saved versions yet.",
    defaultProject: "Workspace",
    projectCreated: "Project created.",
    projectUpdated: "Project updated.",
    projectDeleted: "Project deleted.",
    projectRequired: "Create or select a project before saving models.",
    projectExported: "Project bundle exported.",
    projectExportedPartial: "Project bundle exported with partial data. Some models or results could not be fetched in time.",
    databaseExported: "Database snapshot exported.",
    projectImported: "Project bundle imported.",
    modelSaved: "Saved a new model version.",
    modelCreated: "Saved a new model.",
    modelDeletedStored: "Deleted the saved model.",
    versionLoaded: "Loaded a saved version into the workbench.",
    persistedModelLoaded: "Loaded a saved model from the library.",
    versionRenamed: "Version renamed.",
    versionDeleted: "Version deleted.",
    resultJsonDownloaded: "Analysis result JSON downloaded.",
    resultCsvDownloaded: "Analysis result CSV downloaded.",
    jobCancelled: "Job cancelled.",
    noResultToExport: "Run a study first before exporting analysis data.",
    modelTools: "Editing Tools",
    dragHint: "Drag truss nodes directly in the viewport to reshape geometry.",
    planeHint: "Select plane nodes and triangles to edit supports, loads, and material thickness.",
    parametric: "Parametric Generator",
    panelGenerator: "Panel Generator",
    spaceStudio: "3D Space Studio",
    tabs: { summary: "Summary", controls: "Controls", tools: "Tools", tree: "Browse", jobs: "Jobs", results: "Results", models: "Models", projects: "Projects", samples: "Samples" },
    generate: "Generate",
    generatePanel: "Generate Panel",
    download: "Download JSON",
    saveForSolver: "Use current model",
    bays: "Bays",
    height: "Height (m)",
    divisionsX: "Divisions X",
    divisionsY: "Divisions Y",
    nodeTable: "Object browser",
    dragNode: "Selected node",
    noNodeSelected: "No node selected",
    loadCase: "Load case",
    modelStudioHint: "2D truss and 2D plane studies can be edited directly here. 3D studies can already be imported, solved, and reviewed.",
    frameEditorHint: "Frame studies are ready to import, solve, inspect, and review here. Rich member editing is the next step.",
    spaceStudioHint: "Use orbit, pan, and zoom to navigate the space frame. 3D nodes and members can be selected and edited numerically.",
    sourceModel: "Source model",
    createdAt: "Created",
    updatedAt: "Updated",
    hasResult: "Result",
    yes: "Yes",
    no: "No",
    jobWorkspaceTitle: "Job Workspace",
    jobWorkspaceHint: "Track solver runs first, then drill into a specific record only when you need the details.",
    resultWorkspaceTitle: "Results Workspace",
    resultWorkspaceHint: "Open the newest solved run here, then move into reports, exports, and linked records.",
    modelWorkspaceTitle: "Model Workspace",
    modelWorkspaceHint: "Keep saved studies and reusable versions together so you can reopen or branch them quickly.",
    openLatestJob: "Open latest job",
    openLatestResult: "Open latest result",
    openLatestModel: "Open latest model",
    waitingJobs: "Waiting result",
    readyResults: "Ready results",
    savedCount: "Saved models",
    versionCount: "Versions",
    dragToEdit: "Drag to edit",
    historyLoaded: "Loaded a persisted study from history.",
    modelDownloaded: "Model JSON downloaded.",
    generatedModel: "Generated a parametric truss model.",
    planeElements: "Plane elements",
    thickness: "Thickness",
    poisson: "Poisson ratio",
    poissonRatio: "Poisson ratio",
    sampleLibrary: "Sample Library",
    objectTree: "Objects",
    geometry: "Geometry",
    results: "Results",
    summary: "Summary",
    properties: "Properties",
    diagnostics: "Diagnostics",
    diagnosticsClear: "No blocking issues detected.",
    integrityMissingNodes: "Add at least one node before solving.",
    integrityMissingElements: "Add at least one element before solving.",
    integrityDuplicateNodeId: 'Node "{id}" appears more than once.',
    integrityDuplicateElementId: 'Element "{id}" appears more than once.',
    integrityDuplicateMaterialId: 'Material "{id}" appears more than once.',
    integrityMissingNodeReference: 'Element "{id}" references a missing node.',
    integrityMissingMaterialReference: 'Element "{id}" references missing material "{materialId}".',
    integrityInvalidNodeField: 'Node "{id}" has an invalid "{field}" value.',
    integrityInvalidElementField: 'Element "{id}" has an invalid "{field}" value.',
    integrityDegenerateLineElement: 'Element "{id}" has zero or near-zero length.',
    integrityDegenerateSurfaceElement: 'Element "{id}" has zero or near-zero area.',
    suggestedFixes: "Suggested fixes",
    stabilityScore: "Stability score",
    hotspotNodes: "Hotspot nodes",
    stabilityGood: "Stable",
    stabilityWatch: "Watch",
    stabilityRisk: "At risk",
    translatedSmallDeformation:
      "The structure is behaving too softly for a small-deformation solve. Add supports or reinforce the weak span.",
    translatedConnectivity:
      "The truss likely has a weak or disconnected region. Check supports, member links, and isolated nodes.",
    translatedSingular:
      "The stiffness matrix is singular. The model is still acting like a mechanism, so it needs more restraints or diagonal bracing.",
    translatedWatchdogStalled:
      "The job stopped reporting progress for too long. The watchdog marked it as stalled.",
    translatedWatchdogTimedOut:
      "The job ran too long and was stopped by the watchdog timeout.",
    translatedExecutionTimedOut:
      "The solver took too long to respond. The run was timed out and stopped safely.",
    translatedAgentTimeout:
      "The solver agent did not respond in time. Check the agent process or try the run again.",
    requestTimedOut: "The request took too long. The workbench kept the last stable state.",
    pollingDetached: "Live polling paused to keep the UI responsive. Refresh the job state when ready.",
    heartbeatHealthy: "healthy",
    heartbeatQuiet: "quiet",
    heartbeatStale: "stale",
    mechanismRisk: "This topology still looks mechanism-prone. Add more triangulation or extra supports before solving.",
    addNode: "Add Node",
    addBranchNode: "Branch Node",
    linkMode: "Link Mode",
    linkModeActive: "Linking",
    linkModeIdle: "Pick two nodes in the 3D viewport to link or unlink them.",
    linkModeEnabled: "3D link mode enabled.",
    linkModeDisabled: "3D link mode disabled.",
    linkModeCompleted: "3D link edit applied.",
    deleteNode: "Delete Node",
    addMember: "Add Member",
    toggleMember: "Toggle Link",
    deleteMember: "Delete Member",
    selectTwoNodes: "Select two nodes to create a member.",
    memberCreated: "Member created.",
    memberRemoved: "Member removed.",
    nodeCreated: "Node created.",
    branchCreated: "Node created and linked.",
    nodeDeleted: "Node deleted.",
    memberDeleted: "Member deleted.",
    selectionHint: "Use the object tree or viewport to pick nodes and members.",
    memberSelection: "Member selection",
    noElementSelected: "No member selected",
    nodeX: "Node X",
    nodeY: "Node Y",
    nodeZ: "Node Z",
    fixX: "Fix X",
    fixY: "Fix Y",
    fixZ: "Fix Z",
    loadX: "Load X",
    loadY: "Load Y",
    loadZ: "Load Z",
    nodeI: "Node I",
    nodeJ: "Node J",
    nodeK: "Node K",
    none: "None",
    precheckPrefix: "Precheck failed",
    unstableSupport: "Add at least two restrained degrees of freedom to stabilize the truss.",
    isolatedNode: "Every node should connect to at least one member before solving.",
    underconnected: "This truss is under-connected for a stable 2D solve.",
    freeRigidBody: "Prevent rigid-body motion by constraining both translation directions across the model.",
    supportXMissing: "Add at least one X restraint to prevent sideways drift.",
    supportYMissing: "Add at least one Y restraint to prevent vertical drift.",
    fixCurrentNodeXAction: "Fix current node in X",
    fixCurrentNodeYAction: "Fix current node in Y",
    fixNodeXAction: "Fix flagged node in X",
    fixNodeYAction: "Fix flagged node in Y",
    releaseX: "Release X",
    releaseY: "Release Y",
    releaseZ: "Release Z",
    connectCurrentNodeAction: "Connect current node to nearest node",
    connectNodeAction: "Connect flagged node to nearest node",
    suggestionAppliedSupportX: "Added an X restraint to the suggested node.",
    suggestionAppliedSupportY: "Added a Y restraint to the suggested node.",
    suggestionAppliedLink: "Connected the node to its nearest available neighbor.",
    suggestionNoLinkTarget: "No valid nearby node was available for an automatic link.",
    panelGenerated: "Generated a rectangular plane mesh.",
    planeThickness: "Thickness",
    orbitHint: "Drag to pan, Alt+drag to orbit, scroll to zoom.",
    spaceNodeCreated: "3D node created.",
    spaceBranchCreated: "3D node created and linked.",
    spaceNodeDeleted: "3D node deleted.",
    spaceMemberDeleted: "3D member deleted.",
    switchedTo2dStudio: "Switched to the 2D workbench.",
    switchedTo3dStudio: "Switched to the 3D space studio.",

} as const;
