"use client";

import { buildWorkbenchFlowControllerProps } from "@/components/workbench/workbench-flow-controller-props";
import {
  applyJobContextToWorkbench as applyJobContextToWorkbenchWithDeps,
  openProjectContextById as openProjectContextByIdWithDeps,
  resolveScriptLinkedJob as resolveScriptLinkedJobWithDeps,
} from "@/components/workbench/workbench-admin-data-controller";
import type { JobState } from "@/lib/api";

export function buildWorkbenchFlowComposition(props: Record<string, any>) {
  const { shellState, workspaceState, studyResultDerived, interactionControllers, projectFlows } = props;
  const { assistantAudit, topLevelActions, uiActionController, toggleImmersiveViewport } = interactionControllers;

  return buildWorkbenchFlowControllerProps({
    t: props.t,
    setMessage: workspaceState.setMessage,
    recordHistory: props.recordHistory,
    setAxialForm: workspaceState.setAxialForm,
    setParametric: workspaceState.setParametric,
    setPanelParametric: workspaceState.setPanelParametric,
    startTransition: props.startTransition,
    resultRefreshSeqRef: props.resultRefreshSeqRef,
    fetchResults: props.fetchResults,
    setResultRecords: workspaceState.setResultRecords,
    setSelectedAdminResultJobId: props.setSelectedAdminResultJobId,
    directMeshEndpointsText: shellState.directMeshEndpointsText,
    directMeshSelectionMode: shellState.directMeshSelectionMode,
    frontendRuntimeMode: shellState.frontendRuntimeMode,
    jobPollTokenRef: props.jobPollTokenRef,
    selectedProjectId: workspaceState.selectedProjectId,
    selectedVersionId: workspaceState.selectedVersionId,
    setDirectMeshExecution: shellState.setDirectMeshExecution,
    setJob: workspaceState.setJob,
    setResult: workspaceState.setResult,
    studyKind: workspaceState.studyKind,
    axialForm: workspaceState.axialForm,
    beamModel: workspaceState.beamModel,
    frameModel: workspaceState.frameModel,
    heatBarModel: workspaceState.heatBarModel,
    heatPlaneModel: workspaceState.heatPlaneModel,
    planeModel: workspaceState.planeModel,
    springModel: workspaceState.springModel,
    spring2dModel: workspaceState.spring2dModel,
    spring3dModel: workspaceState.spring3dModel,
    thermalBarModel: workspaceState.thermalBarModel,
    thermalBeamModel: workspaceState.thermalBeamModel,
    thermalFrameModel: workspaceState.thermalFrameModel,
    thermalTrussModel: workspaceState.thermalTrussModel,
    thermalTruss3dModel: workspaceState.thermalTruss3dModel,
    torsionModel: workspaceState.torsionModel,
    trussModel: workspaceState.trussModel,
    truss3dModel: workspaceState.truss3dModel,
    trussDiagnostics: studyResultDerived.trussDiagnostics,
    refreshJobHistory: props.refreshJobHistory,
    fetchJobStatus: props.fetchJobStatus,
    setSidebarSection: workspaceState.setSidebarSection,
    setWorkflowPanelTab: props.workflowController.setWorkflowPanelTab,
    setSelectedWorkflowId: props.workflowController.setSelectedWorkflowId,
    setWorkflowRuns: props.workflowController.setWorkflowRuns,
    openWorkspaceStudy: props.openWorkspaceStudy,
    setStudyKind: workspaceState.setStudyKind,
    setHeatBarModel: workspaceState.setHeatBarModel,
    setHeatPlaneModel: workspaceState.setHeatPlaneModel,
    setThermalBarModel: workspaceState.setThermalBarModel,
    setThermalBeamModel: workspaceState.setThermalBeamModel,
    setThermalFrameModel: workspaceState.setThermalFrameModel,
    setThermalTrussModel: workspaceState.setThermalTrussModel,
    setThermalTruss3dModel: workspaceState.setThermalTruss3dModel,
    setSpringModel: workspaceState.setSpringModel,
    setSpring2dModel: workspaceState.setSpring2dModel,
    setSpring3dModel: workspaceState.setSpring3dModel,
    setTrussModel: workspaceState.setTrussModel,
    setTruss3dModel: workspaceState.setTruss3dModel,
    setPlaneModel: workspaceState.setPlaneModel,
    setFrameModel: workspaceState.setFrameModel,
    setBeamModel: workspaceState.setBeamModel,
    setTorsionModel: workspaceState.setTorsionModel,
    setPlaneResultField: workspaceState.setPlaneResultField,
    setLoadedModelName: workspaceState.setLoadedModelName,
    setSelectedModelId: workspaceState.setSelectedModelId,
    setSelectedVersionId: workspaceState.setSelectedVersionId,
    setModelVersions: workspaceState.setModelVersions,
    setActiveMaterial: workspaceState.setActiveMaterial,
    setSelectedNode: workspaceState.setSelectedNode,
    setSelectedElement: workspaceState.setSelectedElement,
    setMemberDraftNodes: workspaceState.setMemberDraftNodes,
    activeMaterial: workspaceState.activeMaterial,
    round: props.round,
    parametric: workspaceState.parametric,
    panelParametric: workspaceState.panelParametric,
    loadedModelName: workspaceState.loadedModelName,
    updateJobRecord: props.updateJobRecord,
    deleteJobRecord: props.deleteJobRecord,
    selectedAdminJobId: props.selectedAdminJobId,
    adminJobMessage: props.adminJobMessage,
    adminJobProjectId: props.adminJobProjectId,
    adminJobModelVersionId: props.adminJobModelVersionId,
    adminJobCaseId: props.adminJobCaseId,
    updateResultRecord: props.updateResultRecord,
    deleteResultRecord: props.deleteResultRecord,
    adminResultDraft: props.adminResultDraft,
    downloadTextFile: props.downloadTextFile,
    adminDataEffects: projectFlows.adminDataEffects,
    language: shellState.language,
    directMeshEndpoints: studyResultDerived.directMeshEndpoints,
    health: props.health,
    jobIsActive: props.jobIsActive,
    isTruss: studyResultDerived.isTruss,
    isTruss3d: studyResultDerived.isTruss3d,
    immersiveViewport: shellState.immersiveViewport,
    hasAnyResult: studyResultDerived.hasAnyResult,
    cancelCurrentJob: props.cancelCurrentJob,
    applyTrussSuggestion: props.applyTrussSuggestion,
    assistantApiBaseUrl: shellState.assistantApiBaseUrl,
    assistantApiKey: shellState.assistantApiKey,
    assistantModel: shellState.assistantModel,
    getScriptSnapshot: assistantAudit.getScriptSnapshot,
    downloadResultCsv: props.downloadResultCsv,
    toggleImmersiveViewport,
    setLibraryTab: workspaceState.setLibraryTab,
    setSystemPanelTab: workspaceState.setSystemPanelTab,
    refreshHealth: props.refreshHealth,
    setTheme: shellState.setTheme,
    setFrontendRuntimeMode: shellState.setFrontendRuntimeMode,
    setDirectMeshEndpointsText: shellState.setDirectMeshEndpointsText,
    setDirectMeshSelectionMode: shellState.setDirectMeshSelectionMode,
    refreshResults: props.refreshResults,
    refreshProjects: props.refreshProjects,
    refreshSecurityEvents: props.refreshSecurityEvents,
    projectNameDraft: workspaceState.projectNameDraft,
    projectDescriptionDraft: workspaceState.projectDescriptionDraft,
    setProjectNameDraft: workspaceState.setProjectNameDraft,
    setProjectDescriptionDraft: workspaceState.setProjectDescriptionDraft,
    refreshVersions: props.refreshVersions,
    downloadProjectBundleJson: props.downloadProjectBundleJson,
    downloadProjectBundleZip: props.downloadProjectBundleZip,
    createProject: props.createProject,
    updateProject: props.updateProject,
    deleteProject: props.deleteProject,
    createModel: props.createModel,
    updateModel: props.updateModel,
    deleteModel: props.deleteModel,
    createModelVersion: props.createModelVersion,
    updateModelVersion: props.updateModelVersion,
    deleteModelVersion: props.deleteModelVersion,
    handleLanguageChange: props.handleLanguageChange,
    studyKindResetHandlers: props.studyKindResetHandlers,
    handleSidebarSectionChange: uiActionController.handleSidebarSectionChange,
    setStudyTab: workspaceState.setStudyTab,
    setModelTab: workspaceState.setModelTab,
    setModelToolsPage: workspaceState.setModelToolsPage,
    setAssistantWindowOpen: shellState.setAssistantWindowOpen,
    setSystemDataTab: workspaceState.setSystemDataTab,
    ensureFrameModelMaterials: props.ensureFrameModelMaterials,
    ensureBeamModelMaterials: props.ensureBeamModelMaterials,
    resolveTruss2dJobInput: props.resolveTruss2dJobInput,
    resolveTruss3dJobInput: props.resolveTruss3dJobInput,
    resolvePlaneQuad2dJobInput: props.resolvePlaneQuad2dJobInput,
    resolvePlaneTriangle2dJobInput: props.resolvePlaneTriangle2dJobInput,
    projectHeatToThermoStudy: props.projectHeatToThermoStudy,
    handleUndo: topLevelActions.handleUndo,
    handleRedo: topLevelActions.handleRedo,
    setTruss3dLinkMode: workspaceState.setTruss3dLinkMode,
    setTruss3dFocusRequestVersion: shellState.setTruss3dFocusRequestVersion,
    setTruss3dResetRequestVersion: shellState.setTruss3dResetRequestVersion,
    setTruss3dShowGrid: shellState.setTruss3dShowGrid,
    setTruss3dShowLabels: shellState.setTruss3dShowLabels,
    setTruss3dShowNodes: shellState.setTruss3dShowNodes,
    setImmersiveToolDrawerOpen: shellState.setImmersiveToolDrawerOpen,
    setImmersiveHelpDrawerOpen: shellState.setImmersiveHelpDrawerOpen,
    setTruss3dBoxSelectMode: shellState.setTruss3dBoxSelectMode,
    setTruss3dViewPreset: shellState.setTruss3dViewPreset,
    setTruss3dProjectionMode: shellState.setTruss3dProjectionMode,
    setAdminFilterProjectId: props.setAdminFilterProjectId,
    setAdminFilterModelVersionId: props.setAdminFilterModelVersionId,
    setSelectedAdminJobId: props.setSelectedAdminJobId,
    resolveScriptLinkedJob: (nextPayload: Record<string, unknown>) =>
      resolveScriptLinkedJobWithDeps(nextPayload, projectFlows.adminDataEffects),
    openModelVersionById: projectFlows.projectStorageController.openModelVersionById,
    openProjectContextById: (projectId: string) => openProjectContextByIdWithDeps(projectId, projectFlows.adminDataEffects),
    applyJobContextToWorkbench: (linkedJob: JobState) =>
      applyJobContextToWorkbenchWithDeps(linkedJob, projectFlows.adminDataEffects),
    downloadDatabaseSnapshot: props.downloadDatabaseSnapshot,
    recordSecurityAuditEvent: assistantAudit.recordSecurityAuditEvent,
    appendScriptActionLog: assistantAudit.appendScriptActionLog,
  });
}
