export const workbenchScriptPanelCopyEl = {
  title: "Pwdt",
  subtitle: "Εργαλεία Python WASM DSL με Pyodide και τον καταχωρισμένο κατάλογο ενεργειών του προγράμματος περιήγησης.",
  frontendSurface: "Αυτοματισμός διεπαφής",
  frontendSurfaceHint: "Αυτοματισμός στο πρόγραμμα περιήγησης, καταγραφή μακροεντολών, επανάληψη και αποσφαλμάτωση της διεπαφής.",
  headlessSurface: "SDK χωρίς γραφική διεπαφή",
  headlessSurfaceHint: "Ο παρακάτω ανεξάρτητος επεξεργαστής ροών εργασίας αφορά τον αυτοματισμό υπηρεσιών και επιλυτών χωρίς γραφική διεπαφή.",
  launch: "Εκκίνηση",
  author: "Σύνταξη",
  inspect: "Επιθεώρηση",
  catalog: "Κατάλογος",
  scriptMode: "Σκριπτ",
  recordMode: "Καταγραφή",
  outputMode: "Έξοδος",
  timelineMode: "Χρονογραμμή",
  snapshotMode: "Στιγμιότυπο",
  presetsMode: "Προεπιλογές",
  actionsMode: "Ενέργειες",
  macrosMode: "Μακροεντολές",
  authorScriptHint: "Γράψτε ή προσαρμόστε εδώ σκριπτ αυτοματισμού της διεπαφής.",
  authorRecordHint: "Καταγράψτε ενέργειες της διεπαφής, μετατρέψτε τις πρόσφατες ενέργειες σε προσχέδια μακροεντολών και εισαγάγετέ τα στο σκριπτ.",
  inspectOutputHint: "Εδώ εμφανίζονται η έξοδος εκτέλεσης και τα μηνύματα του περιβάλλοντος εκτέλεσης.",
  inspectTimelineHint: "Οι πρόσφατες ενέργειες της διεπαφής εμφανίζονται σε χρονογραμμή με δυνατότητα επανάληψης.",
  inspectSnapshotHint: "Η ζωντανή κατάσταση του Workbench βοηθά τα σκριπτ να εξετάζουν και να αποσφαλματώνουν τη διεπαφή.",
  inspectTimelineDetailHint: "Επιλέξτε μια ενέργεια για να εξετάσετε αναλυτικά τα δεδομένα, το αποτέλεσμα και το πλαίσιο επανάληψής της.",
  insertActionStep: "Εισαγωγή βήματος",
  insertTimelineMacroDraft: "Εισαγωγή προσχεδίου μακροεντολής",
  sendTimelineMacroToHeadless: "Αποστολή στη ροή εργασίας",
  saveTimelineMacroPreset: "Αποθήκευση ως προεπιλογή",
  noTimelineSelection: "Επιλέξτε μια ενέργεια της χρονογραμμής για να δείτε όλες τις λεπτομέρειες.",
  timelineFailed: "Απέτυχε",
  timelineCompleted: "Ολοκληρώθηκε",
  timelineStarted: "Ξεκίνησε",
  failureReason: "Αιτία αποτυχίας",
  continueFromStep: "Συνέχεια από εδώ",
  timelineRangePreview: "Προεπισκόπηση περιοχής",
  timelinePreviewSteps: "Βήματα χρονογραμμής",
  timelinePreviewMacroSteps: "Βήματα μακροεντολής",
  timelinePreviewIncluded: "Συμπεριλαμβάνεται",
  timelinePreviewIncludedYes: "Ναι",
  timelinePreviewIncludedNo: "Όχι",
  timelinePreviewNotEligible: "Μόνο πληροφορίες πλαισίου",
  includeTimelineStep: "Συμπερίληψη",
  excludeTimelineStep: "Εξαίρεση",
  selectAllTimelineSteps: "Επιλογή όλων",
  clearTimelineSteps: "Εκκαθάριση",
  focusFailureWindow: "Εστίαση στις αποτυχίες",
  timelineMacroDraftInserted: "Εισήχθη προσχέδιο μακροεντολής από την επιλεγμένη περιοχή της χρονογραμμής.",
  noTimelineMacroDraft: "Αυτή η περιοχή της χρονογραμμής δεν περιέχει ακόμη επαναχρησιμοποιήσιμα εκτελέσιμα βήματα.",
  timelineMacroPresetSaved: "Η επιλεγμένη περιοχή της χρονογραμμής αποθηκεύτηκε ως προεπιλογή έργου.",
  restoreBridgeMacroToFrontend: "Ο κόμβος γέφυρας επανήλθε στον χώρο αυτοματισμού της διεπαφής.",
  frontendMacroAssetInserted: "Ο πόρος μακροεντολής της διεπαφής φορτώθηκε ξανά στον επεξεργαστή.",
  frontendMacroAssetDerived: "Δημιουργήθηκε νέο επεξεργάσιμο προσχέδιο μακροεντολής από το επιλεγμένο στιγμιότυπο.",
  frontendMacroAssets: "Πόροι μακροεντολών διεπαφής",
  frontendMacroAssetsEmpty: "Δεν έχουν προστεθεί ακόμη πόροι μακροεντολών διεπαφής.",
  deriveFrontendMacroAsset: "Δημιουργία νέου προσχεδίου",
  snapshotCompare: "Σύγκριση στιγμιοτύπων",
  snapshotCompareEmpty: "Επιλέξτε δύο στιγμιότυπα για σύγκριση των βημάτων και των αλλαγών στα δεδομένα τους.",
  snapshotCompareChangedSteps: "Τροποποιημένα βήματα",
  snapshotCompareSame: "Ίδιο",
  snapshotCompareChanged: "Τροποποιημένο",
  snapshotCompareMissing: "Λείπει",
  snapshotCompareStepMissing: "Το βήμα δεν υπάρχει σε αυτό το στιγμιότυπο",
  snapshotComparePayloadChanged: "Τα δεδομένα αυτού του βήματος άλλαξαν.",
  snapshotCompareActionChanged: "Το αναγνωριστικό ενέργειας αυτού του βήματος άλλαξε.",
  compareLeftAsset: "Ορισμός ως αριστερό",
  compareRightAsset: "Ορισμός ως δεξί",
  clearCompareLeft: "Εκκαθάριση αριστερού",
  clearCompareRight: "Εκκαθάριση δεξιού",
  assetSnapshotId: "Αναγνωριστικό στιγμιοτύπου",
  assetSource: "Πηγή",
  assetUpdatedAt: "Ενημερώθηκε",
  assetSourceTimeline: "Επιλογή χρονογραμμής",
  assetSourceBridge: "Επαναφορά γέφυρας",
  assetSourceDerived: "Προέλευση από το ιστορικό",
  catalogHint: "Επαναχρησιμοποιήσιμοι πόροι αυτοματισμού διεπαφής: προεπιλογές έργου, αποσπάσματα ενεργειών και μακροεντολές.",
  runtime: "Περιβάλλον εκτέλεσης",
  loading: "Φόρτωση",
  ready: "Έτοιμο",
  idle: "Σε αδράνεια",
  running: "Εκτελείται",
  error: "Σφάλμα",
  sessionStorageFailed: "Δεν ήταν δυνατή η αποθήκευση της συνεδρίας του επεξεργαστή. Τα υπάρχοντα δεδομένα σκριπτ δεν άλλαξαν.",
  firstRun: "Η πρώτη εκτέλεση κατεβάζει το περιβάλλον Pyodide στην προσωρινή μνήμη του προγράμματος περιήγησης.",
  loadRuntime: "Φόρτωση περιβάλλοντος εκτέλεσης",
  resetScript: "Επαναφορά προτύπου",
  runScript: "Εκτέλεση σκριπτ",
  clearOutput: "Εκκαθάριση εξόδου",
  startRecording: "Έναρξη καταγραφής",
  stopRecording: "Διακοπή καταγραφής",
  recordingActive: "Οι χειροκίνητες ενέργειες της διεπαφής καταγράφονται στη ροή συμβάντων DSL.",
  exportMacroJson: "Εξαγωγή μακροεντολής JSON",
  importMacroJson: "Εισαγωγή μακροεντολής JSON",
  macroJsonExported: "Η τρέχουσα καταγεγραμμένη μακροεντολή εξήχθη σε JSON.",
  macroJsonImported: "Εισήχθη προσχέδιο μακροεντολής JSON στον επεξεργαστή.",
  headlessWorkflowImported: "Εισήχθη σύμβαση ροής εργασίας χωρίς γραφική διεπαφή ως εκτελέσιμο προσχέδιο μακροεντολής.",
  projectPresets: "Προεπιλογές έργου",
  presetName: "Όνομα προεπιλογής",
  presetNamePlaceholder: "έλεγχος πλαισίου τρέχοντος αποτελέσματος",
  savePreset: "Αποθήκευση προεπιλογής",
  insertPreset: "Εισαγωγή προεπιλογής",
  exportPresetJson: "Εξαγωγή προεπιλογής JSON",
  deletePreset: "Διαγραφή προεπιλογής",
  noProjectSelected: "Επιλέξτε πρώτα έργο για να αποθηκεύσετε προεπιλογές στο πλαίσιό του.",
  noPresetDraft: "Δημιουργήστε ή εισαγάγετε πρώτα ένα προσχέδιο μακροεντολής για να το αποθηκεύσετε ως προεπιλογή.",
  noPresets: "Δεν υπάρχουν ακόμη αποθηκευμένες προεπιλογές για το τρέχον έργο.",
  presetSaved: "Το τρέχον προσχέδιο μακροεντολής αποθηκεύτηκε στις προεπιλογές έργου.",
  presetDeleted: "Η επιλεγμένη προεπιλογή έργου διαγράφηκε.",
  presetInserted: "Η επιλεγμένη προεπιλογή έργου εισήχθη στον επεξεργαστή.",
  sensitivePresetRejected: "Η αποθήκευση της προεπιλογής αποκλείστηκε επειδή περιέχει ευαίσθητα πεδία που δεν πρέπει να αποθηκεύονται τοπικά.",
  sensitivePresetRejectedDetails: "Ελέγξτε αυτά τα πεδία και αφαιρέστε διακριτικά πρόσβασης, cookies, κεφαλίδες εξουσιοδότησης και μυστικά από τις αποθηκευμένες προεπιλογές:",
  snapshot: "Στιγμιότυπο",
  actionCatalog: "Κατάλογος ενεργειών",
  macroCatalog: "Κατάλογος μακροεντολών",
  editor: "Σκριπτ Python",
  output: "Έξοδος",
  noOutput: "Η έξοδος του σκριπτ θα εμφανιστεί εδώ.",
  lineCount: "Γραμμές",
  stateKeys: "Πεδία κατάστασης",
  actionCount: "Ενέργειες",
  payload: "Δεδομένα",
  actionLog: "Αρχείο ενεργειών",
  noActionLog: "Δεν υπάρχουν ακόμη ενέργειες από σκριπτ.",
  insertMacroDraft: "Εισαγωγή προσχεδίου μακροεντολής",
  macroDraftInserted: "Εισήχθη προσχέδιο μακροεντολής από το πρόσφατο αρχείο ενεργειών.",
  noMacroDraftSource: "Εκτελέστε πρώτα μερικές ενέργειες για να δημιουργηθεί προσχέδιο μακροεντολής.",
  actionSource: "Πηγή",
  actionPayload: "Δεδομένα",
  actionResult: "Αποτέλεσμα",
  actionNote: "Σημείωση",
  riskNormal: "Κανονικό",
  riskSensitive: "Ευαίσθητο",
  riskDestructive: "Καταστροφικό",
  confirmationRequired: "Απαιτείται επιβεβαίωση πριν από την εκτέλεση.",
  insertLabel: "Εισαγωγή",
  stepsLabel: "Βήματα",
  macroPayloadHint: "Αυτή η μακροεντολή υποστηρίζει παραμέτρους προτύπου μέσω των δεδομένων εισόδου.",
  categories: {
    navigation: "Πλοήγηση",
    settings: "Ρυθμίσεις",
    runtime: "Περιβάλλον εκτέλεσης",
    project: "Έργο",
    model: "Μοντέλο",
    state: "Κατάσταση",
    selection: "Επιλογή",
    job: "Εργασία",
    history: "Ιστορικό",
    viewport: "Προβολή",
    data: "Δεδομένα",
    macro: "Μακροεντολή",
  },
} as const;
