import { copyEnCore } from "@/components/workbench/workbench-copy-en-core";
import { copyEnExtended } from "@/components/workbench/workbench-copy-en-extended";

const copyEn = {
  ...copyEnCore,
  ...copyEnExtended,
} as const;

export const copyJa = {
    ...copyEn,
    permittivity: "誘電率",
    roleLabel: "解析シェル",
    title: "構造解析ワークベンチ",
    subtitle: "モデリング、オーケストレーション、結果レビューを一つにまとめた作業面です。",
    rail: { study: "解析", model: "ワークスペース", workflow: "ワークフロー", library: "履歴", system: "システム" },
    sections: { study: "解析設定", model: "ワークスペース", workflow: "ワークフロースタジオ", library: "ジョブ履歴", system: "システム" },
    studyFamilies: {
      axialAndSprings: "軸・ばね",
      beamsAndFrames: "梁・フレーム",
      trusses: "トラス",
      planes: "平面要素",
    },
    studyDomains: {
      mechanical: "力学",
      thermal: "熱",
      thermoMechanical: "熱応力",
    },
    importModel: "モデルを読み込む",
    importHint: "1D / 2D 解析用の JSON モデルを読み込みます。",
    sampleCatalogPage: "カタログ",
    sampleImportPage: "インポート",
    workflowOverviewPage: "概要",
    workflowCatalogPage: "カタログ",
    workflowBuilderPage: "ビルダー",
    workflowRunsPage: "実行",
    workflowCatalogTitle: "ワークフローカタログ",
    workflowCatalogSearchLabel: "カタログ検索",
    workflowCatalogSearchPlaceholder: "名前、ID、要約、タグ、オペレーターで workflow を検索",
    workflowCatalogSearchEmptyLabel: "一致する workflow がありません。",
    workflowCatalogSearchMatchesLabel: "一致理由",
    workflowCatalogSearchScoreLabel: "一致スコア",
    workflowCatalogHint: "より大きな study path に組み込む前に、命名済みの多算子 workflow をここで実行します。",
    workflowCatalogFilterAllLabel: "すべて",
    workflowCatalogFilterLocalLabel: "ローカル",
    workflowCatalogFilterVariantsLabel: "variant",
    workflowCatalogFilterHealthyLabel: "健全",
    workflowCatalogFilterNeedsReviewLabel: "要確認",
    // Bridge runtime navigation
    workflowCatalogFilterBridgeAlignedLabel: "bridge 整合済み", workflowCatalogFilterBridgeDriftLabel: "bridge ドリフト", workflowCatalogFilterBridgeMissingRuntimeLabel: "bridge 実行態欠落", workflowRunsFilterBridgeAlertsLabel: "bridge 警告", workflowOverviewBridgeStatusLabel: "bridge 整合/ドリフト/欠落",
    workflowOverviewHint: "複合算子 workflow を専用作業面に集め、samples や results に埋め込まないようにします。",
    workflowBuilderHint: "graph のノード、bridge、extract、export を確認してから大きな study chain に接続します。",
    workflowRunsHint: "命名 workflow ジョブ、現在ノード、書き出し済み summary を一か所で追います。",
    workflowCatalogRefresh: "ワークフローを更新",
    workflowCatalogRun: "参照サンプルを実行",
    workflowRunDraftLabel: "現在の草稿を実行",
    workflowCatalogEmpty: "まだ公開済みの命名 workflow はありません。",
    workflowCatalogReady: "ワークフローカタログの準備ができました。",
    workflowCatalogQueued: "ワークフロージョブを投入しました",
    workflowCatalogCompleted: "ワークフローが完了しました",
    workflowCatalogUnsupported: "この workflow にはまだ内蔵サンプル入力がありません。",
    workflowCatalogLoaded: "ワークフローカタログを読み込みました。",
    workflowCatalogFailed: "ワークフロー実行に失敗しました。",
    workflowSelectForBuilder: "ビルダーを開く",
    workflowNoSelection: "まず命名 workflow を選ぶと、ビルダーに graph が表示されます。",
    workflowNodesTitle: "ノード",
    workflowEdgesTitle: "エッジ",
    workflowTopologyEditorTitle: "トポロジーエディタ",
    workflowAddNodeLabel: "ノードを追加",
    workflowAddConnectedNodeLabel: "接続ノードを追加",
    workflowInsertSolveExtractExportLabel: "solve -> extract -> export を挿入",
    workflowInsertFrame2dSolveExportLabel: "2D frame 要約チェーンを挿入",
    workflowInsertThermalFrame2dSolveExportLabel: "熱 2D frame 要約チェーンを挿入",
    workflowInsertTruss3dSolveExportLabel: "3D truss 要約チェーンを挿入",
    workflowInsertHeatBridgeThermoLabel: "heat -> bridge -> thermo を挿入",
    workflowInsertElectrostaticBridgeHeatLabel: "electrostatic -> bridge -> heat を挿入",
    workflowInsertElectrostaticHeatThermoSummaryLabel: "electrostatic -> heat -> thermo 連成要約チェーンを挿入",
    workflowInsertElectrostaticTriangleHeatThermoTriangleSummaryLabel: "electrostatic triangle -> heat triangle -> thermo triangle 連成要約チェーンを挿入",
    workflowInsertElectrostaticSolveExportLabel: "electrostatic -> extract -> export を挿入",
    workflowTemplateChainFavoritesLabel: "お気に入りチェーン",
    workflowTemplateChainFavoriteAddLabel: "チェーンをお気に入りに追加",
    workflowTemplateChainFavoriteRemoveLabel: "チェーンのお気に入り解除",
    workflowTemplateChainRenameLabel: "チェーン名を変更",
    workflowTemplateChainRenamePrompt: "このお気に入りチェーンのローカル名を入力",
    workflowTemplateChainLibraryLabel: "チェーンテンプレートライブラリ",
    workflowTemplateChainImportLabel: "チェーンパッケージを取り込む",
    workflowTemplateChainExportLabel: "チェーンパッケージを書き出す",
    workflowTemplateChainDeleteImportedLabel: "取り込んだチェーンを削除",
    workflowTemplateChainImportedLabel: "取り込み済みチェーン",
    workflowTemplateChainImportSuccessLabel: "チェーンテンプレートパッケージを取り込みました。",
    workflowTemplateChainImportInvalidLabel: "チェーンテンプレートパッケージが無効です。",
    workflowTemplateChainSaveSelectionLabel: "現在のノードをチェーン保存",
    workflowTemplateChainSaveSelectionPrompt: "このテンプレートチェーン名を入力",
    workflowTemplateChainSaveSelectionSuccessLabel: "現在のテンプレートチェーンを保存しました。",
    workflowTemplateChainRenameTemplateLabel: "テンプレート名を変更",
    workflowTemplateChainSummaryEditLabel: "要約を編集",
    workflowTemplateChainSummaryPrompt: "このテンプレートチェーンの要約を編集",
    workflowTemplateChainSearchLabel: "テンプレート検索",
    workflowTemplateChainSearchPlaceholder: "名前、要約、オペレーター ID でチェーン検索",
    workflowTemplateChainBuiltInLabel: "内蔵チェーン",
    workflowTemplateChainAllLabel: "すべてのチェーン",
    workflowTemplateChainPinnedLabel: "固定したお気に入り",
    workflowTemplateChainTagsLabel: "タグ",
    workflowControlFlowPlaneTitle: "制御フロープレーン",
    workflowControlFlowPlaneHint: "条件、分岐、合流を専用プレーンに分け、先に制御骨格を組んでから通常トポロジで詳細を詰めます。",
    workflowControlFlowPlaneInsertLabel: "分岐スケルトンを挿入",
    workflowControlFlowPlaneConditionLabel: "条件ノード",
    workflowControlFlowPlaneMergeLabel: "合流ノード",
    workflowControlFlowPlaneEmptyLabel: "まだ制御フローノードがありません。まず分岐スケルトンを挿入してください。",
    workflowRemoveNodeLabel: "ノードを削除",
    workflowAddEdgeLabel: "エッジを追加",
    workflowRemoveEdgeLabel: "エッジを削除",
    workflowNodeIdLabel: "ノード ID",
    workflowEdgeIdLabel: "エッジ ID",
    workflowFromLabel: "出発",
    workflowToLabel: "到着",
    workflowInputsTitle: "入力ポート",
    workflowOutputsTitle: "出力ポート",
    workflowAddInputPortLabel: "入力ポートを追加",
    workflowAddOutputPortLabel: "出力ポートを追加",
    workflowPortIdLabel: "ポート ID",
    workflowRemovePortLabel: "ポートを削除",
    workflowOperatorSearchLabel: "オペレーター検索",
    workflowOperatorSearchPlaceholder: "名前、ID、要約、能力タグで検索",
    workflowOperatorSearchEmptyLabel: "一致するオペレーターがありません。",
    workflowOperatorSearchScoreLabel: "一致スコア",
    workflowOperatorSearchReasonLabel: "一致理由",
    workflowOperatorDomainFilterLabel: "ドメイン絞り込み",
    workflowOperatorValidationFilterLabel: "検証絞り込み",
    workflowOperatorCapabilityFilterLabel: "能力絞り込み",
    workflowOperatorFilterAllLabel: "すべて",
    workflowOperatorFilterSummaryLabel: "絞り込み要約",
    workflowOperatorFilterMatchesLabel: "一致件数",
    workflowOperatorFilterActiveLabel: "有効な絞り込み",
    workflowOperatorFilterClearLabel: "絞り込みをクリア",
    workflowOperatorRecentLabel: "最近使用",
    workflowOperatorFavoritesLabel: "お気に入り",
    workflowOperatorFavoriteAddLabel: "お気に入りに追加",
    workflowOperatorFavoriteRemoveLabel: "お気に入り解除",
    workflowEntryInputsTitle: "入口入力",
    workflowOutputArtifactsTitle: "出力アーティファクト",
    workflowDatasetContractTitle: "データセット契約",
    workflowDatasetValuesTitle: "データセット値",
    workflowDatasetValueLabel: "データセット値",
    workflowDatasetSemanticTypeLabel: "意味型",
    workflowDatasetEncodingLabel: "エンコード",
    workflowDatasetShapeLabel: "形状",
    workflowDatasetAxesLabel: "軸",
    workflowDatasetSchemaLabel: "スキーマ",
    workflowDatasetClassLabel: "要素型",
    workflowDatasetNoneLabel: "この workflow にはまだ dataset contract がありません。",
    workflowDatasetDraftHint: "まずここで dataset の意味付けをローカル草稿として調整し、port・edge・跨算子値を揃えてから永続化に進みます。",
    workflowDatasetEditorTitle: "データセットエディタ",
    workflowDatasetValueSelectLabel: "選択中のデータセット値",
    workflowDatasetUnitLabel: "単位",
    workflowDatasetMetadataLabel: "メタ情報",
    workflowDatasetPortMappingsTitle: "ポート対応",
    workflowDatasetEdgeMappingsTitle: "エッジ対応",
    workflowDatasetDraftLocalLabel: "ローカル草稿",
    workflowDatasetUnassignedLabel: "未割り当て",
    workflowDatasetAddValueLabel: "値を追加",
    workflowDatasetRemoveValueLabel: "値を削除",
    workflowDatasetAxesEditorTitle: "軸エディタ",
    workflowDatasetAddAxisLabel: "軸を追加",
    workflowDatasetRemoveAxisLabel: "軸を削除",
    workflowDatasetAxisIdLabel: "軸 ID",
    workflowDatasetAxisSizeLabel: "軸サイズ",
    workflowDatasetAxisSemanticLabel: "軸セマンティクス",
    workflowInputArtifactsTitle: "草稿入力",
    workflowInputArtifactsHint: "現在の draft graph を実行する前に、各 entry node の入力 artifact JSON をここで調整します。",
    workflowImportGraphLabel: "Graph JSON を取り込む",
    workflowImportDatasetContractLabel: "Dataset JSON を取り込む",
    workflowImportSuccessLabel: "ローカル workflow 草稿を取り込みました。",
    workflowImportInvalidGraphLabel: "このファイルは有効な workflow graph JSON ではありません。",
    workflowImportInvalidDatasetLabel: "このファイルは有効な workflow dataset JSON ではありません。",
    workflowSaveDraftLabel: "草稿を保存",
    workflowPromoteDraftLabel: "ローカル workflow に昇格",
    workflowDuplicateLocalWorkflowLabel: "variant として複製",
    workflowRenameLocalWorkflowLabel: "ローカル workflow の名前を変更",
    workflowSavedDraftsTitle: "保存済み草稿",
    workflowSavedDraftsHint: "Builder が完全な命名 workflow authoring になるまでの間、ローカル workflow スナップショットをここに残します。",
    workflowSavedDraftsEmptyLabel: "まだ保存済みのローカル workflow 草稿はありません。",
    workflowLoadDraftLabel: "草稿を読み込む",
    workflowDeleteDraftLabel: "草稿を削除",
    workflowDraftSavedLabel: "ローカル workflow 草稿を保存しました。",
    workflowDraftLoadedLabel: "ローカル workflow 草稿を読み込みました。",
    workflowDraftDeletedLabel: "ローカル workflow 草稿を削除しました。",
    workflowLocalWorkflowPromotedLabel: "草稿をローカル workflow library に昇格しました。",
    workflowLocalWorkflowDeleteLabel: "ローカル workflow を削除",
    workflowLocalWorkflowDeletedLabel: "ローカル workflow を削除しました。",
    workflowLocalWorkflowBadgeLabel: "ローカル workflow",
    workflowLocalWorkflowDuplicatedLabel: "ローカル workflow を variant として複製しました。",
    workflowLocalWorkflowRenamePrompt: "このローカル workflow の名前を変更",
    workflowLocalWorkflowSourceLabel: "元 workflow",
    workflowLocalWorkflowPromotedAtLabel: "登録日時",
    workflowLocalWorkflowVariantOfLabel: "variant 元",
    workflowLocalWorkflowPackageIdLabel: "パッケージ元",
    workflowLocalWorkflowPackageVersionLabel: "パッケージ版",
    workflowLocalWorkflowTagsLabel: "タグ",
    workflowPackageManifestTitle: "workflow package manifest",
    workflowPackageManifestNoneLabel: "この workflow はまだ import package にマウントされていません。",
    workflowPackageManifestDraftLabel: "草稿マウント package",
    workflowPackageManifestMountedLabel: "マウント済み package",
    workflowPackageManifestExportedAtLabel: "export 時刻",
    workflowPackageManifestDomainsLabel: "ドメイン",
    workflowPackageManifestCapabilitiesLabel: "能力タグ",
    workflowPackageManifestOperatorsLabel: "オペレーター",
    workflowPackageManifestEntryArtifactsLabel: "入口 artifact",
    workflowPackageManifestOutputArtifactsLabel: "出力 artifact",
    workflowPackageDiagnosticsSearchLabel: "診断検索",
    workflowPackageDiagnosticsSearchPlaceholder: "メッセージ、ノード、データセット値、修復種別で package 診断を検索",
    workflowPackageDiagnosticsSearchEmptyLabel: "一致する診断記録がありません。",
    workflowPackageDiagnosticsNodeLabel: "ノード",
    workflowPackageDiagnosticsDatasetLabel: "データセット",
    workflowPackageDiagnosticsPackageLabel: "package",
    workflowPackageInstallRulesTitle: "package install ルール",
    workflowPackageInstallRulesMountStateLabel: "mount 状態",
    workflowPackageInstallRulesStorageLabel: "storage ルール",
    workflowPackageInstallRulesStorageScopeLabel: "storage 範囲",
    workflowPackageInstallRulesLocalPathLabel: "local workflow key",
    workflowPackageInstallRulesSnapshotPathLabel: "snapshot index key",
    workflowPackageInstallRulesSnapshotPayloadPathLabel: "snapshot payload prefix",
    workflowPackageInstallRulesMaintenancePathLabel: "maintenance log key",
    workflowPackageInstallRulesCleanupLabel: "cleanup ルール",
    workflowPackageInstallRulesSnapshotLabel: "snapshot ルール",
    workflowPackageInstallRulesFormatLabel: "format 契約",
    workflowPackageInstallRulesPortabilityLabel: "可搬性",
    workflowPackageInstallRulesReadonlyLabel: "read-only",
    workflowPackageInstallRulesExportLabel: "ルール report を export",
    workflowPackageInstallRulesScanLabel: "残留を scan",
    workflowPackageInstallRulesRepairLabel: "安全な残留を修復",
    workflowPackageInstallRulesRepairItemLabel: "この項目を修復",
    workflowPackageInstallRulesManualLabel: "手動対応",
    workflowPackageInstallRulesAutoLabel: "自動修復可",
    workflowPackageInstallRulesPreviewTitle: "修復 plan preview",
    workflowPackageInstallRulesPreviewApplyLabel: "実行を確認",
    workflowPackageInstallRulesPreviewCancelLabel: "preview を閉じる",
    workflowPackageInstallRulesReceiptTitle: "実行 receipt",
    workflowPackageInstallRulesHistoryEmptyLabel: "この session ではまだ package 保守記録がありません。",
    workflowPackageInstallRulesResidualsLabel: "残留 scan",
    workflowPackageInstallRulesResidualsCleanLabel: "この workflow の install 残留は見つかりませんでした。",
    workflowPackageInstallRulesReportExportedLabel: "現在の workflow package ルール report を export しました。",
    workflowPackageInstallRulesRepairedLabel: "この workflow package の安全な残留修復を適用しました。",
    workflowPackageInstallRulesRepairUnavailableLabel: "現在の残留は手動対応が必要で、安全な自動修復はありません。",
    settingsInstallPolicyTitle: "install policy",
    settingsInstallPolicyHint: "workflow package、cleanup ルール、標準 local install 挙動をまとめた read-only policy 面です。",
    settingsInstallPolicyIntegrityValue: "component 状態は solve・export・update 前に設定可視かつ監査可能である必要があります。",
    settingsInstallPolicyUpdateValue: "標準置換と明示 cleanup を優先し、version 間に隠れた残留を残しません。",
    workflowLocalWorkflowMetadataTitle: "ローカル metadata",
    workflowLocalWorkflowSummaryLabel: "サマリー",
    workflowLocalWorkflowNotesLabel: "メモ",
    workflowLocalWorkflowSaveMetadataLabel: "metadata を保存",
    workflowLocalWorkflowMetadataSavedLabel: "ローカル workflow metadata を保存しました。",
    workflowRunDraftInvalidInputsLabel: "この入力 JSON は不足しているか無効です。",
    workflowValidationTitle: "整合性チェック",
    workflowValidationSummaryAllLabel: "すべて",
    workflowValidationSummaryFixableLabel: "修正可能",
    workflowValidationSummaryReviewLabel: "要確認",
    workflowValidationOkLabel: "graph と dataset contract の不整合は見つかりませんでした。",
    workflowValidationFixLabel: "修正を適用",
    workflowValidationFixAllLabel: "修正を一括適用",
    workflowValidationPreviewLabel: "修正をプレビュー",
    workflowValidationLocateLabel: "場所を開く",
    workflowValidationAutoFixedLabel: "workflow の問題を {count} 件自動修正しました。",
    workflowValidationFixPreviewLabel: "{count} 件の workflow 問題をまとめて自動修正します:",
    workflowValidationFixPreviewMoreLabel: "ほかに {count} 件の問題も一括修正されます。",
    workflowValidationLatestFixSummaryLabel: "直近の修正サマリー:",
    workflowValidationLatestFixSummaryMoreLabel: "ほかに {count} 件の変更があります。",
    workflowValidationSnapshotsTitle: "修正スナップショット",
    workflowValidationSnapshotsEmptyLabel: "自動修正のスナップショットはまだありません。",
    workflowValidationSnapshotRestoreLabel: "復元",
    workflowValidationSnapshotDeleteLabel: "削除",
    workflowValidationSnapshotSummaryOnlyLabel: "要約のみ",
    workflowValidationSnapshotRestoreUnavailableLabel: "このスナップショットは要約のみ保持しており、完全な草稿は復元できません。",
    workflowFocusStripTitle: "focus route",
    workflowFocusStripFromPolicyLabel: "system / install policy",
    workflowArtifactNodeLabel: "ノード",
    workflowArtifactTypeLabel: "artifact type",
    workflowArtifactDescriptionLabel: "説明",
    workflowArtifactRemoveLabel: "artifact を削除",
    workflowArtifactAdoptSuggestedLabel: "node port type を使う",
    workflowArtifactAddEntryLabel: "entry input を追加",
    workflowArtifactAddOutputLabel: "output artifact を追加",
    workflowArtifactDraftLocalLabel: "ローカル草稿",
    workflowExportGraphLabel: "Graph JSON を書き出す",
    workflowExportDatasetContractLabel: "Dataset JSON を書き出す",
    workflowOperatorLabel: "算子",
    workflowOperatorValidationLabel: "検証状態",
    workflowOperatorCapabilitiesLabel: "能力タグ",
    workflowOperatorInputSchemaLabel: "入力 schema",
    workflowOperatorOutputSchemaLabel: "出力 schema",
    workflowOperatorConfigSchemaLabel: "設定 schema",
    workflowOperatorConfigExampleLabel: "設定例",
    workflowOperatorDocsLabel: "ドキュメントを開く",
    workflowBridgeContractTitle: "ブリッジ契約",
    workflowBridgeContractSourceFieldLabel: "入力フィールド",
    workflowBridgeContractDistributionLabel: "分配方式",
    workflowBridgeContractNodeIndexFieldsLabel: "ノード索引フィールド",
    workflowBridgeContractScaleLabel: "スケール",
    workflowBridgeContractReductionLabel: "集約方式",
    workflowBridgeContractDefaultValueLabel: "デフォルト値",
    workflowBridgeContractTargetFieldLabel: "出力フィールド", workflowBridgeContractAdjustedFieldsLabel: "自動補正された項目",
    workflowBridgeContractPreviewTitle: "影響プレビュー",
    workflowBridgeContractPreviewSummaryLabel: "現在のマッピング",
    workflowBridgeContractPreviewDownstreamLabel: "下流への影響",
    workflowBridgeSeedModelTitle: "シードモデル",
    workflowBridgeSeedModelSummaryLabel: "下流ソルバーのシード",
    workflowBridgeSeedModelNodeCountLabel: "ノード数",
    workflowBridgeSeedModelElementCountLabel: "要素数",
    workflowBridgeSeedModelDraftLabel: "シードモデル JSON",
    workflowBridgeSeedModelApplyLabel: "シードモデルを適用",
    workflowBridgeSeedModelResetLabel: "既定値に戻す",
    workflowBridgeSeedModelImportWorkspaceLabel: "現在のワークスペースモデルを取り込む",
    workflowBridgeSeedModelImportWorkspaceUnavailableLabel: "対応する quad study に切り替えると現在モデルを取り込めます。",
    workflowBridgeSeedModelInvalidLabel: "シードモデル JSON を解析できません。",
    workflowOperatorValidationVerifiedLabel: "検証済み",
    workflowOperatorValidationPartialLabel: "部分検証",
    workflowOperatorValidationUnverifiedLabel: "未検証",
    workflowKindLabel: "種別",
    workflowProgressLabel: "進捗",
    workflowCurrentNodeLabel: "現在ノード",
    workflowLatestSummaryLabel: "最新サマリー",
    workflowOpenRunLabel: "実行を開く",
    workflowRunsEmpty: "まだ workflow 実行はありません。",
    projectManagePage: "管理",
    projectExchangePage: "入出力",
    modelSavedPage: "保存済み",
    modelVersionsPage: "バージョン",
    studyDomain: "物理ドメイン",
    noDomainStudies: "このドメインにはまだ公開済み study がありません。",
    jobWorkspaceTitle: "ジョブ作業面",
    jobWorkspaceHint: "まずは solver 実行を追い、必要になった時だけ個別ジョブに掘り下げます。",
    resultWorkspaceTitle: "結果作業面",
    resultWorkspaceHint: "ここでは最新の完了結果を開き、そこからレポートやエクスポートに進みます。",
    modelWorkspaceTitle: "モデル作業面",
    modelWorkspaceHint: "保存済み study と再利用用バージョンをまとめて、すぐに再開や分岐ができるようにします。",
    openLatestJob: "最新ジョブを開く",
    openLatestResult: "最新結果を開く",
    openLatestModel: "最新モデルを開く",
    waitingJobs: "結果待ち",
    readyResults: "利用可能な結果",
    savedCount: "保存済みモデル",
    versionCount: "バージョン数",
    overview: "概要",
    result: "結果",
    actions: "操作",
    details: "詳細",
    controls: "設定",
    controlsSetupPage: "編集",
    controlsReviewPage: "確認",
    studyTypeLabel: "解析タイプ",
    modelStudyPage: "解析",
    modelOverviewPage: "概要",
    modelStudioPage: "スタジオ",
    modelMaterialsPage: "材料",
    modelGeneratePage: "生成",
    workspaceStudyHint: "Study ファミリー、物理ドメイン、solver 向け setup をここで整えます。",
    workspaceStudioHint: "ノード、部材、境界、幾何の編集はここで行います。",
    workspaceMaterialsHint: "初期材料値と再利用する材料選択をここにまとめます。",
    workspaceGenerateHint: "ジェネレーターとパラメトリック補助で再現可能なモデルを作ります。",
    workspaceBrowseHint: "オブジェクト、ハイライト、結果に結び付く選択をここで参照します。",
    settings: "設定",
    scripts: "スクリプト",
    settingsConfigHint: "テーマ、言語、ルーティング、アクセストークン、言語パックをここで管理します。",
    settingsScriptsHint: "WASM Python、マクロ記録、アクションカタログをここで扱います。",
    assistant: "アシスタント",
    config: "構成",
    runtime: "ランタイム",
    data: "データ",
    packs: "言語パック",
    workspace: "ワークスペース",
    routing: "ルーティング",
    access: "アクセス",
    stack: "スタック",
    security: "セキュリティ",
    agents: "エージェント",
    audit: "監査",
    backend: "バックエンド",
    protocols: "プロトコル",
    dataAdmin: "データ管理",
    languagePacksTitle: "インストール済み言語パック",
    languagePacksHint: "今はローカル JSON パックの取り込みを先にサポートし、この画面を将来のリモート配布入口として残しておきます。",
    languagePacksEmptyLabel: "まだカスタム言語パックはありません。",
    languagePackName: "名称",
    languagePackVersion: "バージョン",
    languagePackSourceImported: "ローカル取込",
    languagePackSourceDownloaded: "リモート取得",
    languagePackDownloadTemplate: "テンプレートを出力",
    languagePackExportInstalled: "現在の言語パックを出力",
    languagePackImport: "言語パックを取込",
    languagePackRemove: "削除",
    languagePackCatalogTitle: "将来のカタログ",
    languagePackCatalogHint: "この欄は将来のリモート言語パック配布を同じ画面で扱えるように先に用意しています。",
    languagePackCatalogAction: "今後対応",
    adminJobs: "ジョブ",
    adminResults: "結果",
    adminBrowsePage: "参照",
    adminEditPage: "編集",
    theme: "テーマ",
    language: "言語",
    themes: { linen: "ワークショップ", marine: "ブループリント", graphite: "Blender Forge" },
    languages: { en: "English", zh: "中文", ja: "日本語", es: "Español" },
    frontendModes: {
      orchestrated_gui: "オーケストレーション GUI",
      direct_mesh_gui: "ダイレクトメッシュ GUI",
    },
    directMeshStrategies: {
      healthiest: "最も健全なノード",
      first_reachable: "最初に到達可能なノード",
    },
    tabs: { summary: "概要", controls: "設定", tools: "ツール", tree: "参照", jobs: "ジョブ", results: "結果", models: "モデル", projects: "プロジェクト", samples: "サンプル" },
    ready: "準備完了",
    busy: "処理中",
    run: "解析を実行",
    running: "実行中...",
    historyEmpty: "まだジョブはありません。",
    refresh: "更新",
    online: "オンライン",
    offline: "オフライン",
    controlPlaneTokenHelp:
      "トークン保護された control-plane 配備向けです。/api/v1 リクエストに x-kyuubiki-token として送信されます。",
    controlPlaneTokenPlaceholder: "任意の control-plane トークン",
    clusterTokenHelp:
      "agent の登録・heartbeat・削除などの cluster ルートに使います。未入力なら control-plane token を使います。",
    clusterTokenPlaceholder: "任意の cluster 専用トークン",
    directMeshTokenHelp:
      "トークン保護された direct mesh ルート向けです。/api/direct-mesh リクエストに送信されます。",
    directMeshTokenPlaceholder: "任意の direct-mesh トークン",
    exportDatabase: "データベーススナップショットを出力",
    runtimeSecurityFooter:
      "実行中のセキュリティ状態は /api/health から取得され、フロントエンドのトークンは現在のブラウザセッションにのみ保持されます。",
    securityAudit: "セキュリティ監査",
    auditSessionLabel:
      "Workbench アシスタント、スクリプト、Hub アシスタントを含む control-plane 永続化イベント列を表示します。",
    auditWindow: "期間",
    auditSource: "ソース",
    auditRisk: "リスク",
    auditStatus: "状態",
    auditAction: "操作",
    auditSummaryTitle: "イベント要約",
    auditTrendTitle: "時間推移",
    auditTrendEmptyLabel: "現在の期間ではトレンドデータがありません。",
    auditSourceStatusTitle: "ソース × 状態",
    auditStudyFacetTitle: "Study ファセット",
    auditProjectFacetTitle: "Project ファセット",
    auditModelVersionFacetTitle: "Version ファセット",
    auditFacetEmptyLabel: "現在の期間では利用できるファセットがありません。",
    auditRefreshLabel: "イベントを更新",
    auditExportLabel: "分析バンドルを出力",
    auditExportCsvLabel: "CSV を出力",
    auditWindowOptions: { all: "全期間", h1: "直近 1 時間", h24: "直近 24 時間", d7: "直近 7 日", d30: "直近 30 日" },
    auditSourceOptions: { all: "すべて", assistant: "アシスタント", hubAssistant: "Hub アシスタント", script: "スクリプト" },
    auditRiskOptions: { all: "すべて", low: "低", sensitive: "機微", high: "高", destructive: "破壊的" },
    auditStatusOptions: { all: "すべて", prompted: "確認待ち", confirmed: "確認済み", cancelled: "取消済み", completed: "完了", failed: "失敗" },
    assistantLauncherHint: "ガイドが必要ですか？",
    assistantFloatingTitle: "ワークベンチに質問",
    assistantFloatingSubtitle: "作業面は軽く保ち、必要なときだけガイドを開きます。",
    assistantOpen: "アシスタントを開く",
    assistantClose: "アシスタントを閉じる",
    modelName: "モデル",
    material: "材料",
    load: "荷重",
    support: "拘束",
    viewport: "ビュー",
    report: "レポート",
    diagnostics: "診断",
    diagnosticsClear: "現在、ブロッキングな事前チェック問題はありません。",
    integrityMissingNodes: "solve の前に少なくとも 1 つの node を追加してください。",
    integrityMissingElements: "solve の前に少なくとも 1 つの element を追加してください。",
    integrityDuplicateNodeId: 'node "{id}" の ID が重複しています。',
    integrityDuplicateElementId: 'element "{id}" の ID が重複しています。',
    integrityDuplicateMaterialId: 'material "{id}" の ID が重複しています。',
    integrityMissingNodeReference: 'element "{id}" が存在しない node を参照しています。',
    integrityMissingMaterialReference: 'element "{id}" が存在しない material "{materialId}" を参照しています。',
    integrityInvalidNodeField: 'node "{id}" の "{field}" の値が不正です。',
    integrityInvalidElementField: 'element "{id}" の "{field}" の値が不正です。',
    integrityDegenerateLineElement: 'element "{id}" の長さが 0 または極端に小さすぎます。',
    integrityDegenerateSurfaceElement: 'element "{id}" の面積が 0 または極端に小さすぎます。',
    suggestedFixes: "推奨修正",
    stabilityScore: "安定性スコア",
    hotspotNodes: "ホットスポット node",
    stabilityGood: "安定",
    stabilityWatch: "注意",
    stabilityRisk: "高リスク",
    summary: "概要",
    messages: "メッセージ",
    nodeTable: "オブジェクト参照",
    objectTree: "オブジェクト",

} as const;
