import type { WorkbenchScriptLanguage } from "@/lib/scripting/workbench-script-runtime";

export const workbenchScriptPanelCopy = {
  en: {
    title: "WASM Python",
    subtitle: "Frontend automation surface powered by Pyodide and the registered browser action catalog.",
    frontendSurface: "Frontend Automation",
    frontendSurfaceHint: "This surface is for in-browser automation, macro recording, replay, and UI-side debugging.",
    headlessSurface: "Headless SDK",
    headlessSurfaceHint: "The panel below is a separate headless workflow builder for service-side and solver-side automation.",
    launch: "Launch",
    author: "Author",
    inspect: "Inspect",
    catalog: "Catalog",
    scriptMode: "Script",
    recordMode: "Record",
    outputMode: "Output",
    timelineMode: "Timeline",
    snapshotMode: "Snapshot",
    presetsMode: "Presets",
    actionsMode: "Actions",
    macrosMode: "Macros",
    authorScriptHint: "Write or adjust frontend automation scripts directly here.",
    authorRecordHint: "Record UI actions, turn recent actions into macro drafts, and then insert them back into the script surface.",
    inspectOutputHint: "Execution output and runtime messages appear here.",
    inspectTimelineHint: "Recent frontend actions appear here as a replayable timeline.",
    inspectSnapshotHint: "Live workbench state helps scripts inspect and debug UI context.",
    catalogHint: "Reusable frontend automation assets live here: project presets, action snippets, and macros.",
    runtime: "Runtime",
    loading: "Loading",
    ready: "Ready",
    idle: "Idle",
    running: "Running",
    error: "Error",
    firstRun: "First run downloads the Pyodide runtime into the browser cache.",
    loadRuntime: "Load runtime",
    resetScript: "Reset template",
    runScript: "Run script",
    clearOutput: "Clear output",
    startRecording: "Start recording",
    stopRecording: "Stop recording",
    recordingActive: "Recording manual UI actions into the DSL event stream.",
    exportMacroJson: "Export macro JSON",
    importMacroJson: "Import macro JSON",
    macroJsonExported: "Exported the current recorded macro as JSON.",
    macroJsonImported: "Imported a macro JSON draft into the editor.",
    projectPresets: "Project presets",
    presetName: "Preset name",
    presetNamePlaceholder: "review current result context",
    savePreset: "Save preset",
    insertPreset: "Insert preset",
    exportPresetJson: "Export preset JSON",
    deletePreset: "Delete preset",
    noProjectSelected: "Select a project first to save presets against project context.",
    noPresetDraft: "Build or import a macro draft first so it can be saved as a preset.",
    noPresets: "No saved presets for the current project yet.",
    presetSaved: "Saved the current macro draft into project presets.",
    presetDeleted: "Deleted the selected project preset.",
    presetInserted: "Inserted the selected project preset into the editor.",
    snapshot: "Snapshot",
    actionCatalog: "Action catalog",
    macroCatalog: "Macro catalog",
    editor: "Python script",
    output: "Output",
    noOutput: "Script output will appear here.",
    lineCount: "Lines",
    stateKeys: "State fields",
    actionCount: "Actions",
    payload: "Payload",
    actionLog: "Action log",
    noActionLog: "No scripted actions yet.",
    insertMacroDraft: "Insert macro draft",
    macroDraftInserted: "Inserted a macro draft from recent action log.",
    noMacroDraftSource: "Run a few actions first so the panel can assemble a draft macro.",
    actionSource: "Source",
    actionPayload: "Payload",
    actionResult: "Result",
    actionNote: "Note",
    riskNormal: "Normal",
    riskSensitive: "Sensitive",
    riskDestructive: "Destructive",
    confirmationRequired: "Requires confirmation before execution.",
    insertLabel: "Insert",
    stepsLabel: "Steps",
    macroPayloadHint: "This macro supports payload-driven template parameters.",
    categories: {
      navigation: "Navigation",
      settings: "Settings",
      runtime: "Runtime",
      project: "Project",
      model: "Model",
      state: "State",
      selection: "Selection",
      job: "Job",
      history: "History",
      viewport: "Viewport",
      data: "Data",
      macro: "Macro",
    },
  },
  zh: {
    title: "WASM Python",
    subtitle: "基于 Pyodide 和前端动作目录的浏览器内自动化面。",
    frontendSurface: "前端自动化",
    frontendSurfaceHint: "这里专门负责浏览器内自动化、宏录制、重放和 UI 侧调试。",
    headlessSurface: "无头 SDK",
    headlessSurfaceHint: "下方面板是独立的无头工作流搭建区，面向 service 和 solver 自动化。",
    launch: "启动",
    author: "编写",
    inspect: "检查",
    catalog: "资源库",
    scriptMode: "脚本",
    recordMode: "录制",
    outputMode: "输出",
    timelineMode: "时间线",
    snapshotMode: "状态快照",
    presetsMode: "预设",
    actionsMode: "动作",
    macrosMode: "宏",
    authorScriptHint: "这里直接编写或调整前端自动化脚本。",
    authorRecordHint: "这里更适合录制 UI 操作、整理最近动作，并把宏草稿再插回脚本面。",
    inspectOutputHint: "这里查看执行输出和运行时消息。",
    inspectTimelineHint: "这里把最近前端动作整理成可回看的时间线。",
    inspectSnapshotHint: "这里提供实时工作台状态，方便脚本检查和调试上下文。",
    catalogHint: "这里集中放前端自动化复用资产：项目预设、动作片段和宏。",
    runtime: "运行时",
    loading: "加载中",
    ready: "就绪",
    idle: "空闲",
    running: "执行中",
    error: "错误",
    firstRun: "首次运行会把 Pyodide 运行时下载到浏览器缓存里。",
    loadRuntime: "加载运行时",
    resetScript: "重置模板",
    runScript: "运行脚本",
    clearOutput: "清空输出",
    startRecording: "开始录制",
    stopRecording: "停止录制",
    recordingActive: "正在把手动 UI 操作记录进 DSL 事件流。",
    exportMacroJson: "导出宏 JSON",
    importMacroJson: "导入宏 JSON",
    macroJsonExported: "已把当前录制宏导出为 JSON。",
    macroJsonImported: "已把宏 JSON 草稿导入编辑器。",
    projectPresets: "项目预设",
    presetName: "预设名称",
    presetNamePlaceholder: "复查当前结果上下文",
    savePreset: "保存预设",
    insertPreset: "插入预设",
    exportPresetJson: "导出预设 JSON",
    deletePreset: "删除预设",
    noProjectSelected: "先选中一个项目，预设才能挂到项目上下文下面。",
    noPresetDraft: "先生成或导入一个宏草稿，才能把它保存成预设。",
    noPresets: "当前项目还没有保存的预设。",
    presetSaved: "已把当前宏草稿保存到项目预设。",
    presetDeleted: "已删除选中的项目预设。",
    presetInserted: "已把选中的项目预设插入编辑器。",
    snapshot: "状态快照",
    actionCatalog: "动作目录",
    macroCatalog: "宏动作目录",
    editor: "Python 脚本",
    output: "输出",
    noOutput: "脚本输出会显示在这里。",
    lineCount: "行数",
    stateKeys: "状态字段",
    actionCount: "动作数",
    payload: "参数",
    actionLog: "动作日志",
    noActionLog: "还没有脚本动作记录。",
    insertMacroDraft: "插入宏草稿",
    macroDraftInserted: "已根据最近动作日志插入宏草稿。",
    noMacroDraftSource: "先执行几条动作，面板才能帮你拼出宏草稿。",
    actionSource: "来源",
    actionPayload: "参数",
    actionResult: "结果",
    actionNote: "备注",
    riskNormal: "普通",
    riskSensitive: "敏感",
    riskDestructive: "高风险",
    confirmationRequired: "执行前需要额外确认。",
    insertLabel: "插入",
    stepsLabel: "步骤",
    macroPayloadHint: "这个宏支持通过 payload 覆盖模板参数。",
    categories: {
      navigation: "导航",
      settings: "设置",
      runtime: "运行时",
      project: "项目",
      model: "模型",
      state: "状态",
      selection: "选择",
      job: "任务",
      history: "历史",
      viewport: "视图",
      data: "数据",
      macro: "宏动作",
    },
  },
  ja: {
    title: "WASM Python",
    subtitle: "Pyodide とフロントエンド向けアクションカタログでブラウザ内自動化を行う面です。",
    frontendSurface: "フロントエンド自動化",
    frontendSurfaceHint: "ここはブラウザ内自動化、マクロ記録、再生、UI 側デバッグのための面です。",
    headlessSurface: "ヘッドレス SDK",
    headlessSurfaceHint: "下のパネルは service / solver 自動化向けの独立したヘッドレスワークフロー面です。",
    launch: "起動",
    author: "作成",
    inspect: "確認",
    catalog: "カタログ",
    scriptMode: "スクリプト",
    recordMode: "記録",
    outputMode: "出力",
    timelineMode: "タイムライン",
    snapshotMode: "スナップショット",
    presetsMode: "プリセット",
    actionsMode: "アクション",
    macrosMode: "マクロ",
    authorScriptHint: "ここではフロントエンド自動化スクリプトを直接編集します。",
    authorRecordHint: "ここでは UI 操作を記録し、最近のアクションからマクロ下書きを作ってスクリプトへ戻せます。",
    inspectOutputHint: "実行出力とランタイムメッセージをここで確認します。",
    inspectTimelineHint: "最近のフロントエンド操作をここでタイムラインとして追えます。",
    inspectSnapshotHint: "ライブ状態を見ながら UI コンテキストを検査・デバッグできます。",
    catalogHint: "プロジェクトプリセット、アクション断片、マクロなど再利用資産をここにまとめます。",
    runtime: "ランタイム",
    loading: "読込中",
    ready: "準備完了",
    idle: "待機",
    running: "実行中",
    error: "エラー",
    firstRun: "初回実行では Pyodide ランタイムをブラウザキャッシュへダウンロードします。",
    loadRuntime: "ランタイムを読み込む",
    resetScript: "テンプレートに戻す",
    runScript: "スクリプトを実行",
    clearOutput: "出力をクリア",
    startRecording: "記録開始",
    stopRecording: "記録停止",
    recordingActive: "手動 UI 操作を DSL イベントとして記録中です。",
    exportMacroJson: "マクロ JSON を書き出す",
    importMacroJson: "マクロ JSON を読み込む",
    macroJsonExported: "現在の記録マクロを JSON で書き出しました。",
    macroJsonImported: "マクロ JSON 下書きをエディタへ読み込みました。",
    projectPresets: "プロジェクトプリセット",
    presetName: "プリセット名",
    presetNamePlaceholder: "現在の結果コンテキストを確認",
    savePreset: "プリセット保存",
    insertPreset: "プリセット挿入",
    exportPresetJson: "プリセット JSON 書き出し",
    deletePreset: "プリセット削除",
    noProjectSelected: "プリセットを保存するには先にプロジェクトを選択してください。",
    noPresetDraft: "先にマクロ下書きを作成または読み込んでください。",
    noPresets: "このプロジェクトにはまだ保存済みプリセットがありません。",
    presetSaved: "現在のマクロ下書きをプロジェクトプリセットに保存しました。",
    presetDeleted: "選択したプリセットを削除しました。",
    presetInserted: "選択したプリセットをエディタに挿入しました。",
    snapshot: "スナップショット",
    actionCatalog: "アクションカタログ",
    macroCatalog: "マクロカタログ",
    editor: "Python スクリプト",
    output: "出力",
    noOutput: "スクリプト出力がここに表示されます。",
    lineCount: "行数",
    stateKeys: "状態キー",
    actionCount: "アクション数",
    payload: "ペイロード",
    actionLog: "アクションログ",
    noActionLog: "まだスクリプトアクションはありません。",
    insertMacroDraft: "マクロ下書きを挿入",
    macroDraftInserted: "最近のアクションログからマクロ下書きを挿入しました。",
    noMacroDraftSource: "先にいくつかのアクションを実行すると、下書きを組み立てられます。",
    actionSource: "ソース",
    actionPayload: "ペイロード",
    actionResult: "結果",
    actionNote: "メモ",
    riskNormal: "通常",
    riskSensitive: "注意",
    riskDestructive: "高リスク",
    confirmationRequired: "実行前に確認が必要です。",
    insertLabel: "挿入",
    stepsLabel: "ステップ",
    macroPayloadHint: "このマクロは payload によるテンプレート引数の上書きに対応しています。",
    categories: {
      navigation: "ナビゲーション",
      settings: "設定",
      runtime: "ランタイム",
      project: "プロジェクト",
      model: "モデル",
      state: "状態",
      selection: "選択",
      job: "ジョブ",
      history: "履歴",
      viewport: "ビュー",
      data: "データ",
      macro: "マクロ",
    },
  },
  es: {
    title: "WASM Python",
    subtitle: "Superficie de automatizacion del frontend dentro del navegador con Pyodide y el catalogo de acciones del browser.",
    frontendSurface: "Automatizacion Frontend",
    frontendSurfaceHint: "Esta superficie se usa para automatizacion en navegador, grabacion de macros, replay y depuracion de UI.",
    headlessSurface: "Headless SDK",
    headlessSurfaceHint: "El panel inferior es un constructor separado de workflows headless para automatizacion de service y solver.",
    launch: "Launch",
    author: "Author",
    inspect: "Inspect",
    catalog: "Catalog",
    scriptMode: "Script",
    recordMode: "Record",
    outputMode: "Output",
    timelineMode: "Timeline",
    snapshotMode: "Snapshot",
    presetsMode: "Presets",
    actionsMode: "Actions",
    macrosMode: "Macros",
    authorScriptHint: "Escribe o ajusta scripts de automatizacion frontend directamente aqui.",
    authorRecordHint: "Graba acciones de UI, convierte acciones recientes en borradores de macro y vuelve a insertarlos en el script.",
    inspectOutputHint: "Aqui aparecen la salida de ejecucion y los mensajes del runtime.",
    inspectTimelineHint: "Las acciones recientes del frontend aparecen aqui como una linea de tiempo.",
    inspectSnapshotHint: "El estado vivo del workbench ayuda a inspeccionar y depurar el contexto de UI.",
    catalogHint: "Aqui viven los recursos reutilizables de automatizacion frontend: presets, acciones y macros.",
    runtime: "Runtime",
    loading: "Loading",
    ready: "Ready",
    idle: "Idle",
    running: "Running",
    error: "Error",
    firstRun: "First run downloads the Pyodide runtime into the browser cache.",
    loadRuntime: "Load runtime",
    resetScript: "Reset template",
    runScript: "Run script",
    clearOutput: "Clear output",
    startRecording: "Start recording",
    stopRecording: "Stop recording",
    recordingActive: "Recording manual UI actions into the DSL event stream.",
    exportMacroJson: "Export macro JSON",
    importMacroJson: "Import macro JSON",
    macroJsonExported: "Exported the current recorded macro as JSON.",
    macroJsonImported: "Imported a macro JSON draft into the editor.",
    projectPresets: "Project presets",
    presetName: "Preset name",
    presetNamePlaceholder: "review current result context",
    savePreset: "Save preset",
    insertPreset: "Insert preset",
    exportPresetJson: "Export preset JSON",
    deletePreset: "Delete preset",
    noProjectSelected: "Select a project first to save presets against project context.",
    noPresetDraft: "Build or import a macro draft first so it can be saved as a preset.",
    noPresets: "No saved presets for the current project yet.",
    presetSaved: "Saved the current macro draft into project presets.",
    presetDeleted: "Deleted the selected project preset.",
    presetInserted: "Inserted the selected project preset into the editor.",
    snapshot: "Snapshot",
    actionCatalog: "Action catalog",
    macroCatalog: "Macro catalog",
    editor: "Python script",
    output: "Output",
    noOutput: "Script output will appear here.",
    lineCount: "Lines",
    stateKeys: "State fields",
    actionCount: "Actions",
    payload: "Payload",
    actionLog: "Action log",
    noActionLog: "No scripted actions yet.",
    insertMacroDraft: "Insert macro draft",
    macroDraftInserted: "Inserted a macro draft from recent action log.",
    noMacroDraftSource: "Run a few actions first so the panel can assemble a draft macro.",
    actionSource: "Source",
    actionPayload: "Payload",
    actionResult: "Result",
    actionNote: "Note",
    riskNormal: "Normal",
    riskSensitive: "Sensitive",
    riskDestructive: "Destructive",
    confirmationRequired: "Requires confirmation before execution.",
    insertLabel: "Insert",
    stepsLabel: "Steps",
    macroPayloadHint: "This macro supports payload-driven template parameters.",
    categories: {
      navigation: "Navigation",
      settings: "Settings",
      runtime: "Runtime",
      project: "Project",
      model: "Model",
      state: "State",
      selection: "Selection",
      job: "Job",
      history: "History",
      viewport: "Viewport",
      data: "Data",
      macro: "Macro",
    },
  },
} as const satisfies Record<WorkbenchScriptLanguage, Record<string, unknown>>;

export type WorkbenchScriptPanelCopyEntry = (typeof workbenchScriptPanelCopy)["en"];
