export const workbenchScriptPanelCopyEs = {
  title: "Pwdt",
  subtitle: "Herramientas de Python WASM DSL con Pyodide y el catálogo de acciones registradas del navegador.",
  frontendSurface: "Automatización de la interfaz",
  frontendSurfaceHint: "Esta área permite automatizar el navegador, grabar y reproducir macros y depurar la interfaz.",
  headlessSurface: "SDK sin interfaz gráfica",
  headlessSurfaceHint: "El panel inferior es un constructor independiente de flujos sin interfaz gráfica para automatizar servicios y solvers.",
  launch: "Inicio",
  author: "Edición",
  inspect: "Inspección",
  catalog: "Catálogo",
  scriptMode: "Script",
  recordMode: "Grabación",
  outputMode: "Salida",
  timelineMode: "Cronología",
  snapshotMode: "Instantánea",
  presetsMode: "Preajustes",
  actionsMode: "Acciones",
  macrosMode: "Macros",
  authorScriptHint: "Escribe o ajusta aquí los scripts de automatización de la interfaz.",
  authorRecordHint: "Graba acciones de la interfaz, convierte las acciones recientes en borradores de macro e insértalos en el script.",
  inspectOutputHint: "Aquí aparecen la salida de ejecución y los mensajes del entorno de ejecución.",
  inspectTimelineHint: "Las acciones recientes de la interfaz aparecen como una cronología que se puede reproducir.",
  inspectSnapshotHint: "El estado en vivo de Workbench permite a los scripts inspeccionar y depurar el contexto de la interfaz.",
  inspectTimelineDetailHint: "Selecciona una acción para inspeccionar sus datos, su resultado y su contexto de reproducción.",
  insertActionStep: "Insertar paso",
  insertTimelineMacroDraft: "Insertar borrador de macro",
  sendTimelineMacroToHeadless: "Enviar al flujo de trabajo",
  saveTimelineMacroPreset: "Guardar como preajuste",
  noTimelineSelection: "Selecciona una acción de la cronología para ver todos sus detalles.",
  timelineFailed: "Fallido",
  timelineCompleted: "Completado",
  timelineStarted: "Iniciado",
  failureReason: "Motivo del fallo",
  continueFromStep: "Continuar desde aquí",
  timelineRangePreview: "Vista previa del intervalo",
  timelinePreviewSteps: "Pasos de la cronología",
  timelinePreviewMacroSteps: "Pasos de macro",
  timelinePreviewIncluded: "Incluido",
  timelinePreviewIncludedYes: "Sí",
  timelinePreviewIncludedNo: "No",
  timelinePreviewNotEligible: "Solo contexto",
  includeTimelineStep: "Incluir",
  excludeTimelineStep: "Excluir",
  selectAllTimelineSteps: "Seleccionar todo",
  clearTimelineSteps: "Limpiar selección",
  focusFailureWindow: "Centrar en los fallos",
  timelineMacroDraftInserted: "Se insertó un borrador de macro a partir del intervalo seleccionado de la cronología.",
  noTimelineMacroDraft: "Este intervalo de la cronología aún no contiene pasos ejecutables reutilizables.",
  timelineMacroPresetSaved: "Se guardó el intervalo seleccionado de la cronología como preajuste del proyecto.",
  restoreBridgeMacroToFrontend: "Se restauró el nodo de enlace en el área de automatización de la interfaz.",
  frontendMacroAssetInserted: "Se volvió a cargar un recurso de macro de la interfaz en el editor.",
  frontendMacroAssetDerived: "Se creó un nuevo borrador de macro editable a partir de la instantánea seleccionada.",
  frontendMacroAssets: "Recursos de macros de la interfaz",
  frontendMacroAssetsEmpty: "Aún no hay recursos de macros de la interfaz preparados.",
  deriveFrontendMacroAsset: "Crear borrador derivado",
  snapshotCompare: "Comparación de instantáneas",
  snapshotCompareEmpty: "Elige dos instantáneas para comparar sus pasos y los cambios en los datos.",
  snapshotCompareChangedSteps: "Pasos modificados",
  snapshotCompareSame: "Igual",
  snapshotCompareChanged: "Modificado",
  snapshotCompareMissing: "Ausente",
  snapshotCompareStepMissing: "No hay paso en esta instantánea",
  snapshotComparePayloadChanged: "Los datos cambiaron en este paso.",
  snapshotCompareActionChanged: "El identificador de la acción cambió en este paso.",
  compareLeftAsset: "Colocar a la izquierda",
  compareRightAsset: "Colocar a la derecha",
  clearCompareLeft: "Limpiar lado izquierdo",
  clearCompareRight: "Limpiar lado derecho",
  assetSnapshotId: "ID de instantánea",
  assetSource: "Origen",
  assetUpdatedAt: "Actualizado",
  assetSourceTimeline: "Selección de la cronología",
  assetSourceBridge: "Restauración del enlace",
  assetSourceDerived: "Derivado del historial",
  catalogHint: "Aquí se encuentran los recursos reutilizables de automatización de la interfaz: preajustes del proyecto, fragmentos de acciones y macros.",
  runtime: "Entorno de ejecución",
  loading: "Cargando",
  ready: "Listo",
  idle: "Inactivo",
  running: "En ejecución",
  error: "Error",
  sessionStorageFailed: "No se pudo guardar la sesión del editor. Los datos del script existente no se modificaron.",
  firstRun: "La primera ejecución descarga el entorno Pyodide en la caché del navegador.",
  loadRuntime: "Cargar entorno de ejecución",
  resetScript: "Restablecer plantilla",
  runScript: "Ejecutar script",
  clearOutput: "Limpiar salida",
  startRecording: "Iniciar grabación",
  stopRecording: "Detener grabación",
  recordingActive: "Se están grabando las acciones manuales de la interfaz en el flujo de eventos DSL.",
  exportMacroJson: "Exportar macro en JSON",
  importMacroJson: "Importar macro desde JSON",
  macroJsonExported: "Se exportó la macro grabada actual en formato JSON.",
  macroJsonImported: "Se importó un borrador de macro en JSON al editor.",
  headlessWorkflowImported: "Se importó al editor un contrato de flujo sin interfaz gráfica como borrador de macro ejecutable.",
  projectPresets: "Preajustes del proyecto",
  presetName: "Nombre del preajuste",
  presetNamePlaceholder: "revisar el contexto del resultado actual",
  savePreset: "Guardar preajuste",
  insertPreset: "Insertar preajuste",
  exportPresetJson: "Exportar preajuste en JSON",
  deletePreset: "Eliminar preajuste",
  noProjectSelected: "Selecciona primero un proyecto para guardar los preajustes en su contexto.",
  noPresetDraft: "Crea o importa primero un borrador de macro para guardarlo como preajuste.",
  noPresets: "Aún no hay preajustes guardados para el proyecto actual.",
  presetSaved: "Se guardó el borrador de macro actual en los preajustes del proyecto.",
  presetDeleted: "Se eliminó el preajuste seleccionado del proyecto.",
  presetInserted: "Se insertó el preajuste seleccionado del proyecto en el editor.",
  sensitivePresetRejected: "Se bloqueó el guardado del preajuste porque contiene campos sensibles que no deben almacenarse localmente.",
  sensitivePresetRejectedDetails: "Revisa estos campos y excluye los tokens, las cookies, las cabeceras de autorización y los secretos de los preajustes guardados:",
  snapshot: "Instantánea",
  actionCatalog: "Catálogo de acciones",
  macroCatalog: "Catálogo de macros",
  editor: "Script de Python",
  output: "Salida",
  noOutput: "La salida del script aparecerá aquí.",
  lineCount: "Líneas",
  stateKeys: "Campos de estado",
  actionCount: "Acciones",
  payload: "Datos enviados",
  actionLog: "Registro de acciones",
  noActionLog: "Aún no hay acciones ejecutadas mediante scripts.",
  insertMacroDraft: "Insertar borrador de macro",
  macroDraftInserted: "Se insertó un borrador de macro a partir del registro de acciones recientes.",
  noMacroDraftSource: "Ejecuta primero algunas acciones para que el panel pueda preparar un borrador de macro.",
  actionSource: "Origen",
  actionPayload: "Datos enviados",
  actionResult: "Resultado",
  actionNote: "Nota",
  riskNormal: "Normal",
  riskSensitive: "Sensible",
  riskDestructive: "Destructivo",
  confirmationRequired: "Requiere confirmación antes de ejecutarse.",
  insertLabel: "Insertar",
  stepsLabel: "Pasos",
  macroPayloadHint: "Esta macro admite parámetros de plantilla definidos mediante los datos enviados.",
  categories: {
    navigation: "Navegación",
    settings: "Configuración",
    runtime: "Entorno de ejecución",
    project: "Proyecto",
    model: "Modelo",
    state: "Estado",
    selection: "Selección",
    job: "Tarea",
    history: "Historial",
    viewport: "Visor",
    data: "Datos",
    macro: "Macro",
  },
} as const;
