"use client";

import { useWorkbenchAssistantController } from "@/components/workbench/workbench-assistant-controller";
import { createWorkbenchPrimaryActionsController } from "@/components/workbench/workbench-primary-actions-controller";
import { createWorkbenchScriptInvoker } from "@/components/workbench/workbench-script-invoker";
import { buildWorkbenchUxGuardrailSummary } from "@/components/workbench/workbench-ux-guardrails";
import { serializeCurrentModel } from "@/lib/workbench/helpers";

export function useWorkbenchFlowControllers(props: Record<string, any>) {
  const primaryActionsController = createWorkbenchPrimaryActionsController({
    t: props.t,
    setMessage: props.setMessage,
    recordHistory: props.recordHistory,
    setAxialForm: props.setAxialForm,
    setParametric: props.setParametric,
    setPanelParametric: props.setPanelParametric,
    startTransition: props.startTransition,
    adminDataBackendService: props.adminDataBackendService,
    resultRefreshSeqRef: props.resultRefreshSeqRef,
    setResultRecords: props.setResultRecords,
    setSelectedAdminResultJobId: props.setSelectedAdminResultJobId,
    directMeshEndpointsText: props.directMeshEndpointsText,
    directMeshSelectionMode: props.directMeshSelectionMode,
    frontendRuntimeMode: props.frontendRuntimeMode,
    jobPollTokenRef: props.jobPollTokenRef,
    selectedProjectId: props.selectedProjectId,
    selectedVersionId: props.selectedVersionId,
    setDirectMeshExecution: props.setDirectMeshExecution,
    setJob: props.setJob,
    setResult: props.setResult,
    setSystemAlerts: props.setSystemAlerts,
    studyKind: props.studyKind,
    axialForm: props.axialForm,
    beamModel: props.beamModel,
    frameModel: props.frameModel,
    heatBarModel: props.heatBarModel,
    heatPlaneModel: props.heatPlaneModel,
    planeModel: props.planeModel,
    springModel: props.springModel,
    spring2dModel: props.spring2dModel,
    spring3dModel: props.spring3dModel,
    thermalBarModel: props.thermalBarModel,
    thermalBeamModel: props.thermalBeamModel,
    thermalFrameModel: props.thermalFrameModel,
    thermalTrussModel: props.thermalTrussModel,
    thermalTruss3dModel: props.thermalTruss3dModel,
    torsionModel: props.torsionModel,
    trussModel: props.trussModel,
    truss3dModel: props.truss3dModel,
    trussDiagnostics: props.trussDiagnostics,
    refreshJobHistory: props.refreshJobHistory,
    setSidebarSection: props.setSidebarSection,
    setWorkflowPanelTab: props.setWorkflowPanelTab,
    setSelectedWorkflowId: props.setSelectedWorkflowId,
    setWorkflowRuns: props.setWorkflowRuns,
    openWorkspaceStudy: props.openWorkspaceStudy,
    setStudyKind: props.setStudyKind,
    setHeatBarModel: props.setHeatBarModel,
    setHeatPlaneModel: props.setHeatPlaneModel,
    setThermalBarModel: props.setThermalBarModel,
    setThermalBeamModel: props.setThermalBeamModel,
    setThermalFrameModel: props.setThermalFrameModel,
    setThermalTrussModel: props.setThermalTrussModel,
    setThermalTruss3dModel: props.setThermalTruss3dModel,
    setSpringModel: props.setSpringModel,
    setSpring2dModel: props.setSpring2dModel,
    setSpring3dModel: props.setSpring3dModel,
    setTrussModel: props.setTrussModel,
    setTruss3dModel: props.setTruss3dModel,
    setPlaneModel: props.setPlaneModel,
    setFrameModel: props.setFrameModel,
    setBeamModel: props.setBeamModel,
    setTorsionModel: props.setTorsionModel,
    setPlaneResultField: props.setPlaneResultField,
    setLoadedModelName: props.setLoadedModelName,
    setSelectedModelId: props.setSelectedModelId,
    setSelectedVersionId: props.setSelectedVersionId,
    setModelVersions: props.setModelVersions,
    setActiveMaterial: props.setActiveMaterial,
    setSelectedNode: props.setSelectedNode,
    setSelectedElement: props.setSelectedElement,
    setMemberDraftNodes: props.setMemberDraftNodes,
    activeMaterial: props.activeMaterial,
    round: props.round,
    parametric: props.parametric,
    panelParametric: props.panelParametric,
    loadedModelName: props.loadedModelName,
    selectedAdminJobId: props.selectedAdminJobId,
    adminJobMessage: props.adminJobMessage,
    adminJobProjectId: props.adminJobProjectId,
    adminJobModelVersionId: props.adminJobModelVersionId,
    adminJobCaseId: props.adminJobCaseId,
    adminResultDraft: props.adminResultDraft,
    selectedAdminResultJobId: props.selectedAdminResultJobId,
    downloadTextFile: props.downloadTextFile,
    adminDataEffects: props.adminDataEffects,
  });

  const assistantController = useWorkbenchAssistantController({
    t: props.t,
    language: props.language,
    studyKind: props.studyKind,
    frontendRuntimeMode: props.frontendRuntimeMode,
    selectedProjectId: props.selectedProjectId,
    directMeshEndpointsCount: props.directMeshEndpoints.length,
    hasHealth: Boolean(props.health),
    jobIsActive: props.jobIsActive,
    isTruss: props.isTruss,
    isTruss3d: props.isTruss3d,
    immersiveViewport: props.immersiveViewport,
    hasAnyResult: props.hasAnyResult,
    trussDiagnostics: props.trussDiagnostics,
    openProjects: () => {
      props.setSidebarSection("library");
      props.setLibraryTab("projects");
    },
    openSystemConfig: () => {
      props.setSidebarSection("system");
      props.setSystemPanelTab("config");
    },
    refreshHealth: () => {
      void props.refreshHealth();
    },
    cancelCurrentJob: props.cancelCurrentJob,
    applyTrussSuggestion: props.applyTrussSuggestion,
    openSample: props.openSample,
    openWorkspaceStudy: props.openWorkspaceStudy,
    runAnalysis: primaryActionsController.runAnalysis,
    downloadResultCsv: props.downloadResultCsv,
    toggleImmersiveViewport: () => {
      void props.toggleImmersiveViewport();
    },
    assistantApiBaseUrl: props.assistantApiBaseUrl,
    assistantApiKey: props.assistantApiKey,
    assistantModel: props.assistantModel,
    getScriptSnapshot: props.getScriptSnapshot,
  });

  const invokeScriptAction = createWorkbenchScriptInvoker({
    language: props.language,
    uxGuardrailSummary: buildWorkbenchUxGuardrailSummary({
      frontendRuntimeMode: props.frontendRuntimeMode === "direct_mesh_gui" ? "direct_mesh_gui" : "orchestrated_gui",
      healthStatus: props.health?.status,
      protocolOnline: Boolean(props.health?.protocol),
      watchdogOnline: Boolean(props.health?.watchdog),
      controlPlaneApiToken: props.controlPlaneApiToken ?? "",
      clusterApiToken: props.clusterApiToken ?? "",
      directMeshApiToken: props.directMeshApiToken ?? "",
      directMeshEndpointsText: props.directMeshEndpointsText ?? "",
      selectedProjectId: props.selectedProjectId ?? null,
      selectedVersionId: props.selectedVersionId ?? null,
      languagePackCount: props.languagePackCount ?? 0,
    }),
    recordSecurityAuditEvent: props.recordSecurityAuditEvent,
    appendScriptActionLog: props.appendScriptActionLog,
    studyKind: props.studyKind,
    studyKindResetHandlers: props.studyKindResetHandlers,
    setStudyKind: props.setStudyKind,
    handleSidebarSectionChange: props.handleSidebarSectionChange,
    recordHistory: props.recordHistory,
    changeStudyTypeLabel: props.t.changeStudyType,
    setStudyTab: props.setStudyTab,
    setModelTab: props.setModelTab,
    setModelToolsPage: props.setModelToolsPage,
    setLibraryTab: props.setLibraryTab,
    setSystemPanelTab: props.setSystemPanelTab,
    setAssistantWindowOpen: props.setAssistantWindowOpen,
    setSystemDataTab: props.setSystemDataTab,
    handleLanguageChange: props.handleLanguageChange,
    setTheme: props.setTheme,
    setFrontendRuntimeMode: props.setFrontendRuntimeMode,
    setDirectMeshEndpointsText: props.setDirectMeshEndpointsText,
    setDirectMeshSelectionMode: props.setDirectMeshSelectionMode,
    refreshHealth: props.refreshHealth,
    refreshJobHistory: props.refreshJobHistory,
    refreshResults: props.refreshResults,
    refreshProjects: props.refreshProjects,
    refreshSecurityEvents: props.refreshSecurityEvents,
    selectedProjectId: props.selectedProjectId,
    selectedModelId: props.selectedModelId,
    selectedVersionId: props.selectedVersionId,
    projectNameDraft: props.projectNameDraft,
    projectDescriptionDraft: props.projectDescriptionDraft,
    loadedModelName: props.loadedModelName,
    activeMaterial: props.activeMaterial,
    setSelectedProjectId: props.setSelectedProjectId,
    setProjectNameDraft: props.setProjectNameDraft,
    setProjectDescriptionDraft: props.setProjectDescriptionDraft,
    setSelectedModelId: props.setSelectedModelId,
    setSelectedVersionId: props.setSelectedVersionId,
    setModelVersions: props.setModelVersions,
    setLoadedModelName: props.setLoadedModelName,
    setActiveMaterial: props.setActiveMaterial,
    refreshVersions: props.refreshVersions,
    downloadProjectBundleJson: props.downloadProjectBundleJson,
    downloadProjectBundleZip: props.downloadProjectBundleZip,
    generateModel: primaryActionsController.generateModel,
    generatePanelModel: primaryActionsController.generatePanelModel,
    serializeCurrentModel: () =>
      serializeCurrentModel(
        props.studyKind,
        props.loadedModelName,
        props.activeMaterial,
        props.axialForm,
        props.heatBarModel,
        props.heatPlaneModel,
        props.thermalBarModel,
        props.thermalBeamModel,
        props.thermalFrameModel,
        props.thermalTrussModel,
        props.trussModel,
        props.thermalTruss3dModel,
        props.truss3dModel,
        props.planeModel,
        props.frameModel,
        props.beamModel,
        props.torsionModel,
        props.springModel,
        props.spring2dModel,
        props.spring3dModel,
        props.parametric,
        props.round,
      ),
    projectLibraryBackendService: props.projectLibraryBackendService,
    projectRequiredLabel: props.t.projectRequired,
    defaultProjectLabel: props.t.defaultProject,
    projectCreatedLabel: props.t.projectCreated,
    projectUpdatedLabel: props.t.projectUpdated,
    projectDeletedLabel: props.t.projectDeleted,
    noSavedModelsLabel: props.t.noSavedModels,
    noVersionsLabel: props.t.noVersions,
    modelCreatedLabel: props.t.modelCreated,
    modelSavedLabel: props.t.modelSaved,
    modelDeletedLabel: props.t.modelDeletedStored,
    versionRenamedLabel: props.t.versionRenamed,
    versionDeletedLabel: props.t.versionDeleted,
    setMessage: props.setMessage,
    setParametric: props.setParametric,
    setPanelParametric: props.setPanelParametric,
    setTrussModel: props.setTrussModel,
    setTruss3dModel: props.setTruss3dModel,
    setPlaneModel: props.setPlaneModel,
    setFrameModel: props.setFrameModel,
    setBeamModel: props.setBeamModel,
    setSelectedNode: props.setSelectedNode,
    setSelectedElement: props.setSelectedElement,
    setSelectedTruss3dNodes: props.setSelectedTruss3dNodes,
    setMemberDraftNodes: props.setMemberDraftNodes,
    setTruss3dLinkMode: props.setTruss3dLinkMode,
    setTruss3dFocusRequestVersion: props.setTruss3dFocusRequestVersion,
    setTruss3dResetRequestVersion: props.setTruss3dResetRequestVersion,
    setTruss3dShowGrid: props.setTruss3dShowGrid,
    setTruss3dShowLabels: props.setTruss3dShowLabels,
    setTruss3dShowNodes: props.setTruss3dShowNodes,
    setImmersiveToolDrawerOpen: props.setImmersiveToolDrawerOpen,
    setImmersiveHelpDrawerOpen: props.setImmersiveHelpDrawerOpen,
    setTruss3dBoxSelectMode: props.setTruss3dBoxSelectMode,
    immersiveViewport: props.immersiveViewport,
    importActionLabel: props.t.importAction,
    editParametricLabel: props.t.editParametric,
    resolveTruss2dJobInput: props.resolveTruss2dJobInput,
    resolveTruss3dJobInput: props.resolveTruss3dJobInput,
    resolvePlaneQuad2dJobInput: props.resolvePlaneQuad2dJobInput,
    resolvePlaneTriangle2dJobInput: props.resolvePlaneTriangle2dJobInput,
    ensureFrameModelMaterials: props.ensureFrameModelMaterials,
    ensureBeamModelMaterials: props.ensureBeamModelMaterials,
    resetActiveResult: props.resetActiveResult,
    projectHeatToThermoStudy: props.projectHeatToThermoStudy,
    toggleImmersiveViewport: props.toggleImmersiveViewport,
    handleUndo: props.handleUndo,
    handleRedo: props.handleRedo,
    runAnalysis: primaryActionsController.runAnalysis,
    cancelCurrentJob: props.cancelCurrentJob,
    setTruss3dViewPreset: props.setTruss3dViewPreset,
    setTruss3dProjectionMode: props.setTruss3dProjectionMode,
    getScriptSnapshot: props.getScriptSnapshot,
    setAdminFilterProjectId: props.setAdminFilterProjectId,
    setAdminFilterModelVersionId: props.setAdminFilterModelVersionId,
    setSelectedAdminJobId: props.setSelectedAdminJobId,
    setSelectedAdminResultJobId: props.setSelectedAdminResultJobId,
    resolveScriptLinkedJob: props.resolveScriptLinkedJob,
    openModelVersionById: props.openModelVersionById,
    openProjectContextById: props.openProjectContextById,
    applyJobContextToWorkbench: props.applyJobContextToWorkbench,
    downloadDatabaseSnapshot: props.downloadDatabaseSnapshot,
  });

  return {
    assistantController,
    invokeScriptAction,
    primaryActionsController,
  };
}
