pub fn print_help() {
    println!(concat!(
        "kyuubiki-installer\n\n",
        "Commands:\n",
        "  help             Show this help\n",
        "  doctor           Check local prerequisites for the current platform\n",
        "  installation-integrity  Validate install layout, versions, and residue\n",
        "  credential-storage  Show sandbox credential storage contract\n",
        "  cross-platform-audit  Validate dist/ parity across macOS, Linux, and Windows\n",
        "  linux-desktop-deps  Show Ubuntu/Tauri dependency plan for remote Linux desktop builds\n",
        "  embedded-runtimes  Show installer-managed runtime payload contract\n",
        "  operator-package-preflight <packages-root> [--out path] [--fail-on-rejected]  Validate external operator packages as JSON\n",
        "  update-plan      Show the unified channel-based update target\n",
        "  update-preview   Show pre-apply checks and blockers for a channel update\n",
        "  prepare-staged-update  Repair, stage, and record a channel update scaffold\n",
        "  remote-deployment-roadmap  Show SSH remote deployment service maturity plan\n",
        "  remote-deployment-plan  Preview the structured SSH deployment step contract\n",
        "  remote-deployment-journal  Preview retry-safe journal records for the plan\n",
        "  remote-artifacts  Preview remote-pull artifact delivery manifest\n",
        "  remote-deployment-dry-run  Validate remote deployment readiness without SSH\n",
        "  remote-host-trust  Show known-host pinning plan for managed SSH\n",
        "  remote-ssh-fixture  Show local SSH fixture command-shape checks\n",
        "  remote-ssh-fixture-plan  Show Docker SSH fixture scaffold paths\n",
        "  repair-installation     Recreate layout and clean removable residue\n",
        "  validate-env     Validate required environment variables from .env.local\n",
        "  init-env         Create .env.local from .env.example when missing\n",
        "  prepare-layout   Create repo-local runtime folders\n",
        "  export-launch    Print a cross-platform launch manifest as JSON\n",
        "  stage-release    Create a portable release directory layout under dist/\n",
        "  bootstrap        Run doctor + prepare-layout + init-env\n\n",
        "Examples:\n",
        "  cargo run -p kyuubiki-installer -- doctor\n",
        "  cargo run -p kyuubiki-installer -- update-plan stable\n",
        "  cargo run -p kyuubiki-installer -- update-preview stable\n",
        "  cargo run -p kyuubiki-installer -- operator-package-preflight ./operator-packages\n",
        "  cargo run -p kyuubiki-installer -- operator-package-preflight ./operator-packages --out tmp/operator-package-preflight.json\n",
        "  cargo run -p kyuubiki-installer -- operator-package-preflight ./operator-packages --fail-on-rejected\n",
        "  cargo run -p kyuubiki-installer -- prepare-staged-update stable macos\n",
        "  cargo run -p kyuubiki-installer -- stage-release\n",
        "  cargo run -p kyuubiki-installer -- stage-release windows ./dist/windows-preview\n",
    ));
}
