use crate::{HeadlessActionContract, HeadlessEngine, HeadlessRisk};

const CONTRACTS: &[HeadlessActionContract] = &[
    HeadlessActionContract {
        id: "service_health",
        engine: HeadlessEngine::Service,
        category: "service",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &[],
        output_keys: &["service", "status"],
    },
    HeadlessActionContract {
        id: "project_create",
        engine: HeadlessEngine::Service,
        category: "project",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["name"],
        output_keys: &["project_id", "name"],
    },
    HeadlessActionContract {
        id: "project_update",
        engine: HeadlessEngine::Service,
        category: "project",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["project_id"],
        output_keys: &["project_id", "name"],
    },
    HeadlessActionContract {
        id: "project_delete",
        engine: HeadlessEngine::Service,
        category: "project",
        risk: HeadlessRisk::Destructive,
        required_payload_keys: &["project_id"],
        output_keys: &["project_id"],
    },
    HeadlessActionContract {
        id: "model_create",
        engine: HeadlessEngine::Service,
        category: "model",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["project_id", "name", "kind", "payload"],
        output_keys: &["model_id", "kind"],
    },
    HeadlessActionContract {
        id: "model_version_create",
        engine: HeadlessEngine::Service,
        category: "model",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model_id", "payload"],
        output_keys: &["model_version_id", "kind"],
    },
    HeadlessActionContract {
        id: "workflow_submit_catalog",
        engine: HeadlessEngine::Service,
        category: "workflow",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["workflow_id"],
        output_keys: &["job_id", "status"],
    },
    HeadlessActionContract {
        id: "workflow_submit_graph",
        engine: HeadlessEngine::Service,
        category: "workflow",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["graph"],
        output_keys: &["job_id", "status"],
    },
    HeadlessActionContract {
        id: "operator_task_prepare",
        engine: HeadlessEngine::Service,
        category: "operator",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["task"],
        output_keys: &[
            "status",
            "task_digest",
            "task_id",
            "operator_id",
            "operator_kind",
            "program_id",
            "runtime_protocol",
            "package_ref",
        ],
    },
    HeadlessActionContract {
        id: "operator_task_execute",
        engine: HeadlessEngine::Service,
        category: "operator",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["task"],
        output_keys: &[
            "status",
            "task_digest",
            "task_id",
            "operator_id",
            "operator_kind",
            "program_id",
            "runtime_protocol",
            "package_ref",
            "result",
        ],
    },
    HeadlessActionContract {
        id: "job_wait",
        engine: HeadlessEngine::Service,
        category: "job",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["job_id"],
        output_keys: &["job_id", "status", "progress"],
    },
    HeadlessActionContract {
        id: "job_fetch",
        engine: HeadlessEngine::Service,
        category: "job",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["job_id"],
        output_keys: &["job_id", "status", "progress"],
    },
    HeadlessActionContract {
        id: "result_fetch",
        engine: HeadlessEngine::Service,
        category: "result",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["job_id"],
        output_keys: &["job_id", "result"],
    },
    HeadlessActionContract {
        id: "direct_mesh_solve",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["endpoints"],
        output_keys: &["job_id", "status", "endpoint"],
    },
    HeadlessActionContract {
        id: "solve_from_model_version",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model_version_id", "endpoints"],
        output_keys: &["job_id", "status", "model_version_id", "endpoint"],
    },
    HeadlessActionContract {
        id: "solve_and_wait_from_model_version",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model_version_id", "endpoints"],
        output_keys: &["job_id", "status", "model_version_id", "endpoint", "result"],
    },
    HeadlessActionContract {
        id: "solve_plane_quad_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_bar_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_acoustic_bar_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_thermal_bar_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_heat_bar_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_transient_heat_bar_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_electrostatic_bar_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_magnetostatic_bar_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_magnetostatic_plane_triangle_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_magnetostatic_plane_quad_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_electrostatic_plane_triangle_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_heat_plane_quad_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_stokes_flow_plane_triangle_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_stokes_flow_plane_quad_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_heat_plane_triangle_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_thermal_plane_quad_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_thermal_plane_triangle_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_electrostatic_plane_quad_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_truss_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_truss_3d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_thermal_truss_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_thermal_truss_3d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_beam_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_thermal_beam_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_torsion_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_spring_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_transient_spring_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_harmonic_spring_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_nonlinear_spring_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_contact_gap_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_spring_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_spring_3d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_plane_triangle_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_frame_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_modal_frame_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_buckling_beam_1d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_frame_3d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_solid_tetra_3d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_modal_frame_3d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_thermal_frame_2d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "solve_thermal_frame_3d",
        engine: HeadlessEngine::Service,
        category: "solve",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["model"],
        output_keys: &["job_id", "status", "progress", "job"],
    },
    HeadlessActionContract {
        id: "open_page",
        engine: HeadlessEngine::Browser,
        category: "navigation",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["url"],
        output_keys: &["url", "status", "ok"],
    },
    HeadlessActionContract {
        id: "click",
        engine: HeadlessEngine::Browser,
        category: "interaction",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["selector"],
        output_keys: &["selector"],
    },
    HeadlessActionContract {
        id: "type",
        engine: HeadlessEngine::Browser,
        category: "interaction",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["selector", "value"],
        output_keys: &["selector", "value"],
    },
    HeadlessActionContract {
        id: "press",
        engine: HeadlessEngine::Browser,
        category: "interaction",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["key"],
        output_keys: &["key"],
    },
    HeadlessActionContract {
        id: "select",
        engine: HeadlessEngine::Browser,
        category: "interaction",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["selector", "value"],
        output_keys: &["selector", "values"],
    },
    HeadlessActionContract {
        id: "wait",
        engine: HeadlessEngine::Browser,
        category: "timing",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &[],
        output_keys: &["timeout_ms"],
    },
    HeadlessActionContract {
        id: "assert_text",
        engine: HeadlessEngine::Browser,
        category: "assertion",
        risk: HeadlessRisk::Normal,
        required_payload_keys: &["selector", "text"],
        output_keys: &["selector", "text"],
    },
    HeadlessActionContract {
        id: "snapshot",
        engine: HeadlessEngine::Browser,
        category: "artifact",
        risk: HeadlessRisk::Sensitive,
        required_payload_keys: &[],
        output_keys: &["path"],
    },
];

pub fn find_action_contract(action: &str) -> Option<&'static HeadlessActionContract> {
    CONTRACTS.iter().find(|contract| contract.id == action)
}

pub fn all_action_contracts() -> &'static [HeadlessActionContract] {
    CONTRACTS
}
