use crate::{
    MaterialEvidenceRef, MaterialModelAssumption, material_evidence_ref, material_model_assumption,
};

pub(crate) fn composite_evidence_refs() -> Vec<MaterialEvidenceRef> {
    vec![
        material_evidence_ref(
            "evidence.layered_dielectric_closed_form",
            "Layered dielectric series closed form",
            "analytic_cross_check",
            "kyuubiki.composite-electrostatic-cross-validation/v1",
            "retained",
            "Independent one-dimensional displacement-continuity solution for the three-region electrostatic fixture.",
        ),
        material_evidence_ref(
            "evidence.electrostatic_mesh_convergence",
            "Electrostatic structured mesh convergence",
            "mesh_convergence",
            "kyuubiki.composite-electrostatic-mesh-convergence/v1",
            "retained",
            "Real Rust solver runs at one, two, four, and eight quad elements per material layer.",
        ),
        material_evidence_ref(
            "evidence.electrothermal_loss_projection",
            "Harmonic dielectric-loss projection",
            "coupling_energy_balance",
            "kyuubiki.composite-electrothermal-loss-projection/v1",
            "active_gate",
            "Converts solved RMS dielectric fields into frequency-local volumetric loss and conservatively lumps the power to heat nodes.",
        ),
        material_evidence_ref(
            "evidence.electrothermal_feedback_convergence",
            "Temperature-dependent electrothermal feedback convergence",
            "coupling_fixed_point_convergence",
            "kyuubiki.composite-electrothermal-feedback-convergence/v1",
            "active_gate",
            "Retains every relaxed electrostatic-loss-heat iteration and gates regional temperature residual, successive loss change, and thermal-conductivity stability.",
        ),
        material_evidence_ref(
            "evidence.joule_heating_projection",
            "Temperature-dependent conductor Joule heating",
            "coupling_energy_balance",
            "kyuubiki.composite-joule-heating-projection/v1",
            "active_gate",
            "Converts prescribed conductor current and temperature-dependent path resistance into conservative regional heat load.",
        ),
        material_evidence_ref(
            "evidence.layered_thermal_resistance_closed_form",
            "Layered thermal-resistance closed form",
            "analytic_cross_check",
            "kyuubiki.composite-heat-cross-validation/v1",
            "retained",
            "Independent downstream thermal-resistance solution for uniform dielectric generation and fixed right-edge temperature.",
        ),
        material_evidence_ref(
            "evidence.heat_mesh_convergence",
            "Heat structured mesh convergence",
            "mesh_convergence",
            "kyuubiki.composite-heat-mesh-convergence/v1",
            "retained",
            "Real Rust solver runs at one, two, four, and eight heat quads per material layer.",
        ),
        material_evidence_ref(
            "evidence.heat_to_thermal_projection",
            "Heat-field to thermal-strain projection",
            "coupling_topology_validation",
            "kyuubiki.composite-heat-to-thermal-projection/v1",
            "active_gate",
            "Maps solved nodal temperatures into structural temperature deltas after node identity and coordinate checks.",
        ),
        material_evidence_ref(
            "evidence.thermal_expansion_projection",
            "Temperature-dependent thermal-expansion projection",
            "material_parameter_projection",
            "kyuubiki.composite-thermal-expansion-projection/v1",
            "active_gate",
            "Updates every declared structural region from its solved local mean temperature and gates complete region coverage.",
        ),
        material_evidence_ref(
            "evidence.thermal_structural_mesh_convergence",
            "Thermal-structural two-dimensional mesh convergence",
            "mesh_convergence",
            "kyuubiki.composite-thermal-mesh-convergence/v1",
            "active_gate",
            "Real Rust solver runs at one, two, four, and eight subdivisions in both panel directions; displacement and strain energy control the gate.",
        ),
        material_evidence_ref(
            "evidence.thermal_convergence_regime",
            "Thermal-structural observed order and GCI",
            "discretization_uncertainty",
            "kyuubiki.composite-thermal-convergence-regime/v1",
            "active_gate",
            "Four refinement levels classify asymptotic behavior before permitting Richardson extrapolation or fine-grid GCI.",
        ),
        material_evidence_ref(
            "evidence.thermal_algebraic_residual",
            "Thermal-structural algebraic residual",
            "solver_convergence",
            "kyuubiki.composite-thermal-algebraic-validation/v1",
            "active_gate",
            "Recomputes original-system residuals for every uniform, regularized, and graded mesh solve.",
        ),
        material_evidence_ref(
            "evidence.thermal_constraint_sensitivity",
            "Thermal-structural restraint sensitivity",
            "boundary_condition_sensitivity",
            "kyuubiki.composite-thermal-constraint-sensitivity/v1",
            "diagnostic",
            "Compares the full edge clamp with a roller edge and one vertical anchor without overriding the primary quality gates.",
        ),
        material_evidence_ref(
            "evidence.thermal_stress_recovery",
            "Area-weighted thermal-stress recovery",
            "stress_recovery",
            "kyuubiki.composite-thermal-stress-recovery/v1",
            "active_gate",
            "Tracks area-weighted von Mises RMS and P95 convergence while retaining the raw maximum as a singularity diagnostic.",
        ),
        material_evidence_ref(
            "evidence.prototype_material_cards",
            "Prototype material cards",
            "internal_screening_card",
            "kyuubiki.material-cards.composite-panel.v1",
            "screening",
            "Scalar room-temperature values for conductor, dielectric, and substrate families.",
        ),
        material_evidence_ref(
            "evidence.synthetic_multiphysics_fixture",
            "Synthetic mixed-material panel fixture",
            "solver_fixture",
            "kyuubiki.composite_thermo_electric_panel.fixture.v1",
            "prototype",
            "Three-region quad panel used to validate mixed-material partitioned feedback coupling.",
        ),
    ]
}

pub(crate) fn composite_model_assumptions() -> Vec<MaterialModelAssumption> {
    vec![
        material_model_assumption(
            "assumption.sequential_coupling",
            "Partitioned electrothermal coupling",
            "electrostatic RMS field plus prescribed-current conductor loss <-> regional temperature feedback -> heat -> thermal stress",
            "Iterates dielectric parameters and heat to a fixed point, but is not a monolithic multiphysics Jacobian.",
        ),
        material_model_assumption(
            "assumption.screening_temperature_sensitivity",
            "Screening temperature sensitivity",
            "linear epsilon_r(T), tan_delta(T), regional k(T), and regional alpha(T) coefficients",
            "Built-in coefficients exercise feedback robustness and must be replaced by validated material-card curves for qualification.",
        ),
        material_model_assumption(
            "assumption.harmonic_dielectric_loss",
            "Frequency-local dielectric loss",
            "q = 2*pi*f*epsilon_0*epsilon_r*tan_delta*E_rms^2",
            "Represents dielectric heating at one screening frequency, not broadband dispersion.",
        ),
        material_model_assumption(
            "assumption.prescribed_current_joule_loss",
            "Prescribed-current conductor path",
            "P = I^2*rho(T)*L/A",
            "Captures temperature-dependent bulk conductor heating, but not solved current crowding, contact resistance, or terminal impedance.",
        ),
        material_model_assumption(
            "assumption.scalar_regions",
            "Scalar isotropic regions",
            "one material parameter set per region and field",
            "Fast to evaluate, but does not represent anisotropy or interfaces.",
        ),
        material_model_assumption(
            "assumption.prototype_geometry",
            "Prototype panel geometry",
            "three quad regions sharing boundary nodes",
            "Captures multi-region topology without CAD-level geometric fidelity.",
        ),
    ]
}
